### PR TITLE
[spirv] Fix CodeGen for no surrounding distributed workgroup loops

### PR DESCRIPTION
**Pull request by ThomasRaoux**
https://github.com/openxla/iree/pull/12800 converts SPIR-V
CodeGen to avoid emitting distributed loops for workgroups.
This means we cannot deduce the number of workgroups from
the loop bounds anymore. To simply `affine.min` ops involving
workgroup ID ops, we need to query the number of workgroups
separately and feed that information to folding patterns.

This commit wires the above to connect the dots to make the
information flow. Additionally we convert the FastSlowPathPass
in SPIR-V to not anchor on surrounding distributed loops.

### CODE REVIEW

**Review by antiagainst — APPROVED** [review]

**Comment by MaheshRavishankar** [comment]
Is this actually fixing the regression? If this is not urgent I might be able to fix all of this for good in a few days. I don't want to add to a bunch of things that I will have to unwind then

**Review by MaheshRavishankar — DISMISSED** [review]
Have a question here

**Comment by antiagainst** [comment]
Yes it fixes the regression as shown in the above.

**Comment by ThomasRaoux** [comment]
> Is this actually fixing the regression? If this is not urgent I might be able to fix all of this for good in a few days. I don't want to add to a bunch of things that I will have to unwind then

Yes as Lei mentioned this fixes the regression as the transform was being skipped. It would be good to recover the perf for now. Any objections?

**Comment by ThomasRaoux** [comment]
> Is this actually fixing the regression? If this is not urgent I might be able to fix all of this for good in a few days. I don't want to add to a bunch of things that I will have to unwind then

How would you fix this without doing those changes to the pass? Would you just remove the pass? If that's the case I don't expect that to cause extra work?

**Comment by MaheshRavishankar** [comment]
> > Is this actually fixing the regression? If this is not urgent I might be able to fix all of this for good in a few days. I don't want to add to a bunch of things that I will have to unwind then
> 
> How would you fix this without doing those changes to the pass? Would you just remove the pass? If that's the case I don't expect that to cause extra work?

Hmmm, maybe I am mistaken then. Well lets see what comes out when I shake this a bit.

**Pull request merged**
