### PR TITLE
Make release run on self-hosted GitHub runners

### PR DESCRIPTION
**Pull request by GMNGeoffrey**
We currently have three n1-standard-64 runners for releases.

This dramatically reduces runtime for the linux releases, leaving the
macos releases as the bottleneck (still taking 3h for the compiler
package). We could consider separating these so mac releases are less
frequent. Here's a comparison of the runtimes (in minutes):

| Build                    | managed | self-hosted |
|--------------------------|---------|-------------|
| main-dist-linux          | 146.5   | 14.6        |
| py-compiler-pkg          | 177.1   | 25.0        |
| py-runtime-pkg           | 13.9    | 9.5         |
| py-tf-compiler-tools-pkg | 242.6   | 23.8        |

https://github.com/google/iree/runs/6905353191
vs
https://github.com/google/iree/runs/6810296844

Was previously #9430, but needed to be a branch on the main repository
to trigger the action on it for testing.

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
Ok still some kinks. We're running into https://github.com/actions/checkout/issues/273 because of docker's obnoxious habit of creating files as root. Do the self-hosted runners run everything as root? We can employ our docker_setup scripting here or use some other solution. We also have this very helpful error message from GitHub:

image

I think this is because the runner was queued too long or something. I forgot to make the disk a reasonable size, so we immediately ran out of space and everything was upset. Still pretty annoying that that's the error though. I think I've seen that once before.

**Comment by GMNGeoffrey** [comment]
Ok I think the difference is that the managed runners have passwordless sudo. There are also some cosmetic differences (like user name being "runner" vs "github") that I'll just unify

**Comment by GMNGeoffrey** [comment]
Well with those things fixed, still running into issues:

```
:::: Auditwheel /wheelhouse/iree_compiler-*-cp37-cp37m-linux_x86_64.whl
usage: auditwheel [-h] [-V] [-v] command ...
auditwheel: error: cannot access /wheelhouse/iree_compiler-*-cp37-cp37m-linux_x86_64.whl. No such file
```

It appears that the scripting is assuming that package-suffix starts with a dash. Given that this is a freeform user input field, I don't think that's a great idea. I can work around it for now, but @stellaraccident I think we should either:

1. validate that the field starts with a dash immediately on workflow launch
2. assume it doesn't start with a dash and add the dash ourselves in cmake_ci.py
3. Not assume it starts with a dash when fetching files

Which is your preference?

**Comment by GMNGeoffrey** [comment]
Ah the checkout issue is because this runner is actually being reused, unlike with the managed runners. Duh. So Docker's shenanigans cause more of an issue. We'll need to be a little more careful in how we use docker or we'll need to wipe the working directory each time. I'll seif there's an obvious hook for that.

**Comment by GMNGeoffrey** [comment]
I keep hitting similar issues like:

> auditwheel: error: cannot access /wheelhouse/iree_runtime_instrumented*cp37-cp37m-linux_x86_64.whl. No such file

Whereas the file is called `iree_runtime_gcmn_testing_runners_instrumented-0.1a1-cp37-cp37m-linux_x86_64.whl`

It seems like this doesn't work with a package suffix at all. Other than that, I believe the self-hosted runners are working.

**Comment by GMNGeoffrey** [comment]
Ok, all the jobs passing on the self-hosted runner: https://github.com/google/iree/actions/runs/2498033117. I filed https://github.com/google/iree/issues/9500 for support for package-suffix being broken

**Comment by GMNGeoffrey** [comment]
Now switched to release runners in a separate project. There are 3 64-core release runners, which should certainly make the linux build not the bottleneck on releases. Latest run (before uncommenting the mac build: https://github.com/google/iree/runs/6905353191)

**Comment by stellaraccident** [comment]
This is great - thank you!

**Comment by GMNGeoffrey** [comment]
I'm waiting till the latest release completes before messing with the setup any further, since we've already had it fail today

**Review by ScottTodd — APPROVED** [review]

**Comment by GMNGeoffrey** [comment]
> I'm waiting till the latest release completes before messing with the setup any further, since we've already had it fail today

Unfortunately, I think this will have to wait until we can have GitHub runner groups. Going to drop back to draft for now

**Comment by GMNGeoffrey** [comment]
Ok I've got secure release builders set up. Unfortunately, making them secure included restricting the workflow version that could run to "main", so this is impossible to test presubmit. I think we can probably add some configurability so that someone can test the build on our presubmit, but there's no way to test the runners on presubmit, so... yolo?

**Comment by ScottTodd** [comment]
> @ScottTodd @stellaraccident are you OK with me going ahead and merging this? If releases fail we can roll back (and I'll kick of a release immediately). Unfortunately the controls GitHub gives us aren't fine-grained enough for what we want here.

Are you going to be online to monitor and deal with any issues? I'm basically offline now through next Wednesday...

**Comment by GMNGeoffrey** [comment]
> > @ScottTodd @stellaraccident are you OK with me going ahead and merging this? If releases fail we can roll back (and I'll kick of a release immediately). Unfortunately the controls GitHub gives us aren't fine-grained enough for what we want here.
> 
> Are you going to be online to monitor and deal with any issues? I'm basically offline now through next Wednesday...

Me too :-D I can wait till next week. @stellaraccident if you want fast releases in the meantime, feel free to merge this and be prepared to revert if necessary

**Comment by GMNGeoffrey** [comment]
JK, I'll be online for a bit now so I'll go ahead and do this

**Comment by GMNGeoffrey** [comment]
Well the first thing I've learned: the "schedule candidate release" workflow invokes the "build release packages" workflow using the workflow file from the tag it just created. I'm not sure how that will interact with the runner group workflow restrictions.

Also, I have a syntax error in my bash. Reverting

**Comment by GMNGeoffrey** [comment]
> Well the first thing I've learned: the "schedule candidate release" workflow invokes the "build release packages" workflow using the workflow file from the tag it just created. I'm not sure how that will interact with the runner group workflow restrictions.

It interacts poorly. Looks like the restriction means that the ref literally has to be "main" and a tag pointing at some past commit on main doesn't work. So we can restrict to a specific workflow, but can't really use the pretty limited feature to limit the ref. There's no option to specify matching patterns for the ref or anything either. And workflows are just the filename and don't distinguish between forks and the main repo because the ref it's looking at is actually `refs/merges/<pr number>` on the main repo. So... runner groups look to actually be completely useless here

**Pull request merged**
