### PR TITLE
[Codegen] Remove depreciated vector distribution transform codegen path

### PR DESCRIPTION
**Pull request by Groverkss**
Removes iree_vector_ext.layout attribute for VectorExt and other related passes which were required for the vector distribution transform dialect path. This path is now depreciated.

### CODE REVIEW

**Review by kuhar — APPROVED** [review]
I love this

**Comment by bjacob** [comment]
Nice! Does this mean that this code can now also be removed from this header:
https://github.com/iree-org/iree/blob/1654ce6dd4cb36061b453e37892d40da2f493bcf/compiler/src/iree/compiler/Codegen/Dialect/GPU/IR/IREEGPUAttrs.h#L71-L85

Meaning, that `struct OpaqueMmaLayout` can move into `IREEGPUAttrs.cpp`, and the `getOpaqueMMALayout` function becomes `static` in `IREEGPUAttrs.cpp`?

**Comment by Groverkss** [comment]
> Nice! Does this mean that this code can now also be removed from this header:
> 
> https://github.com/iree-org/iree/blob/1654ce6dd4cb36061b453e37892d40da2f493bcf/compiler/src/iree/compiler/Codegen/Dialect/GPU/IR/IREEGPUAttrs.h#L71-L85
> 
> Meaning, that `struct OpaqueMmaLayout` can move into `IREEGPUAttrs.cpp`, and the `getOpaqueMMALayout` function becomes `static` in `IREEGPUAttrs.cpp`?

Yes! Do you want me to do it in this patch or a seperate patch?

**Comment by bjacob** [comment]
> Yes! Do you want me to do it in this patch or a seperate patch?

Up to you!

**Review by qedawkins — APPROVED** [review]
🎉

(depreciated -> deprecated)

**Comment by Groverkss** [comment]
> > Yes! Do you want me to do it in this patch or a seperate patch?
> 
> Up to you!

I'll do it in a follow up patch then :)

**Pull request merged**
