### PR TITLE
[LLVMCPU] Add a flag to disable pad + consumer fusion passes by default

### PR DESCRIPTION
**Pull request by hanhanW**
The passes increase the compilation time even there are no pad ops. Disable the passes until fixing the bug.

https://github.com/iree-org/iree/issues/10820

### CODE REVIEW

**Comment by hanhanW** [comment]
it looks like we have compilation time improvements after integrates. Let me rebase it to ToT and see if the regression is false positive.

**Review by MaheshRavishankar — APPROVED** [review]
LGTM! Lets chat about priorities here. Instead of working more on this path (which I view as short term solution, maybe we can prioritize the actual way of handling padding and just once and for all put to rest the comments on fills + memcpys that comes up every other day)

**Comment by dcaballe** [comment]
LGTM. I guess this won't impact RISC-V as we don't have padding enabled by default, right?

**Comment by hanhanW** [comment]
> LGTM! Lets chat about priorities here. Instead of working more on this path (which I view as short term solution, maybe we can prioritize the actual way of handling padding and just once and for all put to rest the comments on fills + memcpys that comes up every other day)

I would mark pad + consumer is done, and deprioritize the investigation about compilation time regression.

> LGTM. I guess this won't impact RISC-V as we don't have padding enabled by default, right?

It does not impact the generated vmfb for default path and experimental path, so it won't impact RISC-V perf for sure. To clarify, the padding is not generated by codegen. This is not a DoubleTilingPadExpert stuff. The pad op is created by the model. There is a pass called `iree-flow-enable-fuse-padding-into-linalg-consumer-ops`, which allows pad + consumer being in a single dispatch. These passes are aimed to handle the case. You could get perf improvements if compile the model with `iree-flow-enable-fuse-padding-into-linalg-consumer-ops` flag and the LLVMCPU flag for convolution models. Again, it is under experimental flags, so it's not on by default.

**Pull request merged**
