### PR TITLE
Integrate llvm/llvm-project@dc275fd03254 

### PR DESCRIPTION
**Pull request by antiagainst**
* Updated to llvm/llvm-project@dc275fd03254 
* Updated to tensorflow/mlir-hlo@df8aeb5

### CODE REVIEW

**Comment by hanhanW** [comment]
The failing tests are `foreach-thread-to-async.mlir` and `foreach-thread-to-scf-for.mlir`. They don't have any users; that's why I'd like to deprecate them in https://github.com/openxla/iree/pull/12756

Maybe we can disable the tests to unblock integrate for now?

**Comment by MaheshRavishankar** [comment]
If it is not an easy fix, then yeah, disable the test and file a bug. @hanhanW you can link the bug in your PR as justification for deprecation (maintenance burden on things not really used/not planned on being used is justification for deprecation)

**Comment by okkwon** [comment]
Created an issue for re-enabling those tests: https://github.com/openxla/iree/issues/13374

**Review by hanhanW — APPROVED** [review]

**Review by MaheshRavishankar — APPROVED** [review]

**Comment by MaheshRavishankar** [comment]
There is a compilation time regression on CUDA. @okkwon can you take a look before landing?

**Comment by hanhanW** [comment]
The compilation time looks fine to me. The recent runs are all about 185k. It is very noisy, and the baseline seems to be outdated.

image

**Comment by okkwon** [comment]
Thanks Hanhan for the analysis. @MaheshRavishankar do you have any other concerns?

**Comment by MaheshRavishankar** [comment]
Nope. Good to go

**Pull request merged**
