### PR TITLE
Avoid fusing broadcast + compute.

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
Current elementwise op fusion heuristics fused producers with single
use into consumers unconditionally. If the use in the consumer is done
using a projected permutation, that leads to redundant
computations. This patch fixes that. There might be some increases in
number of dispatches for a few use cases, we can revisit if it has
latency implications but that doesnt seem to be the case.

Issue #13271

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
@silvasean can you import this change somehow to see the impact. It fixes the fusion issue, but latency might not be affected cause it is probably more related to backend. This change itself does not seem to have latency/binary size impact in our tracked benchmarks, so looking for signal if this helps or not. I still do think this is worth landing.

**Review by hanhanW — APPROVED** [review]

**Comment by okkwon** [comment]
This fixes https://github.com/openxla/iree/issues/13211 too. Thanks @MaheshRavishankar

**Comment by mariecwhite** [comment]
This increases compile time significantly. What used to take 15 mins to compile ~20 models is taking >4 hours.

**Comment by MaheshRavishankar** [comment]
That's unfortunate! I didn't see anything on the runners here, neither I saw anything locally. This  should be a fairly innocuous change. Some matcher is going of the rails. @mariecwhite can you help with narrowing down the benchmark that is having a regression here?

**Comment by MaheshRavishankar** [comment]
Looks like the CUDA builds are timing out... (I tested CPU builds locally and they seem fine). So this is blocked by #13189

**Comment by ThomasRaoux** [comment]
the fix for compile time landed, can we rebase on top of tree?

**Comment by MaheshRavishankar** [comment]
It is rebased. There seems to be a regression in CUDSA dispatch sizes. Also correctness issue on Riscv , but that might be an LLVM issue

**Pull request merged**
