### PR TITLE
Bump torch-mlir to 087fea0608dac3995b74e5c22ae7950287fe7a73

### PR DESCRIPTION
**Pull request by renxida**
Updating torch-mlir to the latest commit 087fea0608dac3995b74e5c22ae7950287fe7a73 on 2024-04-29

### CODE REVIEW

**Comment by renxida** [comment]
Looks like we're getting stuck at 
`FAILED SHARK-TestSuite/iree_tests/onnx/node/generated/test_selu_default/model.mlir::gpu_vulkan_test`

This test case is not included for the most recent successful CI run (https://github.com/iree-org/iree/actions/runs/8881454008/job/24384255449?pr=17217)

I am tempted to just xfail it but maybe i should dive deeper and debug it.

**Comment by ScottTodd** [comment]
> Looks like we're getting stuck at `FAILED SHARK-TestSuite/iree_tests/onnx/node/generated/test_selu_default/model.mlir::gpu_vulkan_test`
> 
> This test case is not included for the most recent successful CI run (https://github.com/iree-org/iree/actions/runs/8881454008/job/24384255449?pr=17217)
> 
> I am tempted to just xfail it but maybe i should dive deeper and debug it.

This is newly passing, so you can remove from xfail:
```
=================================== FAILURES ===================================
___________ IREE compile and run: test_selu_default::gpu_vulkan_test ___________
[gw0] linux -- Python 3.11.9 /runner-root/actions-runner/_work/iree/iree/venv/bin/python
[XPASS(strict)] Expected run to fail (remove from 'expected_run_failures')
```
https://github.com/iree-org/iree/actions/runs/8883049124/job/24389431136?pr=17223#step:9:47

When https://github.com/iree-org/iree/pull/17207 is landed, the CI runs will just upload a .json file for each job that you can download and then commit + push

**Comment by ScottTodd** [comment]
> Updating torch-mlir to the latest commit 087fea0608dac3995b74e5c22ae7950287fe7a73 on 2024-04-29

also, please include the repo along with the commit hash so GitHub turns it into a link, e.g. https://github.com/llvm/torch-mlir/commit/087fea0608dac3995b74e5c22ae7950287fe7a73 (`https://github.com/llvm/torch-mlir/commit/087fea0608dac3995b74e5c22ae7950287fe7a73`)

**Comment by renxida** [comment]
Updating [auto bump script](https://gist.github.com/renxida/c0d90934b77260f8ad00e62d7981a157) to do the commit link automatically. Closing & will create another pr to test new script.

**Pull request closed without merging**
