### PR TITLE
[LinalgExt][Winograd] Add winograd.filter_transform op

### PR DESCRIPTION
**Pull request by Max191**
This PR adds the `iree_linalg_ext.winograd.filter_transform` op, and enables the generation of this op in `ConvertConv2DToWinograd` instead of doing constant folding in the pass. This will enable const-eval folding for the filter transform, which will improve compile times and allow for more robust winograd constant folding.

### CODE REVIEW

**Comment by Max191** [comment]
I still need to fix the `conv2d_to_winograd.mlir` tests in LinalgExt, but everything is in place.

EDIT: I also need to add support in the SPIRV pipeline.

**Review by MaheshRavishankar — COMMENTED** [review]
Can you split this PR to just adding the winograd filter op first and then follow up that ties everything together?

**Comment by hanhanW** [comment]
> Can you split this PR to just adding the winograd filter op first and then follow up that ties everything together?

+1, I think this is similar to what I meant for "next PR" in https://github.com/openxla/iree/pull/17061#pullrequestreview-2004526180 comment. Please split the PR to a couple smaller PRs.

**Comment by Max191** [comment]
> Can you split this PR to just adding the winograd filter op first and then follow up that ties everything together?

Yes, sorry for the big PR again. Now that I confirmed things are working I'll split it into:
 - Add winograd filter op + interface functions
 - Start generating the op in `ConvertConv2DToWinograd` and support it in LLVMCPU + SPIRV pipelines

**Comment by hanhanW** [comment]
> Start generating the op in ConvertConv2DToWinograd and support it in LLVMCPU + SPIRV pipelines

Can it be two PRs? So LLVMCPU developers won't need to look at SPIRV part, and vice versa. The other benefits I can think of is that we don't need to partially revert the single commit if one of the backends is broken on main branch (after we land it).

**Comment by hanhanW** [comment]
> Add winograd filter op + interface functions

This can also be a couple of PRs.

1. Add winograd filter op + some roundtrip tests.
2. interface functions + corresponding tests.

**Comment by Max191** [comment]
I have split this PR up into 5 separate PRs so far (with one more coming for SPIRV pipeline):
 - https://github.com/openxla/iree/pull/17102 Adds the new op with basic interface functions
 - https://github.com/openxla/iree/pull/17103 Adds the decomposition
 - https://github.com/openxla/iree/pull/17104 Adds tiling
 - https://github.com/openxla/iree/pull/17105 Adds LLVMCPU support
 - https://github.com/openxla/iree/pull/17106 updates `ConvertConv2DToWinograd`

**Pull request closed without merging**
