### PR TITLE
Bump TF to 2024-01-24 nightly

### PR DESCRIPTION
**Pull request by jpienaar**
Also bump torch-mlir to 10acea7 to pick up fixes.

#16173

### CODE REVIEW

**Comment by jpienaar** [comment]
torch-mlir was bumped again hour ago. I'll see what the presubmits say here (image at least updated and uploaded).

**Comment by hanhanW** [comment]
I think you probably need to cherry-pick this commit: https://github.com/shark-infra/torch-mlir/commit/65f75ab7124fa000433aab2709553ec91a22fdde to our torch-mlir submodule

Or wait for torch-mlir repo until they bump llvm and fix the issue.

**Comment by jpienaar** [comment]
I'll try picking that one.

**Comment by jpienaar** [comment]
I can't push to shark-infra so can't update the LLVM instance to reapply the TOSA change to allow this to pass. Will need someone to push that and give a rev to use. Or just push an update to submodule on this branch.

**Comment by hanhanW** [comment]
I dropped the revert and push it to shark-infra.

**Comment by hanhanW** [comment]
oh, it looks like I need to help bump torch-mlir submodule as well

**Comment by hanhanW** [comment]
I bump torch-mlir to https://github.com/llvm/torch-mlir/commit/28c7051ceb5a49944dfbd0d1fdf1ada4ac2a5b9e which includes a recent local fix in IREE.

**Comment by hanhanW** [comment]
unused variables again... I'm not going to fix that in torch-mlir repo. Let's bump to what we have and I will cherry-pick the local fix.

```
/work/third_party/torch-mlir/lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp:2620:13: error: unused variable 'zeroList' [-Werror,-Wunused-variable]
      Value zeroList = rewriter.create<PrimListConstructOp>(
```

**Review by hanhanW — APPROVED** [review]

**Pull request merged**
