### PR TITLE
Delete all in-tree benchmark infrastructure code.

### LINKED ISSUE #7795: Handle benchmarking warmup runs better
Right now for each benchmark, we run [10 repetitions](https://github.com/google/iree/blob/64bda351975b968331d84d1c3fe587ba0116b239/build_tools/benchmarks/run_benchmarks_on_android.py#L101) to collect statistics. For each _repetition_, we use Google Benchmark's warmup mechanisms to deduce how many _iterations_ should run, which gives Google Benchmark confidence that the numbers are stable and representative. However, Google Benchmarks are more geared towards microbenchmarks. For full model benchmarks we have, it can cause Google Benchmark to believe one iteration will suffice. Only a single iteration can be problematic as it might just be a cold start run that happens to take longer time. So even if we have 10 repetitions, they can all be cold start runs, which skews the result. So we might want to handle warmups more explicitly.

### LINKED ISSUE #8631: Improve CPU ABI naming in the benchmark
Currently we have `__get_arm_cpu_arch_revision` in the benchmark tool to derive the subversion of ARM processor, such as `ARMv8.2-A`. Our method to derive it is not complete, and we might just want to have `ARMv8-A`. However, there are also ARMv9 processors reporting `ARMv8-A` as CPU ABI, and we still want to differentiate them.

Changing the naming will also invalid the existing records in perf dashboard, we need a backfill to fix them.

### LINKED ISSUE #10599: Refactor bazel_to_cmake_converter to use cmake_builder
We now added the python module to build CMake rule for benchmark suites. We need to refactor `bazel_to_cmake_converter.py` to reuse the same helpers.

### LINKED ISSUE #10928: Improve the checked-in generated cmake files
Right now we generate the cmake files from python scripts (for benchmarks and e2e tests) and commit them into the repo.

The file size can be quite large in some cases (e.g. ~2000 lines in `benchmarks/generated_benchmark_suites.cmake`). We might re-evaluate the methods to only generate it when configuring CMake or reduce the file size (e.g. use for loop in the generated files).

If we generate the files during CMake configuration, it also solves the issue #10557

### LINKED ISSUE #11703: Re-index the git build id with --first-parent
Currently we use `git rev-list --count main` to get the commit count for indexing the benchmark series. However, when there is a merge commit, the current way will result in a big jump on the commit count.

We should use `git rev-list --first-parent --count main` instead. This change will require re-index all benchmark series based on the new count on their commits.

### LINKED ISSUE #11922: Stablize compilation time measurement in benchmarks
Right now we measure the compilation time for compiling various models. Though the numbers reported can vary a lot. For example, [this one ranges from 60s to 140s](https://perf.iree.dev/serie?IREE?MobileBertSquad%20%5Bfp32%5D%20(TFLite)%20GPU-Mali-Valhall%20full-inference%2Cexperimental-flags%20%5Bcompilation%3Amodule%3Acompilation-time%5D); similarly for [CPU](https://perf.iree.dev/serie?IREE?MobileBertSquad%20%5Bfp32%5D%20(TFLite)%20CPU-ARM64-v8A%204-thread%2Cbig-core%2Cfull-inference%2Cdefault-flags%20%5Bcompilation%3Amodule%3Acompilation-time%5D). With such a level of noisiness we cannot draw any meaningful information out of it and it's actually a distraction. We'd need to figure out ways to make the numbers more stable.

### LINKED ISSUE #11953: Offer more x86_64 configurations for benchmarking
Running and building benchmarks for x86_64 (build target `iree-benchmark-suites` and the script `build_tools/benchmarks/run_benchmarks_on_linux.py`) currently only works on `CascakeLake`-capable architectures.

It would be nice to offer a richer feature set to be able to run on non-`CascadeLake` compatible hardware.

@pzread laid down what it should look like in https://github.com/iree-org/iree/pull/11914#issuecomment-1402920267.

### LINKED ISSUE #14993: Update generated PyTorch MLIR in benchmark suites
A dialect update causes the generated PyTorch MLIR fail to compile.

We need to regenerate MLIR with https://github.com/llvm/torch-mlir/pull/2466

### LINKED ISSUE #15452: Revamp Android Benchmarks
### Request description

Given recent changes to how cpu-features are getting picked up, we need to update the Android benchmarks.

1. Use `--iree-llvmcpu-target-cpu` instead of `--iree-llvmcpu-target-cpu-features`. This means no separation between `quant` and `non-quant` models and manually adding CPU features such as `+dotprod`.

This does complicate the pipeline. We'll need a mapping for each phone and core used. So using a (taskset, target-cpu) tuple:

Pixel 6: (c0, cortex-x1), (30, cortex-a76), (0f, cortex-a55)
Pixel 8 Pro: (100, cortex-x3), (f0, cortex-a715), (0f, cortex-a510)
Motorola Edge+: (100, cortex-x3), (c0, cortex-a715), (30, cortex-a710), (0f, cortex-a510)

2. Change the number of threads and cpu core group naming. At the moment we bundle cores into either big and little, but there's actually a spectrum. Another reason why GPT-2 is noisy is that it's actually running on 2 different cores (cortex-x1 2.8Ghz and cortex-a76 2.25 Ghz).

To reduce noise, let's make sure the benchmarks run on homogeneous cores. So using a (number of threads, taskset) tuple:

Pixel 6: (1, 80), (2, c0)
Pixel 8 Pro: (1, 100), (4, f0)
Motorola Edge+: (1, 100), (2, c0)

It may not be the fastest configuration but should reduce noise. We can run the fastest configurations e.g. (5, 1f0) either under `benchmark-large.yml` or the `openxla-benchmark` repo.

### What component(s) does this issue relate to?

Other

### Additional context

_No response_

### LINKED ISSUE #16057: xla_hlo_before_optimizations.txt in benchmarks
Why are xla_hlo_before_optimizations.txt files in the uploaded artifacts?

### PR DESCRIPTION
**Pull request by ScottTodd**
See the related RFC: https://groups.google.com/g/iree-discuss/c/n039Q0trkHk

Deleted components _directly_ related to benchmark infrastructure:
* Workflow files in `.github/workflows/`: benchmark triggering, e2e test artifact generation, benchmark compilation stats, benchmark execution, comment posting
* Benchmark configuration and series definitions (mix of Python scripts, CMake generators, CMake files, etc.)
* Documentation relating to benchmarks on pull requests / using GitHub Actions

Deleted components _indirectly_ related to benchmark infrastructure:
* Support scripts like `build_tools/benchmarks/set_android_scaling_governor.sh` (could be useful for developers, but doesn't need to live in-tree)
* `iree_run_module_test` (was used to test correctness for _some_ benchmark workloads but was not fully adopted)
* Build presets in `build_tools/cmake/` scripts (e.g. `test`, `benchmark`, `benchmark-with-tracing`): too complex, trying to steer away from build scripts and towards CMake presets or explicit workflows without that indirection

Future cleanup possibilities:
* `build_all.yml` (no longer any references)
* Docker files: android, nvidia, nvidia-bleeding-edge

Closes https://github.com/iree-org/iree/issues/7795
Closes https://github.com/iree-org/iree/issues/8631
Closes https://github.com/iree-org/iree/issues/10599
Closes https://github.com/iree-org/iree/issues/10928
Closes https://github.com/iree-org/iree/issues/11703
Closes https://github.com/iree-org/iree/issues/11922
Closes https://github.com/iree-org/iree/issues/11953
Closes https://github.com/iree-org/iree/issues/14993
Closes https://github.com/iree-org/iree/issues/15452
Closes https://github.com/iree-org/iree/issues/16057
Closes https://github.com/iree-org/iree/issues/16157
Closes https://github.com/iree-org/iree/issues/16396
Closes https://github.com/iree-org/iree/issues/16431
Closes https://github.com/iree-org/iree/pull/17749

### CODE REVIEW

**Review by benvanik — APPROVED** [review]

**Comment by benvanik** [comment]
party

**Comment by ScottTodd** [comment]
Synced and added a list of issues this will close as no longer relevant. Getting ready to merge soon.

**Review by antiagainst — APPROVED** [review]
Here you go!! :D

**Comment by hanhanW** [comment]
So many issues are closed! `+39 −23,393` is amazing.

**Pull request merged**
