### PR TITLE
add regression test for #12546

### PR DESCRIPTION
**Pull request by bjacob**
This is a minimized e2e regression test for #12546.  The apparent symptom there was e2e matmul tests with data tiling were failing. This test narrows it down to the `tensor.pack` of the RHS specifically (the one side that gets transposed) and for very specific outer-product shapes (here RHS is 1x9).

This test succeeds if rebased to before the regressing LLVM integrate discussed in #12546.  But after that integrate, and on current `main` branch, it fails as follows:

```
[ RUN      ] module.pack_pad_transpose_1x9_into_2x4x8x4_issue_12546.mlir
iree/runtime/src/iree/modules/check/module.cc:269: Failure
Failed
Expected equality of these values. Contents does not match.
  lhs:
    2x4x8x4xi8=[[[49 0 0 0][2 0 0 0][3 0 0 0][4 0 0 0][5 0 0 0][6 0 0 0][7 0 0 0][8 0 0 0]][[0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0]][[0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0]][[0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0]]][[[95 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0]][[0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0]][[0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0]][[0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0]]]
  rhs:
    2x4x8x4xi8=[[[1 0 0 0][2 0 0 0][3 0 0 0][4 0 0 0][5 0 0 0][6 0 0 0][7 0 0 0][8 0 0 0]][[0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0]][[0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0]][[0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0]]][[[9 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0]][[0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0]][[0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0]][[0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0][0 0 0 0]]]
```

### CODE REVIEW

**Comment by bjacob** [comment]
Note: presubmits are green because the issue that this catches is Android-only.

Android e2e tests are already failing (#12546) because of the issue that this catches -- this just adds a minimized e2e, but still e2e, testcase for the same issue, equally failing or succeeding depending on whether we have the fix. As such I believe that we could just merge this now regardless of the fix's status.

**Review by hanhanW — APPROVED** [review]

**Comment by ScottTodd** [comment]
> Note: presubmits are green because the issue that this catches is Android-only.

The new macOS CI (postsubmit) failed on this: https://github.com/openxla/iree/actions/runs/4368362102/jobs/7640840868#step:7:150

**Comment by antiagainst** [comment]
Yup. We have non-Android AArch64 bots now. :)

**Comment by hanhanW** [comment]
I think Benoit is off, and we can revert it for now.

**Comment by hanhanW** [comment]
hmm I just found that it's expected to be failed on Android and macOS because the upstream fixes are not propagated to IREE yet. In this case, do we revert the commit?

**Comment by bjacob** [comment]
Oh, I thought: if we have any AArch64 CI then it's already failing anyway due to #12546, so I might as well merge this.

And the failure in #12546 would affect any aarch64+dotprod CPU, including the Apple M1.

I guess what I was missing was that our build-system somehow specializes Android, only enabling the failing tests there (?). That would explain why our AArch64 CI didn't see #12546 but is now seeing this.

I'm at EOD, sorry, feel free to either revert this or wait for the llvm integrate or cherrypick that will fix #12546.

Keep in mind that the failure in #12546 is very real.   It means we produce incorrect results by reading uninitialized memory on i8 matmuls on any aarch64+dotprod CPU.  That includes Apple M1.  I hope we don't have too many users yet, but the reason why I jumped on this last night was I feel uncomfortable about this.  At least this PR makes it clear in our CI status that we are currently broken on aarch64, so users who run our tests to check if they have picked a good IREE commit, can at least find about this and check out another commit. If we revert this PR, we hide that useful information from our CI status.

**Comment by ScottTodd** [comment]
It sounds like we're waiting for some upstream LLVM commits to land before this is fully fixed in IREE. Adding the regression test after those commits are integrated makes sense to me.

(Also thanks so much for reducing a regression test case for the bug - it's great to see that it fails before the fixes land :D)

**Comment by hanhanW** [comment]
I'm +1 on what Benoit said. IREE is at a state that this is broken. Reverting the commit is sort of hiding the issue to me. While I also agree that we should keep CI green. The fixes should be integrated in few days. I'm fine with both.

**Comment by ScottTodd** [comment]
I think we're past the point where reverting an LLVM integrate is going to be easy (another one is already started). If the issue is severe enough, we could make a note to not promote any nightly releases in this range to stable.

**Comment by antiagainst** [comment]
Given this is already landed, let's not churn to revert it again--we have failing Android tests so newly landed commits will see a cross mark anyway. Hopefully we can cherry-pick the upstream fixes in the next integration. @vmurali FYI

**Comment by bjacob** [comment]
We also have the option to resolve this by cherry-picking the fix.  The fix commit depends itself on 3 other very recent commits changing the same file, so total 4 commits, listed here https://github.com/openxla/iree/issues/12546#issuecomment-1460420995 . Happy either way but since those are already in the upstream main branch and the present issue matters enough that 4 people have been discussing it, this might be kind of situation that cherry-picks are there for.

**Comment by bjacob** [comment]
Nevermind, I hadn't see that Hanhan already did it :-) (#12568)

**Comment by bjacob** [comment]
@ScottTodd @hanhanW  Actually it seems abnormal that the macOS/arm64 CI wasn't running the same e2e matmul tests that Android/arm64 CI was.  If this isn't some unnecessary Android-only logic (which we should fix) then I wonder if this might be an accident of how CMAKE_SYSTEM_PROCESSOR is not standardized, so we might be unwittingly excluding macOS/arm64 by not checking for the value that that variable has there (e.g. arm64 vs aarch64 vs...).

I'd like to debug that if I get around to setting up my mac for development...

**Pull request merged**
