### PR TITLE
[Codegen][ROCm] Add a codegen pipeline for supported MFMA variants

### PR DESCRIPTION
**Pull request by qedawkins**
The codegen pipeline added here, termed LLVMGPUVectorDistribute, uses
the vector distribution patterns to do distribution to MFMA types. This
is work in progress.

### CODE REVIEW

**Comment by qedawkins** [comment]
Didn't mean to open yet, going to close to avoid pings.

**Comment by antiagainst** [comment]
I received two pings of opening and closing it. ;-P

**Comment by qedawkins** [comment]
yeah sorry :(

**Comment by antiagainst** [comment]
haha, no worries! I was just kidding. :D

**Pull request closed without merging**
