### PR TITLE
Revert "[CMake] Add dep for ukernel internal headers (#15462)"

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
This reverts commit b6d7b830c7cc1f89ca87954cef0a17173964a474. The commit broke Windows build.

### CODE REVIEW

**Review by raikonenfnu — APPROVED** [review]
Thanks Mahesh!

**Comment by ScottTodd** [comment]
Can you elaborate on what that broke / share logs? Our Windows CI is green and I've been building with no problems.

**Comment by ScottTodd** [comment]
Also, please comment on the original PR or tag the author (@RoboTux in this case)

**Comment by raikonenfnu** [comment]
> Can you elaborate on what that broke / share logs? Our Windows CI is green and I've been building with no problems.

"touch" is not a valid command in power shell.

**Comment by ScottTodd** [comment]
> > Can you elaborate on what that broke / share logs? Our Windows CI is green and I've been building with no problems.
> 
> "touch" is not a valid command in power shell.

Arghhhh yeah... okay, I spotted that and figured it worked fine with bash on Windows (what our CI uses and what I use on my dev machine). I did look during the review a bit to see if there was a CMake-native way to touch a file that would fit the usage there... should continue down that path.

Revert SGTM then.

(edit: https://cmake.org/cmake/help/v3.21/command/file.html#writing is a little different than the usage there)

**Comment by ScottTodd** [comment]
(It amazes me that people can tolerate powershell, but I guess we should still support it 😅)

**Comment by bjacob** [comment]
Filed https://github.com/openxla/iree/issues/15560 about catching PowerShell regressions in our own CI, not just downstream CI.

**Pull request merged**
