### PR TITLE
Revert "Bump torch-mlir to https://github.com/llvm/torch-mlir@141202bc"

### PR DESCRIPTION
**Pull request by qedawkins**
This reverts commit a47a47fcfc94bb5266fcf28f8c17e0aeb5b29632. See the discussion in https://discord.com/channels/689900678990135345/1062405112292712499/1182338050664185999

### CODE REVIEW

**Review by ScottTodd — APPROVED** [review]
As discussed on Discord, we can either land this or go for a fix-forward, if https://github.com/llvm/torch-mlir/pull/2617 is merged soon.

**Comment by qedawkins** [comment]
Just waiting on torch-mlir CI, not sure how long it normally takes.

**Comment by ScottTodd** [comment]
> Just waiting on torch-mlir CI, not sure how long it normally takes.

macos-arm64 looks like it takes upwards of 2h-2h30m, windows-x86_64 takes ~1h. Ouch...

**Comment by qedawkins** [comment]
> > Just waiting on torch-mlir CI, not sure how long it normally takes.
> 
> macos-arm64 looks like it takes upwards of 2h-2h30m, windows-x86_64 takes ~1h. Ouch...

ok well if you want to merge this now, that's fine with me. I'll let you make that call.

**Pull request merged**
