### PR TITLE
[CPU] Switch to new pass generation tablegen definitions 

### PR DESCRIPTION
**Pull request by hanhanW**
This is mostly an NFC change. It does more cleanups on ConvertToLLVM pass which moves private options to tablegen definition. Also, the revision removes a duplicated option from the ConvertToLLVM pass. The additional change is that it adds dependent dialects to ConvertToLLVM pass.

This is generally good because it removes the duplication of pass definition, and remove the magic numbers from the pass declarations. Before the change, we duplicate all the option default values to `Passes.h`.

Some passes are still defined in `Passes.h` because passing tablegen option struct is a visual noise. It makes the pipeline configuration much cleaner.

### CODE REVIEW

**Review by benvanik — COMMENTED** [review]
nice cleanup! <3

**Comment by hanhanW** [comment]
The `getDependentDialects` issue in ConvertToLLVM pass is annoying... It's still failing even I dup what we have in upstream.. I'll try to register the dialects myself. Sadly, I can't reproduce it locally, so I will rely on CI to test it..

**Comment by hanhanW** [comment]
Okay, the PR is ready to go. Can someone review it?

**Review by MaheshRavishankar — APPROVED** [review]
Nice!! Thanks! One folder down!

**Review by Max191 — APPROVED** [review]
Nice! Thanks Hanhan!

**Pull request merged**
