### PR TITLE
[EmitC] Support multiple variadic segments in `call.variadic` ops

### PR DESCRIPTION
**Pull request by simon-camp**

### CODE REVIEW

**Comment by marbre** [comment]
Duplicating https://github.com/iree-org/iree/issues/10810#issuecomment-1312270576:

Simon pointed me to the fact that we don't have an end-to-end test in which we test the inline HAL in conjunction with EmitC. Expect for this, PR https://github.com/iree-org/iree/pull/11114 should fine to go and it should at least add lit tests. The only reason that it is a draft is the missing e2e test. Therefore, I propose to merge https://github.com/iree-org/iree/pull/11114. In the case, I will add a lit test at the beginning of next week.

**Comment by marbre** [comment]
It would be awesome if you could review @benvanik if the proposed course of action is fine for you.

**Review by benvanik — APPROVED** [review]

**Comment by benvanik** [comment]
(ok to land - just ready it for review if it's still what you want and I'll merge it)

**Comment by marbre** [comment]
> (ok to land - just ready it for review if it's still what you want and I'll merge it)

I can convert it from a draft to ready for review as it is @simon-camp's PR :see_no_evil:

**Comment by benvanik** [comment]
🧙

**Pull request merged**
