### PR TITLE
Enable detensorize by default

### LINKED ISSUE #1159: Tensor-to-primitive/detensoring HLO conversion
HLO can only represent tensors, meaning that values that should not be tensors are still wrapped in them and operated on just as if they were real dense data. This is most easily visible with loops and conditionals, where the loop iterator initialization, increment, and condition are all in tensors. This results in host readbacks and a bunch of other extraneous work when really these should just be modeled as simple primitive values (i32/index, etc).

For example, this input loop:

```mlir
  func @main() -> tensor<i32> attributes {iree.module.export} {
    %cst = constant dense<1> : tensor<i32>
    %cst_0 = constant dense<3> : tensor<i32>
    %0 = iree.do_not_optimize(%cst) : tensor<i32>
    %1 = iree.do_not_optimize(%cst_0) : tensor<i32>
    %2 = "xla_hlo.while"(%0) ( {
    ^bb0(%arg0: tensor<i32>):	// no predecessors
      %3 = "xla_hlo.compare"(%arg0, %1) {comparison_direction = "LT"} : (tensor<i32>, tensor<i32>) -> tensor<i1>
      "xla_hlo.return"(%3) : (tensor<i1>) -> ()
    },  {
    ^bb0(%arg0: tensor<i32>):	// no predecessors
      %3 = xla_hlo.add %arg0, %arg0 : tensor<i32>
      "xla_hlo.return"(%3) : (tensor<i32>) -> ()
    }) : (tensor<i32>) -> tensor<i32>
    return %2 : tensor<i32>
  }
```

is turned into the following CFG:

```mlir
func @main() -> tensor<i32> attributes {iree.module.export} {
  %cst = constant dense<1> : tensor<i32>
  %cst_0 = constant dense<3> : tensor<i32>
  %0 = iree.do_not_optimize(%cst) : tensor<i32>
  %1 = iree.do_not_optimize(%cst_0) : tensor<i32>
  br ^bb1(%0 : tensor<i32>)
^bb1(%2: tensor<i32>):	// 2 preds: ^bb0, ^bb2
  %3 = "xla_hlo.compare"(%2, %1) {comparison_direction = "LT"} : (tensor<i32>, tensor<i32>) -> tensor<i1>
  %4 = extract_element %3[] : tensor<i1>
  cond_br %4, ^bb2(%2 : tensor<i32>), ^bb3(%2 : tensor<i32>)
^bb2(%5: tensor<i32>):	// pred: ^bb1
  %6 = xla_hlo.add %5, %5 : tensor<i32>
  br ^bb1(%6 : tensor<i32>)
^bb3(%7: tensor<i32>):	// pred: ^bb1
  return %7 : tensor<i32>
}
```

Which then after lowering through flow has the condition dispatched to the device and the condition read back (via `flow.tensor.load`):

```mlir
func @main() -> tensor<i32> attributes {iree.module.export} {
  %cst = constant dense<1> : tensor<i32>
  %cst_0 = constant dense<3> : tensor<i32>
  %cst_1 = constant dense<1> : vector<3xi32>
  %0 = iree.do_not_optimize(%cst) : tensor<i32>
  %1 = iree.do_not_optimize(%cst_0) : tensor<i32>
  br ^bb1(%0 : tensor<i32>)
^bb1(%2: tensor<i32>):	// 2 preds: ^bb0, ^bb2
  %3 = flow.ex.stream.fragment(%arg0 = %cst_1 : vector<3xi32>, %arg1 = %2 : tensor<i32>, %arg2 = %1 : tensor<i32>) -> tensor<i1> {
    %8 = flow.dispatch @main_ex_dispatch_0::@main_ex_dispatch_0[%arg0 : vector<3xi32>](%arg1, %arg2) : (tensor<i32>, tensor<i32>) -> tensor<i1>
    flow.return %8 : tensor<i1>
  }
  %4 = flow.tensor.load %3 : tensor<i1>
  cond_br %4, ^bb2(%2 : tensor<i32>), ^bb3(%2 : tensor<i32>)
^bb2(%5: tensor<i32>):	// pred: ^bb1
  %6 = flow.ex.stream.fragment(%arg0 = %cst_1 : vector<3xi32>, %arg1 = %5 : tensor<i32>) -> tensor<i32> {
    %8 = flow.dispatch @main_ex_dispatch_1::@main_ex_dispatch_1[%arg0 : vector<3xi32>](%arg1) : (tensor<i32>) -> tensor<i32>
    flow.return %8 : tensor<i32>
  }
  br ^bb1(%6 : tensor<i32>)
^bb3(%7: tensor<i32>):	// pred: ^bb1
  return %7 : tensor<i32>
}
```

If instead we found these host-only values (even if only scalar tensors to start) we could run the whole loop in the host VM and avoid the readback.

This is also visible in inputs that have dynamic update slices (translated through to `flow.tensor.update`), where the current loop iterator value is needed to know where to update the tensor (mapping back to which timestep is being processed, etc). These updates need to be recorded into the command buffer on the host which means that we perform a readback to effectively compute an offset and then throw it back to the device.

Other enhancements around indirect dispatch and dynamic `flow.tensor.update` (#1160) will make some of these cases not so bad when device->host data dependencies really do exist, however if we can remove all of the trivial cases without relying on that we'll have much more readable IR and much lower overhead at runtime.

### PR DESCRIPTION
**Pull request by rsuderman**
Wrote a simple cpu test that involves multiple iterations across
low compute workloads. Verified that we saw a 10% improvement in
performance due to detensoring the work. Validating on performance
benchmarks now.

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
Seems like benchmark results are pretty mixed?

**Comment by MaheshRavishankar** [comment]
Unfortunately, these all seem like noise. (Its hard to decouple noise from actual regression in our suite... not complaining, just stating as fact, and is a hard thing to do in general).
I'd say there is nothing obvious here that should be a cause for concern. Its a good feature to have, so ship it! If there are any issues, fix forward.

**Review by MaheshRavishankar — APPROVED** [review]

**Comment by antiagainst** [comment]
Yeah. We really need to look into the mobile CPU nosiness and see how to curb that down. Maybe at least increase the noisy control threshold for them..

**Comment by rsuderman** [comment]
It is worth noting that I was able to make a contrived example that demonstrates a monstrous performance improvement.

**Comment by rsuderman** [comment]
```
Benchmark                               Time             CPU   Iterations
-------------------------------------------------------------------------
BM_main/process_time/real_time      0.605 ms        0.605 ms          910
```

vs

```
Benchmark                               Time             CPU   Iterations
-------------------------------------------------------------------------
BM_main/process_time/real_time      0.013 ms        0.013 ms        52913
```

**Comment by rsuderman** [comment]
```
module @conways {
  func.func @main(%arg0: tensor<128x128xi32>, %arg1: tensor<i32>) {
    call @jit__conway.81$main(%arg0, %arg1) : (tensor<128x128xi32>, tensor<i32>) -> ()
    return
  }
  func.func private @jit__conway.81$main(%arg0: tensor<128x128xi32>, %arg1: tensor<i32>) {
    %0 = mhlo.constant dense<0> : tensor<i32>
    %1:3 = mhlo.while(%iterArg = %0, %iterArg_0 = %arg1, %iterArg_1 = %arg0) : tensor<i32>, tensor<i32>, tensor<128x128xi32>
     cond {
      %2 = mhlo.compare  LT, %iterArg, %iterArg_0,  SIGNED : (tensor<i32>, tensor<i32>) -> tensor<i1>
      "mhlo.return"(%2) : (tensor<i1>) -> ()
    } do {
      %2 = mhlo.constant dense<1> : tensor<i32>
      %3 = mhlo.add %iterArg, %2 : tensor<i32>
      %4 = mhlo.constant dense<0> : tensor<i32>
      %5 = "mhlo.broadcast"(%4) {broadcast_sizes = dense<> : tensor<0xi64>} : (tensor<i32>) -> tensor<i32>
      %6 = "mhlo.reduce_window"(%iterArg_1, %5) ({
      ^bb0(%arg2: tensor<i32>, %arg3: tensor<i32>):
        %19 = mhlo.add %arg2, %arg3 : tensor<i32>
        "mhlo.return"(%19) : (tensor<i32>) -> ()
      }) {base_dilations = dense<1> : tensor<2xi64>, padding = dense<1> : tensor<2x2xi64>, window_dilations = dense<1> : tensor<2xi64>, window_dimensions = dense<3> : tensor<2xi64>, window_strides = dense<1> : tensor<2xi64>} : (tensor<128x128xi32>, tensor<i32>) -> tensor<128x128xi32>
      %7 = mhlo.constant dense<4> : tensor<i32>
      %8 = "mhlo.broadcast_in_dim"(%7) {broadcast_dimensions = dense<> : tensor<0xi64>} : (tensor<i32>) -> tensor<128x128xi32>
      %9 = mhlo.compare  EQ, %6, %8,  SIGNED : (tensor<128x128xi32>, tensor<128x128xi32>) -> tensor<128x128xi1>
      %10 = mhlo.constant dense<0> : tensor<i32>
      %11 = "mhlo.broadcast_in_dim"(%10) {broadcast_dimensions = dense<> : tensor<0xi64>} : (tensor<i32>) -> tensor<128x128xi32>
      %12 = mhlo.compare  NE, %6, %11,  SIGNED : (tensor<128x128xi32>, tensor<128x128xi32>) -> tensor<128x128xi1>
      %13 = mhlo.and %12, %9 : tensor<128x128xi1>
      %14 = mhlo.constant dense<3> : tensor<i32>
      %15 = "mhlo.broadcast_in_dim"(%14) {broadcast_dimensions = dense<> : tensor<0xi64>} : (tensor<i32>) -> tensor<128x128xi32>
      %16 = mhlo.compare  EQ, %6, %15,  SIGNED : (tensor<128x128xi32>, tensor<128x128xi32>) -> tensor<128x128xi1>
      %17 = mhlo.or %13, %16 : tensor<128x128xi1>
      %18 = mhlo.convert(%17) : (tensor<128x128xi1>) -> tensor<128x128xi32>
      "mhlo.return"(%3, %iterArg_0, %18) : (tensor<i32>, tensor<i32>, tensor<128x128xi32>) -> ()
    }
    return
  }
}
```

**Pull request merged**
