### PR TITLE
Fix from Integrate llvm-project at 571eaead173b 

### LINKED ISSUE #13370: [Epic] Add BF16 Support
## Task list

- [x] Validate `bf16` changes for `cuda` address compilation issue @rsuderman 
- [x] #13459 @benvanik 
- [ ] #13414
- [ ] #13969
- [ ] Coordinate with llvm level `bf16` support @jpienaar
- [x] #13720
- [x] #13721
- [x] #13722
- [ ] Coordinate with customer once compilation passing @rsuderman

### What happened?

Repro IR reduced out of a large language model: [gist](https://gist.githubusercontent.com/silvasean/28f8dc8bf8afbe4c150d33d494e65339/raw)

Reproduce with:

```
iree-compile ir21.mlir --iree-hal-target-backends=cuda --iree-input-type=mhlo --iree-hal-cuda-llvm-target-arch=sm_80 -o ir21.vmfb
```

(this seems like the type of issue that will be obvious what a smaller test case is as debugging proceeds -- let me know if not the case and I can bisect the test case itself)

### What component(s) does this issue relate to?

Compiler

### Version information

iree.git @ ab37989652aed11f7f46498c09b9ac515c83eaa3

### PR DESCRIPTION
**Pull request by KoolJBlack**
Corrects issue here: https://github.com/openxla/iree/commit/ab37989652aed11f7f46498c09b9ac515c83eaa3

Fixes #13370

### CODE REVIEW

**Comment by manishucsd** [comment]
Is there an existing IREE test that this change affects?

**Review by MaheshRavishankar — APPROVED** [review]

**Comment by stellaraccident** [comment]
Hey folks, I've been looking at the set of changes around this and echo Manish's question: where is the test that guards this?

(further, this was claimed to have fixed https://github.com/openxla/iree/issues/13370#event-9151358943 but doesn't seem to have been verified)

**Comment by MaheshRavishankar** [comment]
I only saw the change to lowering to LLVM and seemed simple enough. Doesn't look like the change fixed the issue though (I am not a fan of auto merge being enabled on PRs that aren't approved yet)

**Comment by KoolJBlack** [comment]
Hey folks, apologies, I wrote this PR in the late hours of last night right as I was falling asleep (shouldn't do these past my bedtime). 

This fix is specifically for the mistake I made during my last integrate that Manish pointed out here https://github.com/openxla/iree/commit/ab37989652aed11f7f46498c09b9ac515c83eaa3. It wasn't meant to do more than that. 

Unfortunately, I don't know the cause of #13370 or if this is actually related. @stellaraccident this doesn't have a test because it was correcting an obvious mistake from the integrate not fixing a failure.

**Pull request merged**
