### PR TITLE
Cherry-pick deduplication output op operand linalg[Do not merge, for testing purposes only]

### PR DESCRIPTION
**Pull request by raikonenfnu**

### CODE REVIEW

**Comment by raikonenfnu** [comment]
@MaheshRavishankar I forgot I did not have llvm-fork permission, so I needed to use my fork, but we aren't merging this anyways, and is just used for testing so should be OK :)

**Comment by MaheshRavishankar** [comment]
Looks like you are not building with head.

**Comment by raikonenfnu** [comment]
Yeah refactoring and rebuilding now 😅

**Comment by GMNGeoffrey** [comment]
This is very stale and looks like it was a test. I'm going to close the PR

**Pull request closed without merging**
