### PR TITLE
Update LLVM to llvm/llvm-project@33da608

### PR DESCRIPTION
**Pull request by vmurali**
* Update LLVM to llvm/llvm-project@33da608
* Cherry-picked llvm/llvm-project@aa90948
* Updated HLO to tensorflow/mlir-hlo@65eb2d4
  (includes CMake fixes after integrating llvm/llvm-project@33da608)
* Fix transform dialect related tests using #13635.
* Fix `TransformState::getPayloadOps #13621.
* Fix tests after upstream changes hoisting more of
  `vector.transfer_read`.

Closes #13635 
Closes #13621
Should address #13419 (pending confirmation)

### CODE REVIEW

**Comment by vmurali** [comment]
Copy pasted from @ftynse 's PR https://github.com/openxla/iree/pull/13666

**Comment by vmurali** [comment]
From @ftynse : There are e2e test breakages due to https://reviews.llvm.org/D146317, if somebody more familiar with TOSA and those tests could address those, it would speed up the process.

**Comment by vmurali** [comment]
@rsuderman, @jpienaar is this a TOSA front end error as Alex was pointing out?

**Comment by antiagainst** [comment]
https://github.com/openxla/iree/actions/runs/5028492193/jobs/9019430440?pr=13666#step:7:1184 shows a `operand #0 does not dominate this use` error. Digging into it, it's `iree-elimiate-empty-tensors` failing. Repro: `tools/iree-opt --split-input-file --pass-pipeline="builtin.module(iree-eliminate-empty-tensors)"` with the following input:

```mlir
  func.func @main_dispatch_67_generic_384x32_i32xi32xi32xi8() {
    %c0_i32 = arith.constant 0 : i32
    %c16 = arith.constant 16 : index
    %c0 = arith.constant 0 : index
    %c8 = arith.constant 8 : index
    %c32 = arith.constant 32 : index
    %c384 = arith.constant 384 : index
    %c127_i32 = arith.constant 127 : i32
    %c6_i32 = arith.constant 6 : i32
    %c38_i8 = arith.constant 38 : i8
    %c1535803927_i32 = arith.constant 1535803927 : i32
    %c-98304_i32 = arith.constant -98304 : i32
    %c-128_i32 = arith.constant -128 : i32
    %c2_i32 = arith.constant 2 : i32
    %0 = hal.interface.constant.load[0] : i32
    %1 = hal.interface.constant.load[1] : i32
    %2 = hal.interface.constant.load[2] : i32
    %3 = hal.interface.constant.load[3] : i32
    %4 = arith.index_castui %0 {stream.alignment = 512 : index, stream.values = [1673216 : index, 1722368 : index, 1773056 : index, 1823744 : index]} : i32 to index
    %5 = arith.index_castui %1 {stream.alignment = 512 : index, stream.values = [196608 : index, 1771520 : index, 1822208 : index, 1872896 : index]} : i32 to index
    %6 = arith.index_castui %2 {stream.alignment = 128 : index, stream.values = [198144 : index, 198272 : index, 198400 : index, 198528 : index]} : i32 to index
    %7 = arith.index_castui %3 {stream.alignment = 4096 : index, stream.values = [0 : index, 12288 : index, 24576 : index, 36864 : index]} : i32 to index
    %8 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%4) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<48x4x8x8xi32>>
    %9 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%5) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<384xi32>>
    %10 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%6) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<32xi32>>
    %11 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%7) : !flow.dispatch.tensor<writeonly:tensor<384x32xi8>>
    %workgroup_id_x = hal.interface.workgroup.id[0] : index
    %workgroup_count_x = hal.interface.workgroup.count[0] : index
    %workgroup_id_y = hal.interface.workgroup.id[1] : index
    %workgroup_count_y = hal.interface.workgroup.count[1] : index
    %12 = affine.apply affine_map<()[s0] -> (s0 * 256)>()[%workgroup_id_y]
    %13 = affine.apply affine_map<()[s0] -> (s0 * 256)>()[%workgroup_count_y]
    %14 = affine.apply affine_map<()[s0] -> (s0 * 16)>()[%workgroup_id_x]
    %15 = affine.apply affine_map<()[s0] -> (s0 * 16)>()[%workgroup_count_x]
    scf.for %arg0 = %12 to %c384 step %13 {
      %16 = affine.min affine_map<(d0) -> (-d0 + 384, 256)>(%arg0)
      %17 = affine.apply affine_map<(d0) -> (d0 ceildiv 8)>(%16)
      %18 = affine.apply affine_map<(d0) -> (d0 floordiv 8)>(%arg0)
      %19 = flow.dispatch.tensor.load %9, offsets = [%arg0], sizes = [%16], strides = [1] : !flow.dispatch.tensor<readonly:tensor<384xi32>> -> tensor<?xi32>
      scf.for %arg1 = %14 to %c32 step %15 {
        %20 = flow.dispatch.tensor.load %11, offsets = [%arg0, %arg1], sizes = [%16, 16], strides = [1, 1] : !flow.dispatch.tensor<writeonly:tensor<384x32xi8>> -> tensor<?x16xi8>
        %21 = affine.apply affine_map<(d0) -> (d0 floordiv 8)>(%arg1)
        %22 = flow.dispatch.tensor.load %8, offsets = [%18, %21, 0, 0], sizes = [%17, 2, 8, 8], strides = [1, 1, 1, 1] : !flow.dispatch.tensor<readonly:tensor<48x4x8x8xi32>> -> tensor<?x2x8x8xi32>
        %23 = flow.dispatch.tensor.load %10, offsets = [%arg1], sizes = [16], strides = [1] : !flow.dispatch.tensor<readonly:tensor<32xi32>> -> tensor<16xi32>
        %24 = scf.for %arg2 = %c0 to %16 step %c8 iter_args(%arg3 = %20) -> (tensor<?x16xi8>) {
          %25 = affine.min affine_map<(d0)[s0] -> (-d0 + s0, 8)>(%arg2)[%16]
          %26 = affine.apply affine_map<(d0) -> (d0 floordiv 8)>(%arg2)
          %27 = tensor.empty(%25) : tensor<?x8xi32>
          %extracted_slice = tensor.extract_slice %27[0, 0] [%25, 8] [1, 1] : tensor<?x8xi32> to tensor<?x8xi32>
          %extracted_slice_0 = tensor.extract_slice %19[%arg2] [%25] [1] : tensor<?xi32> to tensor<?xi32>
          %28 = scf.for %arg4 = %c0 to %c16 step %c8 iter_args(%arg5 = %arg3) -> (tensor<?x16xi8>) {
            %29 = affine.apply affine_map<(d0) -> (d0 floordiv 8)>(%arg4)
            %30 = vector.transfer_read %22[%26, %29, %c0, %c0], %c0_i32 {in_bounds = [true, true]} : tensor<?x2x8x8xi32>, vector<8x8xi32>
            %31 = vector.transfer_write %30, %extracted_slice[%c0, %c0] {in_bounds = [false, true]} : vector<8x8xi32>, tensor<?x8xi32>
            %inserted_slice = tensor.insert_slice %31 into %27[0, 0] [%25, 8] [1, 1] : tensor<?x8xi32> into tensor<?x8xi32>
            %extracted_slice_1 = tensor.extract_slice %23[%arg4] [8] [1] : tensor<16xi32> to tensor<8xi32>
            %extracted_slice_2 = tensor.extract_slice %arg5[%arg2, %arg4] [%25, 8] [1, 1] : tensor<?x16xi8> to tensor<?x8xi8>
            %32 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0)>, affine_map<(d0, d1) -> (d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%inserted_slice, %extracted_slice_0, %extracted_slice_1 : tensor<?x8xi32>, tensor<?xi32>, tensor<8xi32>) outs(%extracted_slice_2 : tensor<?x8xi8>) attrs =  {lowering_config = #iree_codegen.lowering_config<tile_sizes = [[256, 16], [8, 8], [0, 0]]>} {
            ^bb0(%in: i32, %in_4: i32, %in_5: i32, %out: i8):
              %33 = arith.muli %in_4, %c2_i32 : i32
              %34 = arith.subi %in, %33 : i32
              %35 = arith.muli %in_5, %c-128_i32 : i32
              %36 = arith.subi %34, %35 : i32
              %37 = arith.addi %36, %c-98304_i32 : i32
              %38 = "tosa.apply_scale"(%37, %c1535803927_i32, %c38_i8) <{double_round = true}> : (i32, i32, i8) -> i32
              %39 = arith.addi %38, %c6_i32 : i32
              %40 = arith.cmpi slt, %39, %c-128_i32 : i32
              %41 = arith.select %40, %c-128_i32, %39 : i32
              %42 = arith.cmpi sgt, %39, %c127_i32 : i32
              %43 = arith.select %42, %c127_i32, %41 : i32
              %44 = arith.trunci %43 : i32 to i8
              linalg.yield %44 : i8
            } -> tensor<?x8xi8>
            %inserted_slice_3 = tensor.insert_slice %32 into %arg5[%arg2, %arg4] [%25, 8] [1, 1] : tensor<?x8xi8> into tensor<?x16xi8>
            scf.yield %inserted_slice_3 : tensor<?x16xi8>
          }
          scf.yield %28 : tensor<?x16xi8>
        }
        flow.dispatch.tensor.store %24, %11, offsets = [%arg0, %arg1], sizes = [%16, 16], strides = [1, 1] : tensor<?x16xi8> -> !flow.dispatch.tensor<writeonly:tensor<384x32xi8>>
      }
    }
    return
  }
```

**Comment by MaheshRavishankar** [comment]
@matthias-springer would you able to take a look?

**Comment by antiagainst** [comment]
> @matthias-springer would you able to take a look?

Looking at what's changed for related code in history regarding this integration, maybe due to https://github.com/llvm/llvm-project/commit/1f479c1e46d111a6f001cf4ee24290f60f13257d?

**Comment by vmurali** [comment]
The other error is due to https://github.com/llvm/llvm-project/commit/2fe4d90cac54bf35948bea2ca6d5d8c510f6a1b4. I hope the fix takes care of test_gpu

**Comment by matthias-springer** [comment]
> > @matthias-springer would you able to take a look?
> 
> Looking at what's changed for related code in history regarding this integration, maybe due to [llvm/llvm-project@1f479c1](https://github.com/llvm/llvm-project/commit/1f479c1e46d111a6f001cf4ee24290f60f13257d)?

Thx for tracking down the commit. There was a small mistake in my change, here's a fix: https://reviews.llvm.org/D151077

**Comment by antiagainst** [comment]
> Thx for tracking down the commit. There was a small mistake in my change, here's a fix: https://reviews.llvm.org/D151077

Thanks! Cherry-picked the fix. Let's see if bots are all happy now. :)

**Review by matthias-springer — APPROVED** [review]

**Comment by antiagainst** [comment]
Hmm, still failing test for double_mma_layout_analysis.mlir.. Uploaded 00e95e1 to fix it.

**Comment by antiagainst** [comment]
The CPU regression cases seem real. Can somebody help to investigate it further @dcaballe @MaheshRavishankar FYI.

**Comment by MaheshRavishankar** [comment]
Cc @hanhanW as well. I am in middle of another regression triage. Can probably take this up later today if no one else has gotten to it

**Comment by hanhanW** [comment]
I'm taking a look at CPU regression

**Comment by hanhanW** [comment]
I confirmed that the regression is real. Here is a smaller repro:

```
#map = affine_map<(d0, d1, d2, d3) -> (d3)>
#map1 = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>
#map2 = affine_map<(d0, d1) -> (d1)>
#map3 = affine_map<(d0, d1) -> (d0, d1)>
func.func @main_dispatch_5_matmul_12544x96x16_f32(%0: tensor<12544x16xf32>, %1: tensor<16x96xf32>, %2: tensor<96xf32>) -> tensor<12544x96xf32> {
  %cst = arith.constant 6.000000e+00 : f32
  %cst_0 = arith.constant 0.000000e+00 : f32
  %3 = tensor.empty() : tensor<12544x96xf32>
  %4 = linalg.fill ins(%cst_0 : f32) outs(%3 : tensor<12544x96xf32>) -> tensor<12544x96xf32>
  %5 = linalg.matmul ins(%0, %1 : tensor<12544x16xf32>, tensor<16x96xf32>) outs(%4 : tensor<12544x96xf32>) -> tensor<12544x96xf32>
  %6 = linalg.generic {indexing_maps = [#map2, #map3, #map3], iterator_types = ["parallel", "parallel"]} ins(%2, %5 : tensor<96xf32>, tensor<12544x96xf32>) outs(%3 : tensor<12544x96xf32>) {
  ^bb0(%in: f32, %in_1: f32, %out: f32):
    %7 = arith.addf %in, %in_1 : f32
    %8 = arith.minf %7, %cst : f32
    %9 = arith.maxf %8, %cst_0 : f32
    linalg.yield %9 : f32
  } -> tensor<12544x96xf32>
  return %6 : tensor<12544x96xf32>
}
```

The perf is 2.24 ms without integrate and 2.64 ms with the integrate.

**Comment by hanhanW** [comment]
The regression is caused by https://github.com/iree-org/iree-llvm-fork/commit/3971e80fc53928558604033330b18fa297191005

The difference is that a transfer_read op is hoisted out of a loop. The lefthand side is the IR dump without integrate and the righthand side is the IR dump with the integrate.

image

**Comment by MaheshRavishankar** [comment]
> The regression is caused by [iree-org/iree-llvm-fork@3971e80](https://github.com/iree-org/iree-llvm-fork/commit/3971e80fc53928558604033330b18fa297191005)
> 
> The difference is that a transfer_read op is hoisted out of a loop. The lefthand side is the IR dump without integrate and the righthand side is the IR dump with the integrate.
> 
> image

Thanks Hanhan, was just coming here to pick this up, but looks like you made some progress. Isnt it better to hoist it out?

**Comment by dcaballe** [comment]
Indeed, thanks for the quick analysis!

> Thanks Hanhan, was just coming here to pick this up, but looks like you made some progress. Isnt it better to hoist it out?

Yes, there has to be some other side effect of that change. Also, I would expect LLVM to hoist that loop invariant read so maybe we have some pattern that is not triggering because of the hoisting?

**Review by hanhanW — CHANGES_REQUESTED** [review]
block for regression investigation

**Review by hanhanW — APPROVED** [review]
I don't have an easy fix now. I purpose to land it as what it is and fix the regression afterwards. Issue https://github.com/openxla/iree/issues/13753 filed.

**Comment by antiagainst** [comment]
Thanks @hanhanW for the swift investigation! @MaheshRavishankar @dcaballe are we okay with rolling forward this integration? This was actually created last Wed; so it's almost a week since then.

**Comment by MaheshRavishankar** [comment]
This doesn't seem like an easy fix. We need to go back to the original commit and investigate more. Fine by me to land and investigate after landing

**Comment by antiagainst** [comment]
SG. Landed to push LLVM integration forward. Hanhan filed https://github.com/openxla/iree/issues/13753 to track and fix the known regression.

**Pull request merged**
