### PR TITLE
Update docker image builds for Python 3.8

### PR DESCRIPTION
**Pull request by dellis23**

### CODE REVIEW

**Review by ScottTodd — APPROVED** [review]
Mechanics of this look correct. Let's hope the CI passes :)

**Comment by dellis23** [comment]
🤞

**Comment by dellis23** [comment]
Looks like there was one failure in `CI / cross_compile_and_test (linux, riscv_32, ilp32d,[...]`.  I _think_ it's this:

```295/295 Test  #32: iree/tests/e2e/matmul/e2e_matmul_direct_f32_large_split_k_llvm-cpu_local-task ............................***Timeout  59.98 sec```

**Comment by ScottTodd** [comment]
> Looks like there was one failure in `CI / cross_compile_and_test (linux, riscv_32, ilp32d,[...]`. I _think_ it's this:
> 
> `295/295 Test #32: iree/tests/e2e/matmul/e2e_matmul_direct_f32_large_split_k_llvm-cpu_local-task ............................***Timeout 59.98 sec`

That's a know issue, should be "fixed" with https://github.com/openxla/iree/commit/7758e4830ced8f81cd23e8751cfc1682f2fbbe44. We can merge past that failure.

**Comment by dellis23** [comment]
Thanks!

**Pull request merged**
