### PR TITLE
Use standard runners for samples.yml and rework Colab testing.

### LINKED ISSUE #16373: Drop samples.Dockerfile and bump TensorFlow version used for Colab notebook tests
Filing for when I get a chance to code this...

This can be replaced with a base Dockerfile (from IREE or nod-ai, doesn't really matter) and on-demand pip installs:
https://github.com/openxla/iree/blob/621c186ddc8f3db8ef5b46d92d94ce756f629827/build_tools/docker/dockerfiles/samples.Dockerfile#L7-L29

Colab is shipping TensorFlow version 2.15.0 now, so we can update that and drop this from some Colab notebooks:
```
%%capture
!python -m pip install --upgrade tf-nightly  # Needed for stablehlo export in TF>=2.14
```

This may also fix https://github.com/openxla/iree/actions/workflows/samples.yml

### PR DESCRIPTION
**Pull request by ScottTodd**
Changes:

* Switched samples/dynamic_shapes to use `iree-compile` installed from pip rather than build the compiler from source
* Switched Colab notebook tests to run natively (not under Docker), (this fixes https://github.com/iree-org/iree/issues/16373)
* Disabled experimental web tests pending refactoring work to use installed compiler packages

Logs:

* Tested at https://github.com/iree-org/iree/actions/runs/8820008530
* Compare timing with history at https://github.com/iree-org/iree/actions/workflows/samples.yml.

skip-ci: this only runs nightly

### CODE REVIEW

**Comment by ScottTodd** [comment]
💀 oops, forgot that these build the full compiler: https://github.com/iree-org/iree/blob/330651efa6a3a139a160d4d6420766b3cd5932c3/samples/dynamic_shapes/test.sh#L26-L28

will switch to using pip-installed packages

**Comment by ScottTodd** [comment]
lol and the standard runner ran out of disk space trying to build LLVM anyways: https://github.com/iree-org/iree/actions/runs/8806252487/job/24170630484#step:3:2139
```
[1521/6666] Building CXX object llvm-project/lib/Target/ARM/MCTargetDesc/CMakeFiles/LLVMARMDesc.dir/ARMWinCOFFObjectWriter.cpp.o
FAILED: llvm-project/lib/Target/ARM/MCTargetDesc/CMakeFiles/LLVMARMDesc.dir/ARMWinCOFFObjectWriter.cpp.o 
/usr/bin/clang++-9 -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/work/build-samples/llvm-project/lib/Target/ARM/MCTargetDesc -I/work/third_party/llvm-project/llvm/lib/Target/ARM/MCTargetDesc -I/work/third_party/llvm-project/llvm/lib/Target/ARM -I/work/build-samples/llvm-project/lib/Target/ARM -I/work/build-samples/llvm-project/include -I/work/third_party/llvm-project/llvm/include -I/work/third_party/llvm-project/mlir/include -I/work/build-samples/llvm-project/tools/mlir/include -I/work/third_party/llvm-project/lld/include -I/work/build-samples/llvm-project/tools/lld/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -w -fdiagnostics-color -ffunction-sections -fdata-sections -O2 -g -DNDEBUG -fPIC -fvisibility=hidden  -fno-exceptions -funwind-tables -fno-rtti -std=c++17 -MD -MT llvm-project/lib/Target/ARM/MCTargetDesc/CMakeFiles/LLVMARMDesc.dir/ARMWinCOFFObjectWriter.cpp.o -MF llvm-project/lib/Target/ARM/MCTa
fatal error: error in backend: IO failure on output stream: No space left on device
```

**Comment by ScottTodd** [comment]
(╯°□°)╯︵ ┻━┻

https://github.com/iree-org/iree/actions/runs/8807693591/job/24175321465#step:4:249
```
 python -m pip install --find-links https://iree.dev/pip-release-links.html --upgrade iree-compiler
Looking in links: https://iree.dev/pip-release-links.html
Collecting iree-compiler
  Downloading https://github.com/iree-org/iree/releases/download/candidate-20230906.637/iree_compiler-20230906.637-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (71.9 MB)
```
Note the `manylinux_2_17_x86_64.manylinux2014_x86_64.whl` there. We distribute for manylinux_2_28 now: https://iree.dev/pip-release-links.html, so that's pulling a very old version.

Might need to drop Docker (and fix https://github.com/iree-org/iree/issues/16373) while I'm working on this.

**Comment by ScottTodd** [comment]
Ping?

**Review by benvanik — APPROVED** [review]

**Pull request merged**
