### PR TITLE
Integrate iree-org/torch-mlir@41d04a89959d9197e167302fcae375f947848a88

### PR DESCRIPTION
**Pull request by renxida**

### CODE REVIEW

**Comment by ScottTodd** [comment]
(RE: the PR title) Our fork is at https://github.com/iree-org/torch-mlir now, not https://github.com/shark-infra/torch-mlir, but the github org isn't really relevant

**Comment by renxida** [comment]
> (RE: the PR title) Our fork is at https://github.com/iree-org/torch-mlir now, not https://github.com/shark-infra/torch-mlir, but the github org isn't really relevant

fixed!

btw, any clue on what's happening with the pre-commit lint? looks like something is off with the virtualenv

**Comment by ScottTodd** [comment]
> > (RE: the PR title) Our fork is at https://github.com/iree-org/torch-mlir now, not https://github.com/shark-infra/torch-mlir, but the github org isn't really relevant
> 
> fixed!
> 
> btw, any clue on what's happening with the pre-commit lint? looks like something is off with the virtualenv

Weiiiiiiird. First time seeing that and it failed on a retry. I'll investigate...

**Comment by renxida** [comment]
```
Errors while running CTest
	 57 - iree/compiler/plugins/input/Torch/InputConversion/test/auto_input_conversion.mlir.test (Failed)
	 59 - iree/compiler/plugins/input/Torch/InputConversion/test/bitcast_quant_tensor.mlir.test (Failed)
	 60 - iree/compiler/plugins/input/Torch/InputConversion/test/func_conversion.mlir.test (Failed)
	769 - iree/compiler/bindings/python/test/extras/fx_importer_test (Failed)
```

Probably caused by me adding 

image

because git bisecting in ./third_party/torch-mlir to roll back to earlier versions don't solve the problem.

I had to do this because I encountered:


image

Why is more than 1 dialect present?

**Comment by ScottTodd** [comment]
Similar `-dialect=torch` changes in https://github.com/iree-org/iree/pull/17662:
https://github.com/iree-org/iree/pull/17662/files#diff-611d6de1b0695a6b864d09aa9a310485527df7afeb3431871fe16660b8a980eb

that PR might supersede this one

**Comment by renxida** [comment]
Oh cool. Closing this one to wait for that one.

**Pull request closed without merging**
