### PR TITLE
Cherry-pick LLVM@1654f489e2138673b696053674f33252ed7fac78

### PR DESCRIPTION
**Pull request by nicolasvasilache**
@hanhanW for integrate

### CODE REVIEW

**Comment by ThomasRaoux** [comment]
FYI @vmurali

**Comment by nicolasvasilache** [comment]
subsumed by #11659

**Comment by vmurali** [comment]
This has to be cherry-picked again because of integrate https://github.com/iree-org/iree/pull/11663

**Comment by nicolasvasilache** [comment]
still subsumed by what #11659 is relanded as

**Pull request closed without merging**
