### PR TITLE
Replace tm_tensor with torch-mlir proper

### PR DESCRIPTION
**Pull request by stellaraccident**
Per discussion on iree-discuss, this patch removes the original tm_tensor source snapshots and special casing from the codebase, instead pulling in the parts of torch-mlir that provide a full solution, starting from the torch dialect down.

This reuses the existing `IREE_INPUT_TORCH` CMake define but routes it to a compiler plugin at `compiler/plugins/input/Torch` where all build plumbing to integrate and local pipelines exist. I have kept the original tm_tensor input type for the moment since downstreams are using that, but we will want to eventually replace that with a dedicated `torch` input type which works directly from the `torch` dialect.

This patch should be NFC to all current users, however it allows programmatic and API access to the full Torch dialects and conversion pipelines, which is essential for broader scale integration.

We add `third_party/torch-mlir` as a submodule at torch-mlir's current HEAD. During LLVM integrates, if there are ever API breaks that affect this, we may need to push patches to torch-mlir to address. This can be done on a torch-mlir branch as needed (or committed at head). I have been tracking changes for a couple of months and have not had a need to do this yet, which indicates that this is relatively stable.

Committing with an XFAIL'd lit test, which for some reason was not running previously and now is: https://github.com/openxla/iree/issues/14916

### CODE REVIEW

**Review by benvanik — APPROVED** [review]

**Comment by jpienaar** [comment]
Does torch become a plugin proper now? Having this dep be optional is important for usage where not all packages are available (or desirable).

**Comment by stellaraccident** [comment]
Yes, it is entirely self contained as compiler/plugins/input/Torch

This should be an improvement for such cases over the previous state where it was optional but still threaded through the main codebase.

**Comment by ScottTodd** [comment]
Ah... I just noticed that if someone runs `git submodule update --init --recursive`, that will now also clone `torch-mlir`'s copy of `llvm-project`. Recursive updates are less common when working directly in IREE, but downstream projects may use it for convenience vs explicitly choosing which subfolders and submodules to use.

Not sure how we could improve the situation there... maybe write down the git submodule workflows we suggest and keep an eye on downstream projets (e.g. https://github.com/RechieKho/IREE.gd#build-from-source)?

**Comment by ScottTodd** [comment]
> Ah... I just noticed that if someone runs `git submodule update --init --recursive`, that will now also clone `torch-mlir`'s copy of `llvm-project`. Recursive updates are less common when working directly in IREE, but downstream projects may use it for convenience vs explicitly choosing which subfolders and submodules to use.
> 
> Not sure how we could improve the situation there... maybe write down the git submodule workflows we suggest and keep an eye on downstream projets (e.g. https://github.com/RechieKho/IREE.gd#build-from-source)?

The instructions at https://github.com/iree-org/iree-template-runtime-cmake/ should also be updated to account for that too:

> For a faster checkout the LLVM dependency can be dropped as this template is only compiling the runtime (only bother if optimizing build bots):
> ```
> $ git \
>     -c submodule."third_party/llvm-project".update=none \
>     submodule update --init --recursive
> ```

Output even with that (https://github.com/iree-org/iree-template-runtime-cmake/actions/runs/6656984452/job/18090744983):
```
Submodule path 'third_party/iree/third_party/torch-mlir': checked out '6f81ad72938deb56c6d43bbc01388c1f8f1253c1'
Submodule 'externals/llvm-project' (https://github.com/llvm/llvm-project.git) registered for path 'third_party/iree/third_party/torch-mlir/externals/llvm-project'
Submodule 'externals/stablehlo' (https://github.com/openxla/stablehlo.git) registered for path 'third_party/iree/third_party/torch-mlir/externals/stablehlo'
Cloning into '/home/runner/work/iree-template-runtime-cmake/iree-template-runtime-cmake/third_party/iree/third_party/torch-mlir/externals/llvm-project'...
```

**Pull request merged**
