### PR TITLE
[Stream] Hoist resource allocation out of a loop CFG

### PR DESCRIPTION
**Pull request by ezhulenev**

### CODE REVIEW

**Comment by benvanik** [comment]
Hmm I'm not sure we want this - extending the lifetime of allocations is extremely dangerous as it can make models that work otherwise not - in general we want to sink/more tightly scope the lifetime of allocations instead. This kind of hoisting also can't track timelines and as such if you have a loop with pipelining there's nothing to keep the hoisted allocations from being incorrectly accessed - at the stream.cmd level all memory accesses must be properly tracked with timepoints and that these allocations aren't today only works because they are never hoisted/reused.

Queue-ordered allocations should obviate the need for hoisting for most reasons and pending changes (#14016) turn all allocations produced by schedule allocation into queue-ordered ones. Once they're queue-ordered we can hoist with awareness of timelines and scope but it'll be easier with scf where we can hoist the timepoints into loop-carried variables.

Using the caching allocator (or some future allocators) should help runtime performance with what's there today - I know of a case where we aren't aggressively clearing VM registers so sometimes buffers can live longer than they should but if that's the only thing keeping the caching allocator from helping the cases you're running into we can prioritize fixing that.

If there's no other way to do work around this with the above then we could land it disabled by default but with the large number of footguns/caveats it'd have to be really hard to work around.

**Comment by ezhulenev** [comment]
The problem is that the buffer that gives me troubles is `cuMemAllocHost`/`cuMemFreeHost`, and `free` in particular can be very costly.

Another option I was thinking about is to pre-allocate few kb of paged locked memory in `cuda_allocator` and use very simple ring buffer (iree_arena_allocator with wrap around?) for small host allocations. But @antiagainst was leaning toward fixing it in a compiler. I think that doing it in allocator is indeed safer, because I'm not very confident that checks from this PR actually cover all cases.

**Comment by benvanik** [comment]
The caching allocator can be used to help that - if you've got allocations in your hot path you'll want to use that (or some other implementation).

**Comment by ezhulenev** [comment]
I tried `--device_allocator=caching`, but it adds too much overheads, I'll take a look at cuda-optimized caching allocator

**Comment by benvanik** [comment]
Too much overheads? It's just an LRU and should have nearly no overhead, and is completely configurable (you can say "only cache host-mappable memory and only up to 1MB").

**Pull request closed without merging**
