### PR TITLE
[Codegen] Allow padding of dynamic allocas

### PR DESCRIPTION
**Pull request by Max191**
This PR adds support for padding for allocas in the PadDynamicAllocsPass. The padding works the same for alloca as for alloc.

### CODE REVIEW

**Review by hanhanW — COMMENTED** [review]
Drive-by: Instead of using template, would using AllocLikeOp make sense?

(I'm not asking for a change. It is just a question.)

https://github.com/llvm/llvm-project/blob/12bdeba76eef1c7adf004a280036a7fb690ba573/mlir/include/mlir/Dialect/MemRef/IR/MemRefOps.td#L57-L67

**Comment by Max191** [comment]
> Drive-by: Instead of using template, would using AllocLikeOp make sense?
> 
> (I'm asking for a change. It is just a question.)
> 
> https://github.com/llvm/llvm-project/blob/12bdeba76eef1c7adf004a280036a7fb690ba573/mlir/include/mlir/Dialect/MemRef/IR/MemRefOps.td#L57-L67

Ah, I didn't know about this. That looks a bit better to me, thanks!

**Comment by Max191** [comment]
> Drive-by: Instead of using template, would using AllocLikeOp make sense?

Hmm, actually I think AllocLikeOp is just a tablegen class. I don't think I can access it in C++. I'll update the template typename to be more consistent with other code, though.

**Review by nirvedhmeshram — APPROVED** [review]
LGTM

**Comment by hanhanW** [comment]
> > Drive-by: Instead of using template, would using AllocLikeOp make sense?
> 
> Hmm, actually I think AllocLikeOp is just a tablegen class. I don't think I can access it in C++. I'll update the template typename to be more consistent with other code, though.

Chatted with Max offline. Max is right, please ignore my comment.

**Pull request merged**
