### PR TITLE
Add strip assertions flag

### PR DESCRIPTION
**Pull request by IanWood1**
This change _temporarily_ adds `iree-opt-strip-assertions` to SDXL CI which should fix the regression discussed in https://github.com/iree-org/iree/issues/19002. Assertions within `linalg.generic` ops can mess with dispatch creation and lead to poorly performing dispatches, despite the fact that they get stripped in later pipelines.

Part 2 (future PR or maybe this one): remove flag usage and make this default.

### CODE REVIEW

**Comment by IanWood1** [comment]
Could I get a review on this? This might also be affecting Llama performance, there were ~100 dispatches that could be CSEed if the asserts were removed.

**Review by benvanik — APPROVED** [review]

**Review by MaheshRavishankar — COMMENTED** [review]
So we dont want to turn this on by default?

**Comment by IanWood1** [comment]
The idea was to to fix sdxl regressions first by just using the flag, then make it default after because there may be some side effects of stripping all assertions like this by default. But I can change this to be default if that seems better

**Comment by MaheshRavishankar** [comment]
> The idea was to to fix sdxl regressions first by just using the flag, then make it default after because there may be some side effects of stripping all assertions like this by default. But I can change this to be default if that seems better

Makes sense. Lets keep to the original plan.

**Review by MaheshRavishankar — APPROVED** [review]

**Pull request merged**
