### PR TITLE
Add stack allocation check back to x86 experimental-flags benchmarks

### PR DESCRIPTION
**Pull request by hanhanW**

### CODE REVIEW

**Review by MaheshRavishankar — APPROVED** [review]

**Comment by dcaballe** [comment]
It looks like this is impacting some tile size configurations leading to quite some regressions

**Comment by hanhanW** [comment]
> It looks like this is impacting some tile size configurations leading to quite some regressions

This is an NFC change for benchmark suites. We can add the check back because I fixed some issues in https://github.com/openxla/iree/pull/14441

It looks like the regression is introduced by https://github.com/openxla/iree/commit/80312afef2426a79646852636d6e5cce41cc4b43, but we need some eyes to verify it.

image

**Comment by pzread** [comment]
I reverted 80312af and the got 23% improvement on BertLargeTF https://github.com/openxla/iree/pull/14457#issuecomment-1644334469

**Comment by dcaballe** [comment]
Thanks for the investigation! I would ping Eugene and consider a revert for now.

**Pull request merged**
