### PR TITLE
Revert "Bump manylinux base hash to latest."

### PR DESCRIPTION
**Pull request by GMNGeoffrey**
Releases have started failing with some errors about git safe
directories and this docker change is the suspected culprit.

https://github.com/iree-org/iree/actions/runs/3756783872/jobs/6383251934

Reverts iree-org/iree#11594

skip-ci: Doesn't affect CI builds

### CODE REVIEW

**Review by pzread — APPROVED** [review]

**Comment by stellaraccident** [comment]
Looks like the docker image bump bright a new git which has some extra protections against a vulnerability. And that is keeping it from accessing the source directory mounted from the host.

When running forward, we probably just run the command it recommends when building the image.

**Comment by powderluv** [comment]
Would it be ok to land a fix and rerevert ? Trying to get to 3.11

**Comment by stellaraccident** [comment]
I'm ok with giving it a shot. We can always re-revert.

**Comment by GMNGeoffrey** [comment]
> Looks like the docker image bump brought a new git which has some extra protections against a vulnerability. And that is keeping it from accessing the source directory mounted from the host.

Yeah that was my guess as well. I think we could be using docker a bit more cleanly in these workflows as well. There's a big warning about it writing root-owned files all over the place, and I'm not convinced that's really necessary

**Comment by powderluv** [comment]
Can I do:
```
-repo_root="$(cd "${this_dir}" && git rev-parse --show-toplevel)"
+
+repo_root=$(pwd -P 2>/dev/null || command pwd)
+while [ ! -e "$repo_root/.git" ]; do
+  repo_root=${repo_root%/*}
+  if [ "$repo_root" = "" ]; then break; fi
+done
```

Testing it locally.

**Comment by powderluv** [comment]
Works. https://github.com/iree-org/iree/pull/11649

**Pull request merged**
