### PR TITLE
[GPU] Fix e2e matmul generator to extract the input element type.

### PR DESCRIPTION
**Pull request by hanhanW**
It is a follow-up for https://github.com/iree-org/iree/pull/18134#issuecomment-2273160595

ci-extra: build_packages,test_amd_mi250,test_amd_mi300,test_amd_w7900,test_nvidia_t4

### CODE REVIEW

**Comment by hanhanW** [comment]
@ScottTodd is there a way to trigger AMD related CI jobs in presubmit?

**Review by pashu123 — APPROVED** [review]
LGTM!

**Comment by ScottTodd** [comment]
> @ScottTodd is there a way to trigger AMD related CI jobs in presubmit?

Until https://github.com/iree-org/iree/pull/18138 is merged, add somethign like `ci-extra: build_packages,test_amd_mi250,test_amd_mi300,test_amd_w7900,test_nvidia_t4` to your PR description

**Comment by hanhanW** [comment]
> > @ScottTodd is there a way to trigger AMD related CI jobs in presubmit?
> 
> Until #18138 is merged, add somethign like `ci-extra: build_packages,test_amd_mi250,test_amd_mi300,test_amd_w7900,test_nvidia_t4` to your PR description

I see. I reviewed the code, and I'll rebase on it and test.

**Comment by ScottTodd** [comment]
> > > @ScottTodd is there a way to trigger AMD related CI jobs in presubmit?
> > 
> > 
> > Until #18138 is merged, add somethign like `ci-extra: build_packages,test_amd_mi250,test_amd_mi300,test_amd_w7900,test_nvidia_t4` to your PR description
> 
> I see. I reviewed the code, and I'll rebase on it and test.

Looks like the tests are queued up now. https://github.com/iree-org/iree/actions/runs/10288503045?pr=18140
image

**Comment by hanhanW** [comment]
The MI250 and MI300 CI jobs are happy, so I'm going to land the PR. 

image

**Comment by ScottTodd** [comment]
Thanks!

**Comment by hanhanW** [comment]
It looks like W7900 job is failing because of this change. I'll take a look after lunch.

https://github.com/iree-org/iree/actions/runs/10289449633/job/28478608054

**Pull request merged**
