### PR TITLE
Use system scheduling on mobile phones in new benchmark suites

### PR DESCRIPTION
**Pull request by pzread**
The recommended option `--task_topology_max_group_count` doesn't support processor configurations on mobile phones with heterogeneous architectures. So we use `--task_topology_group_count` + `taskset` instead to run multi-thread benchmarks on mobile phones.

Originally we use the `--task_topology_group_count` + `taskset` to run all benchmarks. After #11834, we changed the new benchmark suites to use `--task_topology_max_group_count` without taskset to run x86_64 benchmarks, as `--task_topology_max_group_count` is recommended to use in server environments (detect NUMA nodes, pinning the threads and not relying on system scheduling). But it also applied the change to Android benchmarks, which won't work. 

The new execution configs are added to differentiate benchmarks with `--task_topology_group_count` and `--task_topology_max_group_count`.

This change doesn't affect the current Android benchmarks because they are still running with the legacy benchmark suites (which use `taskset` + `--task_topology_group_count`).

### CODE REVIEW

**Review by GMNGeoffrey — COMMENTED** [review]
Can you link to the relevant code here? Why weren't we using this before? From what I can see in blame this has been around for a while. I think maybe it's just a tense issue in your description. It's not clear to me whether you're describing the state we had before or the state we're creating, or what. Regardless of IREE flags, it seems good to run IREE under taskset. That provides an external control rather than trusting IREE itself not to use other threads. In particular, with big/little core combinations this matters. Are we not using `taskset` on server benchmarks?

Here's my proposed description based on my best understanding of what's going on here:

```
The recommended option `--task_topology_max_group_count` doesn't
support detecting the appropriate group count for the heterogeneous
core composition common on mobile devices. So we use 
`--task_topology_group_count` directly in our multi-thread benchmarks
on these devices. (In all cases, `taskset` is used to limit the cores
accessible to the benchmarked process).

This PR adds new execution configs to differentiate between benchmarks
using `--task_topology_group_count` and
`--task_topology_max_group_count`
```

Is that right?

**Comment by GMNGeoffrey** [comment]
It's unclear to me whether these latency changes are real...

**Comment by pzread** [comment]
> It's unclear to me whether these latency changes are real...

Updated the description. The latency change should be noise, as we are still using the legacy benchmark to run Android benchmarks.

**Comment by pzread** [comment]
> #11834

**Comment by pzread** [comment]
> Can you link to the relevant code here? Why weren't we using this before? From what I can see in blame this has been around for a while. I think maybe it's just a tense issue in your description. It's not clear to me whether you're describing the state we had before or the state we're creating, or what. Regardless of IREE flags, it seems good to run IREE under taskset. That provides an external control rather than trusting IREE itself not to use other threads. In particular, with big/little core combinations this matters. Are we not using `taskset` on server benchmarks?
> 
> Here's my proposed description based on my best understanding of what's going on here:
> 
> ```
> The recommended option `--task_topology_max_group_count` doesn't
> support detecting the appropriate group count for the heterogeneous
> core composition common on mobile devices. So we use 
> `--task_topology_group_count` directly in our multi-thread benchmarks
> on these devices. (In all cases, `taskset` is used to limit the cores
> accessible to the benchmarked process).
> 
> This PR adds new execution configs to differentiate between benchmarks
> using `--task_topology_group_count` and
> `--task_topology_max_group_count`
> ```
> 
> Is that right?

Updated the description. We changed to use `--task_topology_max_group_count` without `taskset` for x86_64 benchmarks in #11834. The major benefit is that `--task_topology_max_group_count` pins threads and prevents the system migrating threads between cores, which should give more predicable performance. It also handles the NUMA configurations.

To me it seems like we want to benchmark with the mechanism of `--task_topology_max_group_count`, as it's part of the optimization in IREE runtime, and it's also the recommended default options for multi-threading inferences. If we break or improve it, the effects should be shown on the e2e benchmarks.

The #11834 also applied to Android benchmarks, which don't work. So this PR reverts the changes on Android benchmarks.

The actual Android benchmarks are not affected as they are running with the legacy benchmark suites.

**Review by GMNGeoffrey — APPROVED** [review]
Ok, this change seems like a strict improvement, though I commented on that other PR that I'm maybe not sold on not using taskset on server.

**Pull request merged**
