### PR TITLE
Move the CPU to not use attributes.

### PR DESCRIPTION
**Pull request by ThomasRaoux**

### CODE REVIEW

**Review by hanhanW — APPROVED** [review]

**Comment by MaheshRavishankar** [comment]
(@hanhanW and @dcaballe FYI this is not landing in main, you get notifications cause you are code owners, so you can ignore these)

**Comment by hanhanW** [comment]
got it, was thinking it's a revert about yesterday's discussion. I'll ignore the PRs that not merging into main.

**Comment by ThomasRaoux** [comment]
> got it, was thinking it's a revert about yesterday's discussion. I'll ignore the PRs that not merging into main.

yeah sorry about the noise, I couldn't figure out a way to not notify you.

**Comment by MaheshRavishankar** [comment]
> > got it, was thinking it's a revert about yesterday's discussion. I'll ignore the PRs that not merging into main.
> 
> yeah sorry about the noise, I couldn't figure out a way to not notify you.

I don't think we need to worry about that. That is the cost of being code owner. Personally it helps me to track changes to branches as well

**Pull request merged**
