### PR TITLE
Fix check on iree_linalg_ext.scatter for dynamic shapes

### LINKED ISSUE #12575: iree-codegen-tile-and-distribute-to-workgroups resulting in invalid iree_linalg_ext.scatter
### What happened?

For the input at end I get

```
 error: 'iree_linalg_ext.scatter' op indexed shape of update value dim#1 exceeds original value at dim#0 8 -9223372036854775808
```

with also some cases like

```mlir
%20 = "flow.dispatch.tensor.load"(%9, %arg1, %19, %1) {operand_segment_sizes = array<i32: 1, 0, 2, 1, 0>, static_offsets = array<i64: -9223372036854775808, -9223372036854775808>, static_sizes = array<i64: -9223372036854775808, 1>, static_strides = array<i64: 1, 1>} : (!flow.dispatch.tensor<readonly:tensor<16x4xi32>>, index, index, index) -> tensor<?x1xi32>
```

input

```mlir
hal.executable private @_main_dispatch_6 {
  hal.executable.variant public @embedded_elf_x86_64, target = <"llvm-cpu", "embedded-elf-x86_64", {cpu = "generic", cpu_features = "", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128", native_vector_size = 16 : index, target_triple = "x86_64-unknown-unknown-eabi-elf"}> {
    hal.executable.export public @_main_dispatch_6 ordinal(0) layout(#hal.pipeline.layout<push_constants = 2, sets = [<0, bindings = [<0, storage_buffer, ReadOnly>, <1, storage_buffer>]>]>) {
    ^bb0(%arg0: !hal.device, %arg1: index, %arg2: index, %arg3: index):
      %x, %y, %z = flow.dispatch.workgroup_count_from_dag_root %arg1, %arg2, %arg3
      hal.return %x, %y, %z : index, index, index
    }
    builtin.module {
      func.func @_main_dispatch_6() {
        %cst = arith.constant dense<0> : tensor<1x1xi32>
        %cst_0 = arith.constant dense<0> : tensor<1x16x1xi32>
        %0 = hal.interface.constant.load[0] : i32
        %1 = hal.interface.constant.load[1] : i32
        %2 = arith.index_castui %0 {stream.alignment = 64 : index, stream.values = [0 : index, 320 : index]} : i32 to index
        %3 = arith.index_castui %1 {stream.alignment = 64 : index, stream.values = [64 : index, 320 : index]} : i32 to index
        %4 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%2) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<16x4xi32>>
        %5 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%3) : !flow.dispatch.tensor<writeonly:tensor<16x2xi32>>
        %6 = flow.dispatch.tensor.load %4, offsets = [0, 1], sizes = [16, 2], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<16x4xi32>> ->tensor<16x2xi32>
        %7 = iree_linalg_ext.scatter dimension_map = [1] unique_indices(true) ins(%cst_0, %cst : tensor<1x16x1xi32>, tensor<1x1xi32>) outs(%6 : tensor<16x2xi32>) {
        ^bb0(%arg0: i32, %arg1: i32):
          iree_linalg_ext.yield %arg0 : i32
        } -> tensor<16x2xi32>
        flow.dispatch.tensor.store %7, %5, offsets = [0, 0], sizes = [16, 2], strides = [1, 1] : tensor<16x2xi32> -> !flow.dispatch.tensor<writeonly:tensor<16x2xi32>>
        return
      }
    }
  }
}
```

command

```
$ iree-opt t1.mlir --iree-hal-translate-executables
```

### Steps to reproduce your issue

_No response_

### What component(s) does this issue relate to?

Runtime

### Version information

Rev 338b979201804353897f0a5c5f249b27fb62b7bc

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rsuderman**
Shape comparison check should not trigger for dynamic shapes as incompatible behavior is not guaranteed.

### CODE REVIEW

**Review by hanhanW — COMMENTED** [review]
can you add a test to https://github.com/openxla/iree/blob/main/llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/roundtrip.mlir

**Review by hanhanW — APPROVED** [review]
thanks!

**Comment by rsuderman** [comment]
> can you add a test to https://github.com/openxla/iree/blob/main/llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/roundtrip.mlir

Done

**Comment by jpienaar** [comment]
Thanks!

**Pull request merged**
