### PR TITLE
Support distribution of reduction to group in transform dialect

### PR DESCRIPTION
**Pull request by ThomasRaoux**

### CODE REVIEW

**Review by nicolasvasilache — APPROVED** [review]

**Comment by MaheshRavishankar** [comment]
Fairly big change. This needs more description

**Comment by ThomasRaoux** [comment]
> Fairly big change. This needs more description

The actual change is only few lines of code (second commit in the PR) the rest is just NFC of moving code into Utils.

**Comment by nicolasvasilache** [comment]
I still don't get why the auto-merge did not create the bulletpoints corresponding to the 3 commits to be added to the description ..

**Comment by MaheshRavishankar** [comment]
Still better to add that to description

**Pull request merged**
