### PR TITLE
[Codegen][GPU] Stop using redundant transfer hoisting pattern on memrefs

### PR DESCRIPTION
**Pull request by qedawkins**
This pattern is a footgun and doesn't model parallel regions properly as noted here: https://github.com/llvm/llvm-project/blob/cc5ddae5e29ef2d7dd132469caee5cac54523ce5/mlir/include/mlir/Dialect/Linalg/Transforms/Hoisting.h#L42

### CODE REVIEW

**Comment by Groverkss** [comment]
FYI: After this patch, that transformation shouldn't be needed: https://github.com/llvm/llvm-project/pull/111533#issuecomment-2400353491

**Comment by qedawkins** [comment]
that would be great because this pattern is a total footgun. I don't have the cycles to remove it from older pipelines though so I still need this.

**Review by hanhanW — APPROVED** [review]
This pass is very old. It does too many mixed things which is like an incomplete vector-lowering pass. I've spent some time to decouple the logics for CPU codegen; we no longer use it on CPU side.

We have `OptimizeTensorInsertExtractSlicesPass` pass for the hosting, `DropVectorUnitDimsPass` for dropping unit dims, and optimized version of `DropVectorUnitDimsPass` which flattens inner dims based on the native vector size. It'd be a plus if you can figure what you really need and stop using the pass.

**Comment by Groverkss** [comment]
You might also want to remove it from here: https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Codegen/Common/OptimizeTensorInsertExtractSlices.cpp#L243 . I'm going to send a patch to remove that anyway from that pass if you can wait a bit for it.

**Comment by hanhanW** [comment]
> You might also want to remove it from here: https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Codegen/Common/OptimizeTensorInsertExtractSlices.cpp#L243 . I'm going to send a patch to remove that anyway from that pass if you can wait a bit for it.

Why do we need that? I thought that the issue happens on memrefs in your work. IMO, the `OptimizeTensorInsertExtractSlices` pass is supposed to be run right after vectorization because it cleans things up and hoists redundant transfer ops (on tensors).

**Comment by Groverkss** [comment]
> > You might also want to remove it from here: https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Codegen/Common/OptimizeTensorInsertExtractSlices.cpp#L243 . I'm going to send a patch to remove that anyway from that pass if you can wait a bit for it.
> 
> Why do we need that? I thought that the issue happens on memrefs in your work. IMO, the `OptimizeTensorInsertExtractSlices` pass is supposed to be run right after vectorization because it cleans things up and hoists redundant transfer ops (on tensors).

linalg::hoistRedundantVectorTransfers only hoists out memref code (and runs LICM), which is why it should be removed from that pass. That pass is meant to only work on tensors. A lot of pass pipelines run this pass post bufferization and rely on the memref hoisting from this pass.

**Comment by qedawkins** [comment]
I'm confused why we're talking about OptimizeTensorInsertExtractSlice, this patch is about OptimizeVectorTransfers

**Comment by hanhanW** [comment]
> I'm confused why we're talking about OptimizeTensorInsertExtractSlice, this patch is about OptimizeVectorTransfers

+1, I'm confused.. Anyway, this patch looks fine to me. I'll follow up on other PRs if there are changes about `OptimizeTensorInsertExtractSlice`.

**Comment by Groverkss** [comment]
> > > You might also want to remove it from here: https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Codegen/Common/OptimizeTensorInsertExtractSlices.cpp#L243 . I'm going to send a patch to remove that anyway from that pass if you can wait a bit for it.
> > 
> > 
> > Why do we need that? I thought that the issue happens on memrefs in your work. IMO, the `OptimizeTensorInsertExtractSlices` pass is supposed to be run right after vectorization because it cleans things up and hoists redundant transfer ops (on tensors).
> 
> linalg::hoistRedundantVectorTransfers only hoists out memref code (and runs LICM), which is why it should be removed from that pass. That pass is meant to only work on tensors. A lot of pass pipelines run this pass post bufferization and rely on the memref hoisting from this pass.

Just giving you a headsup that this footgun pattern also runs in OptimizeTensorInsertExtractSlices and multiple pipelines run this pattern post bufferization (https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Codegen/LLVMGPU/Passes.cpp#L49). Not blocking, just signaling it might become a problem in future.1

**Pull request merged**
