### PR TITLE
Prune old uses of C++ TF importers (built via Bazel).

### PR DESCRIPTION
**Pull request by ScottTodd**
Follow-up to the work tracked on https://github.com/openxla/iree/issues/13037.

* `integrations/tensorflow/iree_tf_compiler/iree-import-tflite-main.cpp` is no longer built (replaced with `integrations/tensorflow/python_projects/iree_tflite/iree/tools/tflite/scripts/iree_import_tflite
/__main__.py`)
* `build_tools/cmake/build_linux_benchmark_modules.sh` was calling `bazel build //iree_tf_compiler:iree-import-tflite`, which no longer works. That script is actually only used by `build_tools/buildkite/cmake/linux/pipeline.yml`, which has been disabled since March 2023 (https://buildkite.com/iree/iree-benchmark-linux)
  * Similar story for `build_tools/cmake/build_linux_benchmark.sh`?

### CODE REVIEW

**Review by mariecwhite — COMMENTED** [review]
The scripts in `build_tools/benchmarks/comparisons` are still used to run benchmarks manually. They generate these results: https://storage.googleapis.com/tflite-benchmark-artifacts/mobile/latest/mobile_summary.html, https://storage.googleapis.com/tflite-benchmark-artifacts/server/latest/server_summary.html. Is it possible to replace uses of //iree_tf_compiler:iree-import-tflite with the new one instead of deleting them?

**Comment by ScottTodd** [comment]
> The scripts in `build_tools/benchmarks/comparisons` are still used to run benchmarks manually. They generate these results: https://storage.googleapis.com/tflite-benchmark-artifacts/mobile/latest/mobile_summary.html, https://storage.googleapis.com/tflite-benchmark-artifacts/server/latest/server_summary.html. Is it possible to replace uses of //iree_tf_compiler:iree-import-tflite with the new one instead of deleting them?

If they're still useful, I'll avoid touching them, sure. You'll need to tweak the scripts around here:
```bash
cd integrations/tensorflow
bazel build -c opt --cxxopt="-Wno-deprecated-builtins" iree_tf_compiler:iree-import-tflite
./symlink_binaries.sh
```
to use the new Python-based importer instead.

**Review by GMNGeoffrey — APPROVED** [review]
I think you're deleting something and the reference to it in separate PRs, which is a bit weird. Maybe just merge them? But overall LGTM to delete this stuff as long as we get all the references as well.

**Comment by ScottTodd** [comment]
Ah... yeah. I'll just merge this into https://github.com/openxla/iree/pull/13437.

**Pull request closed without merging**
