### PR TITLE
Restructure website sections and navigation.

### PR DESCRIPTION
**Pull request by ScottTodd**
This is loosely inspired by the framework described at https://diataxis.fr/, as well as website layouts for similar projects.

## Preview

|  | |
|--------|--------|
| Current website | https://openxla.github.io/iree/ |
| Preview of this PR | https://scotttodd.github.io/iree/ | 

## Background

Some motivating goals / observations:

* We're interested in adding reference pages for MLIR dialects and API bindings. There will be many (5-30) of these pages, so they should be nested somewhere.
* Guides like "how to benchmark IREE" didn't have a good place in the prior schema
* "Deployment configurations" has always been a weird top level category. The existing pages are somewhere between "explanation" and a "tutorial", to use the Diátaxis framework's terminology.
* Similarly, "Getting Started" was weird at the top level since it referred to ML frameworks (one "end" of an "end to end" workflow), and "building from source" also had a "getting started" page.

## Category changes

Old top level categories were:

`Home | Getting Started | Deployment configurations | Building from source | Bindings | Extensions | Blog | Reference | Community`

New top level categories (each with an index page) are:

`Home | Building from source | Guides | Reference | Community`

* I also considered adding "Developers" section, but the lines there are blurry.

To support these new categories, I also enabled the [`navigation.tabs` setting](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs) in Material for MkDocs.

## Moving existing pages

Existing pages were moved to fit the new structure:

* Moved `getting-started/` to `guides/ml-frameworks/`
* Moved `deployment-configurations/` under `guides/`
* Moved `bindings/` under `reference/`
* Moved `blog/` under `community/`

I used the [mkdocs-redirects](https://github.com/mkdocs/mkdocs-redirects) plugin to add redirects from old locations to new locations.

### CODE REVIEW

**Review by GMNGeoffrey — APPROVED** [review]
Sweet, I like this cleanup, thank you :-) Please do the thing to make yamllint happy

**Comment by ScottTodd** [comment]
I'm testing a bit on the preview site, sooo... maybe ignore the "MLIR dialects" subsection under "Reference" for this PR, e.g. https://scotttodd.github.io/iree/reference/mlir-dialects/HALDialect/

(or don't, this is just some text on the Internet)

**Comment by jpienaar** [comment]
Nice! I also wanted to add some "debugging user journeys", would such things go under guides? (its a bit unstructured what I was doing, like a "here is me walking through debugging a thing that could be useful for you too" doc)

**Comment by ScottTodd** [comment]
> Nice! I also wanted to add some "debugging user journeys", would such things go under guides? (its a bit unstructured what I was doing, like a "here is me walking through debugging a thing that could be useful for you too" doc)

They could go under "guides", yeah. I think we'd want to evaluate on a case by case basic what the audience for a document is, and if it's worth putting on the website or keeping local to GitHub. For example, I wrote https://github.com/openxla/iree/blob/main/docs/developers/debugging/compile_time_regressions.md recently, but I think it's geared more towards project contributors/maintainers vs "users" (as nebulous as "users" can be with these projects).

**Pull request merged**
