### PR TITLE
Integrate llvm-project at 4706251a3186

### PR DESCRIPTION
**Pull request by hanhanW**
* Reset third_party/llvm-project: 4706251a3186c34da0ee8fd894f7e6b095da8fdc (2023-07-25 13:58:49 +0200): Clear release notes for 18.x

### CODE REVIEW

**Comment by hanhanW** [comment]
@stellaraccident there are compilation failures about `llvm-external-projects/mlir-iree-dialects/python/dialects/_iree_structured_transform_ops_gen.py`. I feel that it's related to https://reviews.llvm.org/D91961 but the includes look good to me. Can you help on fixing it?

**Comment by stellaraccident** [comment]
> @stellaraccident there are compilation failures about `llvm-external-projects/mlir-iree-dialects/python/dialects/_iree_structured_transform_ops_gen.py`. I feel that it's related to https://reviews.llvm.org/D91961 but the includes look good to me. Can you help on fixing it?

Appears from https://reviews.llvm.org/D154469

I think it can just be removed and have pushed a patch that does so.

**Review by stellaraccident — APPROVED** [review]
lgtm if tests pass.

**Comment by stellaraccident** [comment]
Looks like there are three failing Stream dialect unit tests. Need to go to bed so didn't look too closely but probably just some match patterns need updating (hopefully).

@benvanik if you see this in the AM, might be something you can fix easily

**Comment by hanhanW** [comment]
All the tests are passed. There are flaky benchmark build, re-run jobs now.

**Review by dcaballe — APPROVED** [review]

**Comment by hanhanW** [comment]
It consistently failed, let me try if I can repro locally.

**Comment by hanhanW** [comment]
I can reproduce it locally, it looks like an issue in the model file. @jpienaar @mariecwhite does it mean that we need to update the mlirbc file?

```
../models/transformers/BertLargefp16PTBatch1.mlirbc:0:0: error: expected mlir::detail::DenseArrayAttrImpl<int64_t>, but got: array<i32: 1, 0, 0, 0>
../models/transformers/BertLargefp16PTBatch1.mlirbc:0:0: note: in bytecode version 5 produced by: MLIR17.0.0git
```

The model is from https://github.com/openxla/iree/blob/268b6de58fecfb3a9b314ee3baab771b82ea0488/tests/e2e/test_artifacts/generated_e2e_test_fetch_models.cmake#L204-L209

To repro: `build/tools/iree-opt ~/BertLargefp16PTBatch1.mlirbc`

**Comment by jpienaar** [comment]
> I can reproduce it locally, it looks like an issue in the model file. @jpienaar @mariecwhite does it mean that we need to update the mlirbc file?
> 
> ```
> ../models/transformers/BertLargefp16PTBatch1.mlirbc:0:0: error: expected mlir::detail::DenseArrayAttrImpl<int64_t>, but got: array<i32: 1, 0, 0, 0>
> ../models/transformers/BertLargefp16PTBatch1.mlirbc:0:0: note: in bytecode version 5 produced by: MLIR17.0.0git
> ```
> 
> The model is from
> 
> https://github.com/openxla/iree/blob/268b6de58fecfb3a9b314ee3baab771b82ea0488/tests/e2e/test_artifacts/generated_e2e_test_fetch_models.cmake#L204-L209
> 
> To repro: `build/tools/iree-opt ~/BertLargefp16PTBatch1.mlirbc`

The error could be improved as it doesn't even say due to what, is this a StableHLO input? (Also I know bytecode side we had one revert but I'm assuming this is synced to a TF or JAX version which would have not been cut in between)

**Comment by hanhanW** [comment]
> The error could be improved as it doesn't even say due to what, is this a StableHLO input? (Also I know bytecode side we had one revert but I'm assuming this is synced to a TF or JAX version which would have not been cut in between)

Based on the source link `.../pytorch/.../linalg.mlirbc`, I think it is a pytorch model and in LinAlg format. @pzread do you know the answer?

Yes, it is synced to a TF version, which is https://github.com/tensorflow/tensorflow/commit/3e3e3cabf17f358e10d28d1387dbd6b1376753d1. What commit is reverted? I can check if it is [included](https://github.com/iree-org/iree-llvm-fork/compare/37937b8a040c5525a92c7ce23c329383e9d0c8e4...4706251a3186c34da0ee8fd894f7e6b095da8fdc). 

There are a couple more options popped out today. Would you suggest me bumping it to a later version?

**Comment by jpienaar** [comment]
> What commit is reverted?

I don't see it here - it was 3 in short time by River on bytecode, but this looks from before that (on mobile, will check in a bit more)

**Comment by pzread** [comment]
> > The error could be improved as it doesn't even say due to what, is this a StableHLO input? (Also I know bytecode side we had one revert but I'm assuming this is synced to a TF or JAX version which would have not been cut in between)
> 
> Based on the source link `.../pytorch/.../linalg.mlirbc`, I think it is a pytorch model and in LinAlg format. @pzread do you know the answer?
> 
> Yes, it is synced to a TF version, which is [tensorflow/tensorflow@3e3e3ca](https://github.com/tensorflow/tensorflow/commit/3e3e3cabf17f358e10d28d1387dbd6b1376753d1). What commit is reverted? I can check if it is [included](https://github.com/iree-org/iree-llvm-fork/compare/37937b8a040c5525a92c7ce23c329383e9d0c8e4...4706251a3186c34da0ee8fd894f7e6b095da8fdc).
> 
> There are a couple more options popped out today. Would you suggest me bumping it to a later version?

Yes, those are PyTorch models imported through torch-mlir and the dialect IIUC is linalg instead of stablehlo. So maybe there is a change in linalg?

I think here is the instruction to regenerate artifacts. @mariecwhite will know more about it: https://github.com/openxla/iree/blob/main/build_tools/python/e2e_test_framework/models/torch_models.py#L14-L19

**Comment by pzread** [comment]
Let me see if I can regenerate the model

**Comment by hanhanW** [comment]
Thanks for looking into it.

I was going to ask if iree-samples depends on iree. If so, we probably need to disable the benchmark and wait for propagation happening to iree-samples?

**Comment by pzread** [comment]
> Thanks for looking into it.
> 
> I was going to ask if iree-samples depends on iree. If so, we probably need to disable the benchmark and wait for propagation happening to iree-samples?

The torch-mlir doesn't rely on iree but relies on LLVM I believe (https://github.com/llvm/torch-mlir/tree/main/externals). I'm not sure if its nightly build has picked up the change. Do we know which LLVM commit breaks it?

**Comment by hanhanW** [comment]
> The torch-mlir doesn't rely on iree but relies on LLVM I believe (https://github.com/llvm/torch-mlir/tree/main/externals). I'm not sure if its nightly build has picked up the change. Do we know which LLVM commit breaks it?

I don't know yet. Maybe we can disable it to unblock integrate; enable it later. Because we are not actively looking at this model?

@MaheshRavishankar what do you think?

**Comment by pzread** [comment]
Yeah, I think we can disable it first (I also ran into some issues to regenerate the models)

**Comment by MaheshRavishankar** [comment]
There is a circular dependency here. TorchMLIR needs IREE to be update to LLVM commit before it can go to that commit. So I see disabling test for now and then re-enabling as the only solution.

**Comment by hanhanW** [comment]
@pzread and @mariecwhite please take a look, thanks!

**Review by pzread — APPROVED** [review]
There is another one to disable. I pushed the change.

**Comment by mariecwhite** [comment]
Thanks for disabling the benchmarks. @pzread were you planning on regenerating the artifacts? I can also look into it.

**Comment by jpienaar** [comment]
Btw https://github.com/llvm/llvm-project/commit/16b75cd2bb439633d29c99a7663f2586e4068ecf seems likely that it would require regenerating again here too ( @matthias-springer in case others are incoming), so depending on effort to regenerate, we may want to delay a little.

**Comment by hanhanW** [comment]
The regression about MobileNetV1 looks true because artifacts are different. Others look like noise. I think we can land it and fix the regression afterwards?

**Comment by hanhanW** [comment]
@MaheshRavishankar @benvanik the number of dispatch count changes in MobileNetV1, FYI.

**Comment by MaheshRavishankar** [comment]
> @MaheshRavishankar @benvanik the number of dispatch count changes in MobileNetV1, FYI.

Yeah. I saw that. Please file an issue. it's only mobilenetv1. So not high priority, but needs tracking. Please assign to me as P1

**Comment by pzread** [comment]
> Thanks for disabling the benchmarks. @pzread were you planning on regenerating the artifacts? I can also look into it.

I might need some help here. I tried to regenerate last week but ran into some errors. And now I couldn't boot my A100 VM because of outstock... If you have everything ready, please go ahead; otherwise I'll see when I can get the A100 VM

**Pull request merged**
