### PR TITLE
Cherry-pick MLIR changes for multi reduction tiling and distribution

### PR DESCRIPTION
**Pull request by antiagainst**
* llvm/llvm-project@9f37c21349580d88858a463df88235923a9bf7e0
* llvm/llvm-project@7897a944d9e72d79f38a443afffbbfd1accfe4ad
* llvm/llvm-project@73ddc4474bc4c34d3b6f50cd7a6e88a12ca83f8d
* llvm/llvm-project@2cc5f5d43c20428c9b9799176ae2d1da0bf9330d

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
There seem to be some errors. Are we OK with cherry picking so many changes? If we are I'll probably stack some more.. maybe make a branch in `iree-llvm-fork` that we can push all the changes to so that on next integrate we can just rebase the branch if any commit doesnt make it.

**Comment by antiagainst** [comment]
I'm fine doing it occasionally. But yeah this should not be a norm. @hanhanW is doing integration right now so I'd happy to let him decide.

**Comment by hanhanW** [comment]
I'm actually not the integrator this week, but I can help organize a new one later this week. So far we only need to revert a NVGPU related commit. I'm okay with cherry-picking these commits if they are already landed upstream.

**Comment by antiagainst** [comment]
Oh okay. I saw you were doing integrations. Thanks! I'm actually scheduled for next week and can help with it. Is there a timeline on the reverted NVGPU commit? If we are still gonna carry it forward, it won't be a clean integration anyway; so fine to pick up more to me.

**Comment by MaheshRavishankar** [comment]
To clarify, I am not saying we shouldnt cherry pick. Just saying instead of some patches branch, lets just have a branch with all the cherry picks for the vicuna effort. It's just a naming thing, but is easier to process (for me at least)

**Comment by antiagainst** [comment]
> To clarify, I am not saying we shouldnt cherry pick. Just saying instead of some patches branch, lets just have a branch with all the cherry picks for the vicuna effort. It's just a naming thing, but is easier to process (for me at least)

SGTM. I can create an git alias for such a branch. With the same branch it does mean we won't be able to do new integrates in the middle, given that would mean rebasing the whole branch and rewriting the history. It's an okay trade-off; I think we will see all the commits ready in upstream soon anyway.

**Comment by antiagainst** [comment]
Actually we can have both -- one better named branch for easy to collab, and another `patched-llvm-project*` for locking a point in the history. So rewriting the better named branch is fine this way.

**Comment by antiagainst** [comment]
Created `llm-vicuna-int4` alias for this.

**Review by stellaraccident — APPROVED** [review]

**Comment by hanhanW** [comment]
> Is there a timeline on the reverted NVGPU commit?

@MaheshRavishankar is working on it (https://github.com/llvm/llvm-project/issues/64606). (many thanks to Mahesh!)

**Pull request merged**
