### PR TITLE
Run sharktank llama tests on CI, qualify test names.

### PR DESCRIPTION
**Pull request by ScottTodd**
Progress on https://github.com/nod-ai/sharktank/issues/22. See https://github.com/nod-ai/SHARK-TestSuite/pull/272 for the specifics of what the new test is exercising.

The "models" tests now include `pytorch/models/` and `sharktank/`, so all test names are qualified relative to `iree_tests/` in the test suite repo. (Totally inflating my commit stats here, sorry :P)

ci-exactly: build_packages,regression_test

### CODE REVIEW

**Review by saienduri — APPROVED** [review]
lgtm

**Comment by ScottTodd** [comment]
May want some help updating the rocm pipeline benchmark: https://github.com/iree-org/iree/actions/runs/9719916305/job/26830734727?pr=17772

BTW, reported numbers are down quite a bit at tip of tree also:

```
E2E Benchmark Time: 1330.0 ms (golden time 1661.5 ms)
Scheduled Unet Benchmark Time: 340.0 ms (golden time 450.5 ms)
Prompt Encoder Benchmark Time: 16.8 ms (golden time 17.5 ms)
VAE Decode Benchmark Time: 288.0 ms (golden time 288.5 ms)
```

Seems like that changed around https://github.com/iree-org/iree/commit/9da0309b0491df57629a2177ab1dbec4aa73ae6e , but the code there seems to be off by default?

**Comment by saienduri** [comment]
> May want some help updating the rocm pipeline benchmark: https://github.com/iree-org/iree/actions/runs/9719916305/job/26830734727?pr=17772

Looks like the error is because we need to update by adding the two compilation flags to the three sdxl config files here: 
https://github.com/nod-ai/SHARK-TestSuite/blob/main/iree_tests/configs/sdxl_prompt_encoder_gpu_rocm.json#L18-L19

The files that need updating are:
https://github.com/iree-org/iree/blob/main/build_tools/pkgci/external_test_suite/sdxl_prompt_encoder_gpu_rocm_gfx90a.json
https://github.com/iree-org/iree/blob/main/build_tools/pkgci/external_test_suite/sdxl_scheduled_unet_gpu_rocm_gfx90a.json
https://github.com/iree-org/iree/blob/main/build_tools/pkgci/external_test_suite/sdxl_vae_decode_gpu_rocm_gfx90a.json

Let's see if it works with those changes.

**Comment by saienduri** [comment]
> Seems like that changed around [9da0309](https://github.com/iree-org/iree/commit/9da0309b0491df57629a2177ab1dbec4aa73ae6e) , but the code there seems to be off by default?

It looks like we already have that flag enabled for the sdxl models (https://github.com/iree-org/iree/blob/main/build_tools/pkgci/external_test_suite/sdxl_vae_decode_gpu_rocm_gfx90a.json#L9). So looks like this PR is a further optimization on the `--iree-llvmgpu-enable-prefetch=true` flag giving us a boost :)

**Pull request merged**
