### PR TITLE
Allow disabling vmfb builds when check tests are disabled.

### PR DESCRIPTION
**Pull request by ScottTodd**
I thought it might be useful to build bytecode modules even when a hal driver was disabled on https://github.com/openxla/iree/pull/16086, but I've changed my mind. We have a few CI jobs that build for specific platforms and it is wasteful to generate .vmfb files for tests that won't be run.

Tests like WebGPU that _only compile_ should still slip through here and be included in the build stage.

`build_and_test_android / cross_compile`

* before: https://github.com/openxla/iree/actions/runs/7718833215/job/21041245404?pr=16271#step:7:1041 (1197 targets, 1.35GB, 1m30s build)
* after: https://github.com/openxla/iree/actions/runs/7719242041/job/21042369507?pr=16273#step:7:1041 (801 targets, 1.34GB, 1m11s build)

### CODE REVIEW

**Comment by ScottTodd** [comment]
Whyyyy is the Android build 1.3GB? Each individual cc test in the HAL CTS is 12+ MB?
image

(I was hoping this would shave off more than 0.01GB lol... something isn't adding up)

edit: here's the folder I'm looking at: https://storage.googleapis.com/iree-github-actions-presubmit-artifacts/7719242041/1/build-android-arm_64.tar

**Comment by benvanik** [comment]
12MB/piece is pretty large - worth a bloaty run
for tests (not benchmarks) we can also try shared library builds

I do think we need to totally reboot the CTS - we should have one binary per test that has the various backends compiled in, not one per test per target (given that these are all the same size I'm assuming they're linking in everything anyway)

**Comment by ScottTodd** [comment]
> Tests like WebGPU that only compile should still slip through here and be included in the build stage.

I'm debating the continued value of compile-only usage of 'check' tests here.

Also, while this patch helps CI flows, it could also be awkward for development flows. On the CI, test jobs should only need to either download or build artifacts that they actually use. On developer machines, it's nice being able to test that the compiler is able to successfully compile the test suite for all backends - even those that the developer's machine does not support or want to run.

Might be time to pick a short term plan with compromises and rebuild in the longer term with that flexibility in mind. Short term flexibility could be to add more CMake options... but that's stacking complexity on top of complexity :/

**Comment by benvanik** [comment]
Yeah :( anything in the direction of making things easier to remove/replace wholesale is nice - if it's a mechanism on the chopping block then feel free to muddy it up so long as it doesn't add more coupling/one-off options plumbed into places we want to preserve.

**Comment by ScottTodd** [comment]
> 12MB/piece is pretty large - worth a bloaty run
> for tests (not benchmarks) we can also try shared library builds

```
D:\dev\projects\iree (infra-lit-hostonly)
λ D:\dev\tools\bloaty\bloaty.exe D:\dev\projects\iree-tmp\2024_01_30_infra\build-android-arm_64\runtime\src\iree\hal\drivers\local_task\cts\local-task_vmvx_allocator_test
    FILE SIZE        VM SIZE
 --------------  --------------
  28.9%  3.50Mi   0.0%       0    .debug_info
  28.3%  3.43Mi   0.0%       0    .debug_loc
  12.8%  1.55Mi   0.0%       0    .debug_str
   7.8%   970Ki   0.0%       0    .debug_ranges
   7.8%   967Ki   0.0%       0    .debug_line
   6.7%   826Ki  68.7%   826Ki    .text
   1.9%   240Ki   0.0%       0    .symtab
   1.8%   219Ki   0.0%       0    .strtab
   1.1%   133Ki   0.0%       0    .debug_abbrev
   0.9%   113Ki   9.4%   113Ki    .rodata
   0.7%  85.6Ki   7.1%  85.6Ki    .eh_frame
   0.6%  70.5Ki   5.8%  70.5Ki    .rela.dyn
   0.2%  28.1Ki   2.3%  28.1Ki    .gcc_except_table
   0.2%  26.7Ki   2.2%  26.7Ki    .data.rel.ro
   0.2%  19.5Ki   1.6%  19.5Ki    .eh_frame_hdr
   0.1%  10.1Ki   0.6%  7.20Ki    [20 Others]
   0.0%       0   0.8%  9.55Ki    .bss
   0.0%  4.73Ki   0.4%  4.73Ki    .data
   0.0%  4.50Ki   0.4%  4.50Ki    .dynsym
   0.0%  4.39Ki   0.4%  4.39Ki    .rela.plt
   0.0%  2.95Ki   0.2%  2.95Ki    .plt
 100.0%  12.1Mi 100.0%  1.18Mi    TOTAL
```

Is that a debug build?

* https://github.com/openxla/iree/blob/main/build_tools/cmake/build_android.sh doesn't set a build type.
* [Logs say](https://github.com/openxla/iree/actions/runs/7719242041/job/21042369507?pr=16273#step:7:148) `-- No build type selected, default to Release`

> I do think we need to totally reboot the CTS - we should have one binary per test that has the various backends compiled in, not one per test per target (given that these are all the same size I'm assuming they're linking in everything anyway)

Not sure I agree with this. I find it useful to run each individual binary directly under a debugger. I could change my workflow though (https://xkcd.com/1172/)

image

**Comment by benvanik** [comment]
Obviously has debug symbols - if we don't want those (which sucks for CI because it means any failure stacks can't be symbolized) then we can strip them, but I'd have expected cmake release to not include them (vs relwithdebinfo).

Shared libraries with shim executables would still let that workflow work without duplicating things. We don't need 100 copies of the same exact full binary on the CI.

**Comment by ScottTodd** [comment]
lol so this is a release build, but with assertions: https://github.com/openxla/iree/blob/010710b6b13f6385e514d53eeb1de1daf7d683d3/build_tools/cmake/build_android.sh#L53-L58
... which sets
```
-- IREE_ENABLE_ASSERTIONS force disabled NDEBUG for CMAKE_CXX_FLAGS_RELEASE: '-O3 -DNDEBUG ' -> '-O3 '
-- IREE_ENABLE_ASSERTIONS force disabled NDEBUG for CMAKE_C_FLAGS_RELEASE: '-O3 -DNDEBUG ' -> '-O3 '
```

**Comment by benvanik** [comment]
lol this is why cmake flags like that are dangerous :P

**Comment by ScottTodd** [comment]
> Shared libraries with shim executables would still let that workflow work without duplicating things. We don't need 100 copies of the same exact full binary on the CI.

Ah, I see what you mean. Looks like removing the duplicate link steps there could also shave 4 seconds or so off of some CI builds.

**Comment by benvanik** [comment]
yeah - a .c main() per test with a build-file specified device preprocessor flag that just sets the device name and passes it to the `run_the_real_cts_thing(device)` in a shared library would get you flagless debuggable tests without the duplication

should hopefully save more than 4 seconds as we'll compile and link each cts once regardless of how many backends there are, then the shim should be real cheap (5 lines of code in a main), and we'll do a lot less I/O 🥳

**Comment by ScottTodd** [comment]
Oh, on standard GitHub-hosted runners I'm actually seeing around 40-50 seconds spent _building_ files like `iree_hal_drivers_local_sync_cts_local-sync_embedded-elf_command_buffer_test.dir/local-sync_embedded-elf_command_buffer_test.cc.o` then around 4 seconds _linking_ the executables. (logs here: https://github.com/ScottTodd/iree/actions/runs/7734158188/job/21087643265#step:6:637)

**Comment by ScottTodd** [comment]
> Yeah :( anything in the direction of making things easier to remove/replace wholesale is nice - if it's a mechanism on the chopping block then feel free to muddy it up so long as it doesn't add more coupling/one-off options plumbed into places we want to preserve.

The setup I think I want for the short term is:

* One CI job generates all 'check' test .vmfb files, even those that are build-only (rocm/webgpu/etc.). Ideally that job would have debug symbols included.
* Test CI jobs only generate 'check' test .vmfb files for tests they are going to run
* Developers can do either - maybe with the current behavior (build all) as the default

That would involve adding a new CMake option.

> Obviously has debug symbols - if we don't want those (which sucks for CI because it means any failure stacks can't be symbolized) then we can strip them, but I'd have expected cmake release to not include them (vs relwithdebinfo).

I've been thinking about this for package-based CI... Should we have iree-dist include debug symbols too? I'll need to check, but I think a release build would be way smaller and easier to pass around using standard GitHub Actions artifacts (vs GCS / Azure cloud storage). Test jobs would then be using the release _compiler_ but at least they could build debug _runtime_ binaries.

**Review by benvanik — APPROVED** [review]

**Review by pzread — APPROVED** [review]

**Pull request merged**
