### PR TITLE
[LLVMGPU] Turn on TD strategy for unaligned matmul

### PR DESCRIPTION
**Pull request by ThomasRaoux**

### CODE REVIEW

**Review by nicolasvasilache — APPROVED** [review]

**Comment by nicolasvasilache** [comment]
Rescinded my approval for now as there are other concerns that need to still be addressed:
  1. I am unclear from the changes I see in this PR if we are actually testing the unaligned / mixed unaligned cases. I see 
```    name = "e2e_matmul_direct_f32_gpu_large_unaligned",
    compiler_flags = [
        "--iree-hal-cuda-llvm-target-arch=sm_80",
    ],
    generator_args = [
        "--lhs_rhs_type=f32",
        "--shapes=large",
    ],
    ...
```
in the tests but I cannot correlate that to actually producing an unaligned test. I was expecting we'd see some concrete sizes 
plugged in, which leads me to ask if we are indeed testing what we think we are?

  2. @qedawkins is adapting the transform to also work for the aligned and partially cases in #13541. However my 1+ month old recollection is I was still missing optimization of the copy-back in the aligned case and did not yet bridge the perf gap, so this will require more work to avoid regressions. We could also add a flag to avoid the cases that work well in IREE for now.
  3. we were trying to benchmark unaligned with mmperf with @mariecwhite but both saw errors like: ```iree/runtime/src/iree/hal/buffer.c:339: PERMISSION_DENIED; buffer does not support the requested access type; buffer allows DISCARD|ANY|7F20h, operation requires WRITE
102/112 done, matmul_ireecuda_2176x2176x2176 took 0 and yields 0.0
iree/runtime/src/iree/hal/buffer.c:339: PERMISSION_DENIED; buffer```. It is possible there is some latent bug that is not yet tested against and does not show up, which also reflects back to 1.

**Comment by nicolasvasilache** [comment]
Once this lands, will address #13104

**Comment by bjacob** [comment]
Does #13657 unblock this? Notice how you can choose, for each TestShape, whether to test an accumulating or non-accumulating matmul. See: https://github.com/openxla/iree/blob/a012e45cd81f10be08fbb11238e6327f503a7510/tests/e2e/matmul/generate_e2e_matmul_tests.py#L150-L151

**Comment by ThomasRaoux** [comment]
> Does #13657 unblock this? Notice how you can choose, for each TestShape, whether to test an accumulating or non-accumulating matmul. See:
> 
> https://github.com/openxla/iree/blob/a012e45cd81f10be08fbb11238e6327f503a7510/tests/e2e/matmul/generate_e2e_matmul_tests.py#L150-L151

Yes I think this is good enough, that will allow make sure we can have tests going through the TD path. It should be easy to add more if we want more robust testing.

**Comment by ThomasRaoux** [comment]
@nicolasvasilache now with Benoit's PR this PR will run those shapes:
```
   TestShape(m=123, k=456, n=789, accumulate=True),
        TestShape(m=654, k=321, n=234, accumulate=False),
        # shapes involving vectors (i.e. most rectangular cases)
        TestShape(m=1, k=1000, n=1000, accumulate=True),  # large vector*matrix
        TestShape(m=1000, k=1000, n=1, accumulate=True),  # large matrix*vector
        TestShape(m=1000, k=1000, n=1, accumulate=False),  # large matrix*vector
```

only the accumulate = false will go through the TD path. Do you think it is good enough. Do you have any suggestions on good sizes to add?

**Comment by ThomasRaoux** [comment]
@nicolasvasilache the new shapes all seem to pass, this should be ready to land. 

What do you think?

**Comment by nicolasvasilache** [comment]
> @nicolasvasilache the new shapes all seem to pass, this should be ready to land.
> 
> What do you think?

Rebased on main to hopefully see some benchmark number changes on cases that were formerly just ignored.

**Comment by ThomasRaoux** [comment]
> > @nicolasvasilache the new shapes all seem to pass, this should be ready to land.
> > What do you think?
> 
> Rebased on main to hopefully see some benchmark number changes on cases that were formerly just ignored.

Looks like we see the perf boost as expected. I think this is ready to land!

**Review by nicolasvasilache — APPROVED** [review]
Ok, let's land and iterate.

I am still unclear about the mmperf issues but I don't have much confidence in that part of the tooling.

**Pull request merged**
