### PR TITLE
Drop lists of VulkanSPIRV flags.

### PR DESCRIPTION
**Pull request by ScottTodd**
Previously this could take a list of `--iree-vulkan-target-triple` and `--iree-vulkan-target-env` flags. Other backends only support a single flag and as we move towards multi-device, we will be standardizing on device spec files with `#hal.device.target`s and their executable formats, _not_ loose flags for each backend.

Now only one of those flags can be set at a time and both are a single value, not a list.

Progress on https://github.com/openxla/iree/issues/15468 (the flag parsing code in here was not compatible with how compiler plugins are currently configured).

### CODE REVIEW

**Comment by benvanik** [comment]
one quick q: _could_ we make plugins support list options?

**Comment by ScottTodd** [comment]
> one quick q: _could_ we make plugins support list options?

I can check. https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/Utils/OptionUtils.h is what plugins use (with the `IREE_DEFINE_COMPILER_OPTION_FLAGS` macro). This code did _two_ nonstandard things with flags:

1. Using a list
2. Inspecting the _flags themselves_, not just their parsed values. See the `getPosition()` and `getNumOccurrences()` calls ([LLVM source here](https://github.com/llvm/llvm-project/blob/064c2e7579228389c8a6b78ee40280c319935715/llvm/include/llvm/Support/CommandLine.h#L296-L298))

**Comment by benvanik** [comment]
I see list supported in there (and thought we used it in other places) - so sounds like the issue is the position/etc manipulation. This could have been a single list flag with `=` or something in the values to split things instead of two synchronized flags. I think it's fine to pull this out and we could add it back like that if someone wants it for development.

**Review by benvanik — APPROVED** [review]

**Comment by ScottTodd** [comment]
> I see list supported in there (and thought we used it in other places) - so sounds like the issue is the position/etc manipulation. 

Here's the compile error I saw yesterday:

```
[build] ccache C:\PROGRA~2\MICROS~1\2022\Preview\VC\Tools\MSVC\1431~1.311\bin\Hostx64\x64\cl.exe  /nologo /TP -DIREE_TRACING_MODE=2 -DIREE_TRACING_PROVIDER_H=\"iree/base/tracing/tracy.h\" -ID:\dev\projects\iree -ID:\dev\projects\iree-build -ID:\dev\projects\iree\third_party\llvm-project\llvm\include -ID:\dev\projects\iree-build\llvm-project\include -ID:\dev\projects\iree\third_party\llvm-project\mlir\include -ID:\dev\projects\iree-build\llvm-project\tools\mlir\include -ID:\dev\projects\iree\third_party\llvm-project\lld\include -ID:\dev\projects\iree-build\llvm-project\tools\lld\include -ID:\dev\projects\iree\compiler\src -ID:\dev\projects\iree-build\compiler\src -ID:\dev\projects\iree\runtime\src -ID:\dev\projects\iree-build\runtime\src -ID:\dev\projects\iree-build\runtime\src\iree\base\internal\flatcc -ID:\dev\projects\iree\llvm-external-projects\iree-dialects\include -ID:\dev\projects\iree-build\llvm-external-projects\mlir-iree-dialects\include -ID:\dev\projects\iree-build\runtime\src\iree\schemas -external:ID:\dev\projects\iree\third_party\tracy\public -external:ID:\dev\projects\iree\third_party\flatcc\include -external:W0 /DWIN32 /D_WINDOWS /EHsc /Z7 /O2 /Ob1  -std:c++17 -MD /Zc:preprocessor /DWIN32_LEAN_AND_MEAN /DNOMINMAX /D_USE_MATH_DEFINES /D_CRT_SECURE_NO_WARNINGS /D_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES /D_SILENCE_NONFLOATING_COMPLEX_DEPRECATION_WARNING /GR- /bigobj /W3 /wd4200 /wd4018 /wd4146 /wd4244 /wd4267 /wd4005 /wd4065 /wd4141 /wd4624 /wd4576 /wd5105 -ID:/dev/projects/iree/third_party/flatcc/include/ -ID:/dev/projects/iree/third_party/flatcc/include/flatcc/reflection/ /showIncludes /Focompiler\plugins\target\VulkanSPIRV\CMakeFiles\iree_compiler_plugins_target_VulkanSPIRV_VulkanSPIRV.objects.dir\VulkanSPIRVTarget.cpp.obj /Fdcompiler\plugins\target\VulkanSPIRV\CMakeFiles\iree_compiler_plugins_target_VulkanSPIRV_VulkanSPIRV.objects.dir\ /FS -c D:\dev\projects\iree\compiler\plugins\target\VulkanSPIRV\VulkanSPIRVTarget.cpp
[build] D:\dev\projects\iree\compiler\src\iree/compiler/Utils/OptionUtils.h(60): error C2672: 'mlir::iree_compiler::OptionsBinder::makePrintCallback': no matching overloaded function found
[build] D:\dev\projects\iree\compiler\plugins\target\VulkanSPIRV\VulkanSPIRVTarget.cpp(52): note: see reference to function template instantiation 'void mlir::iree_compiler::OptionsBinder::opt<llvm::cl::list<std::string,bool,llvm::cl::parser<std::string>>,llvm::SmallVector<std::string,1>,llvm::cl::desc>(llvm::StringRef,V &,llvm::cl::desc)' being compiled
[build]         with
[build]         [
[build]             V=llvm::SmallVector<std::string,1>
[build]         ]
[build] D:\dev\projects\iree\compiler\src\iree/compiler/Utils/OptionUtils.h(46): error C2893: Failed to specialize function template 'unknown-type mlir::iree_compiler::OptionsBinder::makePrintCallback(llvm::StringRef,ParserTy &,V *)'
[build] D:\dev\projects\iree\compiler\src\iree/compiler/Utils/OptionUtils.h(127): note: see declaration of 'mlir::iree_compiler::OptionsBinder::makePrintCallback'
[build] D:\dev\projects\iree\compiler\src\iree/compiler/Utils/OptionUtils.h(46): note: With the following template arguments:
[build] D:\dev\projects\iree\compiler\src\iree/compiler/Utils/OptionUtils.h(46): note: 'V=V'
[build] D:\dev\projects\iree\compiler\src\iree/compiler/Utils/OptionUtils.h(46): note: 'ParserTy=ParserClass'
[build] D:\dev\projects\iree\compiler\src\iree/compiler/Utils/OptionUtils.h(46): error C3536: 'printCallback': cannot be used before it is initialized
[build] D:\dev\projects\iree\compiler\src\iree/compiler/Utils/OptionUtils.h(63): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'mlir::iree_compiler::OptionsBinder::LocalOptionInfo'
[build] D:\dev\projects\iree\compiler\src\iree/compiler/Utils/OptionUtils.h(63): note: Invalid aggregate initialization
[build] ninja: build stopped: subcommand failed.
```

That was with this code:

```c++
struct VulkanSPIRVOptions {
  // Vulkan target triples.
  llvm::SmallVector<std::string> targetTriples;

  void bindOptions(OptionsBinder &binder) {
    static llvm::cl::OptionCategory category("VulkanSPIRV HAL Target");
    binder.opt<llvm::cl::list<std::string>>(
        "iree-vulkan-target-triple", targetTriples,
        llvm::cl::desc(
            "Vulkan target triple controlling the SPIR-V environment."));
```

I didn't dig much deeper - figured the code could be refactored anyways.

**Comment by qedawkins** [comment]
yeah I might have been trying to avoid changing the names of the flags when I first did this to avoid breaking downstream flows. Refactoring sounds good to me because I think those downstream flows have mostly moved on.

**Review by qedawkins — APPROVED** [review]

**Review by qedawkins — CHANGES_REQUESTED** [review]
wait, does this drop `iree-vulkan-target-env` entirely?

**Comment by benvanik** [comment]
oh, you need to use `binder.list(` - not an opt on a list type.

**Comment by ScottTodd** [comment]
> wait, does this drop `iree-vulkan-target-env` entirely?

Yeah, it does. I could keep that if I drop the positional handling (and use the right syntax for lists of flags, thanks Ben 😅)

**Comment by qedawkins** [comment]
> > wait, does this drop `iree-vulkan-target-env` entirely?
> 
> Yeah, it does. I could keep that if I drop the positional handling (and use the right syntax for lists of flags, thanks Ben 😅)

Yeah that would be good. Just make `--iree-vulkan-target-triple` and `--iree-vulkan-target-env` mutually exclusive. The target env version is the more powerful one so we need to keep that, and dropping target triples is a big hit to developer flows. Basically the positional handling is just to allow users to mix them and we don't need to keep that functionality.

**Comment by ScottTodd** [comment]
Would it be fine to drop the list aspect and only allow a single env or a single triple? (Trying to keep the various backends consistent)

**Comment by qedawkins** [comment]
> Would it be fine to drop the list aspect and only allow a single env or a single triple? (Trying to keep the various backends consistent)

Sounds good to me!

**Review by qedawkins — APPROVED** [review]
nice, thanks!

**Pull request merged**
