### PR TITLE
Revert "Switch e2e tests and benchmarks to `--iree-flow-enable-data-tiling` on `llvm-cpu`"

### PR DESCRIPTION
**Pull request by pzread**
Due to the #11434, I think we can revert iree-org/iree#11411 first.

### CODE REVIEW

**Review by ScottTodd — APPROVED** [review]

**Comment by MaheshRavishankar** [comment]
If Mobilbertint8 is the problem can we just drop this for that one.

**Review by MaheshRavishankar — COMMENTED** [review]
I am fine with revert, but maybe we can just drop this for mobilebertint8

**Comment by benvanik** [comment]
that's the only one we track - I suspect the shark tank/the model zoo/etc will have hits like this as well in at least a few models

**Comment by MaheshRavishankar** [comment]
> that's the only one we track - I suspect the shark tank/the model zoo/etc will have hits like this as well in at least a few models

Sure, but it isnt enabled by default. So in our CI we can just drop mobilebertint8

**Comment by benvanik** [comment]
ah good point!

as part of the follow-up we should figure out why it takes so long - I feel like we've had this happen a few times in the past and it'd be good to find a more permanent fix to avoid the whackamole - probably next year :)

**Comment by MaheshRavishankar** [comment]
> ah good point!
> 
> as part of the follow-up we should figure out why it takes so long - I feel like we've had this happen a few times in the past and it'd be good to find a more permanent fix to avoid the whackamole - probably next year :)

It comes down to hitting a bad fallback path w.r.t vectorization, but I wouldnt expect this to happen here. Yes something to figure out if this has to go live by default for sure.

**Comment by MaheshRavishankar** [comment]
@bjacob FYI. I think you can re-enable, but just drop the mobilebertint8 changes.

**Comment by bjacob** [comment]
It feels worth understanding this compile time problem rather than necessarily reenabling around it. Is it the same as you and @hanhanW had dealt with in the past? Does it come down to "tiled matmul int8 vector codegen runs into bad cases" ? Do you have a sense of how hard it would be to fix?

**Comment by bjacob** [comment]
Also, is this issue avoided on AArch64, where the codegen goes into `VectorContractCustomKernels` inline assembly? Is it x86-only?

Is there a breakdown of targets compile times so we can answer these questions generically ?

**Comment by bjacob** [comment]
ok, i'm nerdsniped.

**Comment by pzread** [comment]
I'm fine to re-enable the rest (thought about that but decided to let @bjacob decide)

**Comment by MaheshRavishankar** [comment]
CI tracks compilation time on benchmarks... but the above report shows no improved or regressed compilation time.

First step might be to enable everything else apart from mobilebertint8. Then we can triage issue there. It is a problem with the current vectorization path...

**Comment by bjacob** [comment]
Above I wondered if it might be specific to x86, like the previous time that we discussed long compile times with mmt4d due to generic codegen on x86, while on aarch64 we have custom kernels.

But the benchmarks that this issue is talking about here are android aarch64 benchmarks.

I reproduced:

```
$ time tools/iree-compile --iree-hal-target-backends=llvm-cpu --iree-flow-mmt4d-target-options='arch=aarch64 features=+dotprod' --iree-input-type=tosa --iree-llvm-target-cpu-features=+dotprod --iree-llvm-target-triple=aarch64-none-linux-android29 benchmark_suites/TFLite/mobilebert-baseline-tf2-quant.tflite.mlir -o /tmp/a.vmfb

real    1m3.686s

$ time tools/iree-compile --iree-hal-target-backends=llvm-cpu --iree-flow-enable-data-tiling --iree-input-type=tosa --iree-llvm-target-cpu-features=+dotprod --iree-llvm-target-triple=aarch64-none-linux-android29 benchmark_suites/TFLite/mobilebert-baseline-tf2-quant.tflite.mlir -o /tmp/a.vmfb

... hit Ctrl-C after 10 minutes
```

This shouldn't be explainable by "slow generic vector codegen" in the vector.contract's, since the new tiles should be the same shape as the old tiles.

So either there's a bug in my tile shape selection and the tiles are not actually the same (would be surprising, as there are tests that say they are).

Or it's in the codegen of the **packing/unpacking code** as opposed to the matmul kernel vector.contract codegen.

**Comment by bjacob** [comment]
I have checked that with the new `--iree-flow-enable-data-tiling`, there are no `vector.contract` at all past `VectorContractCustomKernels`. So whatever is triggering long vectorization / vector codegen compile times, is not the matmul kernel / vector.contract.  @hanhanW do you find it plausible that it might be packing/unpacking code?

**Comment by MaheshRavishankar** [comment]
It is probably the Codegen for fusing pack op with generic op producers that is the issue.

**Comment by bjacob** [comment]
Confirmed! This diff fixes the compile time regression (and even improves it, 57s vs 63s).  Clearly not fit for a PR, but what does this tell us?  @hanhanW does it make sense for you to take over https://github.com/iree-org/iree/issues/11434 at this point if your think our understanding is correct here that this is about these fusions?

```diff
benoitjacob@cloud:~/iree$ git diff
diff --git a/compiler/src/iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp b/compiler/src/iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
index 6c7662494..71570923a 100644
--- a/compiler/src/iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
+++ b/compiler/src/iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
@@ -534,6 +534,13 @@ static bool isFusableWithConsumer(OpOperand &fusedOperand,
   Operation *producer = fusedOperand.get().getDefiningOp();
   Operation *consumer = fusedOperand.getOwner();
 
+  if (isa<LinalgExt::PackOp>(consumer) || isa<LinalgExt::PackOp>(producer) ||
+      isa<LinalgExt::UnPackOp>(consumer) || isa<LinalgExt::UnPackOp>(producer) ||
+      isa<LinalgExt::UnsetEncodingOp>(consumer) || isa<LinalgExt::UnsetEncodingOp>(producer) ||
+      isa<LinalgExt::SetEncodingOp>(consumer) || isa<LinalgExt::SetEncodingOp>(producer) ) {
+    return false;
+  }
+
   // Fuse unset_encoding operations with `tensor.extract_slice` and elementwise
   // generic ops.
   auto producerUnsetEncodingOp = dyn_cast<LinalgExt::UnsetEncodingOp>(producer);
@@ -625,6 +632,13 @@ static bool isFusableWithProducer(OpOperand &operand, bool aggressiveFusion) {
   Operation *producer = operand.get().getDefiningOp();
   Operation *consumer = operand.getOwner();
 
+  if (isa<LinalgExt::PackOp>(consumer) || isa<LinalgExt::PackOp>(producer) ||
+      isa<LinalgExt::UnPackOp>(consumer) || isa<LinalgExt::UnPackOp>(producer) ||
+      isa<LinalgExt::UnsetEncodingOp>(consumer) || isa<LinalgExt::UnsetEncodingOp>(producer) ||
+      isa<LinalgExt::SetEncodingOp>(consumer) || isa<LinalgExt::SetEncodingOp>(producer) ) {
+    return false;
+  }
+
   auto linalgProducerOp = dyn_cast<linalg::LinalgOp>(producer);
   auto setEncodingOp = dyn_cast<IREE::LinalgExt::SetEncodingOp>(consumer);
   if (linalgProducerOp && setEncodingOp) {
```

**Pull request merged**
