### PR TITLE
Convert tests in e2e/models to be check tests

### PR DESCRIPTION
**Pull request by antiagainst**
This provides better support for running those model tests in environments where we cannot have LIT testing framework. It also enables reusing these tests from `experimental/` directory w/o touching the source code to add `RUN` directives.

Progress towards https://github.com/openxla/iree/issues/4370

### CODE REVIEW

**Comment by benvanik** [comment]
This is a little unfortunate as I use these models on a daily basis for compiler testing and making them check tests breaks that (they no longer output values, and include a host readback/comparison that a real model would not have). I think we may want to not make these tests but instead reference samples or something - I think we have plenty of test coverage from other larger models but if these get switched we'll have no "check out repo and compile a model without needing to do other stuff" examples.

That is, if you're changing these to have them as tests I'd rather have actual tests and leave these as is but maybe move them to an examples directory. resnet and undirectional_lstm are my reference models, for example, but not particularly interesting as e2e tests outside of compiler testing (unidirectional_lstm finds lots of issues, but rarely ones in codegen/etc and mostly in flow/stream/hal compiler stuff).

**Comment by benvanik** [comment]
(basically, these files are the most "hello world" things we have in the repo, and I don't want to lose having "hello world")

**Comment by antiagainst** [comment]
Ah, I didn't know that you are using these tests in your daily workflow; just saw that we have some in lit tests and some in check tests so though it would be nice to unify them. Plus with it I can reference them when writing tests for Metal.

Thinking about it, maybe we can support both? I mean, in each file, have two public entry points, one for the existing style with explicit input/output so you can still use as-is, and another one for wrapping it up with constant inputs and check ops. Does that work for you?

**Comment by antiagainst** [comment]
Actually I'm also fine to keep them as-is too. My main goal right now is trying to isolate the Metal stuff--don't want to touch code in `tests/e2e/` before we decided to move Metal from `experiemental/` to `runtime/../hal`. But meh, even adding a few lines there won't be the end of the world..

**Comment by antiagainst** [comment]
Don't really need this anymore. So dropping it.

**Pull request closed without merging**
