### PR TITLE
Add Falcon7b int4 to CI benchmarks

### PR DESCRIPTION
**Pull request by mariecwhite**
Added to x86 benchmarks only. ARM is taking >2 hours.

### CODE REVIEW

**Comment by kuhar** [comment]
I'd love to have this for desktop GPUs. @mariecwhite do you know if this bytecode works on cuda/rocm/vulkan?

**Comment by pzread** [comment]
I think it should be easy to add this model to CUDA and Vulkan benchmark suite:
https://github.com/openxla/iree/blob/main/build_tools/python/benchmark_suites/iree/cuda_benchmarks.py
https://github.com/openxla/iree/blob/main/build_tools/python/benchmark_suites/iree/vulkan_nvidia_benchmarks.py

For ROCM we might need to write another one (but reuse the MLIR) here https://github.com/openxla/iree/tree/main/experimental/regression_suite/tests/pregenerated, as we haven't integrated the current and experimental benchmark suite

**Review by pzread — COMMENTED** [review]
The x86_64 benchmarks is now taking 47mins to run. We might want to cut some other benchmarks or enable the sharding in the workflow:

https://github.com/openxla/iree/blob/6c1b1ab6ca2d628570d779a775a82ff4662a6a3f/.github/workflows/build_e2e_test_artifacts.yml#L42-L48

I guess something like `shard-count: "c2-standard-60=2,default=1"` might work. The parameter can be passed here:
https://github.com/openxla/iree/blob/6c1b1ab6ca2d628570d779a775a82ff4662a6a3f/.github/workflows/ci.yml#L825-L835

**Review by pzread — APPROVED** [review]

**Comment by mariecwhite** [comment]
@pzread we can also change the thread config from 8 to 15 since we're using `c2-standard-60`. It will change the benchmark series though.

**Comment by mariecwhite** [comment]
> I'd love to have this for desktop GPUs. @mariecwhite do you know if this bytecode works on cuda/rocm/vulkan?

I haven't tried but it's straightforward to add it to CI and test, as @pzread mentioned.

**Pull request merged**
