### PR TITLE
cherry-pick revert of 2fc3c5c34c4c0ce94a217717a469620e06325fb0

### PR DESCRIPTION
**Pull request by ThomasRaoux**
This reverts a commit causing performance regressions.

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
I am not sure we should cherry pick reverts if they are perf regressions. Cherry picks causes issues with internal integration. Can we fix forward?

**Comment by ThomasRaoux** [comment]
> I am not sure we should cherry pick reverts if they are perf regressions. Cherry picks causes issues with internal integration. Can we fix forward?

Yeah but I don't think we want to live with a big perf regression for that long. I think this is going to affect users like Nod if we leave it.

**Comment by ThomasRaoux** [comment]
> I am not sure we should cherry pick reverts if they are perf regressions. Cherry picks causes issues with internal integration. Can we fix forward?

By forward fix you mean fix in IREE only? I don't see an easy way

**Review by MaheshRavishankar — APPROVED** [review]

**Comment by MaheshRavishankar** [comment]
Big perf regressions are candidates for cherry pick reverts, but small regressions should be fix forward (might even mean fix in MLIR and wait on next integrate). Main is not meant to be stable. I am still not comfortable with main being treated as stable from user perspective.

**Comment by ThomasRaoux** [comment]
> Big perf regressions are candidates for cherry pick reverts, but small regressions should be fix forward (might even mean fix in MLIR and wait on next integrate). Main is not meant to be stable. I am still not comfortable with main being treated as stable from user perspective.

in addition to the disturbance we take the risk of piling regressions if we have to wait on integrate.

**Pull request merged**
