### PR TITLE
Add new metrics to MobileBert benchmarks.

### PR DESCRIPTION
**Pull request by hanhanW**

### CODE REVIEW

**Comment by hanhanW** [comment]
@MaheshRavishankar I have the doc to set this up, not send out yet. However, this is still not available to benchmark on Android. Hit the same reason in https://github.com/google/iree/issues/5152

Error log:

```
../iree/modules/hal/hal_module.c:742: OUT_OF_RANGE; binding count 36 > 32; while invoking native function hal.descriptor_set_layout.create; while calling import
```

**Comment by MaheshRavishankar** [comment]
FYI : @asaadaldien . Was just chatting with Ahmed who hit this issue.

I was hoping that the non-splat constants being inlined will help a bit here. If not, we need to add a mechanism here to control fusion. Right now the elementwise operations fuse everything it can, but that has a cost.

One way to control this is to have a callback function to the elementwise operation fusion pattern, that once it has decided that a producer can be fused with the consumer will invoke a callback to check if it should go ahead with the fusion. Here we could bail if we hit some limits. The mechanism goes into core. The actual callback will live in IREE. I can file an issue for tracking this.

Any takers?

**Comment by hanhanW** [comment]
This still does not work because it takes real weight. I tested locally and remotely, I got the same error, ie `OUT_OF_RANGE; binding count 36 > 32; while invoking native function hal.descriptor_set_layout.create;`.

**Comment by MaheshRavishankar** [comment]
> This still does not work because it takes real weight. I tested locally and remotely, I got the same error, ie `OUT_OF_RANGE; binding count 36 > 32; while invoking native function hal.descriptor_set_layout.create;`.

I am working on adding a cost model upstream to limit fusion. But thats not a satisfactory solution.

**Comment by MaheshRavishankar** [comment]
> This still does not work because it takes real weight. I tested locally and remotely, I got the same error, ie `OUT_OF_RANGE; binding count 36 > 32; while invoking native function hal.descriptor_set_layout.create;`.

In the meantime, could you increase the limit of constants inlined to 2048 and try?

**Comment by hanhanW** [comment]
> > This still does not work because it takes real weight. I tested locally and remotely, I got the same error, ie `OUT_OF_RANGE; binding count 36 > 32; while invoking native function hal.descriptor_set_layout.create;`.
> 
> In the meantime, could you increase the limit of constants inlined to 2048 and try?

I already tried. I think this is because they are real weights, not small constants or splat constants.

**Comment by MaheshRavishankar** [comment]
> > > This still does not work because it takes real weight. I tested locally and remotely, I got the same error, ie `OUT_OF_RANGE; binding count 36 > 32; while invoking native function hal.descriptor_set_layout.create;`.
> > 
> > 
> > In the meantime, could you increase the limit of constants inlined to 2048 and try?
> 
> I already tried. I think this is because they are real weights, not small constants or splat constants.

That limit should work for non-splat constants too.

**Pull request closed without merging**
