### PR TITLE
Cherry-pick SPIRV-related llvm-project changes

### PR DESCRIPTION
**Pull request by kuhar**
Cherry-pick a SPIR-V change:
- https://github.com/llvm/llvm-project/commit/fce33e1140bbf5ddf2afa5c3be89433ed2a70e4d

Fixes: https://github.com/iree-org/iree/issues/10818

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
There is already an integrate in progress. Can we please wait for that to land?

Cc @vmurali

**Comment by antiagainst** [comment]
> Cherry-pick two SPIR-V related changes:
> 
> 1. https://reviews.llvm.org/rGfae258e6c6194ddd88894b79053b0fd31df5990d
> 2. https://reviews.llvm.org/rGfce33e1140bbf5ddf2afa5c3be89433ed2a70e4d
> 
> Fixes: #10818

Nit: use links to GitHub llvm commits?

**Comment by kuhar** [comment]
> > Cherry-pick two SPIR-V related changes:
> > 
> > 1. https://reviews.llvm.org/rGfae258e6c6194ddd88894b79053b0fd31df5990d
> > 2. https://reviews.llvm.org/rGfce33e1140bbf5ddf2afa5c3be89433ed2a70e4d
> > 
> > Fixes: #10818
> 
> Nit: use links to GitHub llvm commits?

done

**Comment by MaheshRavishankar** [comment]
> > There is already an integrate in progress. Can we please wait for that to land?
> > Cc @vmurali
> 
> FYI, the integrate does not include one of the cherry-picked changes. I can wait a few days if this can be cherry-picked before the next integrate.

You can cherry pick the missing commit after the integrate lands.

**Comment by MaheshRavishankar** [comment]
FYI the integrate has landed now....

**Comment by ThomasRaoux** [comment]
Are the hlo changes there on purpose?

**Comment by kuhar** [comment]
> Are the hlo changes there on purpose?

No, I'll undo them

**Review by ThomasRaoux — APPROVED** [review]

**Comment by kuhar** [comment]
Not sure why CI is failing, I'll try opening a new PR to see if that fixes it

**Pull request closed without merging**
