### PR TITLE
[spirv][vulkan] Switch from NV to KHR coop matrix extension

### PR DESCRIPTION
**Pull request by kuhar**

### CODE REVIEW

**Comment by kuhar** [comment]
I want to run a few more e2e tests before landing

**Review by antiagainst — APPROVED** [review]
Awesome! Thanks for the great work!

**Review by qedawkins — APPROVED** [review]
Downstream usage on latest drivers seems good! Thanks for the awesome work!

**Comment by kuhar** [comment]
Note: this suffers from the same issue as the NV coop matrix extension -- we do not check & declare the capabilities on the runtime side. But since this PR replaces the NV implementation, I will land as-is and fix validation issues as a follow-up.

**Pull request merged**
