### PR TITLE
Replace constant `outs` operands of Linalg ops as well.

### LINKED ISSUE #11830: TileAndDistributeToWorkgroups change introducing stack allocations and causing crashes/compile failures/etc
This integrate caused a regression in bufferization that leads to large stack allocations when none should be required:
https://github.com/iree-org/iree/commit/cc0c10cc67fe8b65aecdc0be7bdda61c79e4e219

This causes either compilation failures on certain targets (Windows) or crashes at runtime (Windows, OS X). It's also slow.

Testing before/after the integrate with `tests/e2e/models/resnet50_fake_weights.mlir` for x64 CPU on Windows I get this diff showing the additional allocations:
image

This seems to be the root cause (the first diff in the compilation):
image

Executable before TileAndDistributeToWorkgroups pass:
```mlir
#executable_target_embedded_elf_x86_64_ = #hal.executable.target<"llvm-cpu", "embedded-elf-x86_64", {cpu = "znver2", cpu_features = "-avx512pf,-tsxldtrk,+cx16,+sahf,-tbm,-avx512ifma,+sha,+crc32,-fma4,-vpclmulqdq,+prfchw,+bmi2,-cldemote,+fsgsbase,-avx512bf16,-amx-tile,-raoint,-uintr,-gfni,+popcnt,-ptwrite,+aes,-avx512bitalg,-movdiri,-widekl,+xsaves,-avx512er,-avxvnni,-avx512fp16,-avx512vnni,-amx-bf16,-avxvnniint8,-avx512vpopcntdq,-pconfig,+clwb,-cmpccxadd,-avx512f,+xsavec,+clzero,-pku,-amx-fp16,+mmx,-lwp,+rdpid,-xop,+rdseed,-waitpkg,-prefetchi,-kl,-movdir64b,+sse4a,-avx512bw,-avxneconvert,+clflushopt,+xsave,-avx512vbmi2,+64bit,-avx512vl,-serialize,-hreset,-invpcid,-avx512cd,+avx,-vaes,-amx-int8,+cx8,+fma,-rtm,+bmi,-enqcmd,+rdrnd,-mwaitx,+sse4.1,+sse4.2,+avx2,+fxsr,-wbnoinvd,+sse,+lzcnt,+pclmul,-rdpru,-avxifma,+f16c,+ssse3,-sgx,-prefetchwt1,+cmov,-avx512vbmi,-shstk,+movbe,-avx512vp2intersect,+xsaveopt,-avx512dq,+sse2,+adx,+sse3", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128", native_vector_size = 32 : index, target_triple = "x86_64-unknown-unknown-eabi-elf"}>
#map = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>
#map1 = affine_map<(d0, d1, d2, d3) -> (d3)>
#map2 = affine_map<(d0, d1, d2, d3, d4) -> (d0 * 2 + d3, d1 * 2 + d4, d2)>
#map3 = affine_map<(d0, d1, d2, d3, d4) -> (d3, d4)>
#map4 = affine_map<(d0, d1, d2, d3, d4) -> (d0, d1, d2)>
#map5 = affine_map<(d0, d1) -> (d0, d1)>
#map6 = affine_map<(d0, d1) -> (d1)>
#map7 = affine_map<(d0, d1) -> (d1, d0)>
#map8 = affine_map<(d0, d1) -> (d0)>
#map9 = affine_map<(d0) -> (d0)>
#map10 = affine_map<(d0) -> ()>
#map11 = affine_map<(d0, d1) -> ()>
#pipeline_layout = #hal.pipeline.layout<push_constants = 0, sets = [<0, bindings = [<0, storage_buffer, ReadOnly>, <1, storage_buffer>]>]>
#device_target_llvm_cpu = #hal.device.target<"llvm-cpu", {executable_targets = [#executable_target_embedded_elf_x86_64_]}>
module attributes {hal.device.targets = [#device_target_llvm_cpu]} {
  hal.executable private @predict_dispatch_3 {
    hal.executable.variant public @embedded_elf_x86_64, target = #executable_target_embedded_elf_x86_64_ {
      hal.executable.export public @predict_dispatch_3_generic_56x56x64x3x3 ordinal(0) layout(#pipeline_layout) {
      ^bb0(%arg0: !hal.device, %arg1: index, %arg2: index, %arg3: index, %arg4: index, %arg5: index):
        %x, %y, %z = flow.dispatch.workgroup_count_from_dag_root %arg1, %arg2, %arg3, %arg4, %arg5
        hal.return %x, %y, %z : index, index, index
      }
      builtin.module {
        func.func @predict_dispatch_3_generic_56x56x64x3x3() {
          %c3846080 = arith.constant 3846080 : index
          %c0 = arith.constant 0 : index
          %cst = arith.constant dense<0xFF800000> : tensor<56x56x64xf32>
          %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) offset(%c3846080) alignment(64) : !flow.dispatch.tensor<readonly:tensor<114x114x64xf32>>
          %1 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) offset(%c0) alignment(64) : !flow.dispatch.tensor<writeonly:tensor<56x56x64xf32>>
          %2 = flow.dispatch.tensor.load %0, offsets = [0, 0, 0], sizes = [114, 114, 64], strides = [1, 1, 1] : !flow.dispatch.tensor<readonly:tensor<114x114x64xf32>> -> tensor<114x114x64xf32>
          %3 = tensor.empty() : tensor<3x3xf32>
          %4 = linalg.generic {indexing_maps = [#map2, #map3, #map4], iterator_types = ["parallel", "parallel", "parallel", "reduction", "reduction"]} ins(%2, %3 : tensor<114x114x64xf32>, tensor<3x3xf32>) outs(%cst : tensor<56x56x64xf32>) {
          ^bb0(%in: f32, %in_0: f32, %out: f32):
            %5 = arith.maxf %out, %in : f32
            linalg.yield %5 : f32
          } -> tensor<56x56x64xf32>
          flow.dispatch.tensor.store %4, %1, offsets = [0, 0, 0], sizes = [56, 56, 64], strides = [1, 1, 1] : tensor<56x56x64xf32> -> !flow.dispatch.tensor<writeonly:tensor<56x56x64xf32>>
          return
        }
      }
    }
  }
}
```

And from flow:
```mlir
#map = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>
#map1 = affine_map<(d0, d1, d2, d3) -> (d3)>
#map2 = affine_map<(d0, d1, d2, d3, d4) -> (d0 * 2 + d3, d1 * 2 + d4, d2)>
#map3 = affine_map<(d0, d1, d2, d3, d4) -> (d3, d4)>
#map4 = affine_map<(d0, d1, d2, d3, d4) -> (d0, d1, d2)>
#map5 = affine_map<(d0, d1) -> (d0, d1)>
#map6 = affine_map<(d0, d1) -> (d1)>
#map7 = affine_map<(d0, d1) -> (d1, d0)>
#map8 = affine_map<(d0, d1) -> (d0)>
#map9 = affine_map<(d0) -> (d0)>
#map10 = affine_map<(d0) -> ()>
#map11 = affine_map<(d0, d1) -> ()>
  flow.executable private @predict_dispatch_3 {
    flow.executable.export public @predict_dispatch_3_generic_56x56x64x3x3 workgroups(%arg0: index, %arg1: index, %arg2: index, %arg3: index, %arg4: index) -> (index, index, index) {
      %x, %y, %z = flow.dispatch.workgroup_count_from_dag_root %arg0, %arg1, %arg2, %arg3, %arg4
      flow.return %x, %y, %z : index, index, index
    }
    builtin.module {
      func.func @predict_dispatch_3_generic_56x56x64x3x3(%arg0: !flow.dispatch.tensor<readonly:tensor<114x114x64xf32>>, %arg1: !flow.dispatch.tensor<writeonly:tensor<56x56x64xf32>>) {
        %cst = arith.constant dense<0xFF800000> : tensor<56x56x64xf32>
        %0 = flow.dispatch.tensor.load %arg0, offsets = [0, 0, 0], sizes = [114, 114, 64], strides = [1, 1, 1] : !flow.dispatch.tensor<readonly:tensor<114x114x64xf32>> -> tensor<114x114x64xf32>
        %1 = tensor.empty() : tensor<3x3xf32>
        %2 = linalg.generic {indexing_maps = [#map2, #map3, #map4], iterator_types = ["parallel", "parallel", "parallel", "reduction", "reduction"]} ins(%0, %1 : tensor<114x114x64xf32>, tensor<3x3xf32>) outs(%cst : tensor<56x56x64xf32>) {
        ^bb0(%in: f32, %in_0: f32, %out: f32):
          %3 = arith.maxf %out, %in : f32
          linalg.yield %3 : f32
        } -> tensor<56x56x64xf32>
        flow.dispatch.tensor.store %2, %arg1, offsets = [0, 0, 0], sizes = [56, 56, 64], strides = [1, 1, 1] : tensor<56x56x64xf32> -> !flow.dispatch.tensor<writeonly:tensor<56x56x64xf32>>
        return
      }
    }
  }
```

`predict_dispatch_1_conv_2d_nhwc_hwcf_1x112x112x64x7x7x3` (and many others) also exhibit similar changes, but dispatch_3 there is simpler.

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
This change replaces the `outs` operands of Linalg ops that are splat constants with `fill` of that value. Having constants operands for `outs` causes bufferization issues downstream (which are harder to fix, though in theory whether the outs is a constant or not it shouldnt matter. The general case fix looks very similar to what happens here anyway).

Fixes #11830

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
@benvanik could you check with this PR if that fixes the windows builds (or if there is a way to do it in CI through labels). If it doesnt catch all cases, I can make this cast a wider net.

**Comment by ScottTodd** [comment]
> @benvanik could you check with this PR if that fixes the windows builds (or if there is a way to do it in CI through labels). If it doesnt catch all cases, I can make this cast a wider net.

I'm aware of one crash on Windows this might fix, but to test that on CI you'd need to uncomment this: https://github.com/iree-org/iree/blob/273225105ade2463f9d99048cb191f1fd04c76a0/build_tools/cmake/ctest_all.sh#L79-L80

and change this to not include the check for `postsubmit`: https://github.com/iree-org/iree/blob/273225105ade2463f9d99048cb191f1fd04c76a0/.github/workflows/ci.yml#L161-L163

**Comment by benvanik** [comment]
Confirming that now I no longer see compile or runtime errors for resnet! Thanks Mahesh!

**Comment by MaheshRavishankar** [comment]
> > @benvanik could you check with this PR if that fixes the windows builds (or if there is a way to do it in CI through labels). If it doesnt catch all cases, I can make this cast a wider net.
> 
> I'm aware of one crash on Windows this might fix, but to test that on CI you'd need to uncomment this:
> 
> https://github.com/iree-org/iree/blob/273225105ade2463f9d99048cb191f1fd04c76a0/build_tools/cmake/ctest_all.sh#L79-L80
> 
> and change this to not include the check for `postsubmit`:
> 
> https://github.com/iree-org/iree/blob/273225105ade2463f9d99048cb191f1fd04c76a0/.github/workflows/ci.yml#L161-L163

Since I am here can you check that the mobilenet_fake_weights test passes now?

**Comment by ScottTodd** [comment]
> Since I am here can you check that the mobilenet_fake_weights test passes now?

I still see a segfault in `iree/tests/e2e/models/check_llvm-cpu_local-task_mobilenetv3_fake_weights.mlir` with this PR on my Windows machine.

**Comment by MaheshRavishankar** [comment]
> > Since I am here can you check that the mobilenet_fake_weights test passes now?
> 
> I still see a segfault in `iree/tests/e2e/models/check_llvm-cpu_local-task_mobilenetv3_fake_weights.mlir` with this PR on my Windows machine.

I cant repro it since I dont have a windows machine... So if you give me more info

**Review by benvanik — APPROVED** [review]

**Pull request merged**
