### PR TITLE
Switch CI to install TF instead of using 'frontends' Docker images.

### PR DESCRIPTION
**Pull request by ScottTodd**
Progress on https://github.com/openxla/iree/issues/16203 and https://github.com/openxla/iree/issues/15332

At the point where a job is installing a multi-gigabyte Docker image, it might as well just install Python requirements like TF directly. Switching to install from pip loses some control over the supply chain but I think that is fine for these test/benchmark jobs.

Comparing [`build_e2e_test_artifacts` before](https://github.com/openxla/iree/actions/runs/7815739382/job/21320388848) to [`build_e2e_test_artifacts` after](https://github.com/openxla/iree/actions/runs/7818347765/job/21328712850?pr=16346) (sample size 1):
* Docker fetch time decreased from 1m50s to 30s
  * 'frontends' depended on 'android' so it included the NDK too 😛
* Python setup (including pip install) time increased from 6s to 1m20s

So about the same time taken, just using less cloud storage / infra complexity.

### CODE REVIEW

**Comment by ScottTodd** [comment]
> ci-exactly: build_all, build_e2e_test_artifacts, build_packages, test_tensorflow_cpu

I think that's all that could be affected here. LMK if you want me to run all presubmits instead.

**Comment by pzread** [comment]
We also prefetch the docker image when building the runner image:

https://github.com/openxla/iree/blob/8c2a3a9cb9f9bb97bc9c7d03be88bfd87e127940/build_tools/github_actions/runner/gcp/image_setup.sh#L329

So this line also needs to be removed. LGTM once that line is deleted.

Actually if we auto-rollout new images, we can cache up-to-date docker image and save ~1m fetch time on tenserflow. But I agree it is more involved (and harder to update TF version when needed)

Regarding the pros and cons, I guess this also increases the chance of network failure as `pip install tf-nightly` will download a quiet amount of files. We can see if this is a problem later.

**Comment by ScottTodd** [comment]
Oops good catch. I had the image_setup change locally but forgot to save/commit/push it.

**Comment by stellaraccident** [comment]
We can't embed fast-changing deps we depend on in docker images (esp those that can't be changed by anyone else).

One trick I've used before to speed things up:

Setup the env and `pip install <whatever> &` in the background before starting to checkout the repo. Then do it again (after running `wait`) after without running in the background. On success, the second one will be very fast. On failure, it will try again and report a nice error.

**Review by pzread — APPROVED** [review]

**Comment by ScottTodd** [comment]
> One trick I've used before to speed things up:
> 
> Setup the env and `pip install <whatever> &` in the background before starting to checkout the repo. Then do it again (after running `wait`) after without running in the background. On success, the second one will be very fast. On failure, it will try again and report a nice error.

Nice, I saw that prefetch/wait trick used for Docker in some workflows.

`build_test_e2e_artifacts` has this timing distribution ([source here](https://github.com/openxla/iree/actions/runs/7818347765/job/21328712850?pr=16346)):

image

The "Building e2e test artifacts" step that took 7 minutes there included time spent fetching Docker and pip deps. Some of that network time could overlap with the 30 seconds spent extracting the install dir.

**Comment by ScottTodd** [comment]
> > ci-exactly: build_all, build_e2e_test_artifacts, build_packages, test_tensorflow_cpu
> 
> I think that's all that could be affected here. LMK if you want me to run all presubmits instead.

I'll run the full CI just in case...

**Comment by stellaraccident** [comment]
> > One trick I've used before to speed things up:
> > Setup the env and `pip install <whatever> &` in the background before starting to checkout the repo. Then do it again (after running `wait`) after without running in the background. On success, the second one will be very fast. On failure, it will try again and report a nice error.
> 
> Nice, I saw that prefetch/wait trick used for Docker in some workflows.
> 
> `build_test_e2e_artifacts` has this timing distribution ([source here](https://github.com/openxla/iree/actions/runs/7818347765/job/21328712850?pr=16346)):
> 
> image
> 
> The "Building e2e test artifacts" step that took 7 minutes there included time spent fetching Docker and pip deps. Some of that network time could overlap with the 30 seconds spent extracting the install dir.

I've used a caching squid proxy server on some runners to eliminate network overhead, but I don't have any access to the IREE runner VMs and there is surgery needed. In general, I strongly prefer this kind of infra-level make-it-fast vs developer process impacting things.

**Pull request merged**
