### PR TITLE
Always run GPU test jobs, regardless of path filters.

### PR DESCRIPTION
**Pull request by ScottTodd**
These workflows were opt-in to limit the load on test runners. Let's see if we have enough runner capacity to support always running them.

### CODE REVIEW

**Review by benvanik — APPROVED** [review]

**Comment by ScottTodd** [comment]
Watching to see what the total turnaround time is with current queues (relatively light but still pretty long, unfortunately).

Seeing quite a few flakes though:
```
[Regression Test / test_onnx :: nvidiagpu_cuda](https://github.com/iree-org/iree/actions/runs/10493246406/job/29067287830)
The self-hosted runner: gh-runner-presubmit-gpu-us-central1-ngzx lost communication with the server.
```
```
[Regression Test / test_onnx :: nvidiagpu_vulkan](https://github.com/iree-org/iree/actions/runs/10493246406/job/29067288214)
The self-hosted runner: gh-runner-presubmit-gpu-us-central1-r01t lost communication with the server.
```
```
[Test AMD MI300 / test](https://github.com/iree-org/iree/actions/runs/10493246406/job/29067287194?pr=18312#logs)
failed 13 minutes ago in 40s

Hit:16 https://packagecloud.io/github/git-lfs/ubuntu jammy InRelease
Reading package lists...
W: http://repo.zabbix.com/zabbix/6.0/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
E: Failed to fetch http://compute-cdn.amd.com/artifactory/list/rocm-osdb-22.04-deb/dists/compute-rocm-dkms-no-npi-hipclang/InRelease  409  Conflict [IP: 10.235.20.142 3128]
E: The repository 'http://compute-cdn.amd.com/artifactory/list/rocm-osdb-22.04-deb compute-rocm-dkms-no-npi-hipclang InRelease' is no longer signed.
```

**Comment by ScottTodd** [comment]
Ugh... the queue is 2 hours long and this hasn't even been merged x_x. 

These unit test jobs are lighter than the regression test jobs though: https://gist.github.com/ScottTodd/5f3b457e59a684b5264dd6b5d0119487 . Should really have flipped that to always run unit tests and only sometimes run the larger tests...

**Comment by ScottTodd** [comment]
2 hours 20 minutes from PR sent to all jobs finished 😭

**Comment by benvanik** [comment]
strictly because we are running with like a single raspberry pi or something, right? I see nothing in that chart over ~15mins, and nearly all should be concurrently executable?

**Comment by ScottTodd** [comment]
We have 30 minutes of CI time per run needing a w7900 runner. We only have one runner at the moment. When there are 10 runs in the queue (https://github.com/iree-org/iree/actions?query=is%3Aqueued), that will take 5 hours to clear.

**Comment by benvanik** [comment]
yeah, so it's insufficient runners, right? (it's a zero sum game to have one runner and a bunch of tests to run - we either don't run tests or they take awhile to run - the only solution is to add more runners)

**Comment by ScottTodd** [comment]
With https://github.com/iree-org/iree/pull/18322, we should go down from 30 minutes of CI time to 15 minutes of CI time needing the w7900 runner, and we've added more mi250 and mi300 runners. That might be enough to make this switch to always running all jobs.

**Comment by ScottTodd** [comment]
Total workflow time and runner availability seems much better today, after our work yesterday (more runner instances, moved jobs from w7900 to mi250/mi300). The longest job is `test_regression_suite :: cpu_llvm_task`, which is testing SDXL and SD3 on lower powered CPUs.

Going to merge this and then monitor the queues today.

**Pull request merged**
