### PR TITLE
Bump LLVM to llvm/llvm-project@730f498c961f

### PR DESCRIPTION
**Pull request by hanhanW**
- Revert llvm/llvm-project@2800448 locally because it crashes many the RISC-V compilation. After raising it to the author, they reverted it upstream.
- Revert llvm/llvm-project@66347e51 locally because it causes regression. It is already reverted in upstream.
- The cuda matmul regression appears in the LLVM NVPTX backend. We are generating the same LLVM bitcode before [converting to ISA](https://github.com/openxla/iree/blob/861815c/compiler/plugins/target/CUDA/CUDATarget.cpp#L600); CUDA perf is not our priority; we don't have folks super familiar with that layer and it is quite involved fixing there. So we are fine taking the hit for now and revisit later. (maybe later it'd be fixed in upstream..)

Additional fixes:

- Apply fixes for https://github.com/llvm/llvm-project/commit/ce7cc723b9d51ad9c741bbaeecb5e008b2b81338 
- Apply fixes for https://github.com/llvm/llvm-project/commit/b91bba89edfb25d011e1f2366cda5dec605c87f6

### CODE REVIEW

**Comment by hanhanW** [comment]
I need to revert https://github.com/llvm/llvm-project/commit/ce7cc723b9d51ad9c741bbaeecb5e008b2b81338 because I don't know how to fix it. It falls into a weird situation, and I'm raising it to the author in https://github.com/llvm/llvm-project/pull/79865#issuecomment-1920675987

EDIT: I have fixes in https://github.com/openxla/iree/pull/16286/commits/6c9f8e3a40f9a89457cdb76c6b5363f62f57cbea

**Comment by hanhanW** [comment]
@dcaballe there are DeepLabV3 perf regression on Pixel 6. Can you or someone help take a look at it?

**Comment by hanhanW** [comment]
@antiagainst do we need someone to look at cuda matmul regression? If so, can you or someone help on this?

**Comment by sogartar** [comment]
Merging my PR #16199 would create a conflict with this bump, since I made changes to the MLIR Mesh dialect.
@hanhanW, I can address these issues.
If it is important to bump LLVM quickly I can postpone merging #16199. I am not in a hurry there.

**Comment by hanhanW** [comment]
> Merging my PR #16199 would create a conflict with this bump, since I made changes to the MLIR Mesh dialect. @hanhanW, I can address these issues. If it is important to bump LLVM quickly I can postpone merging #16199. I am not in a hurry there.

In whatever order, you will generate a patch for conflicts (and thanks you very much). So I think you can land your PR, merge main to the branch, and add your fixes to the branch. This branch is on IREE, so we can coordinate on this.

**Comment by dcaballe** [comment]
> @dcaballe there are DeepLabV3 perf regression on Pixel 6. Can you or someone help take a look at it?

Looking! May need some help from @pzread if I have to run on Pixel 6.

**Comment by dcaballe** [comment]
The main differences I see in DeepLabV3 are around `tensor.pack` ops where unit dims are dropped. It looks like dropping the unit dimension leads to generating different code after `LLVMCPUVectorTransferLowering`. Before the integrate, we generate a bunch of insertions and a vector store at the end of the pack. After the integrate, we generate a loop that is storing scalar elements one by one.

Before integrate: https://gist.github.com/dcaballe/de63c398daa18236806fd840579c7175
After integrate: https://gist.github.com/dcaballe/f60319ace2e5fda6c01f8f99719ed9ab

Reverting https://github.com/llvm/llvm-project/pull/79752 seems to get rid of the `tensor.pack` IR differences.
It's very likely that removing the unit dimension leads to a different path in `LLVMCPUVectorTransferLowering` so we may want to investigate what is going on there.

Let's wait and see if the performance is back after the revert. Otherwise, I'll take another look.

**Comment by antiagainst** [comment]
> @antiagainst do we need someone to look at cuda matmul regression? If so, can you or someone help on this?

The issue appears in the LLVM NVPTX backend. We are generating the same LLVM bitcode [before converting to ISA](https://github.com/openxla/iree/blob/861815c/compiler/plugins/target/CUDA/CUDATarget.cpp#L600);  the generated PTX  is different w.r.t. quite registers some indexing: [before](https://gist.github.com/antiagainst/5157cafb6f54c763ea216d84ba56b9d0#file-before-integration-ptx) vs [after](https://gist.github.com/antiagainst/5157cafb6f54c763ea216d84ba56b9d0#file-after-integration-ptx). CUDA perf is not our priority; we don't have folks super familiar with that layer and it is quite involved fixing there. So I'd be fine taking the hit for now and revisit later. (maybe later it'd be fixed in upstream..)

**Comment by hanhanW** [comment]
> The main differences I see in DeepLabV3 are around `tensor.pack` ops where unit dims are dropped. It looks like dropping the unit dimension leads to generating different code after `LLVMCPUVectorTransferLowering`. Before the integrate, we generate a bunch of insertions and a vector store at the end of the pack. After the integrate, we generate a loop that is storing scalar elements one by one.
> 
> Before integrate: https://gist.github.com/dcaballe/de63c398daa18236806fd840579c7175 After integrate: https://gist.github.com/dcaballe/f60319ace2e5fda6c01f8f99719ed9ab
> 
> Reverting [llvm/llvm-project#79752](https://github.com/llvm/llvm-project/pull/79752) seems to get rid of the `tensor.pack` IR differences. It's very likely that removing the unit dimension leads to a different path in `LLVMCPUVectorTransferLowering` so we may want to investigate what is going on there.
> 
> Let's wait and see if the performance is back after the revert. Otherwise, I'll take another look.

I did not expect that because it was improving all the workloads in my prototype https://github.com/openxla/iree/pull/16213 Maybe the IREE changes are needed in this case. I think we can file an issue (and assign it to me), and land the integrate without the revert. It makes integration state cleaner, and we still track the issue. What do you think?



> The issue appears in the LLVM NVPTX backend. We are generating the same LLVM bitcode [before converting to ISA](https://github.com/openxla/iree/blob/861815c/compiler/plugins/target/CUDA/CUDATarget.cpp#L600); the generated PTX is different w.r.t. quite registers some indexing: [before](https://gist.github.com/antiagainst/5157cafb6f54c763ea216d84ba56b9d0#file-before-integration-ptx) vs [after](https://gist.github.com/antiagainst/5157cafb6f54c763ea216d84ba56b9d0#file-after-integration-ptx). CUDA perf is not our priority; we don't have folks super familiar with that layer and it is quite involved fixing there. So I'd be fine taking the hit for now and revisit later. (maybe later it'd be fixed in upstream..)

SGTM, thanks for taking a look at it!

**Comment by hanhanW** [comment]
>  I think we can file an issue (and assign it to me), and land the integrate without the revert. It makes integration state cleaner, and we still track the issue. What do you think?

The other option is that I can drop the revert with IREE changes afterwards. So we can land the PR as what it is now.

**Comment by MaheshRavishankar** [comment]
> >  I think we can file an issue (and assign it to me), and land the integrate without the revert. It makes integration state cleaner, and we still track the issue. What do you think?
> 
> The other option is that I can drop the revert with IREE changes afterwards. So we can land the PR as what it is now.

If you have local changes that will allow you to drop the revert we can then just revert it locally for now. With megabump carrying revert for a few days is OK

**Comment by hanhanW** [comment]
I found the difference between my upstream changes and my prototype. The upstream one has additional support for vector.transfer_read while I only implemented vector.transfer_write support in my prototype. I'm testing if partially reverting on transfer_read cases helps or not.

**Comment by dcaballe** [comment]
This may impact vecmat ops so I would go with the revert either in IREE or MLIR. It looks like you almost have a fix so it shouldn't be a big deal

**Comment by hanhanW** [comment]
> This may impact vecmat ops so I would go with the revert either in IREE or MLIR. It looks like you almost have a fix so it shouldn't be a big deal

We can revert it in upstream and land the integrate. I will land it correctly in MLIR repo, and wait for getting the commit later. I think it is the common way to make progress on integrate. So I will need someone to review the revert PR and the integrate PR.

**Comment by hanhanW** [comment]
I created the revert PR: https://github.com/llvm/llvm-project/pull/80712

**Review by ScottTodd — APPROVED** [review]

**Pull request merged**
