### PR TITLE
Enable Python bindings builds/tests in 'runtime' CI builds.

### PR DESCRIPTION
**Pull request by ScottTodd**
Hoping to add more coverage for these tests:
image

Some of the tests use compiler APIs though: https://github.com/openxla/iree/blob/278bcf0283769a1303fa6a9205527940da653a17/runtime/bindings/python/CMakeLists.txt#L256-L258

### CODE REVIEW

**Comment by ScottTodd** [comment]
Ping?

**Comment by ScottTodd** [comment]
Seeing some errors after syncing: https://github.com/iree-org/iree/actions/runs/9164893455/job/25197219527?pr=15878#step:4:1068

```
/work/runtime/bindings/python/io.cc:217:26: error: no member named 'bool_' in namespace 'nanobind'
        if (py::cast<py::bool_>(self_object.attr("is_host_allocation"))) {
                     ~~~~^
/work/runtime/bindings/python/io.cc:217:32: error: type name requires a specifier or qualifier
        if (py::cast<py::bool_>(self_object.attr("is_host_allocation"))) {
                               ^
```

edit: fixed by installing build requirements (via python venv)

**Comment by ScottTodd** [comment]
Ping, @sogartar I think you wanted to build off of this?

**Comment by ScottTodd** [comment]
Ping? (Just noticed these tests still not being included in the lightweight 'runtime' builds on https://github.com/iree-org/iree/pull/17959)

**Review by stellaraccident — APPROVED** [review]
Oh thanks! I've been looking at those bots assuming they are testing things properly.

**Comment by ScottTodd** [comment]
Hah yeah. They were close but had some gaps. I'll sync this then merge. Thanks for looking!

**Comment by ScottTodd** [comment]
before: https://github.com/iree-org/iree/actions/runs/10001221131/job/27644479262?pr=17959#step:9:1067
```
iree/modules/check/test                                       =   0.00 sec*proc (4 tests)
iree/task                                                     =   1.95 sec*proc (8 tests)
```

after: https://github.com/iree-org/iree/actions/runs/10002430990/job/27647713462?pr=15878#step:9:1081
```
iree/modules/check/test                                       =   0.00 sec*proc (4 tests)
iree/runtime/bindings/python                                  =   1.73 sec*proc (7 tests)
iree/task                                                     =   1.79 sec*proc (8 tests)
```

**Pull request merged**
