### PR TITLE
Update sdxl rocm flags to match branch performance

### PR DESCRIPTION
**Pull request by qedawkins**
With these additions we get to ~70ms on MI300, which reaches parity with the sdxl branch bar tunings.

### CODE REVIEW

**Comment by qedawkins** [comment]
@saienduri is there a CI flag I can add to run this or does it happen automatically?

**Review by antiagainst — APPROVED** [review]

**Review by monorimet — APPROVED** [review]
LGTM, thanks!

**Comment by ScottTodd** [comment]
> @saienduri is there a CI flag I can add to run this or does it happen automatically?

It ran: https://github.com/iree-org/iree/actions/runs/8897947826/job/24434436488?pr=17232. That file is currently controlling _test_ flags. We should also have an in-tree version of https://github.com/nod-ai/SHARK-TestSuite/blob/main/iree_tests/benchmarks/benchmark_sdxl_rocm.sh for _benchmark_ flags.

**Comment by qedawkins** [comment]
> > @saienduri is there a CI flag I can add to run this or does it happen automatically?
> 
> It ran: https://github.com/iree-org/iree/actions/runs/8897947826/job/24434436488?pr=17232. That file is currently controlling _test_ flags. We should also have an in-tree version of https://github.com/nod-ai/SHARK-TestSuite/blob/main/iree_tests/benchmarks/benchmark_sdxl_rocm.sh for _benchmark_ flags.

ah ok so looks like we should probably update the flags for that script also.

**Comment by ScottTodd** [comment]
Yeah. Though I'd want to pull the script into this repo so we don't need to cross repos to change flags and test performance changes.

**Comment by saienduri** [comment]
Nice! I can take care of updating the flags on the SHARK-TestSuite side of things. So, these flags will only help for scheduled unet? (not prompt encoder or vae decode). Also, the benchmark script is using vmfbs generated by the model tests, so we don't have to worry about changing flags for that script (it's all connected).

**Review by saienduri — APPROVED** [review]

**Comment by qedawkins** [comment]
> Nice! I can take care of updating the flags on the SHARK-TestSuite side of things. So, these flags will only help for scheduled unet? (not prompt encoder or vae decode). Also, the benchmark script is using vmfbs generated by the model tests, so we don't have to worry about changing flags for that script (it's all connected).

yeah it might help on the others but I haven't tested. Unet is the main one for now anyway.

**Pull request merged**
