### PR TITLE
Adding initial vm.fail op, fixing #1593.

### PR DESCRIPTION
**Pull request by benvanik**
This will get better with work on iree_status_t to attach stacks and
messages but for now will at least allow us to lower assertions into
runtime checks that cause failures. I decided to omit cond_fail for now
as these cases should be rather exceptional. We can see if we end up with
a lot of failure leaf branches in larger models and decide what to do
then.

### CODE REVIEW

**Review by silvasean — APPROVED** [review]
Thanks Ben!

It would be nice if you could build out the interface to this a bit further up the stack. Concretely, I need to emit failures here (and other places related to shapes): https://github.com/google/iree/blob/282d060ea85aeb69fb32a9f11df08914ff057abe/iree/compiler/Dialect/Shape/Transforms/MaterializeShapeCalculations.cpp#L90

So we probably want an iree.cond_fail that is not tied to the vm.

Also notice how in that code it would be quite annoying to have to insert new control flow, and besides introducing the new control flow there is going to effectively split the basic blocks at every op with a potentially failing shape assertion, messing with dispatch region formation. Splitting the blocks also makes code motion for the fail's much more difficult than if we had cond_fail and retained everything in a single basic block (where e.g. a modest extension of HoistShapeCalculations would naturally coalesce them).

**Comment by benvanik** [comment]
All of that is right, but also not part of the VM dialect. The idea is that you'd add a shape assert op to the shape dialect, emit that in your linked code, and then add a shape->vm conversion that emits this fail op. That way all the things you mentioned are done on the shape op (doesn't have to be a terminator, etc) but then lowered to the vm (which must be a terminator to ensure that we properly track liveness/can allocate registers in a way that has defined behavior when the VM aborts). You want to be able to write patterns against shape ops where you still know what you are working with, not against vm ops that are purposefully agnostic. You also want to be able to generate messages that have details based on the particular assertion you are making ("dimension 2 is expected to be N" or whatever). It's like how in gtest the only real assertion routine is AssertionFailure and everything else is built on top of that as just ways to construct better messages.

**Comment by benvanik** [comment]
Specifically, the shape dialect ops can remain in the IR right until the vm conversion and that's a better time to do the failure. Then the shape dialect is not IREE-specific; if the shape assertion was upstreamed into MLIR we'd end up with a shape->vm conversion anyway. Going to a generic iree.* op wouldn't really do much but add an extra indirection.

**Comment by silvasean** [comment]
Thanks Ben, that's super helpful!

**Pull request closed without merging**
