### PR TITLE
Add a pass to materialize encodings into nop.

### PR DESCRIPTION
**Pull request by hanhanW**

### CODE REVIEW

**Comment by hanhanW** [comment]
This depends on https://github.com/openxla/iree/pull/15302

**Review by bjacob — COMMENTED** [review]
Sorry, I don't see the test mentioned in the PR description - was this PR intending to add a test or is that somehow already covered by an existing test ?

**Comment by hanhanW** [comment]
> Sorry, I don't see the test mentioned in the PR description - was this PR intending to add a test or is that somehow already covered by an existing test ?

They are covered by an existing test. Let me update the description better

**Review by MaheshRavishankar — COMMENTED** [review]
This pass isnt called anywhere, and has no tests, so missing what this is for.

**Comment by hanhanW** [comment]
Tests are added.

**Review by bjacob — APPROVED** [review]

**Pull request merged**
