### PR TITLE
Track both DT-UK and no-DT benchmarks on x86_64 and ARM

### PR DESCRIPTION
**Pull request by pzread**
This change restores the no-DT benchmarks by:
- Disable the DT on the original `default-flags` series and rename them to `experimental-flags,no-dt`
  - We will see another bump on these benchmark series again but I think this helps us retain the previous no-DT numbers.
- Rename the `experimental-flags` to `default-flags,dt-uk`
- No-DT and DT+UK run the same benchmark sets (30mins on x86_64 benchmarks)

Since DT+UK will be the default flags in the near future (#15586), I think it's fine to call it `default-flags`. Note that with this change we remove the DT-only benchmarks (the current default flags). This is trying to find a balance between coverage and benchmark workload.

### CODE REVIEW

**Review by dcaballe — APPROVED** [review]
Thanks!

**Comment by dcaballe** [comment]
Any changes needed on the compilation statistics side of things?

**Review by hanhanW — APPROVED** [review]
thanks!

**Comment by hanhanW** [comment]
`PkgCI / Regression Test AMDGPU-Vulkan / Linux (x86_64) (pull_request)` is not a blocker. Can we land the PR?

**Comment by pzread** [comment]
I just finished the benchmarks. I'm checking if anything is wrong

**Comment by pzread** [comment]
I quickly checked the current no-DT with results before we enable DT as default. These three benchmarks are showing the regressions (so something happened during the period we were not benchmarking no-DT):

- https://perf.iree.dev/serie?IREE?ab3be2a007f3201e419112cd2bf753bbbe4e15431946411433a61ab0e34cdfca
- https://perf.iree.dev/serie?IREE?8f03b8167746d6dfe9237cf890831c5521ab5169b0892d660c2f817c5f579223
- https://perf.iree.dev/serie?IREE?4cc57db28e42e4b50f3d234a99faee5e7d48ac787d70f106ed2260e4160f27fc

**Comment by hanhanW** [comment]
They are all ARM numbers. The potential root causes are:

1. https://github.com/openxla/iree/commit/68d0df6d0e54e751c6223044320133bf72e465a6
2. https://github.com/openxla/iree/commit/c85865d0e54aecee39eacb73fe862bbf8a1ac55a
3. https://github.com/openxla/iree/commit/77f8c58da95c1cbbe6d33eb4ffdd8eb9705a8160

(1) depends on (2).

**Comment by dcaballe** [comment]
We have verified performance improvements of 1) and 2) locally, at least for the cases we were looking at... I would also add [68451db](https://github.com/openxla/iree/commit/68451dba5ee582285860f0157837c1d972e79e5a) We can create revert commits for all of suspicious commits to trigger the new benchmark configuration once it lands. Could someone please help with this? (11pm here so won't be able to help much until tomorrow)

**Comment by hanhanW** [comment]
> We have verified performance improvements of 1) and 2) locally, at least for the cases we were looking at... I would also add [68451db](https://github.com/openxla/iree/commit/68451dba5ee582285860f0157837c1d972e79e5a) We can create revert commits for all of suspicious commits to trigger the new benchmark configuration once it lands. Could someone please help with this? (11pm here so won't be able to help much until tomorrow)

I can help create three PRs for this:

1. Revert https://github.com/openxla/iree/commit/68d0df6d0e54e751c6223044320133bf72e465a6 and https://github.com/openxla/iree/commit/c85865d0e54aecee39eacb73fe862bbf8a1ac55a
2. Revert https://github.com/openxla/iree/commit/c85865d0e54aecee39eacb73fe862bbf8a1ac55a only
3. Revert https://github.com/openxla/iree/commit/77f8c58da95c1cbbe6d33eb4ffdd8eb9705a8160 only

**Comment by hanhanW** [comment]
I created some PRs with some combination of revert. Some changes are depending on others, so there are stack revert. https://github.com/openxla/iree/pull/15848 https://github.com/openxla/iree/pull/15847 https://github.com/openxla/iree/pull/15849 https://github.com/openxla/iree/pull/15850 https://github.com/openxla/iree/pull/15851

**Comment by hanhanW** [comment]
I suspect that https://github.com/openxla/iree/commit/68d0df6d0e54e751c6223044320133bf72e465a6 is the root cause. I'm benchmarking with partially revert it.

**Comment by dcaballe** [comment]
Thanks a lot, Hanhan! Numbers point to 68d0df6, indeed! It brings some improvements but also some regressions that could be larger in the models we are looking at. This is the commit that also causes large compilation times so I think we should revert and investigate. I'm running local experiments and I'll report back here.

**Comment by dcaballe** [comment]
I can confirm that https://github.com/openxla/iree/commit/68d0df6d0e54e751c6223044320133bf72e465a6 is contributing to the regression internally as well so let's revert it and open an issue to re-enable it. Unfortunately, that is not fixing the internal regression completely so I'm running more experiments to find what else is going on.

**Comment by pzread** [comment]
Hi @dcaballe, I just recalled we actually agreed for the regressions on no-DT in https://github.com/openxla/iree/pull/15621#issuecomment-1834636524 (the root problem was `Mmt4dTilingExpert` used too large tile sizes, but we were okay to merge because at that time we choose DT as default).

I'm wondering if that is one of the reasons we are currently seeing regression with no-DT. This was the regression benchmark results we saw on that PR with no-DT: https://gist.github.com/iree-github-actions-bot/1dae31731b59aca8a570dd1d50efc16d.

The regressions were on MobileBertSquad, DeepLabV3, (GPT2 looks like noise), which matches what we found now.

**Pull request merged**
