### PR TITLE
Revert "Drop `-Wno-unused-function` on Clang, find out about actually unused functions, silence false positives."

### PR DESCRIPTION
**Pull request by bjacob**
Reverts openxla/iree#15471

### CODE REVIEW

**Comment by bjacob** [comment]
@benvanik @hanhanW

**Comment by hanhanW** [comment]
Is it better to partially revert the change? I think we still can delete the unused functions in compiler codebase.

**Comment by hanhanW** [comment]
> Is it better to partially revert the change? I think we still can delete the unused functions in compiler codebase.

oh, just saw this: `Then I'll do a 2nd pass here selectively applying only the removal of true positives.`. I think it is okay to revert all of them in this PR.

**Comment by bjacob** [comment]
exactly. This is auto-merge so just approve this, it'll merge and then i'll do the manual selection of useful code-delete diffs but not changing the copts.

**Review by hanhanW — APPROVED** [review]

**Pull request merged**
