### PR TITLE
Small cleanup pass through developer docs folder.

### PR DESCRIPTION
**Pull request by ScottTodd**
Starting to clean up some of our older docs prior to setting up a new section on the website (https://github.com/openxla/iree/issues/15116), in case any of these docs make the cut for hosting there.

* `design_docs/codegen_passes.md` uses old concepts (MHLO, `iree.placeholder`, 404s to upstream passes, etc.)
* `design_docs/dynamic_shapes.md` predates a few iterations on dynamic shape representations in MLIR, PyTorch/JAX, etc.
* `design_docs/hal_driver_features.md` focuses on older Vulkan compiler and HAL code
* `design_roadmap.md` hasn't been updated. I picked a few items that are already solved or clearly obsolete (e.g. XLA HLO)
* Removed "Google source code repository" details from contributing/releasing/repo management docs (those of us on the Google side haven't been sticking to the processes there closely anyways, so fine to just simplify the docs here)
* Removed a few old TODOs

### CODE REVIEW

**Comment by Groverkss** [comment]
Do you think it's worth keeping them in a `design_docs/old/...` instead? With a notice these docs are not representative of today?

**Comment by powderluv** [comment]
git history is your friend :D

**Comment by Groverkss** [comment]
> git history is your friend :D

That works for someone who knows about the old deleted documents. It's still interesting to see what things looked like before they materialized in IREE. Anyways, not a strong concern, just a suggestion.

**Comment by ScottTodd** [comment]
> Do you think it's worth keeping them in a `design_docs/old/...` instead? With a notice these docs are not representative of today?

Keeping old docs around does have a cost, both for these sorts of "move files around and organize them onto a website" tasks and for information retrieval tasks where a stale document can be a source of confusion. I see value in keeping "design docs" as they were originally written (and not just in git history), but I do want it to be clear what is historical vs what is up-to-date. How about I go through and put a created/updated date near the top of each design doc?

**Comment by Groverkss** [comment]
> > Do you think it's worth keeping them in a `design_docs/old/...` instead? With a notice these docs are not representative of today?
> 
> Keeping old docs around does have a cost, both for these sorts of "move files around and organize them onto a website" tasks and for information retrieval tasks where a stale document can be a source of confusion. I see value in keeping "design docs" as they were originally written (and not just in git history), but I do want it to be clear what is historical vs what is up-to-date. How about I go through and put a created/updated date near the top of each design doc?

SGTM! Thank you for doing this. Maybe even a warning that these documents may be old may also help.

**Comment by benvanik** [comment]
Preserving outdated information in the main repo is almost always more harmful than a page of links to interesting old historical documents in git history. There's no way to stop search engine indexing of the files and unless there's much better and much hotter hits available (and we don't have those :) it'll be the thing that always comes up first. The number of people looking for documentation on outdated/deprecated/removed features is vanishingly small compared to the number who will get tripped up when they google something to solve a problem/understand a current mechanism and find the old stuff. We shouldn't have a blanket "don't delete anything" rule and if we do preserve things they need the biggest boldest H1 headlines at the top saying it's archived/historical and even then given the cost it's gotta be a pretty stellar doc to warrant that.

**Comment by ScottTodd** [comment]
Cool, arguments for and against. I removed a few of the design docs again (now also including "codegen_passes"). It would help if the original authors / current area owners would weigh in (and ideally update/delete docs themselves).

**Comment by ScottTodd** [comment]
Synced. PTAL?

**Review by antiagainst — APPROVED** [review]

**Comment by ScottTodd** [comment]
Oh, I missed @antiagainst 's approval here. Whoops. I'm going to close this in favor of a larger PR for https://github.com/openxla/iree/issues/15116, just so I don't trip over my own merge conflicts.

**Pull request closed without merging**
