### PR TITLE
Simplify tests/e2e/stablehlo_ops.

### LINKED ISSUE #9583: FFT lowering needs to be adapted to the updated workload + workgroup count calculation mode
PR #9552 makes the following changes to workload + workgroup count spec

1) The `workload` is now the same as the number of points in the iteration space of the operation, i.e.
		- The number of entries is same as the dimensionality of the iteration space (and not just 3 as it was previously)
		- The entries are ordered from "highest to lowest" (and not in x, y and z mode it was done previously)
		- The value for each dimension that is "parallel" is `ceilDiv(ub - lb, step)` instead of just `ub`.
	For now those dimension of the iteration space that are "reduction" are set to 1, but that doesnt need to happen either. Will be relaxed subsequently.

2) The backend generates the number of workgroups to use in the same manner as before, just adapted to the new workload representation

Its mostly an NFC change, but the `tests/e2e/xla_ops/fft.mlir` fails on SPIR-V. There seems to be some assumption in the tile size selection that conflicts with the above and needs to be addressed. The test is disabled in PR #9552 since the spir-v fft isnt load bearing at this point, but still needs to be adapted. This bug is to track the re-enabling of this test.

### LINKED ISSUE #12415: [vulkan][spirv] `reverse` tests fail on newer Android builds on Pixel 6
### What happened?

The two reverse tests fail on Pixel 6 with newer Android builds. I first observed this on a build from ~July 2022 and confirmed this today on the newest build `230205.002`.

These work fine on older builds used by the Pixel 6 Pro in the lab.

```
1/570 Test  #20: iree/tests/e2e/linalg_ext_ops/check_vulkan-spirv_vulkan_reverse.mlir_on_android_device .....................................***Failed    1.81 sec
+ set -e
++ basename /usr/local/google/home/kubak/iree/android-relass/tools/iree-check-module
+ adb push /usr/local/google/home/kubak/iree/android-relass/tools/iree-check-module /data/local/tmp/iree/tests/e2e/linalg_ext_ops/check_vulkan-spirv_vulkan_reverse.mlir/iree-check-module
/usr/local/google/home/kubak/iree/android-relass/tools/iree-check-module: 1 file pushed, 0 skipped. 316.9 MB/s (9486560 bytes in 0.029s)
+ '[' -n check_vulkan-spirv_vulkan_reverse.mlir_module.vmfb ']'
+ for datafile in $TEST_DATA
++ basename check_vulkan-spirv_vulkan_reverse.mlir_module.vmfb
+ adb push check_vulkan-spirv_vulkan_reverse.mlir_module.vmfb /data/local/tmp/iree/tests/e2e/linalg_ext_ops/check_vulkan-spirv_vulkan_reverse.mlir/check_vulkan-spirv_vulkan_reverse.mlir_module.vmfb
check_vulkan-spirv_vulkan_reverse.mlir_module.vmfb: 1 file pushed, 0 skipped. 133.1 MB/s (16472 bytes in 0.000s)
+ '[' -n /data/local/tmp/iree/tests/e2e/linalg_ext_ops/check_vulkan-spirv_vulkan_reverse.mlir/test_tmpdir ']'
+ adb shell 'mkdir -p /data/local/tmp/iree/tests/e2e/linalg_ext_ops/check_vulkan-spirv_vulkan_reverse.mlir/test_tmpdir'
+ tmpdir=TEST_TMPDIR=/data/local/tmp/iree/tests/e2e/linalg_ext_ops/check_vulkan-spirv_vulkan_reverse.mlir/test_tmpdir
+ adb shell 'cd /data/local/tmp && LD_LIBRARY_PATH=/data/local/tmp TEST_TMPDIR=/data/local/tmp/iree/tests/e2e/linalg_ext_ops/check_vulkan-spirv_vulkan_reverse.mlir/test_tmpdir /data/local/tmp/iree/tests/e2e/linalg_ext_ops/check_vulkan-spirv_vulkan_reverse.mlir/iree-check-module /data/local/tmp/iree/tests/e2e/linalg_ext_ops/check_vulkan-spirv_vulkan_reverse.mlir/check_vulkan-spirv_vulkan_reverse.mlir_module.vmfb --device=vulkan'
[==========] Running 3 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 3 tests from module
[ RUN      ] module.reverse_dim0
iree/runtime/src/iree/modules/check/module.cc:351: Failure
Failed
Expected near equality of these values. Contents does not match.
  lhs:
    2x3xf32=[1 2 3][1 2 3]
  rhs:
    2x3xf32=[4 5 6][1 2 3]
[  FAILED  ] module.reverse_dim0, where GetParam() = 0 (70 ms)
[ RUN      ] module.reverse_dim1
iree/runtime/src/iree/hal/drivers/vulkan/direct_command_queue.cc:115: INTERNAL; VK_ERROR_DEVICE_LOST; while invoking native function hal.device.queue.execute; while calling import; 
[ 1]   native hal.device.queue.execute:0 -
[ 0] bytecode module.__init:782 [
    /usr/local/google/home/kubak/iree/iree/tests/e2e/linalg_ext_ops/reverse.mlir:11:3,
    /usr/local/google/home/kubak/iree/iree/tests/e2e/linalg_ext_ops/reverse.mlir:2:12,
    /usr/local/google/home/kubak/iree/iree/tests/e2e/linalg_ext_ops/reverse.mlir:29:3,
    /usr/local/google/home/kubak/iree/iree/tests/e2e/linalg_ext_ops/reverse.mlir:38:12,
    /usr/local/google/home/kubak/iree/iree/tests/e2e/linalg_ext_ops/reverse.mlir:20:12,
    /usr/local/google/home/kubak/iree/iree/tests/e2e/linalg_ext_ops/reverse.mlir:47:3
  ]
Aborted
```

```
211/571 Test #433: iree/tests/e2e/xla_ops/check_vulkan-spirv_vulkan_reverse.mlir_on_android_device ............................................***Failed    1.17 sec
+ set -e                                                                                                                                                             
++ basename /usr/local/google/home/kubak/iree/android-relass/tools/iree-check-module                                                                                
+ adb push /usr/local/google/home/kubak/iree/android-relass/tools/iree-check-module /data/local/tmp/iree/tests/e2e/xla_ops/check_vulkan-spirv_vulkan_reverse.mlir/ire
e-check-module                                                                                                                                                       
/usr/local/google/home/kubak/iree/android-relass/tools/iree-check-module: 1 file pushed, 0 skipped. 300.9 MB/s (9486560 bytes in 0.030s)                            
+ '[' -n check_vulkan-spirv_vulkan_reverse.mlir_module.vmfb ']'                                                                                                      
+ for datafile in $TEST_DATA                                                                                                                                         
++ basename check_vulkan-spirv_vulkan_reverse.mlir_module.vmfb                                                                                                       
+ adb push check_vulkan-spirv_vulkan_reverse.mlir_module.vmfb /data/local/tmp/iree/tests/e2e/xla_ops/check_vulkan-spirv_vulkan_reverse.mlir/check_vulkan-spirv_vulkan
_reverse.mlir_module.vmfb                                                                                                                                            
check_vulkan-spirv_vulkan_reverse.mlir_module.vmfb: 1 file pushed, 0 skipped. 148.5 MB/s (14051 bytes in 0.000s)                                                    
+ '[' -n /data/local/tmp/iree/tests/e2e/xla_ops/check_vulkan-spirv_vulkan_reverse.mlir/test_tmpdir ']'                                                              
+ adb shell 'mkdir -p /data/local/tmp/iree/tests/e2e/xla_ops/check_vulkan-spirv_vulkan_reverse.mlir/test_tmpdir'                                                    
+ tmpdir=TEST_TMPDIR=/data/local/tmp/iree/tests/e2e/xla_ops/check_vulkan-spirv_vulkan_reverse.mlir/test_tmpdir                                                       
+ adb shell 'cd /data/local/tmp && LD_LIBRARY_PATH=/data/local/tmp TEST_TMPDIR=/data/local/tmp/iree/tests/e2e/xla_ops/check_vulkan-spirv_vulkan_reverse.mlir/test_tmp
dir /data/local/tmp/iree/tests/e2e/xla_ops/check_vulkan-spirv_vulkan_reverse.mlir/iree-check-module /data/local/tmp/iree/tests/e2e/xla_ops/check_vulkan-spirv_vulkan_
reverse.mlir/check_vulkan-spirv_vulkan_reverse.mlir_module.vmfb --device=vulkan'                                                                                     
[==========] Running 1 test from 1 test suite.                                                                                                                       
[----------] Global test environment set-up.                                                                                                                         
[----------] 1 test from module                                                                                                                                      
[ RUN      ] module.xla_reverse                                                                                                                                      
iree/runtime/src/iree/modules/check/module.cc:351: Failure                                                                                                           
Failed                                                                                                                                                               
Expected near equality of these values. Contents does not match.                                                                                                     
  lhs:                                                                                                                                                               
    2x3xf32=[0 0 0][1 2 3]                                                                                                                                           
  rhs:                                                                                                                                                               
    2x3xf32=[4 5 6][1 2 3]                                                                                                                                           
iree/tools/iree-check-module-main.cc:68: Failure                                                                                                                     
Value of: iree_vm_invoke(context_, function_, IREE_VM_INVOCATION_FLAG_NONE, nullptr, nullptr, nullptr, iree_vm_instance_allocator(instance_))                       
Expected: error code OK                                                                                                                                              
  Actual: 0xb40000791f2f294d, whose error code is INTERNAL: iree/runtime/src/iree/hal/drivers/vulkan/direct_command_queue.cc:115: INTERNAL; VK_ERROR_DEVICE_LOST; whi
le invoking native function hal.device.queue.execute; while calling import;                                                                                          
[ 1]   native hal.device.queue.execute:0 -                                                                                                                           
[ 0] bytecode module.xla_reverse:1196 /usr/local/google/home/kubak/iree/iree/tests/e2e/xla_ops/reverse.mlir:14:11                                                    
      at /usr/local/google/home/kubak/iree/iree/tests/e2e/xla_ops/reverse.mlir:5:1                                                                                  
[  FAILED  ] module.xla_reverse, where GetParam() = 0 (18 ms)                                                                                                        
[----------] 1 test from module (18 ms total)                                                                                                                        
                                                                                                                                                                     
[----------] Global test environment tear-down                                                                                                                       
[==========] 1 test from 1 test suite ran. (18 ms total)                                                                                                             
[  PASSED  ] 0 tests.                                                                                                                                                
[  FAILED  ] 1 test, listed below:                                                                                                                                   
[  FAILED  ] module.xla_reverse, where GetParam() = 0                                                                                                                
                                                                                                                                                                     
 1 FAILED TEST                                                                                                                                                       
Test failed 
```

### Steps to reproduce your issue

1. Flash Pixel 6 with Android 13 build `TQ1A.230205.002`
2. Run all tests on the phone.
3. Observe 2 test failures:
   ```
        20 - iree/tests/e2e/linalg_ext_ops/check_vulkan-spirv_vulkan_reverse.mlir_on_android_device (Failed)
        433 - iree/tests/e2e/xla_ops/check_vulkan-spirv_vulkan_reverse.mlir_on_android_device (Failed)
   ```

### What component(s) does this issue relate to?

Compiler

### Version information

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ScottTodd**
Forking this from https://github.com/iree-org/iree/pull/17766 to just look at a single directory.

* Moved Metal and ROCm tests from being exclusively defined in CMake to being defined (but then no-op'd) in Bazel
  * Taught the test function to insert `--iree-rocm-target-chip=${IREE_HIP_TEST_TARGET_CHIP}` (not happy that this is required though)
* Merged test srcs down to a single `ALL_SRCS` glob for test suites that work across all configurations
* Enabled previously disabled tests
  * Fixes https://github.com/iree-org/iree/issues/9583
  * Fixes https://github.com/iree-org/iree/issues/12415 (maybe, might have to disable those tests on Android/Vulkan again)

### CODE REVIEW

**Review by benvanik — APPROVED** [review]
nice cleanup!
mandatory iree-rocm-target-chip bit me earlier today trying to run the CTS and wondering wtf it wasn't getting built

**Comment by ScottTodd** [comment]
Hoping the CI is happy this time... the first PR I sent tried to change too many things at once.

**Comment by ScottTodd** [comment]
Almost got the CI happy. Need to disable `exponential_fp16` on Vulkan again, then not sure if `reverse.mlir` is safe to re-enable (was failing on Android, which isn't tested on presubmit)

https://github.com/iree-org/iree/actions/runs/9865662072/job/27243219702?pr=17843#step:9:345
```
121/423 Test  #489: iree/tests/e2e/stablehlo_ops/check_vulkan-spirv_vulkan_exponential_fp16.mlir ........................***Failed    0.64 sec
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from module
[ RUN      ] module.tensor_fp16
/work/runtime/src/iree/modules/check/module.cc:458: Failure
Failed
Expected near equality of these values. Contents does not match.
  lhs:
    4xf16=0 1.87598 0 NAN
  rhs:
    4xf16=1 2.71875 7.39062 54.5938

[  FAILED  ] module.tensor_fp16, where GetParam() = 0 (633 ms)
```

Have fun, tomorrow-me.

**Comment by ScottTodd** [comment]
Yeah Android failures: 
https://github.com/iree-org/iree/actions/runs/9878085552/job/27282128712#step:6:1357
```
The following tests FAILED:
	569 - iree/tests/e2e/stablehlo_ops/check_vulkan-spirv_vulkan_fft.mlir_on_android_device (Failed)
	588 - iree/tests/e2e/stablehlo_ops/check_vulkan-spirv_vulkan_reverse.mlir_on_android_device (Failed)
```
Supporting the pixel 6 phones is tricky :/

**Pull request merged**
