### PR TITLE
Microkernels: add arm64 bitcode. Test everywhere.

### LINKED ISSUE #13804: Multi-architecture microkernels bitcode
The initial microkernels bitcode (#13460) has been limited to x86-64.

This issue is about generalizing enough that `--iree-llvmcpu-enable-microkernels` always works, never results in linker errors due to missing microkernel symbols.

A naive generalization of #13460, merely putting side by side separate builds of microkernels bitcode for different architectures, would be unsatisfactory:
- It would only support a finite list of architectures, so we would need to continue treating `--iree-llvmcpu-enable-microkernels` as something that does not always work. If we did support all of the architectures that IREE currently supports (currently 8) that would be a lot of side-by-side bitcode to ship unconditionally.
- It would always be sub-optimal in terms of code size, since about 50% of microkernels code is identical (as IR) across all architectures and should really be shared.

The plan is to compile architecture-generic parts of microkernel code separately and process that with a script that strips target triple and attributes. Then, when we link, we can load separately that architecture-generic bitcode library, and any architecture-specific bitcode library for the target architecture.

### PR DESCRIPTION
**Pull request by bjacob**
This adds arm64 to the ukernels bitcode build, and, following #13825 , that is automatically picked up by `iree-compile` when the target is arm64.

This generalizes the e2e matmul tests BUILD with data-tiling + microkernels to cover relevant cases on both x86-64 and arm64.

This drops tags on that e2e matmul test, so it's now enabled everywhere. It just uses generic (not fast) bitcode if we don't have dedicated fast code for some architecture, but it runs everywhere.

Fixes #13804 .

### CODE REVIEW

**Review by benvanik — APPROVED** [review]

**Review by MaheshRavishankar — APPROVED** [review]

**Review by MaheshRavishankar — APPROVED** [review]
Nice!

**Comment by GMNGeoffrey** [comment]
This appears to have somehow broken the windows build:
- https://github.com/openxla/iree/actions/runs/5147952977/jobs/9269009668
- https://github.com/openxla/iree/actions/runs/5143318003/jobs/9258178755

**Comment by GMNGeoffrey** [comment]
Specifically, so we don't lose the logs:

```
2023-06-01T10:45:38.9166081Z           Start  137: iree/tests/e2e/regression/check_regression_vmvx_linalg_ops.mlir
2023-06-01T10:45:38.9220017Z   26/1310 Test   #51: iree/tests/e2e/matmul/e2e_matmul_mmt4d_i8_small_vmvx_ukernel_vmvx_local-task ......................................................................***Failed    0.35 sec
2023-06-01T10:45:38.9220595Z --- CALL[module.matmul_accumulate_DYNxDYNxi8_times_DYNxDYNxi8_into_DYNxDYNxi32] ---
2023-06-01T10:45:38.9220997Z Matmul shape (MxKxN): 1x1x1
2023-06-01T10:45:38.9221506Z 
2023-06-01T10:45:38.9221524Z 
2023-06-01T10:45:38.9222247Z error: the actual and expected result matrices disagree at row 0, column 0.
2023-06-01T10:45:38.9222462Z 
2023-06-01T10:45:38.9222534Z actual value: 0
2023-06-01T10:45:38.9222704Z expected value: 7
2023-06-01T10:45:38.9222814Z 
2023-06-01T10:45:38.9223039Z left-hand side (rows 0..0 out of 0..0, columns 0..0 out of 0..0)
2023-06-01T10:45:38.9223236Z 0   
2023-06-01T10:45:38.9223325Z 
2023-06-01T10:45:38.9223528Z right-hand side (rows 0..0 out of 0..0, columns 0..0 out of 0..0)
2023-06-01T10:45:38.9223832Z 1   
2023-06-01T10:45:38.9223985Z 
2023-06-01T10:45:38.9224172Z input accumulator (rows 0..0 out of 0..0, columns 0..0 out of 0..0)
2023-06-01T10:45:38.9224470Z 7   
2023-06-01T10:45:38.9224618Z 
2023-06-01T10:45:38.9224790Z expected result (rows 0..0 out of 0..0, columns 0..0 out of 0..0)
2023-06-01T10:45:38.9225056Z 7🦄 
2023-06-01T10:45:38.9227474Z 
2023-06-01T10:45:38.9227672Z actual result (rows 0..0 out of 0..0, columns 0..0 out of 0..0)
2023-06-01T10:45:38.9228149Z 0🐞 
2023-06-01T10:45:38.9228347Z 
2023-06-01T10:45:38.9229101Z C:\a\iree\iree\tools\iree-e2e-matmul-test.c:847: ABORTED; replaying trace file 'C:/a/iree/iree/build-windows/tests/e2e/matmul/e2e_matmul_mmt4d_i8_small_vmvx_ukernel_vmvx_local-task.yaml'
2023-06-01T10:45:38.9229529Z 
2023-06-01T10:45:38.9229830Z           Start  138: iree/tests/e2e/regression/check_regression_vmvx_reduction_broadcast_elementwise.mlir
2023-06-01T10:45:38.9281231Z   27/1310 Test   #52: iree/tests/e2e/matmul/e2e_matmul_mmt4d_f32_small_vmvx_ukernel_vmvx_local-task .....................................................................***Failed    0.35 sec
2023-06-01T10:45:38.9281804Z --- CALL[module.matmul_accumulate_DYNxDYNxf32_times_DYNxDYNxf32_into_DYNxDYNxf32] ---
2023-06-01T10:45:38.9282536Z Matmul shape (MxKxN): 1x1x1
2023-06-01T10:45:38.9282670Z 
2023-06-01T10:45:38.9282677Z 
2023-06-01T10:45:38.9282829Z error: the actual and expected result matrices disagree at row 0, column 0.
2023-06-01T10:45:38.9283006Z 
2023-06-01T10:45:38.9283083Z actual value: 0
2023-06-01T10:45:38.9283346Z expected value: -1
2023-06-01T10:45:38.9283460Z 
2023-06-01T10:45:38.9283666Z left-hand side (rows 0..0 out of 0..0, columns 0..0 out of 0..0)
2023-06-01T10:45:38.9283878Z 8   
2023-06-01T10:45:38.9283970Z 
2023-06-01T10:45:38.9284155Z right-hand side (rows 0..0 out of 0..0, columns 0..0 out of 0..0)
2023-06-01T10:45:38.9284397Z -1   
2023-06-01T10:45:38.9284489Z 
2023-06-01T10:45:38.9284618Z input accumulator (rows 0..0 out of 0..0, columns 0..0 out of 0..0)
2023-06-01T10:45:38.9284827Z 7   
2023-06-01T10:45:38.9284940Z 
2023-06-01T10:45:38.9285126Z expected result (rows 0..0 out of 0..0, columns 0..0 out of 0..0)
2023-06-01T10:45:38.9285645Z -1🦄 
2023-06-01T10:45:38.9285752Z 
2023-06-01T10:45:38.9285879Z actual result (rows 0..0 out of 0..0, columns 0..0 out of 0..0)
2023-06-01T10:45:38.9286121Z  0🐞 
2023-06-01T10:45:38.9286215Z 
2023-06-01T10:45:38.9286748Z C:\a\iree\iree\tools\iree-e2e-matmul-test.c:847: ABORTED; replaying trace file 'C:/a/iree/iree/build-windows/tests/e2e/matmul/e2e_matmul_mmt4d_f32_small_vmvx_ukernel_vmvx_local-task.yaml'
2023-06-01T10:45:38.9287169Z 
2023-06-01T10:45:38.9287420Z           Start  139: iree/tests/e2e/regression/check_regression_vmvx_softmax.mlir

2023-06-01T10:46:01.3117370Z The following tests FAILED:
2023-06-01T10:46:01.3117678Z 	 51 - iree/tests/e2e/matmul/e2e_matmul_mmt4d_i8_small_vmvx_ukernel_vmvx_local-task (Failed)
2023-06-01T10:46:01.3118038Z 	 52 - iree/tests/e2e/matmul/e2e_matmul_mmt4d_f32_small_vmvx_ukernel_vmvx_local-task (Failed)
```

**Comment by GMNGeoffrey** [comment]
Oh I see we have https://github.com/openxla/iree/issues/13893 for this, sorry for the extra noise (but also please cross-link things :slightly_smiling_face:)

**Comment by stellaraccident** [comment]
Sorry - was halfway to do that and had to go to a meeting :)

**Pull request merged**
