### PR TITLE
[GPU] NFC: rename software pipeline depth to multibuffer count

### PR DESCRIPTION
**Pull request by antiagainst**
This should make it clear and better reflect the purpose of the control.

### CODE REVIEW

**Comment by ThomasRaoux** [comment]
Those two are not strictly equivalent and I think it is better for the control to control the pipeline depth. Is it not the case right now?

**Comment by antiagainst** [comment]
> Those two are not strictly equivalent and I think it is better for the control to control the pipeline depth. Is it not the case right now?

Actually good question. Looks to me we are just only using it to control the multiple buffer count, particularly [here](https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Codegen/SPIRV/Passes.cpp#L328). But I might be confused. Is it also meant to control whether doing software pipelining at all (with depth = 0)?

**Comment by ThomasRaoux** [comment]
> > Those two are not strictly equivalent and I think it is better for the control to control the pipeline depth. Is it not the case right now?
> 
> Actually good question. Looks to me we are just only using it to control the multiple buffer count, particularly [here](https://github.com/iree-org/iree/blob/main/compiler/src/iree/compiler/Codegen/SPIRV/Passes.cpp#L328). But I might be confused. Is it also meant to control whether doing software pipelining at all (with depth = 0)?

Yes depth=0 should be mean no software pipeline. Based on the schedule we can pipeline without doing multi-buffer, it really depends on how things are getting scheduled, the two may be equal or off by 1.

**Comment by antiagainst** [comment]
> Yes depth=0 should be mean no software pipeline. Based on the schedule we can pipeline without doing multi-buffer, it really depends on how things are getting scheduled, the two may be equal or off by 1.

Cool thanks for the explanation. Let me drop this one then.

**Pull request closed without merging**
