### PR TITLE
[Stream] Use llvm::EquivalenceClasses to build aliasing sets

### PR DESCRIPTION
**Pull request by ezhulenev**
Fix for: https://github.com/openxla/iree/issues/14753

### CODE REVIEW

**Review by jpienaar — COMMENTED** [review]
Is this purely on aliases? E.g., could the equivalence class helper from LLVM be useful here?

**Comment by ezhulenev** [comment]
Didn't know it exists, replaced my custom union-find with `EquivalenceClasses`

**Review by jpienaar — APPROVED** [review]

**Comment by jpienaar** [comment]
@ezhulenev just checking: are you waiting for me to merge?

**Comment by ezhulenev** [comment]
Oops, forgot about this one, merged

**Pull request merged**
