### PR TITLE
[LLVMCPU] Re-enable vector masking for sub-byte element types

### PR DESCRIPTION
**Pull request by qedawkins**

### CODE REVIEW

**Review by MaheshRavishankar — COMMENTED** [review]
I didnt know that masking worked for this.... cc @dcaballe to confirm.

Could we add a pipeline test, and/or e2e test for this.

**Comment by qedawkins** [comment]
> I didnt know that masking worked for this.... cc @dcaballe to confirm.
> 
> Could we add a pipeline test, and/or e2e test for this.

This was a follow up to https://github.com/openxla/iree/issues/15031#issuecomment-1783887927 so it was mainly to check the CI for this case (probably should have started it as a draft). Looks like there are still some missing pieces though so moving to a draft for now.

**Comment by qedawkins** [comment]
Looks like it works now, thanks for the push @tyb0807!

**Review by dcaballe — APPROVED** [review]
Thanks you both for working on this!

**Review by hanhanW — APPROVED** [review]

**Pull request merged**
