### PR TITLE
Windows and macOS fixes following #13460.

### LINKED ISSUE #13699: Reenable ukernels bitcode on Windows
In #13697 I had to disable building ukernels bitcode on Windows due to a linking error:
https://github.com/openxla/iree/pull/13697#issuecomment-1555184414

### PR DESCRIPTION
**Pull request by ScottTodd**
Follow-up to https://github.com/openxla/iree/pull/13460

Closes https://github.com/openxla/iree/pull/13697
Fixes https://github.com/openxla/iree/issues/13699

### CODE REVIEW

**Review by stellaraccident — APPROVED** [review]

**Comment by bjacob** [comment]
Thank you so much @ScottTodd !! I'd never heard about `-fno-short-wchar`.  Much better to have this properly fixed like this --- and avoid a rollback of #13460!  Thanks!

**Comment by ScottTodd** [comment]
Still some errors on macOS (`build_test_all_macos_arm64` job): https://github.com/openxla/iree/actions/runs/5029073957/jobs/9020379886#step:6:6462

```
In file included from /Users/antiagainst/actions-runner/_work/iree/iree/runtime/src/iree/builtins/ukernel/arch/x86_64/common_x86_64.h:7:
In file included from /Users/antiagainst/actions-runner/_work/iree/iree/build-macos/llvm-project/lib/clang/17/include/immintrin.h:21:
/Users/antiagainst/actions-runner/_work/iree/iree/build-macos/llvm-project/lib/clang/17/include/mmintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"
#error "This header is only meant to be used on x86 and x64 architecture"
 ^
```

Other postsubmit builds are still running

**Comment by ScottTodd** [comment]
And my patches for the warnings weren't enough for macOS:
```
In file included from /Users/antiagainst/actions-runner/_work/iree/iree/runtime/src/iree/builtins/ukernel/mmt4d.h:10:
/Users/antiagainst/actions-runner/_work/iree/iree/runtime/src/iree/builtins/ukernel/common.h:289:44: warning: overflow in expression; result is -2147483648 with type 'int' [-Winteger-overflow]
IREE_UK_STATIC_ASSERT(IREE_UK_INT32_MIN == -(1 << 31));
                                           ^
/Users/antiagainst/actions-runner/_work/iree/iree/runtime/src/iree/builtins/ukernel/common.h:290:44: warning: overflow in expression; result is -9223372036854775808 with type 'long long' [-Winteger-overflow]
IREE_UK_STATIC_ASSERT(IREE_UK_INT64_MIN == -(1LL << 63));
                                           ^
```

Or for Linux, apparently: https://github.com/openxla/iree/actions/runs/5029073957/jobs/9020380846#step:4:7692

**Comment by bjacob** [comment]
I will be back online to look into these in ~1 hour.

**Comment by bjacob** [comment]
The macOS/arm64 occur while building the x86-64 ukernel files as bitcode. The reason is, our command lines never specify the architecture, so there was all along here an assumption that the default i.e. host architecture is x86-64, defeated on mac/arm64.  Fix to pass some `-march=` flag in BITCODE_COPTS, coming.

**Comment by bjacob** [comment]
Additional fixes in #13708.

**Pull request merged**
