### PR TITLE
Turn on blocking of contractions by default

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
#19164 added an option to turn off blocking dynamic dimensions of contractions due to regressions. This PR fixes the regressions and turns them on again.
 
Fixes are:

1) If the original code had multiple dynamic dimensions, where one or
   more of those are not blocked, those need to be accounted for in
   the `expand_shape` generated.

### CODE REVIEW

**Comment by hanhanW** [comment]
I did not review PRs related to the pass before, so it'll take me some time to get familiar with it. It's okay to me because I'll spend time on it anyway. I just wanna say that the review turnaround time is longer if I'm the only reviewer.

EDIT: the change is very simple though, so I can probably review it quickly. I'll do it on Monday.

**Comment by MaheshRavishankar** [comment]
> I did not review PRs related to the pass before, so it'll take me some time to get familiar with it. It's okay to me because I'll spend time on it anyway. I just wanna say that the review turnaround time is longer if I'm the only reviewer.
> 
> EDIT: the change is very simple though, so I can probably review it quickly. I'll do it on Monday.

No worries. I added more people. You got added cause you are the only one listed as CODEOWNER (apart from me)

**Comment by MaheshRavishankar** [comment]
https://github.com/nod-ai/e2eshark-reports/tree/main/2024-11-16-iree-test/ci_reports_onnx no ONNX regressions

**Review by hanhanW — APPROVED** [review]
LGTM

**Comment by nithinsubbiah** [comment]
This still causes compilation failure for scheduler in SDXL

**Pull request merged**
