### PR TITLE
Make 0D memrefs legal for `FlattenMemRefSubspanPass`.

### PR DESCRIPTION
**Pull request by MaheshRavishankar**

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
@antiagainst I think I know the cause for the failures in this PR, but I think I will need your help on that.  Let me know when you have time to connect.

**Comment by MaheshRavishankar** [comment]
@antiagainst I will probably need your help here... any pointers?

**Comment by antiagainst** [comment]
You mean the failing test? Let me take a look there..

**Comment by antiagainst** [comment]
It's a bit weird. I don't see very obvious issues. I'd need to look it closer.

**Comment by antiagainst** [comment]
Looking into this again. I'm playing with some changes in https://github.com/openxla/iree/pull/12414.

**Comment by antiagainst** [comment]
Okay I think I fixed the failures in https://github.com/openxla/iree/pull/12414.

**Pull request closed without merging**
