### PR TITLE
Integrate llvm-project to https://github.com/llvm/llvm-project/commit/c5d22f4e1866

### PR DESCRIPTION
**Pull request by okkwon**
Integrate llvm-project and bump dependencies   
  * llvm-project: c5d22f4e1866
  * mlir-hlo: ab587867e4aa4307c4b573d7926c3f869563eaa2
  * tensorflow: 9615158d0edb847c5f56ed33c403a4737a36a110

Fixes:
* add getCallableArgAttrs() and getCallableResAttrs()
* register builtin dialect translation
* cherry-pick 9104c104fe2422b1034be276f94f9b53b61751eb in iree-tf-fork to revert fix the tosa rescale issue

### CODE REVIEW

**Review by MaheshRavishankar — APPROVED** [review]

**Comment by MaheshRavishankar** [comment]
These regressions seems high for android. Ill look into this and triage. Blocking this one till then.

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
Blocking changes while traiging regressions.

**Comment by MaheshRavishankar** [comment]
@dcaballe I am trying to triage the regression in Deeplab and I am seeing a lot of instructions related to masking on GEMM based dispatches (this is happening with and without the integrate batch, but makes it really hard to get an idea of where things diverged). I didnt expect the masking stuff to kick in on GEMM dispatches...

**Comment by dcaballe** [comment]
Sorry about that. I can't think of what could be going on... Masking for matmul hasn't landed yet (https://github.com/openxla/iree/pull/12604) and masking in general is explicitly disabled for Aarch64 (unless it has SVE support, which is not the case): https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPULowerExecutableTarget.cpp#L188

How can I repro?

**Comment by MaheshRavishankar** [comment]
> Sorry about that. I can't think of what could be going on... Masking for matmul hasn't landed yet (#12604) and masking in general is explicitly disabled for Aarch64 (unless it has SVE support, which is not the case): [`main`/compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPULowerExecutableTarget.cpp#L188](https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPULowerExecutableTarget.cpp?rgh-link-date=2023-03-28T18%3A36%3A35Z#L188)
> 
> How can I repro?

THis is the command I am using 
```
iree-compile --iree-hal-target-backends=llvm-cpu --iree-input-type=tosa --iree-llvmcpu-target-cpu=cascadelake --iree-llvmcpu-target-triple=x86_64-unknown-linux-gnu ~/iree/build_relwithdebinfo/benchmark_suites/TFLite/deeplabv3.tflite.mlir 
```

So its the regression in x86 actually.

**Comment by MaheshRavishankar** [comment]
Ok, before and after generated code is identical for deeplabv3. (I mistakenly thought regression was on x86, but it is ARM). I triggered CI again to see if I see 50% again. If so, then I am not sure what next :P

**Comment by MaheshRavishankar** [comment]
@pzread I triggered the benchmarks again and I am not sure the reported numbers changed. Also there is no change in the compiler output for the regressed models, so not sure what's happening here. Any ideas?

**Comment by hanhanW** [comment]
> @pzread I triggered the benchmarks again and I am not sure the reported numbers changed. Also there is no change in the compiler output for the regressed models, so not sure what's happening here. Any ideas?

You'll see something like this -- edited XX minutes ago:

image

**Comment by MaheshRavishankar** [comment]
> > @pzread I triggered the benchmarks again and I am not sure the reported numbers changed. Also there is no change in the compiler output for the regressed models, so not sure what's happening here. Any ideas?
> 
> You'll see something like this -- edited XX minutes ago:
> 
> image
> 

Right. That's what I was looking for. Maybe doesn't show up on phone

**Comment by pzread** [comment]
> @pzread I triggered the benchmarks again and I am not sure the reported numbers changed. Also there is no change in the compiler output for the regressed models, so not sure what's happening here. Any ideas?

It looks like the Android benchmark didn't get re-triggered early today:
https://buildkite.com/iree/iree-benchmark-android/builds?branch=bump-llvm-20230324

The last successful run was yesterday and the Android summery also only has one version.

The x86_64 benchmarks have a finished run 1hr ago (as Hanhan posted), maybe we re-triggered the wrong benchmarks...

**Comment by MaheshRavishankar** [comment]
> > @pzread I triggered the benchmarks again and I am not sure the reported numbers changed. Also there is no change in the compiler output for the regressed models, so not sure what's happening here. Any ideas?
> 
> It looks like the Android benchmark didn't get re-triggered early today: [buildkite.com/iree/iree-benchmark-android/builds?branch=bump-llvm-20230324](https://buildkite.com/iree/iree-benchmark-android/builds?branch=bump-llvm-20230324)
> 
> The last successful run was yesterday and the Android summery also only has one version.
> 
> The x86_64 benchmarks have a finished run 1hr ago (as Hanhan posted), maybe we re-triggered the wrong benchmarks...

Not sure what I did wrong to `retrigger the wrong benchmarks`. I just said restart all jobs on the CI.

**Comment by pzread** [comment]
> > > @pzread I triggered the benchmarks again and I am not sure the reported numbers changed. Also there is no change in the compiler output for the regressed models, so not sure what's happening here. Any ideas?
> > 
> > 
> > It looks like the Android benchmark didn't get re-triggered early today: [buildkite.com/iree/iree-benchmark-android/builds?branch=bump-llvm-20230324](https://buildkite.com/iree/iree-benchmark-android/builds?branch=bump-llvm-20230324)
> > The last successful run was yesterday and the Android summery also only has one version.
> > The x86_64 benchmarks have a finished run 1hr ago (as Hanhan posted), maybe we re-triggered the wrong benchmarks...
> 
> Not sure what I did wrong to `retrigger the wrong benchmarks`. I just said restart all jobs on the CI.

Oh... That won't re-trigger the Android benchmarks... Android benchmark is still on another (buildkite) CI. Yeah it's confusing. Remove and re-add the corresponding labels is an easier way to re-trigger the benchmarks.

**Comment by MaheshRavishankar** [comment]
Ok. I see the CI for Android benchmarks running. Do I need to retrigger?

**Comment by pzread** [comment]
> Ok. I see the CI for Android benchmarks running. Do I need to retrigger?

I think Hanhan just triggered it. It should give the results we are waiting for.

**Review by MaheshRavishankar — APPROVED** [review]
Seems like the regressions were false alarm.

**Comment by dcaballe** [comment]
I see 20% regression on both x86 and ARM on different models. Am I missing something?

**Comment by MaheshRavishankar** [comment]
> I see 20% regression on both x86 and ARM on different models. Am I missing something?

Looks like noise to me... I dont see anything on the perf dashboard either.

**Comment by dcaballe** [comment]
Idk... I've never seen 20% noise on x86 but this `ClipTextSeqLen64PT` looks like a new model... The previous run also had 15% regression, though... Let's keep an eye on it...

**Comment by MaheshRavishankar** [comment]
> Idk... I've never seen 20% noise on x86 but this `ClipTextSeqLen64PT` looks like a new model... The previous run also had 15% regression, though... Let's keep an eye on it...

Yeah. But the first run didn't.

**Pull request merged**
