### PR TITLE
[LLVMCPU] Move ARM GEMMs codegen to use upstream tileFuseAndVectorize.

### PR DESCRIPTION
**Pull request by hanhanW**
It retires LLVMCPUTileFuseAndVectorize pass in IREE, and renames the pipeline to CPUAArchDoubleTilingExpert.

The L1TileSizes are splitted into two tiling sizes. One is for parallel dims, and the other is for reduction dims.

### CODE REVIEW

**Comment by bjacob** [comment]
Thanks for looping me in! I'll assess the performance impact very soon, but even before I do I think I know something that needs to be done to allow merging this without regressing mmt4d performance: drop the custom vectorization pattern that we had for mmt4d and use generic linalg vectorization instead. I was working on it anyway and now I'll prioritize finishing this asap.

**Comment by hanhanW** [comment]
> Thanks for looping me in! I'll assess the performance impact very soon, but even before I do I think I know something that needs to be done to allow merging this without regressing mmt4d performance: drop the custom vectorization pattern that we had for mmt4d and use generic linalg vectorization instead. I was working on it anyway and now I'll prioritize finishing this asap.

This is mostly NFC. It keeps the same logic in the PR, i.e., we're still using custom vectorization pattern. I added a TODO to you for retiring custom vectorization patterns.

I think the regression is noise. I uploaded some NFC commits and got different results. If the regression does not show up on both pixel-4 and pixel-6, I usually assume them noise. Please also help verify it before I land the PR, thanks!

**Comment by hanhanW** [comment]
Note: the generic linalg vectorization breaks `VectorContractCustomKernels`. I did not investigate the reason. Probably some checks stop it. The PR is mostly NFC to mmt4d path.

**Comment by bjacob** [comment]
Ah sorry, I had assumed that "upstread" tileFuseAndVectorize would imply not using custom VectorizeMMt4d.

I'll leave it to @MaheshRavishankar to verify that this really is NFC.

> Note: the generic linalg vectorization breaks VectorContractCustomKernels. I did not investigate the reason. Probably some checks stop it. The PR is mostly NFC to mmt4d path.

Yes, I've seen that. That's most of the difficulty in dropping VectorizeMMt4d. The reason is that generic linalg vectorization produces vector shapes with extra unit dimensions. Part of the fix is to add an upstream pattern to drop as many of those as possible, and after that's done, there still remains some extra unit dimension and the fix is to generalize a bit the logic in VectorContractCustomKernels. I'm taking care of it.

**Review by MaheshRavishankar — APPROVED** [review]
THanks Hanhan!

**Review by bjacob — APPROVED** [review]

**Pull request merged**
