### PR TITLE
Cherry-pick llvm/llvm-project@dc26c03

### PR DESCRIPTION
**Pull request by raikonenfnu**

### CODE REVIEW

**Comment by ThomasRaoux** [comment]
@hanhanW are you okay with a cherry pick right now?

**Review by ThomasRaoux — APPROVED** [review]
Since I don’t see any integrate in progress I assume this is okay.

**Comment by hanhanW** [comment]
We're (or say the mlir-hlo and tensorflow) behind this commit, I'll cherry-pick it into today's integrate.

**Comment by ThomasRaoux** [comment]
> We're (or say the mlir-hlo and tensorflow) behind this commit, I'll cherry-pick it into today's integrate.

Thanks!

**Pull request merged**
