### PR TITLE
Change LLVM optimization level from O3 to O2

### PR DESCRIPTION
**Pull request by dcaballe**

### CODE REVIEW

**Comment by dcaballe** [comment]
Testing `O2` and `Default` vs `O2` and `Aggressive` as optimization levels for the middle-end and the back-end respectively. Some nice code side reductions and no obvious performance regressions. I think there is only one in `[MobileBertSquad [fp32] (TFLite) big-core,full-inference,experimental-flags with IREE-Dylib-Sync @ Pixel-6-Pro (CPU-ARMv8.2-A)] when `Aggressive` is used.

No regressions on RISC-V either...

Re-testing again.

**Comment by MaheshRavishankar** [comment]
Yeah, O2 seems like a good default. If it really becomes critical we can plumb through optimization level input from iree-compile into LLVM

**Comment by dcaballe** [comment]
> Testing O2 and Default vs O2 and Aggressive as optimization levels for the middle-end and the back-end respectively. 

Ok, no bit differences between the two so I would suggest going with `O2` and `Aggressive` by default. It's better to spend more resources in the back-end than in the middle-end.

**Review by benvanik — APPROVED** [review]
image

**Review by MaheshRavishankar — APPROVED** [review]

**Pull request merged**
