### PR TITLE
Remove ArithmeticExpandOpsPass from SPIRV and VMVX lowerings.

### PR DESCRIPTION
**Pull request by ScottTodd**
Based on discussion at https://github.com/iree-org/iree/issues/10142#issuecomment-1223107567 . This "fixes" one case of `spv.IsNan` ops getting introduced while lowering of `arith.minf`, but it does not generally address NaNs coming from other sources (user-space or internal to the compiler).

## Rationale

The `ArithmeticExpandOpsPass` pass (declaration [here](https://github.com/llvm/llvm-project/blob/af29db64b2c7091070dd623c81872559657e7b3d/mlir/include/mlir/Dialect/Arithmetic/Transforms/Passes.td#L31-L34) and [here](https://github.com/llvm/llvm-project/blob/af29db64b2c7091070dd623c81872559657e7b3d/mlir/include/mlir/Dialect/Arithmetic/Transforms/Passes.h#L23-L24)) is overly specific to a particular lowering to LLVM. The `minf` and `maxf` lowerings in particular generate IR like
```mlir
  %8 = arith.cmpf ult, %7, %5 : vector<1x5xf32>
  %9 = arith.select %8, %7, %5 : vector<1x5xi1>, vector<1x5xf32>
  %10 = arith.cmpf uno, %5, %5 : vector<1x5xf32>
  %11 = arith.select %10, %5, %9 : vector<1x5xi1>, vector<1x5xf32>
```
rather than tunnel down to intrinsics like [`llvm.minnum`](https://llvm.org/docs/LangRef.html#llvm-minnum-intrinsic). Digging through the history a bit, I see where the min/max ops were added in https://reviews.llvm.org/D110540, which carries forward some rational for using `select` to implement min/max.

For our uses, quoting @benvanik ,
> Yeah, that cmp/select/cmp/select dance is really bad as IIRC LLVM/other backends can't/don't practically ever simplify that again while retaining the same semantics. The behavior that nearly everything uses is "return the non-nan value if either value is nan" (GLSL min, OpenCL fminf, C/C++ fminf, CUDA fminf, numpy.fmin, AVX minps, etc), aka "between a NaN and a numeric value, the numeric value is chosen". We need to make sure that if that's the intent of the model (which I hope it is, as it's the only thing that makes sense) we can propagate that all the way to backends. There's some ISAs that do weird things but it'd be better to pay the cost there rather than everywhere like we do today.

So this PR removes the `ArithmeticExpandOpsPass` from our SPIRV and VMVX lowerings, allowing us to lower min/max/ceil/floor directly from `arith` to the backend dialects (e.g. `spv.GL.FMin`). The LLVM-based backends would need direct lowerings implemented for us to drop the pass there too (e.g. I see errors like `error: failed to legalize operation 'arith.maxf' that was explicitly marked illegal` if I remove it from the LLVMGPU pipeline used for CUDA).

### CODE REVIEW

**Comment by benvanik** [comment]
Yeah would be good to track down CUDA/LLVM lowerings so we can remove it entirely - maybe an issue against thomas? (I suspect the same LLVM lowerings for both CPU/CUDA)

**Review by benvanik — APPROVED** [review]

**Comment by ScottTodd** [comment]
> Yeah would be good to track down CUDA/LLVM lowerings so we can remove it entirely - maybe an issue against thomas? (I suspect the same LLVM lowerings for both CPU/CUDA)

@ThomasRaoux fyi ^

**Comment by ScottTodd** [comment]
Test failures are just 
```
The following tests FAILED:
	657 - iree/compiler/Codegen/LLVMCPU/test/illegal_configuration.mlir.test (Failed)
```
, which will be fixed by https://github.com/iree-org/iree/pull/10163

**Comment by benvanik** [comment]
21% improvement! ... on a backend that didn't change :C

**Comment by ScottTodd** [comment]
> 21% improvement! ... on a backend that didn't change :C

Yep! Looks like we have some noisy benchmarks on Android still. I was sort of hoping to see some GPU improvements, but I guess a few extra floating point ops in a shader wouldn't impact much outside of a microbenchmark or really weird program. At least the benchmark suites build and run as expected :)

**Comment by antiagainst** [comment]
> Digging through the history a bit, I see where the min/max ops were added in https://reviews.llvm.org/D110540, which carries forward some rational for using select to implement min/max.

Yeah. I guess the original intent was to bridge everybody to the new world where we now have more direct arith ops. But even after direct patterns were added, no one actually took action to remove these bridging patterns.

> 21% improvement! ... on a backend that didn't change :C

Yeah. The noisy Android CPU numbers really needs curbing down.. At least we should increase the threshold for them. I did a few runs previously; but looks now things changed with all recent developments.

**Review by antiagainst — APPROVED** [review]
Looks nice. Thanks for cleaning this up, Scott!

**Pull request merged**
