### PR TITLE
NFC: Add VectorLayoutInterface method for getting the layout rank

### PR DESCRIPTION
**Pull request by qedawkins**
The rank of a layout, especially the NestedLayout, is commonly queried when manipulating the layout. An interface method makes this slightly easier and more uniform than just checking the size of one of the nested layout fields.

### CODE REVIEW

**Comment by Groverkss** [comment]
This has annoyed me so much :P Thank you!

**Review by Groverkss — APPROVED** [review]
LGTM

**Comment by qedawkins** [comment]
> This has annoyed me so much :P Thank you!

yeah same

**Review by kuhar — APPROVED** [review]

**Comment by qedawkins** [comment]
why is cmake not catching unused variables anymore? Only bazel caught this.
```
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
llvm-external-projects/iree-dialects/lib/Dialect/VectorExt/IR/VectorExtAttrs.cpp:105:11: error: unused variable 'rank' [-Werror,-Wunused-variable]
  105 |   int64_t rank = getRank();
      |           ^~~~
1 error generated.
```

**Comment by qedawkins** [comment]
ah it's because the only users are asserts.
```
  int64_t rank = getRank();
  assert(permutation.size() == rank &&
         "permutation size must match layout rank");
             assert(index >= 0 && index < rank);
```

**Pull request merged**
