### PR TITLE
[LinalgExt] Retire linalg_ext.reverse by linalg.index and tensor.extract.

### PR DESCRIPTION
**Pull request by harrisonGPU**
This PR aims to use linalg.index and tensor.extract ops to retire the linalg_ext.reverse op. It will fix issue #16060

### CODE REVIEW

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
Thanks for looking into this. I'd like to know more about the issue you are facing. I am not sure using `tensor.extract` is a good idea. It really is a "bottom" representation of the reverse kernel, essentially dropping semantic information that this is a reverse that might help in various decision. Is there a a specific reason you want to not use the explicit reverse operation. This was a deliberate choice cause `LinalgOp`s cannot represent reverse computation, and for such outliers we have oeprations in LinalgExt.

**Comment by harrisonGPU** [comment]
> Thanks for looking into this. I'd like to know more about the issue you are facing. I am not sure using `tensor.extract` is a good idea. It really is a "bottom" representation of the reverse kernel, essentially dropping semantic information that this is a reverse that might help in various decision. Is there a a specific reason you want to not use the explicit reverse operation. This was a deliberate choice cause `LinalgOp`s cannot represent reverse computation, and for such outliers we have oeprations in LinalgExt.

Hello， @MaheshRavishankar ，
I am really happy to talk with you! I have no specific reason not to use the explicit reverse operation. I just want to fix the 
#16060 issue; it's a good first issue. As a student, I really want to learn about IREE and MLIR, so I am trying to implement this issue. I am very eager to participate in this open source project!

**Comment by hanhanW** [comment]
It looks like there are correctness issue:

```
Expected near equality of these values. Contents does not match.
  lhs:
    2x3xf32=[0 0 0][0 0 0]
  rhs:
    2x3xf32=[4 5 6][1 2 3]
...
//tests/e2e/stablehlo_ops:check_llvm-cpu-host_local-task_reverse.mlir    FAILED in 0.2s
```

**Comment by harrisonGPU** [comment]
> 2x3xf32=[4 5 6][1 2 3]

Thanks, hanhanW. I will debug this problem as quickly as possible!

**Comment by harrisonGPU** [comment]
hello, @hanhanW 
I apologize for the delay in addressing this issue due to the Spring Festival. I am currently using the following MLIR as input:
```
func.func @xla_reverse() {
  %t1 = util.unfoldable_constant dense<[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]> : tensor<2x3xf32>

  %dim0 = "stablehlo.reverse"(%t1) {dimensions = array<i64: 0>} : (tensor<2x3xf32>) -> tensor<2x3xf32>
  check.expect_almost_eq_const(
      %dim0,
      dense<[[4.0, 5.0, 6.0], [1.0, 2.0, 3.0]]> : tensor<2x3xf32>
  ) : tensor<2x3xf32>

  %dim1 = "stablehlo.reverse"(%t1) {dimensions = array<i64: 1>} : (tensor<2x3xf32>) -> tensor<2x3xf32>
  check.expect_almost_eq_const(
      %dim1,
      dense<[[3.0, 2.0, 1.0], [6.0, 5.0, 4.0]]> : tensor<2x3xf32>
  ) : tensor<2x3xf32>

  %both_dims = "stablehlo.reverse"(%t1) {dimensions = array<i64: 0, 1>} : (tensor<2x3xf32>) -> tensor<2x3xf32>
  check.expect_almost_eq_const(
      %both_dims,
      dense<[[6.0, 5.0, 4.0], [3.0, 2.0, 1.0]]> : tensor<2x3xf32>
  ) : tensor<2x3xf32>
  return
}
```
Subsequently, I used these commands to generate the output MLIR:
```
./iree-opt --split-input-file --iree-stablehlo-to-linalg-ext $INPUT/input.mlir -o $INPUT/output.mlir
```
The resulting output MLIR is:
```
#map = affine_map<(d0, d1) -> (d0, d1)>
module {
  func.func @xla_reverse() {
    %0 = util.unfoldable_constant dense<[[1.000000e+00, 2.000000e+00, 3.000000e+00], [4.000000e+00, 5.000000e+00, 6.000000e+00]]> : tensor<2x3xf32>
    %1 = tensor.empty() : tensor<2x3xf32>
    %c0 = arith.constant 0 : index
    %c2 = arith.constant 2 : index
    %c3 = arith.constant 3 : index
    %c1 = arith.constant 1 : index
    %2 = linalg.generic {indexing_maps = [#map, #map], iterator_types = ["parallel", "parallel"]} ins(%0 : tensor<2x3xf32>) outs(%1 : tensor<2x3xf32>) {
    ^bb0(%in: f32, %out: f32):
      %7 = linalg.index 0 : index
      %c2_8 = arith.constant 2 : index
      %c1_9 = arith.constant 1 : index
      %8 = arith.subi %c2_8, %c1_9 : index
      %9 = arith.subi %8, %7 : index
      %10 = linalg.index 1 : index
      %extracted = tensor.extract %0[%9, %10] : tensor<2x3xf32>
      linalg.yield %extracted : f32
    } -> tensor<2x3xf32>
    check.expect_almost_eq_const(%1, dense<[[4.000000e+00, 5.000000e+00, 6.000000e+00], [1.000000e+00, 2.000000e+00, 3.000000e+00]]> : tensor<2x3xf32>) : tensor<2x3xf32>
    %3 = tensor.empty() : tensor<2x3xf32>
    %c0_0 = arith.constant 0 : index
    %c2_1 = arith.constant 2 : index
    %c3_2 = arith.constant 3 : index
    %c1_3 = arith.constant 1 : index
    %4 = linalg.generic {indexing_maps = [#map, #map], iterator_types = ["parallel", "parallel"]} ins(%0 : tensor<2x3xf32>) outs(%3 : tensor<2x3xf32>) {
    ^bb0(%in: f32, %out: f32):
      %7 = linalg.index 0 : index
      %8 = linalg.index 1 : index
      %c3_8 = arith.constant 3 : index
      %c1_9 = arith.constant 1 : index
      %9 = arith.subi %c3_8, %c1_9 : index
      %10 = arith.subi %9, %8 : index
      %extracted = tensor.extract %0[%7, %10] : tensor<2x3xf32>
      linalg.yield %extracted : f32
    } -> tensor<2x3xf32>
    check.expect_almost_eq_const(%3, dense<[[3.000000e+00, 2.000000e+00, 1.000000e+00], [6.000000e+00, 5.000000e+00, 4.000000e+00]]> : tensor<2x3xf32>) : tensor<2x3xf32>
    %5 = tensor.empty() : tensor<2x3xf32>
    %c0_4 = arith.constant 0 : index
    %c2_5 = arith.constant 2 : index
    %c3_6 = arith.constant 3 : index
    %c1_7 = arith.constant 1 : index
    %6 = linalg.generic {indexing_maps = [#map, #map], iterator_types = ["parallel", "parallel"]} ins(%0 : tensor<2x3xf32>) outs(%5 : tensor<2x3xf32>) {
    ^bb0(%in: f32, %out: f32):
      %7 = linalg.index 0 : index
      %c2_8 = arith.constant 2 : index
      %c1_9 = arith.constant 1 : index
      %8 = arith.subi %c2_8, %c1_9 : index
      %9 = arith.subi %8, %7 : index
      %10 = linalg.index 1 : index
      %c3_10 = arith.constant 3 : index
      %c1_11 = arith.constant 1 : index
      %11 = arith.subi %c3_10, %c1_11 : index
      %12 = arith.subi %11, %10 : index
      %extracted = tensor.extract %0[%9, %12] : tensor<2x3xf32>
      linalg.yield %extracted : f32
    } -> tensor<2x3xf32>
    check.expect_almost_eq_const(%5, dense<[[6.000000e+00, 5.000000e+00, 4.000000e+00], [3.000000e+00, 2.000000e+00, 1.000000e+00]]> : tensor<2x3xf32>) : tensor<2x3xf32>
    return
  }
}
```
In my attempts to debug this issue, my analysis is limited to the conversion at the IR level. Could you advise me on how to obtain the expected result, as shown in the following example?
```
runtime/src/iree/modules/check/module.cc:456
Failed
Expected near equality of these values. Contents does not match.
  lhs:
    2x3xf32=[0 0 0][0 0 0]
  rhs:
    2x3xf32=[4 5 6][1 2 3]
```
I'm truly grateful for your assistance so far!

**Comment by hanhanW** [comment]
Can you try to check what the generated IR is doing?

On the other hand, I recently found that there is a bug in vectorization. This might be impacted by the issue. To verify it, you can disable the vectorization for the case and re-run the test.

https://github.com/openxla/iree/blob/eeda5ca54ab39c509142d8d6adcbd8317b462084/compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp#L331

**Comment by harrisonGPU** [comment]
> Can you try to check what the generated IR is doing?
> 
> On the other hand, I recently found that there is a bug in vectorization. This might be impacted by the issue. To verify it, you can disable the vectorization for the case and re-run the test.
> 
> https://github.com/openxla/iree/blob/eeda5ca54ab39c509142d8d6adcbd8317b462084/compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp#L331

Thank you, hanhanW. I will try to check what the generated IR is doing and continue trying to solve this issue!

**Pull request closed without merging**
