### PR TITLE
bump torch to 80c7bc3f7ae12413836a2f610a6491794b4dbb08

### PR DESCRIPTION
**Pull request by dan-garvey**

### CODE REVIEW

**Comment by ScottTodd** [comment]
Regression Test CPU/AMDGPU-Vulkan "failures" are legit - more test cases are passing now.
* https://github.com/openxla/iree/actions/runs/8209109924/job/22454253305?pr=16717#step:10:45
* https://github.com/openxla/iree/actions/runs/8209109924/job/22454253556?pr=16717#step:9:45

The list of XFAIL tests in the config files at https://github.com/openxla/iree/tree/main/experimental/regression_suite/external_test_suite should be updated

I can help with that, but I'd appreciate if you gave it a try yourself. These things get easier once a few people start to use them.

**Comment by dan-garvey** [comment]
Can we add a job to torch-mlir to test these changes on presubmit as well? Catching them all on a bump to iree is going to make iterating on the fx_importer hell for turbine maintainers

**Comment by ScottTodd** [comment]
> Can we add a job to torch-mlir to test these changes on presubmit as well? Catching them all on a bump to iree is going to make iterating on the fx_importer hell for turbine maintainers

torch-mlir has its own test suite that also "caught" these tests flipping from failing to passing. IREE is more than torch-mlir though - we can't test compiling and running through IREE in upstream torch-mlir

**Comment by dan-garvey** [comment]
I see, I misunderstood what was going on, thanks

**Comment by ScottTodd** [comment]
For these particular "failures", I've been removing any test cases with `[XPASS(strict)] Expected compilation to fail` from "expected_compile_failures". Some might then need to be added back to "expected_run_failures" after re-running the CI.

In the future I'd want the CI job to just spit out a config file to replace the one currently in the repo if you want to accept the results. Need to refactor a bit for that though.

**Comment by dan-garvey** [comment]
> For these particular "failures", I've been removing any test cases with `[XPASS(strict)] Expected compilation to fail` from "expected_compile_failures". Some might then need to be added back to "expected_run_failures" after re-running the CI.
> 
> In the future I'd want the CI job to just spit out a config file to replace the one currently in the repo if you want to accept the results. Need to refactor a bit for that though.

Yeah, I was just thinking about how I would write that. I am expecting to have missed some or removed too many, but I'm going to let the CI double check = )

**Comment by ScottTodd** [comment]
> Yeah, I was just thinking about how I would write that.

I have a few ideas to try for that next week. Another thing that's helped me for updating CPU and Vulkan XFAIL sets has been to run the tests locally on my machine where I can have much faster iteration times. That won't work for configurations that my/your local environment doesn't support (ROCm in my case today, Metal etc. in the future once we start testing there too).

Instructions for running the tests locally are at https://github.com/nod-ai/SHARK-TestSuite/tree/main/iree_tests#running-tests. Basically pip install a few things, get the IREE tools onto your path, set an environment variable pointing at the config file(s) you want to test, then run pytest. If you're on Linux, you can even download the IREE tools from a CI run like https://github.com/openxla/iree/actions/runs/8210315101 on this PR: image

**Review by ScottTodd — APPROVED** [review]

**Pull request merged**
