### PR TITLE
[Codegen][GPU] Remove insert_slice semantics from shuffle_tensor

### PR DESCRIPTION
**Pull request by qedawkins**
The insert_slice semantics on `iree_gpu.shuffle_tensor` were restrictive when trying to enable fusion of `scf.forall` ops with different worker counts. Such cases are common when generating code for oddly shaped or dynamically shaped matrix multiplications.

This additionally renames the operation to `iree_gpu.barrier_region` given that the notion of "shuffling" a tensor doesn't make as much sense anymore.

### CODE REVIEW

**Review by Max191 — APPROVED** [review]

**Review by MaheshRavishankar — COMMENTED** [review]
Sorry it took me a while to get to this PR in my review queue. I am curious why the barrier is "after" the insert slice. If the `dest` has to bufferize to memory space `gpu.address<workgroup>` .  The `insert_slice` is the write. So a barrier "after" the write seems off to me.

**Comment by qedawkins** [comment]
Not sure I follow, isn't barrier after the write normally what you want? We have two barriers because tensors can't capture the WaR dependencies caused `scf.forall` being a distributed context, so the second barrier after the read is there to prevent that. We could also have a barrier before the first `insert_slice`, but that has a problem that we would basically end up with
```
scf.for
  %alloc = bufferization.alloc_tensor
  iree_gpu.value_barrier %alloc
```
and because it is tensor operations and those are loop invariant, they can freely be hoisted out of the loop. I haven't come up with a good solution for this yet so this patch keeps the behavior the same as it was before.

**Comment by MaheshRavishankar** [comment]
> Not sure I follow, isn't barrier after the write normally what you want? We have two barriers because tensors can't capture the WaR dependencies caused `scf.forall` being a distributed context, so the second barrier after the read is there to prevent that. We could also have a barrier before the first `insert_slice`, but that has a problem that we would basically end up with
> 
> ```
> scf.for
>   %alloc = bufferization.alloc_tensor
>   iree_gpu.value_barrier %alloc
> ```
> 
> and because it is tensor operations and those are loop invariant, they can freely be hoisted out of the loop. I haven't come up with a good solution for this yet so this patch keeps the behavior the same as it was before.

Ah shucks! you are right. Ignore what I said. The barrier should be after the right before the read.

Looking at this though, my sense is that eventually we should drop this `shuffle_tensor` op and just lower to `alloc_tensor` + barrier. I dont think this op is adding much value.

**Comment by qedawkins** [comment]
> > Not sure I follow, isn't barrier after the write normally what you want? We have two barriers because tensors can't capture the WaR dependencies caused `scf.forall` being a distributed context, so the second barrier after the read is there to prevent that. We could also have a barrier before the first `insert_slice`, but that has a problem that we would basically end up with
> > ```
> > scf.for
> >   %alloc = bufferization.alloc_tensor
> >   iree_gpu.value_barrier %alloc
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and because it is tensor operations and those are loop invariant, they can freely be hoisted out of the loop. I haven't come up with a good solution for this yet so this patch keeps the behavior the same as it was before.
> 
> Ah shucks! you are right. Ignore what I said. The barrier should be after the right before the read.
> 
> Looking at this though, my sense is that eventually we should drop this `shuffle_tensor` op and just lower to `alloc_tensor` + barrier. I dont think this op is adding much value.

yeah I've been thinking that too. My only thought is that regions might be easier to do pipelining related transformations than the floating barriers which is the main reason I didn't opt to drop it yet.

**Pull request merged**
