### PR TITLE
Add EfficientNet V2 FP16 Torch to models and CUDA_MODELS

### PR DESCRIPTION
**Pull request by reichlfl**
This adds EfficientNet V2 FP16 Torch (single batch size) to the benchmarking suite.

This model existed in FP32 already, and worked out of the box when adding support
for FP16 models to the suite (https://github.com/openxla/iree/issues/13506).

It is not part of our current focus set (https://github.com/openxla/iree/issues/12873),
so I'm completely open to not include it in any of the benchmarking runs, but I
wanted to have the model in for completeness.

### CODE REVIEW

**Review by pzread — APPROVED** [review]

**Comment by pzread** [comment]
> _ No description provided. _

Could you add a short PR description?

**Comment by GMNGeoffrey** [comment]
Things that could go in the description:
- Why are we adding this model?
- The tracking issue for the larger effort this is for

**Review by mariecwhite — APPROVED** [review]

**Comment by reichlfl** [comment]
> Things that could go in the description:

> Why are we adding this model?
> The tracking issue for the larger effort this is for

Done. As this model is not part of our current focus set, we may also choose to not include it in CUDA_MODELS - wdyt?

**Comment by mariecwhite** [comment]
> 

I think having an FP16 version of a model that we are already benchmarking in FP32 would be useful. `CUDA_MODELS` runs as part of presubmit (when the tags are added) so having at least one FP16 model is important to catch any regressions.

**Pull request merged**
