### PR TITLE
Disable cross compilation tests for now

### PR DESCRIPTION
**Pull request by jpienaar**
To decrease resource pressure on presubmits, disable the cross compile tests for now.

#17957

### CODE REVIEW

**Review by stellaraccident — APPROVED** [review]

**Comment by ScottTodd** [comment]
There are yaml errors in this (needed to remove more code): https://github.com/iree-org/iree/actions/runs/10009380335

I'll push a fix commit.

**Comment by jpienaar** [comment]
Thanks Scott

**Comment by rednoah91** [comment]
Hi @ScottTodd @jpienaar, do you know when will the cross compilation tests be re-enabled? Seems now still be disabled.

**Comment by ScottTodd** [comment]
> Hi @ScottTodd @jpienaar, do you know when will the cross compilation tests be re-enabled? Seems now still be disabled.

Latest update here: https://github.com/iree-org/iree/issues/16203#issuecomment-2284555485 . The jobs need to be refactored and I've done that (partially) for Android already. Contributions are welcome as the platforms listed there are lower priority for several of us.

**Comment by rednoah91** [comment]
Got it, thanks @ScottTodd. We plan to submit PR for enabling `riscv_64_linux` tests. Just would like to know any concern about this?

**Comment by ScottTodd** [comment]
> Got it, thanks @ScottTodd. We plan to submit PR for enabling `riscv_64_linux` tests. Just would like to know any concern about this?

General documentation was recently added here: https://iree.dev/developers/general/github-actions/#writing-and-editing-workflows .

I'd try to follow what https://github.com/iree-org/iree/blob/main/.github/workflows/pkgci_test_android.yml is doing for a new riscv workflow and you could put a matrix in such a file if you want to test 32 and 64 bit, but I'd start with just a single configuration. Definitely try to use standard GitHub-hosted runners instead of the self-hosted runners that the cross compile jobs were using before.

Docker may be required and tricky. We have https://github.com/iree-org/iree/blob/main/build_tools/docker/dockerfiles/riscv.Dockerfile today, but I'm planning on moving those Dockerfiles to a separate repository like https://github.com/nod-ai/base-docker-images/ (in iree-org) somewhat soon. If you can find a github action that installs the deps needed or can use another public dockerfile that might be preferred.

**Comment by alexsifivetw** [comment]
Hi @ScottTodd ,
we prepare a PR to enable riscv64 ci jobs.
Could you help trigger the ci test? Thx.

https://github.com/iree-org/iree/pull/18274

**Pull request merged**
