### PR TITLE
Set `iree-llvmcpu-target-cpu` to `cortex-x1` for benchmarking Pixel 6

### PR DESCRIPTION
**Pull request by pzread**

### CODE REVIEW

**Comment by mariecwhite** [comment]
This is no longer feasible, I've updated https://github.com/openxla/iree/issues/15452 for rationale.

**Comment by dcaballe** [comment]
On the ARM side, target cpus are adding certain feature flags. Not sure about the specifics, though (perhaps just some common set?). However, to be certain, we would need to add the feature flags, as Marie mentioned. We can use the suggestion that Quentin provided in an internal issue to get the flags from any device. That should be a direct copy paste.

**Comment by pzread** [comment]
> On the ARM side, target cpus are adding certain feature flags. Not sure about the specifics, though (perhaps just some common set?). However, to be certain, we would need to add the feature flags, as Marie mentioned. We can use the suggestion that Quentin provided in an internal issue to get the flags from any device. That should be a direct copy paste.

Currently the benchmarks are running on Pixel 6. I haven't tested yet but seems like the CPU features are different from Pixel 8. I'll try another run with CPU features

**Comment by mariecwhite** [comment]
Benoit added some code to automatically detect cpu features given a target ARM CPU, but then reverted it when we realized that each vendor implements the ARM CPU spec differently (i.e. a cortex-x3 might have different CPU features on Pixel 8 vs Galaxy S23). `iree-llvmcpu-target-cpu` for ARM is a no-op now. This explains the large latency regressions on int8 since the `+dotprod` feature is not included.

**Comment by dcaballe** [comment]
> > However, to be certain, we would need to add the feature flags, as Marie mentioned. We can use the suggestion that Quentin provided in an internal issue to get the flags from any device. That should be a direct copy paste.
> 
> Currently the benchmarks are running on Pixel 6. I haven't tested yet but seems like the CPU features are different from Pixel 8. I'll try another run with CPU features

Sorry, I meant, if you use Quentin instructions, you can create a binary and run it on the device to dump the target features of the CPU, so if you run it on Pixel 6, the binary will dump the target features that of Pixel 6.

> Benoit added some code to automatically detect cpu features given a target ARM CPU, but then reverted it when we realized that each vendor implements the ARM CPU spec differently (i.e. a cortex-x3 might have different CPU features on Pixel 8 vs Galaxy S23). `iree-llvmcpu-target-cpu` for ARM is a no-op now. This explains the large latency regressions on int8 since the `+dotprod` feature is not included.

Yes, sorry, I meant for LLVM. If you pass `cortex-x3` to LLVM, it adds a subset of the expected features but I don't understand the rationale there. If Benoit is clearing the cpu field, yes, neither IREE nor LLVM will add any feature flags.

**Pull request closed without merging**
