### PR TITLE
Bump torch-mlir to 8358e8c255cb5945b0f69c5fd0c5c5f738cea3f4

### PR DESCRIPTION
**Pull request by PhaneeshB**
Bump torch-mlir to https://github.com/llvm/torch-mlir/commit/8358e8c255cb5945b0f69c5fd0c5c5f738cea3f4

### CODE REVIEW

**Review by ScottTodd — COMMENTED** [review]
Waiting for CI results to approve. Auto-merge does not wait for these tests.

**Comment by PhaneeshB** [comment]
> Waiting for CI results to approve. Auto-merge does not wait for these tests.

Okay disabled auto-merge, CI should be green this time.
I might not get to it tonight, please do help to merge if you get a chance before me. 🙏 
Thanks

**Comment by ScottTodd** [comment]
Looks like xfails are slightly off:
https://github.com/iree-org/iree/actions/runs/10324878160/job/28585847687?pr=18169
```
=================================== FAILURES ===================================
_ IREE compile and run: test_group_normalization_epsilon_expanded::model.mlir::model.mlir::cpu_llvm_sync _
[gw3] linux -- Python 3.11.9 /home/runner/work/iree/iree/venv/bin/python
[XPASS(strict)] Expected compilation to fail (included in 'expected_compile_failures')
_ IREE compile and run: test_group_normalization_example_expanded::model.mlir::model.mlir::cpu_llvm_sync _
[gw3] linux -- Python 3.11.9 /home/runner/work/iree/iree/venv/bin/python
[XPASS(strict)] Expected compilation to fail (included in 'expected_compile_failures')
--- generated report log file: /tmp/iree_tests_onnx_cpu_llvm_sync_logs.json ----
...

FAILED SHARK-TestSuite/iree_tests/onnx/node/generated/test_group_normalization_epsilon_expanded/test_data_flags.txt::model.mlir::cpu_llvm_sync
FAILED SHARK-TestSuite/iree_tests/onnx/node/generated/test_group_normalization_example_expanded/test_data_flags.txt::model.mlir::cpu_llvm_sync
============ 2 failed, 727 passed, 528 xfailed in 164.10s (0:02:44) ============
```

**Review by ScottTodd — APPROVED** [review]

**Comment by ScottTodd** [comment]
Oh weird, one test failure slipped through: https://github.com/iree-org/iree/actions/runs/10327554642/job/28593323504#step:8:54 . Looks like this branch was 6 commits behind when tests ran.

```
_ IREE compile and run: test_group_normalization_example_expanded::model.mlir::model.mlir::cpu_llvm_sync _
[gw3] linux -- Python 3.11.9 /home/runner/work/iree/iree/venv/bin/python
Error invoking iree-compile
Error code: 1
Stderr diagnostics:
model.mlir:20:11: error: failed to legalize operation 'stream.cmd.dispatch' that was explicitly marked illegal
    %16 = torch.operator "onnx.ReduceMean"(%15, %13) : (!torch.vtensor<[?,?,?],f32>, !torch.vtensor<[1],si64>) -> !torch.vtensor<[?,?,1],f32> 
          ^
model.mlir:20:11: note: see current operation: "stream.cmd.dispatch"(%3, %4, %5, %9, %[54](https://github.com/iree-org/iree/actions/runs/10327554642/job/28593323504#step:8:55), %56, <<UNKNOWN SSA VALUE>>, <<UNKNOWN SSA VALUE>>, %2, %42, %7, %7, %2, %42) <{entry_points = [@test_group_normalization_example_expanded$async_dispatch_0::@embedded_elf_x86_64::@test_group_normalization_example_expanded$async_dispatch_0_generic_Dx2x8_f32], operandSegmentSizes = array<i32: 4, 2, 2, 2, 2, 2>, resource_accesses = [1 : i32, 2 : i32]}> : (index, index, index, index, i32, i32, !stream.resource<external>, !stream.resource<transient>, index, index, index, index, index, index) -> ()


Invoked with:
  cd /home/runner/work/iree/iree/SHARK-TestSuite/iree_tests/onnx/node/generated/test_group_normalization_example_expanded && iree-compile model.mlir --iree-hal-target-backends=llvm-cpu --iree-input-demote-f64-to-f32=false -o model_cpu_llvm_sync_.vmfb
```

**Comment by ScottTodd** [comment]
Maybe those group normalization tests are flaky... to compile. Could skip them if so, but would be better to fix.

**Comment by ScottTodd** [comment]
Pushed a patch for the possibly flaky tests: https://github.com/iree-org/iree/commit/552bb63fcf0515083a330c7dc4aae81300708f05

See also [discussion on Discord here](https://discord.com/channels/689900678990135345/689957613152239638/1272396356673343488)

**Pull request merged**
