### PR TITLE
[CPU] Disable transpose propagation in CI benchmarks

### PR DESCRIPTION
**Pull request by hanhanW**
https://github.com/openxla/iree/issues/15973

### CODE REVIEW

**Review by pzread — APPROVED** [review]
Looks fine to me. Although I'm curious about why we don't keep this option default to false until we resolve the related transpose issues?

**Comment by hanhanW** [comment]
> Looks fine to me. Although I'm curious about why we don't keep this option default to false until we resolve the related transpose issues?

I don't have a preference. The way I see this is that there are three regressions:

- CPU with dt
- CPU with non-dt
- cuda

I have a plan to fix it for CPU with dt. I don't who is going to look at CPU with non-dt and cuda. I don't see active changes on CUDA side, so I assume it is likely in maintenance mode.

Generally it is a good pass because it saves many dispatches and makes the program graph better. Do you think it is better to flip the option after we fix CPU with dt issue?

@qedawkins is it okay to make the pass off by default, and flip it after fixing CPU with dt issue? Any other thoughts?

**Comment by qedawkins** [comment]
> > Looks fine to me. Although I'm curious about why we don't keep this option default to false until we resolve the related transpose issues?
> 
> I don't have a preference. The way I see this is that there are three regressions:
> 
>     * CPU with dt
> 
>     * CPU with non-dt
> 
>     * cuda
> 
> 
> I have a plan to fix it for CPU with dt. I don't who is going to look at CPU with non-dt and cuda. I don't see active changes on CUDA side, so I assume it is likely in maintenance mode.
> 
> Generally it is a good pass because it saves many dispatches and makes the program graph better. Do you think it is better to flip the option after we fix CPU with dt issue?
> 
> @qedawkins is it okay to make the pass off by default, and flip it after fixing CPU with dt issue? Any other thoughts?

That's fine with me, but there are benefits in other models.

**Comment by hanhanW** [comment]
After thinking a bit more, I think it is better to keep the option default to false. Because some people are out for holiday season, and I don't want to surprise them when they are back. I prefer flip it to true after we fix CPU DT issue; it likely will happen in 2024.

**Pull request closed without merging**
