### PR TITLE
Integrate llvm-project at 98f5a340975b and bump dependencies

### PR DESCRIPTION
**Pull request by KoolJBlack**
LLVM_COMMIT=”98f5a340975bc00197c57e39eb4ca26e2da0e8a2”
MHLO_COMMIT=”146ed8f97af889a450056a5551a22943e9d4a0d2”

### CODE REVIEW

**Comment by matthias-springer** [comment]
https://reviews.llvm.org/D148771 has landed.

**Review by nicolasvasilache — APPROVED** [review]

**Review by hanhanW — APPROVED** [review]

**Comment by MaheshRavishankar** [comment]
@antiagainst the binary size seems to change here. Could you PTAL.

@KoolJBlack please wait for Lei to respond.

**Comment by KoolJBlack** [comment]
actually I just merged https://github.com/openxla/iree/pull/13200 (auto-merge was enabled). This was a future integrate with additional changes requested by @nicolasvasilache . was about to close this. I see the same binary size increase there however... @antiagainst

**Comment by antiagainst** [comment]
The change in performance and binary size is intended if https://github.com/llvm/llvm-project/commit/5041fe8439c161e5d9d8f7774f7ca95af46d880e is included.

**Pull request closed without merging**
