### PR TITLE
Add vscode workspace files to `.gitignore`

### PR DESCRIPTION
**Pull request by bjacob**

### CODE REVIEW

**Comment by benvanik** [comment]
(by default these are stored in .vs/ or .vscode/, which I recommend as otherwise you'll end up with other random files in your root dir like launch.json/etc)

**Review by benvanik — APPROVED** [review]

**Comment by bjacob** [comment]
Oh... OK.

**Comment by bjacob** [comment]
Sorry, hadn't seen you had still approved.  OK, i'll merge that then.

**Comment by benvanik** [comment]
Yeah still fine to exclude, just heads up that you may have an easier time without it in the root :)

**Pull request merged**
