### PR TITLE
[Codegen][GPU] Allow aliasing for iree_gpu.lowering_config

### PR DESCRIPTION
**Pull request by Groverkss**
Implements aliasing for iree_gpu.lowering_config. This makes the behavior same as iree_codegen.lowering_config.

### CODE REVIEW

**Review by qedawkins — COMMENTED** [review]
I'm not sure we want this. There should only ever be one copy of a lowering config right? So we shouldn't ever really benefit from aliasing it.

**Comment by Groverkss** [comment]
> I'm not sure we want this. There should only ever be one copy of a lowering config right? So we shouldn't ever really benefit from aliasing it.

It just makes it easier to update tests when switching from iree_codegen.lowering_config to iree_gpu.lowering_config. I think the benefit is consistency rather than performance/readibility.

But if you feel we don't need this, i'll inline these attributes in my patch that needs this.

**Comment by qedawkins** [comment]
I'd prefer to keep it inline right now. I've seen cases before of lowering configs being omitted from repros and I've found it easier to read during later lowerings. This was different for iree_codegen.lowering_config because we were propagating it, but now we don't propagate so we get to keep it inline.

**Comment by Groverkss** [comment]
> I'd prefer to keep it inline right now. I've seen cases before of lowering configs being omitted from repros and I've found it easier to read during later lowerings. This was different for iree_codegen.lowering_config because we were propagating it, but now we don't propagate so we get to keep it inline.

makes sense. time to update tests :(

**Pull request closed without merging**
