### PR TITLE
Updating torch-mlir of iree to 6aa46967b69a01a46d56146250978d08e243e75e

### PR DESCRIPTION
**Pull request by AmosLewis**
Updating torch-mlir of iree to https://github.com/llvm/torch-mlir/pull/3845

Replace the test json with new generated file in checks summary.

### CODE REVIEW

**Comment by AmosLewis** [comment]
UNKNOWN SSA VALUE Bug
```
model.mlir:4:10: error: failed to legalize operation 'arith.sitofp' that was explicitly marked illegal
    %0 = torch.operator "onnx.TfIdfVectorizer"(%arg0) {torch.onnx.max_gram_length = 2 : si64, torch.onnx.max_skip_count = 0 : si64, torch.onnx.min_gram_length = 2 : si64, torch.onnx.mode = "TF", torch.onnx.ngram_counts = [0 : si64, 4 : si64], torch.onnx.ngram_indexes = [0 : si64, 1 : si64, 2 : si64, 3 : si64, 4 : si64, 5 : si64, 6 : si64], torch.onnx.pool_int64s = [2 : si64, 3 : si64, 5 : si64, 4 : si64, 5 : si64, 6 : si64, 7 : si64, 8 : si64, 6 : si64, 7 : si64]} : (!torch.vtensor<[2,6],si32>) -> !torch.vtensor<[2,7],f32> 
         ^
model.mlir:4:10: note: see current operation: %327 = "arith.sitofp"(<<UNKNOWN SSA VALUE>>) : (i64) -> f64
```
Input program:
```
module {
  func.func @test_tfidfvectorizer_tf_batch_onlybigrams_skip0(%arg0: !torch.vtensor<[2,6],si32>) -> !torch.vtensor<[2,7],f32> attributes {torch.onnx_meta.ir_version = 4 : si64, torch.onnx_meta.opset_version = 17 : si64, torch.onnx_meta.producer_name = "backend-test", torch.onnx_meta.producer_version = ""} {
    %none = torch.constant.none
    %0 = torch.operator "onnx.TfIdfVectorizer"(%arg0) {torch.onnx.max_gram_length = 2 : si64, torch.onnx.max_skip_count = 0 : si64, torch.onnx.min_gram_length = 2 : si64, torch.onnx.mode = "TF", torch.onnx.ngram_counts = [0 : si64, 4 : si64], torch.onnx.ngram_indexes = [0 : si64, 1 : si64, 2 : si64, 3 : si64, 4 : si64, 5 : si64, 6 : si64], torch.onnx.pool_int64s = [2 : si64, 3 : si64, 5 : si64, 4 : si64, 5 : si64, 6 : si64, 7 : si64, 8 : si64, 6 : si64, 7 : si64]} : (!torch.vtensor<[2,6],si32>) -> !torch.vtensor<[2,7],f32> 
    return %0 : !torch.vtensor<[2,7],f32>
  }
}

```

Compiled with:
`iree-compile model.mlir --iree-hal-target-backends=llvm-cpu --iree-input-demote-f64-to-f32=false -o model_cpu_llvm_sync.vmfb`

This onnx lower to linalg with torch-mlir successfully.

**Review by zjgarvey — APPROVED** [review]
I personally think we should accept the TFIDF regressions. The other progressions are more important from a model coverage perspective. 

I looked into the shape tests, and all of these are not frontend issues. Will post more details in an issue soon.

**Comment by zjgarvey** [comment]
@ScottTodd do you have opinions on allowing the TFIDF regressions for now?

**Comment by ScottTodd** [comment]
> @ScottTodd do you have opinions on allowing the TFIDF regressions for now?

Those are fine with me.

**Review by ScottTodd — APPROVED** [review]

**Pull request merged**
