### PR TITLE
Set --iree-llvmcpu-link-embedded=false when --iree-llvmcpu-sanitize=address is enabled.(#15519)

### PR DESCRIPTION
**Pull request by harrisonGPU**
This PR is aimed at fixing #15519 ,When --iree-llvmcpu-sanitize=address is enabled, we should auto set --iree-llvmcpu-link-embedded=false

### CODE REVIEW

**Comment by harrisonGPU** [comment]
@stellaraccident Hello, this is my PR. Could you please review my code? I would really appreciate it. Thank you!

**Comment by harrisonGPU** [comment]
hello, @ScottTodd @pzread ,this is issue link: https://github.com/openxla/iree/issues/15519,could you please reviewe my PR,I am really appreciate it!

**Comment by ScottTodd** [comment]
Please sign the CLA (https://github.com/openxla/iree/pull/15934/checks?check_run_id=19661724404).

From the issue, I think some other code in the compiler flag parsing and CMake around https://github.com/openxla/iree/blob/f97aa4dec694c6c484d8eb35fc8dc9ba14459544/CMakeLists.txt#L449-L458 should also be updated.

(Also FYI, a few of us, like myself, are going to be less responsive over the holidays)

**Comment by harrisonGPU** [comment]
> Please sign the CLA (https://github.com/openxla/iree/pull/15934/checks?check_run_id=19661724404).
> 
> From the issue, I think some other code in the compiler flag parsing and CMake around
> 
> https://github.com/openxla/iree/blob/f97aa4dec694c6c484d8eb35fc8dc9ba14459544/CMakeLists.txt#L449-L458
> 
> should also be updated.
> (Also FYI, a few of us, like myself, are going to be less responsive over the holidays)

Thanks for your reply!I will update this cmake!I am really thanks for you!Have a nice day!

**Comment by harrisonGPU** [comment]
Hello, @ScottTodd ,I have already updated the CMake flag; it might not be the best choice, please review it or give me more advice.Have a good holiday!

**Comment by benvanik** [comment]
This was landed as part of #16452.

**Pull request closed without merging**
