### PR TITLE
[WIP] Upload benchmark suites artifacts

### PR DESCRIPTION
**Pull request by pzread**

### CODE REVIEW

**Comment by hcindyl** [comment]
I was implementing something similar too at https://github.com/iree-org/iree/pull/10442 :p

I don't think there is a `build-benchmarks/benchmark_suites/iree-*` object. The benchmark_suites currently has two subdirectories, `TF` and `TFLite`

Also, I found that if we excluded `.mlir` and `.tflite` we could reduce the archive size from 6GB to 2GB

```
tar --exclude '*.tflite' --exclude '*.mlir' -cf \
            "${BENCHMARKS_ARCHIVE}" "${BENCHMARKS_DIR}/benchmark_suites"
```

**Comment by pzread** [comment]
> I was implementing something similar too at #10442 :p
> 
> I don't think there is a `build-benchmarks/benchmark_suites/iree-*` object. The benchmark_suites currently has two subdirectories, `TF` and `TFLite`
> 
> Also, I found that if we excluded `.mlir` and `.tflite` we could reduce the archive size from 6GB to 2GB
> 
> ```
> tar --exclude '*.tflite' --exclude '*.mlir' -cf \
>             "${BENCHMARKS_ARCHIVE}" "${BENCHMARKS_DIR}/benchmark_suites"
> ```

Oh thanks. The `iree` folder is generated by the new benchmark framework. We're in the process to replace the current benchmark suites. Will need to update the part you've done later.

**Comment by hcindyl** [comment]
> > I was implementing something similar too at #10442 :p
> > I don't think there is a `build-benchmarks/benchmark_suites/iree-*` object. The benchmark_suites currently has two subdirectories, `TF` and `TFLite`
> > Also, I found that if we excluded `.mlir` and `.tflite` we could reduce the archive size from 6GB to 2GB
> > ```
> > tar --exclude '*.tflite' --exclude '*.mlir' -cf \
> >             "${BENCHMARKS_ARCHIVE}" "${BENCHMARKS_DIR}/benchmark_suites"
> > ```
> 
> Oh thanks. The `iree` folder is generated by the new benchmark framework. We're in the process to replace the current benchmark suites. Will need to update the part you've done later.

Got it. When do you plan to open this PR for review? I can hold off my PR and base it on this work once it is landed.

**Comment by hcindyl** [comment]
Oh, and we would need to archive all the flagfiles too (unless that part is also changed), otherwise we can't tell from one compile config to another based on the `.vmfb` alone.

**Comment by pzread** [comment]
> > > I was implementing something similar too at #10442 :p
> > > I don't think there is a `build-benchmarks/benchmark_suites/iree-*` object. The benchmark_suites currently has two subdirectories, `TF` and `TFLite`
> > > Also, I found that if we excluded `.mlir` and `.tflite` we could reduce the archive size from 6GB to 2GB
> > > ```
> > > tar --exclude '*.tflite' --exclude '*.mlir' -cf \
> > >             "${BENCHMARKS_ARCHIVE}" "${BENCHMARKS_DIR}/benchmark_suites"
> > > ```
> > 
> > 
> > Oh thanks. The `iree` folder is generated by the new benchmark framework. We're in the process to replace the current benchmark suites. Will need to update the part you've done later.
> 
> Got it. When do you plan to open this PR for review? I can hold off my PR and base it on this work once it is landed.

So I reviewed #10442 and here are some of my thoughts:

Essentially we want to have `iree_run_module_test` with some fixed inputs and expected outputs to check each benchmark we defined in the benchmark suites (and maybe some extra cases outside the benchmark suites). The new framework we are working on now is using python to define models/compile flags/run flags/... For example:
- https://github.com/iree-org/iree/blob/main/build_tools/python/e2e_test_framework/models/model_groups.py
- https://github.com/iree-org/iree/blob/main/build_tools/python/benchmarks/iree/definitions.py

This frees us from the limited CMake expressiveness and we don't need to parse those directory names to get the parameters of a benchmark (like [this part](https://github.com/iree-org/iree/pull/10442/files#diff-60a9e2ce1837000bf7fa23331fc2a8b98a63b2aed1a9edf305fbd92a01091cf5R103)), which is fragile and hard to maintain.

So since [this e2e list](https://github.com/iree-org/iree/pull/10442/files#diff-c99cf0ac73114228d1cfb2d87f6cb22890f6cd9c69b43b0eeb4bf07501d89b53R147) is basically a copy of the benchmark list, I'm wondering it might be a good idea to also generate that list with a python script, similar to what we are doing now for the new benchmark suites (https://github.com/iree-org/iree/blob/main/benchmarks/generated_benchmark_suites.cmake).

If we use python scripts to generate the e2e test list, you can easily get all of the benchmark parameters (arch, driver, runtime, run flags...) by importing those python modules. And we won't miss the new added benchmarks because they will also be generated in the list.

The whole framework is not completely ready now, I can try to make everything ready for e2e tests next week. In the meantime, I won't block #10442 if you want to merge it first, but eventually we will remove the current `benchmark_suites` and we need to refactor.

**Comment by hcindyl** [comment]
> > > > I was implementing something similar too at #10442 :p
> > > > I don't think there is a `build-benchmarks/benchmark_suites/iree-*` object. The benchmark_suites currently has two subdirectories, `TF` and `TFLite`
> > > > Also, I found that if we excluded `.mlir` and `.tflite` we could reduce the archive size from 6GB to 2GB
> > > > ```
> > > > tar --exclude '*.tflite' --exclude '*.mlir' -cf \
> > > >             "${BENCHMARKS_ARCHIVE}" "${BENCHMARKS_DIR}/benchmark_suites"
> > > > ```
> > > 
> > > 
> > > Oh thanks. The `iree` folder is generated by the new benchmark framework. We're in the process to replace the current benchmark suites. Will need to update the part you've done later.
> > 
> > 
> > Got it. When do you plan to open this PR for review? I can hold off my PR and base it on this work once it is landed.
> 
> So I reviewed #10442 and here are some of my thoughts:
> 
> Essentially we want to have `iree_run_module_test` with some fixed inputs and expected outputs to check each benchmark we defined in the benchmark suites (and maybe some extra cases outside the benchmark suites). The new framework we are working on now is using python to define models/compile flags/run flags/... For example:
> 
> * https://github.com/iree-org/iree/blob/main/build_tools/python/e2e_test_framework/models/model_groups.py
> * https://github.com/iree-org/iree/blob/main/build_tools/python/benchmarks/iree/definitions.py
> 
> This frees us from the limited CMake expressiveness and we don't need to parse those directory names to get the parameters of a benchmark (like [this part](https://github.com/iree-org/iree/pull/10442/files#diff-60a9e2ce1837000bf7fa23331fc2a8b98a63b2aed1a9edf305fbd92a01091cf5R103)), which is fragile and hard to maintain.
> 
> So since [this e2e list](https://github.com/iree-org/iree/pull/10442/files#diff-c99cf0ac73114228d1cfb2d87f6cb22890f6cd9c69b43b0eeb4bf07501d89b53R147) is basically a copy of the benchmark list, I'm wondering it might be a good idea to also generate that list with a python script, similar to what we are doing now for the new benchmark suites (https://github.com/iree-org/iree/blob/main/benchmarks/generated_benchmark_suites.cmake).
> 
> If we use python scripts to generate the e2e test list, you can easily get all of the benchmark parameters (arch, driver, runtime, run flags...) by importing those python modules. And we won't miss the new added benchmarks because they will also be generated in the list.
> 
> The whole framework is not completely ready now, I can try to make everything ready for e2e tests next week. In the meantime, I won't block #10442 if you want to merge it first, but eventually we will remove the current `benchmark_suites` and we need to refactor.

Thanks for the review. However, the full test list should happen in the benchmark framework. What we put in `tests/e2e/models` is a small sublist that provides us the safeguard on 1) compiler codegen change 2) upstream toolchain change that could cause a garbage/wrong module output. It is _NOT_ meant to be complete, and we may extend it as needed, but not required.

I am all for not parsing the archive structure in CMake, and hence the question I asked in the discord #builds channel (https://discord.com/channels/689900678990135345/689957613152239638/1019035921817018469). If we have a tool in place that can make this task easier, I am more than happy to change the function once the new feature is landed.

**Comment by hcindyl** [comment]
> > > > > I was implementing something similar too at #10442 :p
> > > > > I don't think there is a `build-benchmarks/benchmark_suites/iree-*` object. The benchmark_suites currently has two subdirectories, `TF` and `TFLite`
> > > > > Also, I found that if we excluded `.mlir` and `.tflite` we could reduce the archive size from 6GB to 2GB
> > > > > ```
> > > > > tar --exclude '*.tflite' --exclude '*.mlir' -cf \
> > > > >             "${BENCHMARKS_ARCHIVE}" "${BENCHMARKS_DIR}/benchmark_suites"
> > > > > ```
> > > > 
> > > > 
> > > > Oh thanks. The `iree` folder is generated by the new benchmark framework. We're in the process to replace the current benchmark suites. Will need to update the part you've done later.
> > > 
> > > 
> > > Got it. When do you plan to open this PR for review? I can hold off my PR and base it on this work once it is landed.
> > 
> > 
> > So I reviewed #10442 and here are some of my thoughts:
> > Essentially we want to have `iree_run_module_test` with some fixed inputs and expected outputs to check each benchmark we defined in the benchmark suites (and maybe some extra cases outside the benchmark suites). The new framework we are working on now is using python to define models/compile flags/run flags/... For example:
> > 
> > * https://github.com/iree-org/iree/blob/main/build_tools/python/e2e_test_framework/models/model_groups.py
> > * https://github.com/iree-org/iree/blob/main/build_tools/python/benchmarks/iree/definitions.py
> > 
> > This frees us from the limited CMake expressiveness and we don't need to parse those directory names to get the parameters of a benchmark (like [this part](https://github.com/iree-org/iree/pull/10442/files#diff-60a9e2ce1837000bf7fa23331fc2a8b98a63b2aed1a9edf305fbd92a01091cf5R103)), which is fragile and hard to maintain.
> > So since [this e2e list](https://github.com/iree-org/iree/pull/10442/files#diff-c99cf0ac73114228d1cfb2d87f6cb22890f6cd9c69b43b0eeb4bf07501d89b53R147) is basically a copy of the benchmark list, I'm wondering it might be a good idea to also generate that list with a python script, similar to what we are doing now for the new benchmark suites (https://github.com/iree-org/iree/blob/main/benchmarks/generated_benchmark_suites.cmake).
> > If we use python scripts to generate the e2e test list, you can easily get all of the benchmark parameters (arch, driver, runtime, run flags...) by importing those python modules. And we won't miss the new added benchmarks because they will also be generated in the list.
> > The whole framework is not completely ready now, I can try to make everything ready for e2e tests next week. In the meantime, I won't block #10442 if you want to merge it first, but eventually we will remove the current `benchmark_suites` and we need to refactor.
> 
> Thanks for the review. However, the full test list should happen in the benchmark framework. What we put in `tests/e2e/models` is a small sublist that provides us the safeguard on 1) compiler codegen change 2) upstream toolchain change that could cause a garbage/wrong module output. It is _NOT_ meant to be complete, and we may extend it as needed, but not required.
> 
> I am all for not parsing the archive structure in CMake, and hence the question I asked in the discord #builds channel (https://discord.com/channels/689900678990135345/689957613152239638/1019035921817018469). If we have a tool in place that can make this task easier, I am more than happy to change the function once the new feature is landed.

Add a TODO in https://github.com/iree-org/iree/pull/10442/files#diff-60a9e2ce1837000bf7fa23331fc2a8b98a63b2aed1a9edf305fbd92a01091cf5R101 to mark the future cleanup.

**Pull request closed without merging**
