### PR TITLE
Revert "Freeze all statuses emitted by calls into dynamic modules

### PR DESCRIPTION
**Pull request by qedawkins**
This reverts commit 37e65de8d29eb961777dbf39cda93217d1d12add due to CI failures on mac and windows.

https://github.com/openxla/iree/actions/runs/7632630125/job/20799143734

### CODE REVIEW

**Comment by hanhanW** [comment]
Can you put the failure link to commit description? Here is the https://github.com/openxla/iree/actions/runs/7632630125/job/20799143734

**Review by hanhanW — APPROVED** [review]

**Comment by benvanik** [comment]
oh yeah, didn't catch that you had a filename in the expected output - that should just be matching on the `UNKNOWN` (as we if the IREE_STATUS_MODE has source location and messages disabled `UNKNOWN` is the only thing that we can print)

**Comment by qedawkins** [comment]
> oh yeah, didn't catch that you had a filename in the expected output - that should just be matching on the `UNKNOWN` (as we if the IREE_STATUS_MODE has source location and messages disabled `UNKNOWN` is the only thing that we can print)

right that makes sense... I just wanted to test the filename because that's what was broken :P

**Comment by benvanik** [comment]
hah, yeah, that'd be nice - but probably not worth the contortions to make it work on CI for now (at least, not via a sample that isn't really a unit test)

**Pull request merged**
