### PR TITLE
Re-land "[Dispatch] extend CollapseDimensionsPass to more…"

### PR DESCRIPTION
**Pull request by IanWood1**
Re-lands https://github.com/iree-org/iree/pull/19326 after adding a few more matmul specs that were missed. I left `@match_mmt_8192x640x2560` commented out because the config was causing a slight regression in perf but the overall time spent was very low.

This reverts commit 7177c29.

### CODE REVIEW

**Comment by IanWood1** [comment]
I think the sdxl regressions have been fixed (possibly faster?), @raikonenfnu @nithinsubbiah could you confirm this?

**Comment by IanWood1** [comment]
Merging with main to fix ci_summary

**Review by MaheshRavishankar — APPROVED** [review]

**Review by nithinsubbiah — APPROVED** [review]
CI summary suggests better e2e numbers for SDXL, let's merge it

**Comment by nithinsubbiah** [comment]
@IanWood1 can you decreased the UNet bound to 51ms here [https://github.com/iree-org/iree/blob/main/.github/workflows/pkgci_regression_test.yml#L251](url) and here [https://github.com/iree-org/iree/blob/main/.github/workflows/pkgci_regression_test.yml#L254](url)

**Pull request merged**
