### PR TITLE
Add PR template file

### PR DESCRIPTION
**Pull request by dezhiAmd**
This is a template for creating pull request.
The goal is to 

1. reduce regression
2. encourage better knowledge sharing

### CODE REVIEW

**Review by benvanik — CHANGES_REQUESTED** [review]
I'm not a fan of this - has there been discussion?
Documenting recommended practices in the root [CONTRIBUTING.md](https://github.com/iree-org/iree/blob/main/CONTRIBUTING.md) is the recommended approach.

**Comment by ScottTodd** [comment]
I'm not necessarily against adding pull request templates, but I'd want to see some demo screenshots and some examples from other projects to see how well they work.

We could use templates for LLVM and torch-mlir integrates since those usually follow common patterns. For other changes from regular contributors, it's hard to group them in my experience since we have so many different components (language bindings, docs, compiler, runtime, infra, etc.).

**Comment by ScottTodd** [comment]
Like for LLVM integrates, we typically "carry some reverts" and a pull request template could give a place to list them if the author forgets.

**Comment by benvanik** [comment]
Agreed - integrate templates make sense as they are usually following a checklist and that can be in the PR - unfortunately it looks like github doesn't have a native way of having template selection like they do for issues, but you can link to templates (?expand=1&template=some_template.md under the .github dir somewhere), so the integrate guidebook can have a link to one.

**Comment by benvanik** [comment]
(note that my pushback here is that PR descriptions end up in git commits and given that we've seen very little cleanliness around issue templates we cannot rely on that here - 95% of people file issues with the template and don't fill in or delete half the sections)

**Comment by dezhiAmd** [comment]
Thanks

**Pull request closed without merging**
