### PR TITLE
Adding ExpandMaxfExtended

### PR DESCRIPTION
**Pull request by Ranvirsv**

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
I think these need to go to MLIR with other math operation expansions

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
Thanks for pushing on this! This is probably better going upstream though.

**Comment by MaheshRavishankar** [comment]
@Ranvirsv are the changes being worked out here just for evaluation. I think these changes are better suited to land in MLIR, somewhere here https://github.com/llvm/llvm-project/tree/main/mlir/lib/Dialect/Math/Transforms

**Comment by Ranvirsv** [comment]
I see 
Sorry about that

**Comment by qedawkins** [comment]
> @Ranvirsv are the changes being worked out here just for evaluation. I think these changes are better suited to land in MLIR, somewhere here https://github.com/llvm/llvm-project/tree/main/mlir/lib/Dialect/Math/Transforms

Yes, I think the idea was to prototype here and then land upstream (given the context of a fairly similar looking pattern [here](https://github.com/openxla/iree/blob/76e36ff694eeff16e1cf511979eae7646fc6c503/compiler/src/iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp#L880), albeit with a different purpose).

Although I wasn't expecting it to land in [Math](https://github.com/llvm/llvm-project/tree/main/mlir/lib/Dialect/Math/Transforms), seems more like a missing class of Arith transforms maybe?

**Comment by MaheshRavishankar** [comment]
> I see Sorry about that

Totally fine to do. Just mark it as a draft if you are just experiment with e2e flow in IREE.

**Comment by MaheshRavishankar** [comment]
> > @Ranvirsv are the changes being worked out here just for evaluation. I think these changes are better suited to land in MLIR, somewhere here [llvm/llvm-project@`main`/mlir/lib/Dialect/Math/Transforms](https://github.com/llvm/llvm-project/tree/main/mlir/lib/Dialect/Math/Transforms?rgh-link-date=2023-05-22T19%3A55%3A30Z)
> 
> Yes, I think the idea was to prototype here and then land upstream (given the context of a fairly similar looking pattern [here](https://github.com/openxla/iree/blob/76e36ff694eeff16e1cf511979eae7646fc6c503/compiler/src/iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp#L880), albeit with a different purpose).
> 
> Although I wasn't expecting it to land in [Math](https://github.com/llvm/llvm-project/tree/main/mlir/lib/Dialect/Math/Transforms?rgh-link-date=2023-05-22T19%3A55%3A30Z), seems more like a missing class of Arith transforms maybe?

Arith also seems to have an expand ops pass https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/Arith/Transforms/ExpandOps.cpp

**Comment by qedawkins** [comment]
> > > @Ranvirsv are the changes being worked out here just for evaluation. I think these changes are better suited to land in MLIR, somewhere here [llvm/llvm-project@`main`/mlir/lib/Dialect/Math/Transforms](https://github.com/llvm/llvm-project/tree/main/mlir/lib/Dialect/Math/Transforms?rgh-link-date=2023-05-22T19%3A55%3A30Z)
> > 
> > 
> > Yes, I think the idea was to prototype here and then land upstream (given the context of a fairly similar looking pattern [here](https://github.com/openxla/iree/blob/76e36ff694eeff16e1cf511979eae7646fc6c503/compiler/src/iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp#L880), albeit with a different purpose).
> > Although I wasn't expecting it to land in [Math](https://github.com/llvm/llvm-project/tree/main/mlir/lib/Dialect/Math/Transforms?rgh-link-date=2023-05-22T19%3A55%3A30Z), seems more like a missing class of Arith transforms maybe?
> 
> Arith also seems to have an expand ops pass https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/Arith/Transforms/ExpandOps.cpp

Ah, I misinterpreted those patterns a bit, that does seem like a reasonable place for this. Although the pattern here doesn't seem quite like an expansion to me because we're still generating an arith.maxf op, only instead on f32 and then truncating back. I'm also not certain I know exactly what an "expansion" is though, just inferring based on the patterns there :/

**Comment by Ranvirsv** [comment]
> > > > @Ranvirsv are the changes being worked out here just for evaluation. I think these changes are better suited to land in MLIR, somewhere here [llvm/llvm-project@`main`/mlir/lib/Dialect/Math/Transforms](https://github.com/llvm/llvm-project/tree/main/mlir/lib/Dialect/Math/Transforms?rgh-link-date=2023-05-22T19%3A55%3A30Z)
> > > 
> > > 
> > > Yes, I think the idea was to prototype here and then land upstream (given the context of a fairly similar looking pattern [here](https://github.com/openxla/iree/blob/76e36ff694eeff16e1cf511979eae7646fc6c503/compiler/src/iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp#L880), albeit with a different purpose).
> > > Although I wasn't expecting it to land in [Math](https://github.com/llvm/llvm-project/tree/main/mlir/lib/Dialect/Math/Transforms?rgh-link-date=2023-05-22T19%3A55%3A30Z), seems more like a missing class of Arith transforms maybe?
> > 
> > 
> > Arith also seems to have an expand ops pass https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/Arith/Transforms/ExpandOps.cpp
> 
> Ah, I misinterpreted those patterns a bit, that does seem like a reasonable place for this. Although the pattern here doesn't seem quite like an expansion to me because we're still generating an arith.maxf op, only instead on f32 and then truncating back. I'm also not certain I know exactly what an "expansion" is though, just inferring based on the patterns there :/

Arith only has a maxf op, so I thought it uses that for fmaxf, or did you mean something else in the code? I am a little confused, I tried to write an expansion similar to the one above it (ExpandMulSIExtended)

**Comment by MaheshRavishankar** [comment]
If it doesnt fit in with any existing "file", we can add a new file... Point is, it is better to have this pattern upstream. 
If you want to keep this in IREE, thats fine to, but it shouldnt go into ConvertToLLVM.cpp. That is just converting to LLVM. It needs to a be a separate pass before hand.

@rsuderman dont know if this fits into any of the existing passes you added for bf16 handling....

**Comment by qedawkins** [comment]
> If it doesnt fit in with any existing "file", we can add a new file... Point is, it is better to have this pattern upstream. If you want to keep this in IREE, thats fine to, but it shouldnt go into ConvertToLLVM.cpp. That is just converting to LLVM. It needs to a be a separate pass before hand.

Makes sense, probably better to be having the "where does this go" discussion upstream also. On that note, this probably shouldn't be in ConvertToLLVM either then? https://github.com/openxla/iree/blob/76e36ff694eeff16e1cf511979eae7646fc6c503/compiler/src/iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp#L880

**Comment by MaheshRavishankar** [comment]
> > If it doesnt fit in with any existing "file", we can add a new file... Point is, it is better to have this pattern upstream. If you want to keep this in IREE, thats fine to, but it shouldnt go into ConvertToLLVM.cpp. That is just converting to LLVM. It needs to a be a separate pass before hand.
> 
> Makes sense, probably better to be having the "where does this go" discussion upstream also. On that note, this probably shouldn't be in ConvertToLLVM either then?
> 
> https://github.com/openxla/iree/blob/76e36ff694eeff16e1cf511979eae7646fc6c503/compiler/src/iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp#L880

Yeah, if we could move all of those to a separate pass, that'd be great!

**Pull request closed without merging**
