### PR TITLE
[LLVMGPU] Add 32x32x16 F8 MFMA intrinsic

### PR DESCRIPTION
**Pull request by raikonenfnu**
To enable faster SDXL on attention we'd need different FP8 MFMA intrinsics. This 32x32x16 FP8 intrinsic (and virtual intrinsic for 2nd matmul) has been especially performant when used on this SDXL attention shape (B0: 2, B1: 10, (M, K2): 4096: K1: 64).

### CODE REVIEW

**Review by kuhar — COMMENTED** [review]
Should we wait for https://github.com/iree-org/iree/pull/19098 from @bjacob to land first?

**Comment by raikonenfnu** [comment]
> Should we wait for #19098 from @bjacob to land first?

Sounds good to me!

**Review by bjacob — APPROVED** [review]
This sounds time-sensitive (motivated by actual usage) so feel free to merge this. I can easily rebase https://github.com/iree-org/iree/pull/19098 and https://github.com/iree-org/iree/pull/19099 over that. They are respectively 2- and 3-deep into a chain of dependent PRs under review, so I can't guarantee that I'll be able to merge them tomorrow.

If I rebase my stuff around this, I will be tempted to support not just this particular intrinsic, but the whole family (all 2x2=4 combination of f8e4m3 / f8e5m2 data types for A and B). Not necessarily asking for this generalization to be made in this PR, if it's time sensitive, but definitely a suggestion :-)

**Comment by raikonenfnu** [comment]
> This sounds time-sensitive (motivated by actual usage) so feel free to merge this. I can easily rebase #19098 and #19099 over that. They are respectively 2- and 3-deep into a chain of dependent PRs under review, so I can't guarantee that I'll be able to merge them tomorrow.
> 
> If I rebase my stuff around this, I will be tempted to support not just this particular intrinsic, but the whole family (all 2x2=4 combination of f8e4m3 / f8e5m2 data types for A and B). Not necessarily asking for this generalization to be made in this PR, if it's time sensitive, but definitely a suggestion :-)

@bjacob Thanks for being super considerate, this one is not super time sensitive, and I am not blocked on this for development. Please land your PRs first, they seem to be mostly landable anyways!

> combination of f8e4m3 / f8e5m2 data types for A and B). Not necessarily asking for this generalization to be made in this PR, if it's time sensitive, but definitely a suggestion :-)

Haha sure thing! That'd save us another PR! :)

**Comment by bjacob** [comment]
Both my PRs are merged. You can now rebase this! Note: the numbering scheme for these enum values has changed in #19098. Please renumber accordingly!

**Review by bjacob — APPROVED** [review]
Looking great!

**Pull request merged**
