### PR TITLE
use getTypeBitWidth() to get the element type's bit width

### PR DESCRIPTION
**Pull request by okkwon**
getTypeBitWidth() supports ComplexType too.

### CODE REVIEW

**Comment by okkwon** [comment]
@qedawkins FYI

**Review by qedawkins — APPROVED** [review]
Thanks. Is there a test case worth adding?

**Comment by okkwon** [comment]
> Thanks. Is there a test case worth adding?

Actually I wanted to ask you about that since you added the function. Did you add any tests? I can add a complex type test to it.

**Review by MaheshRavishankar — APPROVED** [review]
Is it possible to add a test

**Comment by qedawkins** [comment]
> > Thanks. Is there a test case worth adding?
> 
> Actually I wanted to ask you about that since you added the function. Did you add any tests? I can add a complex type test to it.

Oh, right. This was a work around to disable vector masking for sub-byte types, and the test is essentially whether `PkgCI / Regression Test CPU / Linux (x86_64) (pull_request)` passes. There are no performance requirements here and (ideally) this function is transient anyway until vector masking for sub-byte element types is supported. Since it's just for configurations, if there is a specific configuration you want to check, add it here. Otherwise if it's fixing a crash, either an e2e test (in case this is somehow load bearing for your specific case) or no test if it's not.

**Comment by qedawkins** [comment]
I would try removing the check here: https://github.com/openxla/iree/blob/03d655a99408f43bd5d960172b15fb0d5823e633/compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPULowerExecutableTarget.cpp#L193

And see whether your case still passes. If it doesn't then add a pipeline test for it (here maybe? https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/Codegen/LLVMCPU/test/pipeline_tests.mlir)

**Comment by okkwon** [comment]
I think you know better than me. Can you come up with a test please?
It fixes a crash for me, so I made this hotfix. But if you guys think a test is worth it, @qedawkins please add a test to this PR.

**Comment by qedawkins** [comment]
> I think you know better than me. Can you come up with a test please? It fixes a crash for me, so I made this hotfix. But if you guys think a test is worth it, @qedawkins please add a test to this PR.

It's hard to say without seeing an example of what crashed. If I had to guess, you are using a complex type with `> 8` bits, and thus the check that you are fixing here has no effect, and more importantly won't be broken when we remove the check altogether, hence no need for a test. The main thing I want to figure out for adding a test is whether removing this check will break your use case.

**Comment by qedawkins** [comment]
So if you set this to always true: https://github.com/openxla/iree/blob/03d655a99408f43bd5d960172b15fb0d5823e633/compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPULowerExecutableTarget.cpp#L197 and your code still works, then feel free to merge. I can't think of any other test for this.

**Comment by okkwon** [comment]
It fixes a crash in jax primitive tests with complex<f32> FYI. The problematic IR was:

```mlir
%3 = flow.dispatch.tensor.load %0, offsets = [0], sizes = [400], strides = [1] : !flow.dispatch.tensor<readonly:tensor<400xcomplex<f32>>> -> tensor<400xcomplex<f32>>
```

**Comment by qedawkins** [comment]
> It fixes a crash in jax primitive tests with complex FYI. The problematic IR was:
> 
> ```
> %3 = flow.dispatch.tensor.load %0, offsets = [0], sizes = [400], strides = [1] : !flow.dispatch.tensor<readonly:tensor<400xcomplex<f32>>> -> tensor<400xcomplex<f32>>
> ```

ok yeah, I'm confident that isn't hitting this path. Should be good to merge then.

**Comment by okkwon** [comment]
Thanks @qedawkins. Merging.

**Comment by MaheshRavishankar** [comment]
If this was a crash, then isn't it easier to add lit test. Which part did it crash at?

**Pull request merged**
