### PR TITLE
Revert "Propagate reshapes through generics with reduction…

### PR DESCRIPTION
**Pull request by IanWood1**
…(#18857)"

This regresses sdxl int8 perf by increasing the dimensionality of `attention` ops which messes with the attention spec. Revert this for now and reland once `CollapseDimensionsPass` can handle attention.

This reverts commit 78481a6ed98c9be1dd9c33eda0572e391a4d8d89.

### CODE REVIEW

**Comment by IanWood1** [comment]
Update: this still should be reverted but @Groverkss is going to also work on making the spec more robust for attention

**Review by hanhanW — APPROVED** [review]

**Comment by MaheshRavishankar** [comment]
oh oh, this cause quite a big regression in llama_8b_fp16

At this commit (a5c3879bdd0779de2858f8095771dcc7e353b544)

```
-------------------------------------------------------------------------------------------------------
Benchmark                                             Time             CPU   Iterations UserCounters...
-------------------------------------------------------------------------------------------------------
BM_prefill_bs4/process_time/real_time              2511 ms         5351 ms            1 items_per_second=0.398218/s
BM_prefill_bs4/process_time/real_time              1593 ms         3223 ms            1 items_per_second=0.62773/s
BM_prefill_bs4/process_time/real_time              1577 ms         3192 ms            1 items_per_second=0.633948/s
BM_prefill_bs4/process_time/real_time              1576 ms         3192 ms            1 items_per_second=0.634657/s
BM_prefill_bs4/process_time/real_time              1575 ms         3191 ms            1 items_per_second=0.634738/s
BM_prefill_bs4/process_time/real_time              1568 ms         3177 ms            1 items_per_second=0.637676/s
BM_prefill_bs4/process_time/real_time              1567 ms         3172 ms            1 items_per_second=0.638253/s
BM_prefill_bs4/process_time/real_time              1572 ms         3184 ms            1 items_per_second=0.636193/s
BM_prefill_bs4/process_time/real_time_mean         1692 ms         3460 ms            8 items_per_second=0.605177/s
BM_prefill_bs4/process_time/real_time_median       1576 ms         3191 ms            8 items_per_second=0.634698/s
BM_prefill_bs4/process_time/real_time_stddev        331 ms          764 ms            8 items_per_second=0.0836861/s
BM_prefill_bs4/process_time/real_time_cv          19.55 %         22.08 %             8 items_per_second=13.83%
```

Before this commit (80cbf6b6fe)
```
-------------------------------------------------------------------------------------------------------
Benchmark                                             Time             CPU   Iterations UserCounters...
-------------------------------------------------------------------------------------------------------
BM_prefill_bs4/process_time/real_time               960 ms         2209 ms            1 items_per_second=1.04156/s
BM_prefill_bs4/process_time/real_time              45.6 ms         88.7 ms            1 items_per_second=21.9521/s
BM_prefill_bs4/process_time/real_time              46.0 ms         91.8 ms            1 items_per_second=21.7303/s
BM_prefill_bs4/process_time/real_time              59.3 ms          118 ms            1 items_per_second=16.8629/s
BM_prefill_bs4/process_time/real_time              46.1 ms         92.3 ms            1 items_per_second=21.6801/s                                                                                               BM_prefill_bs4/process_time/real_time              46.1 ms         92.6 ms            1 items_per_second=21.6903/s
BM_prefill_bs4/process_time/real_time              46.0 ms         90.5 ms            1 items_per_second=21.7216/s
BM_prefill_bs4/process_time/real_time              46.0 ms         92.4 ms            1 items_per_second=21.7274/s                                                                                               BM_prefill_bs4/process_time/real_time_mean          162 ms          359 ms            8 items_per_second=18.5508/s
BM_prefill_bs4/process_time/real_time_median       46.1 ms         92.4 ms            8 items_per_second=21.706/s
BM_prefill_bs4/process_time/real_time_stddev        323 ms          747 ms            8 items_per_second=7.27908/s
BM_prefill_bs4/process_time/real_time_cv         199.22 %        207.93 %             8 items_per_second=39.24%
```

**Comment by IanWood1** [comment]
I'd suspect that its causing reduction/matmul ops to get expanded but they can't get collapsed because they are dynamic. Do you have the traces and/or dispatch counts for the runs?

**Comment by MaheshRavishankar** [comment]
I can give you a full repro in the morning

**Pull request merged**
