### PR TITLE
Cherry-pick SPIR-V change for llvm-project

### PR DESCRIPTION
**Pull request by kuhar**
Fixes https://github.com/iree-org/iree/issues/10818

Cherry-pick a SPIR-V change:
- https://github.com/llvm/llvm-project/commit/fce33e1140bbf5ddf2afa5c3be89433ed2a70e4d

### CODE REVIEW

**Comment by kuhar** [comment]
Hmmm, this is weird, I don't know why the CI script is failing. Any ideas? @MaheshRavishankar @ThomasRaoux

**Comment by ThomasRaoux** [comment]
> Hmmm, this is weird, I don't know why the CI script is failing. Any ideas? @MaheshRavishankar @ThomasRaoux @dcaballe

@pzread any idea?

**Comment by MaheshRavishankar** [comment]
Maybe you need to advance the forks to fetch the commits from LLVM

**Comment by hanhanW** [comment]
Is it a branch in the fork repo? Did you use the script? https://github.com/iree-org/iree/tree/main/build_tools/scripts/integrate#cherry-picking

**Comment by MaheshRavishankar** [comment]
Seems like CI is OK. I cherry picked here https://github.com/iree-org/iree/pull/10860 . That seems fine...
(btw, we probably have to co-ordinate which one goes in first)

**Comment by ThomasRaoux** [comment]
The same exact change works when I create the PR with my account:
https://github.com/iree-org/iree/pull/10861

**Comment by hanhanW** [comment]
let me poke the CI..

**Comment by pzread** [comment]
I think it might be due to the PR description `Fixes: https://github.com/iree-org/iree/issues/10818` and the bug in `configure_ci.py`. Fixed the PR description. Could you push a new commit to trigger the CI again?

**Comment by pzread** [comment]
The `configure_ci.py` thought `Fixes: https://github.com/iree-org/iree/issues/10818` is a git trailer `key: value` and try to parse it. But it splits the whole line with `:` and expects there are only two segments, while here we have an extra `:` in the url, so triggers the bug.

**Comment by GMNGeoffrey** [comment]
I think this just needs a maxsplit=1. Sending a fix

**Pull request closed without merging**
