### PR TITLE
[GlobalOpt] Add a pass to simplify tensor pack ops.

### PR DESCRIPTION
**Pull request by hanhanW**

### CODE REVIEW

**Comment by hanhanW** [comment]
I just rebased it to ToT, which includes a fix for the total dispatch sizes regression.

**Review by MaheshRavishankar — APPROVED** [review]
THis looks fine! I have some ideas around using pack propagation to help fusion with mmt4d better. Lets make sure to chat about it some time.

**Review by Max191 — APPROVED** [review]
This looks good, but when https://github.com/openxla/iree/pull/15984 lands, I think this will not have any effect. The simplification patterns check for no `outer_dims_perm`, but with my PR all pack and unpacks will have explicit `outer_dims_perm` even if it is identity.

https://github.com/llvm/llvm-project/blob/16b8a0dc6885dea0882887a6e642a504fd1e193c/mlir/lib/Dialect/Tensor/Transforms/PackAndUnpackPatterns.cpp#L41-L42

Just wanted to point this out here, but we should allow identity permutations in the upstream patterns.

**Comment by hanhanW** [comment]
> This looks good, but when #15984 lands, I think this will not have any effect. The simplification patterns check for no `outer_dims_perm`, but with my PR all pack and unpacks will have explicit `outer_dims_perm` even if it is identity.
> 
> https://github.com/llvm/llvm-project/blob/16b8a0dc6885dea0882887a6e642a504fd1e193c/mlir/lib/Dialect/Tensor/Transforms/PackAndUnpackPatterns.cpp#L41-L42
> 
> Just wanted to point this out here, but we should allow identity permutations in the upstream patterns.

Thanks for the heads-up. This is fine because we can add it to folders or relax the check. I will send a follow-up upstream.

**Comment by hanhanW** [comment]
> THis looks fine! I have some ideas around using pack propagation to help fusion with mmt4d better. Lets make sure to chat about it some time.

SGTM, I also have few ideas about propagation. Let's chat after I address mmt4d fusion codegen issue.

**Pull request merged**
