### PR TITLE
[NFC] Omitting default N=4 from SmallVector and to_vector.

### PR DESCRIPTION
**Pull request by hanhanW**
It is generated by sed commands, e.g.,

```
sed 's/SmallVector<\([^,]*\), 4>/SmallVector<\1>/g'
sed 's/to_vector<4>/to_vector/g'
```

Then run clang-format.

### CODE REVIEW

**Comment by hanhanW** [comment]
We have mixed style in our codebase, maybe it's good to have a consistent style which keeps it in the short?

**Review by MaheshRavishankar — COMMENTED** [review]
I like this change, but sometimes it depends on what the callee/caller want. If the callee/caller in MLIR use `SmallVector<..., 4>` then this leads to an implicit copy.

**Comment by hanhanW** [comment]
> I like this change, but sometimes it depends on what the callee/caller want. If the callee/caller in MLIR use `SmallVector<..., 4>` then this leads to an implicit copy.

I think that's fine for most of cases. Many people just use `auto`... The compiler could notify the case (like `-Wreturn-std-move` flag). For IREE codebase, it is okay to pass `SmallVector` to any upstream function because they should take `SmallVectorImp` or `ArrayRef` as input arguments. For using upstream function, I think the compiler would warn out if that is the case.

**Comment by dcaballe** [comment]
> I like this change, but sometimes it depends on what the callee/caller want. If the callee/caller in MLIR use SmallVector<..., 4> then this leads to an implicit copy.

The default size is 4, isn't that the case? So this change shouldn't change the existing behavior? Not sure if I'm missing something...

**Comment by MaheshRavishankar** [comment]
> > I like this change, but sometimes it depends on what the callee/caller want. If the callee/caller in MLIR use SmallVector<..., 4> then this leads to an implicit copy.
> 
> The default size is 4, isn't that the case? So this change shouldn't change the existing behavior? Not sure if I'm missing something...

I dont think the default size is 4. It is computed based on the machine being compiled on (at least thats what I remember seeing). Unless there is any other objection, I am fine with this change.

**Review by MaheshRavishankar — APPROVED** [review]

**Pull request merged**
