### PR TITLE
Bump torch-mlir to llvm/torch-mlir@63505ad6b

### PR DESCRIPTION
**Pull request by qedawkins**
ci-extra: build_test_all_windows

### CODE REVIEW

**Review by ScottTodd — APPROVED** [review]

**Comment by qedawkins** [comment]
Windows passed this time so enabling auto-merge.

**Comment by qedawkins** [comment]
Actually @stellaraccident do you want to just do this bump as a part of the larger bump now?

**Comment by stellaraccident** [comment]
I'm going to lunch. If it works, go ahead and land it. Saves me a step.

**Review by stellaraccident — APPROVED** [review]

**Comment by ScottTodd** [comment]
Ready to merge this?

**Pull request merged**
