### PR TITLE
file_io_test was noisy when run on multiple parallel processes

### PR DESCRIPTION
**Pull request by bjacob**
as in ctest --repeat-until-fail 10 -j 10

The issue was that GetUniquePath would return the same path in
multiple processes so the assumption that the path didn't actually
exist would get defeated.

### CODE REVIEW

**Comment by benvanik** [comment]
/cc @GMNGeoffrey I thought our per-test directories would have prevented this?

Do you know why this same test would be running multiple times? That's also a bit suspicious.

(if we have to do this that's fine, but it's gnarly and if the root issue is that we're running the same test multiple times in a single test invocation that feels like what we should fix instead)

**Comment by benvanik** [comment]
ah just reread (semi afk and skimming, sorry!); this is because you're purposefully doing it

I think I'd prefer if we didn't have the linux stuff in there - debugging flakes that only show up on mac/windows because they have different behavior doesn't sound fun

**Comment by bjacob** [comment]
It's run multiple times not by default, but when I specifically ask for it, e.g.

```
ctest -R file_io_test -j5 --repeat-until-fail 5
```

This is in preparation for a subsequent CL enabling such multi-running of a few test directories with TSan, motivated by TSan non-determinism, but ironically this turned up a form of nondeterminism in plain non-TSan tests!

**Comment by bjacob** [comment]
OK, let's drop the cutesy linux auxv stuff (however superior that is :-P )

**Comment by benvanik** [comment]
yeah, agreed 🥴
we do have some temp file stuff doing the right thing (mkstemp/etc) in https://github.com/google/iree/blob/main/runtime/src/iree/base/internal/dynamic_library_win32.c#L69 and https://github.com/google/iree/blob/main/runtime/src/iree/base/internal/dynamic_library_posix.c#L42
I could probably hoist that out to a helper in file_io, but I think your workaround here is good for unblocking. I'll file an issue against myself.

**Review by benvanik — APPROVED** [review]

**Comment by GMNGeoffrey** [comment]
Ugh :-/ That's an issue with the approach I used in https://github.com/iree-org/iree/pull/9405 of doing the tmpdir creation at ctest beginning/end. I didn't consider ctest repeating. This is going to be a problem with any test we have that actually uses the temp directories then...

**Comment by bjacob** [comment]
Actually I was looking at the man page for `mkstemp` and wondering how random/unique that was.  Technically, for the present purpose, if we go down to OS-specific concepts, the PID is a more interesting value to use here than a random value because two concurrently running tests can't have the same PID (or the Windows equivalent of PID), and we only care about concurrently running processes so PID recycling is not an issue...

**Comment by GMNGeoffrey** [comment]
We care about serially running tests too. The whole idea is that tests shouldn't be able to interfere with each other

**Comment by bjacob** [comment]
Right -- if the make the test unlink the path at the end, then serially running tests just works too, regardless of the 'random' values being recycled.

**Comment by GMNGeoffrey** [comment]
Yeah but just writing all tests correctly is not necessarily a foolproof system :-) Especially in the presence of failures. Bazel guarantees a test directory that the test can do whatever with and not have to worry about. We were trying to replicate that in CMake, which was of course a giant PITA

**Pull request merged**
