### PR TITLE
NFC - Refactor and simplify reduction strategies

### PR DESCRIPTION
**Pull request by nicolasvasilache**
This PR simplifies the logic of reduction strategies and avoids unnecessary subclassing.
It is otherwise NFC and a step towards fixing #11991

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
(Please mark such PRs as draft :) )

**Comment by nicolasvasilache** [comment]
> (Please mark such PRs as draft :) )

I am confused, isn't it already a draft ?

**Comment by MaheshRavishankar** [comment]
It wasn't. I make it a draft

**Comment by nicolasvasilache** [comment]
Ah thanks, sorry about that!

**Review by qcolombet — APPROVED** [review]
Nice clean-up!

**Pull request merged**
