### PR TITLE
[Flow][LinalgExt] Move bitwidth helpers from Flow to LinalgExt

### PR DESCRIPTION
**Pull request by IanWood1**
Move `isBitExtendOp` and `isBitTruncateOp` into linalgext.

### CODE REVIEW

**Review by benvanik — CHANGES_REQUESTED** [review]
Gotta find something better for this (util should not depend on flow).

Oh man I didn't even see that LLVMGPU and all are also relying on flow for this. This is a mess. This should be in linalg or linalg ext - or an interface added to linalg ops.

**Comment by benvanik** [comment]
Yeah, isBitExtendOp needs to move if it's going to be used like this - RegionOpUtils being used in util and LLVMGPU (and likely then more places in the future - it's been there a day and already grown to two spaghetti deps) is not good. If this is something associated with linalg ops (seems to only be relevant to linalg::GenericOp) then it should live close to linalg. LinalgExt/Utils/ is a better dumping ground for linalg related things if that's what it is, but this feels like something that should be an interface (LinalgExt BitWidthChangeOpInterface with queries for isBitExtendOp/isBitTruncateOp instead of free-floating functions that dyn_cast to GenericOp and check details). Free floating functions that spider around tangle up too much stuff. If it's moved to LinalgExt/Utils/ (which the UtilExternalModels already depends on) then it'd be ok.

/cc @MaheshRavishankar

**Comment by IanWood1** [comment]
@benvanik I was planning on moving "isBitExtend" out of flow since it only really requires linalg.generic so there is no reason for it to be in flow. But I didn't know where to move it. If we owned linalg, then it would make sense to put it there. Are we treating Linalgext as a superset of linalg? Because then it would make sense to move it there.

**Comment by benvanik** [comment]
yep! it's got history but is the "what we would add to linalg if we could/wanted to" place for interfaces/ops/helpers.

As a general litmus test (that hasn't been observed but may increasingly start to be) the flow dialect should not rely on linalg at all - it should be possible to use flow without linalg. At some point everything related to linalg in there is likely to move out into a pipeline that sits before the flow pipelines.

**Review by qedawkins — COMMENTED** [review]
I am still skeptical that this is even necessary. The hoisting analysis already compares input/output operand sizes to determine whether hoisting is resulting in a much larger constant. This works nicely for both type extensions and broadcasts without even needing to know that it is a linalg op. I think it would help to see a concrete test case that this is fixing if possible.

**Comment by IanWood1** [comment]
Mahesh's argument was that bit extending (dequant) operations should never be hoisted, even if small. Looking at the stats after this change for int8 with hoisting enabled, there are 3 fewer dispatches ~~and 40kb smaller size~~. Edit: larger


Also, If were going to use an interface should i remove the helper functions? I feel like dyn cast to an interface to call a single method is a bit verbose, so im unsure which is better

**Comment by MaheshRavishankar** [comment]
Its ok to move the `bitExtend/bitTruncate` methods to `LinalgExt`. I'd avoid having a whole interface for now... just keep it as utility methods for now. We can revisit making it an interface.

**Comment by IanWood1** [comment]
Mahesh is waiting for isBitExtendOp to be & it seems sdxl is fine with hoisted bitextend ops. So, I'm just changing the purpose of this PR to simply move `isBitExtendOp` and `isBitTruncateOp` into linalgext. To clean up this PR, I backed up the state of the branch [here](https://github.com/IanWood1/iree/tree/dont_hoist_bitextend_back) and then squashed.

**Review by MaheshRavishankar — APPROVED** [review]
Cool! Thanks so much! @benvanik  can you take a look as well?

**Review by benvanik — APPROVED** [review]

**Pull request merged**
