### PR TITLE
[CPU] Enable codegen fallback when ukernels are not available.

### PR DESCRIPTION
**Pull request by hanhanW**
https://github.com/openxla/iree/issues/15784

### CODE REVIEW

**Comment by hanhanW** [comment]
Sending this for early feedback..

**Comment by pzread** [comment]
> ## Abbreviated Benchmark Summary
> @ commit [4567c2fb8a49cf006ac4940439da16a95950feb2](https://github.com/openxla/iree/commit/4567c2fb8a49cf006ac4940439da16a95950feb2) (vs. base [69398bc9fa793b8ce7e89bdeb12e196f819a60e0](https://github.com/openxla/iree/commit/69398bc9fa793b8ce7e89bdeb12e196f819a60e0))
> 
> ### Data-Tiling Comparison Table
> Click to show
> ### Regressed Latencies 🚩
> Benchmark Name	Average Latency (ms)	Median Latency (ms)	Latency Standard Deviation (ms)
> [MiniLML12H384Uncased(stablehlo) [x86\_64-cascadelake-linux\_gnu-llvm\_cpu][experimental-flags,no-dt] local\_task(embedded\_elf)[1-thread,full-inference,default-flags] with default @ c2-standard-60[cpu]](https://perf.iree.dev/serie?IREE?e076babcf92c08d76f05c53bec9bcf823f3855b6280c2c74465ed25bb2bb2bd7)	84.508 (vs. 76.591, 10.34%↑)	84.051	1.190
> [MobileNetV1\_fp32(tflite) [x86\_64-cascadelake-linux\_gnu-llvm\_cpu][experimental-flags,no-dt] local\_task(embedded\_elf)[1-thread,full-inference,default-flags] with default @ c2-standard-60[cpu]](https://perf.iree.dev/serie?IREE?1622e274d5ac570e18826aaec62f223c538583eb2f76e771d24eb2f7785954aa)	30.458 (vs. 27.912, 9.12%↑)	30.323	0.322
> ### Improved Latencies 🎉
> Benchmark Name	Average Latency (ms)	Median Latency (ms)	Latency Standard Deviation (ms)
> [MobileBertSquad\_int8(tflite) [armv8.2-a-generic-linux\_android29-llvm\_cpu][default-flags,dt-uk] local\_task(embedded\_elf)[2-thread,full-inference,system-scheduling] with default @ pixel-6-pro[big-cores]](https://perf.iree.dev/serie?IREE?9cff4a1b1873b4cda93168fc674fdc046c7b6640f81283cae57c871afbbe216d)	158.515 (vs. 169.948, 6.73%↓)	159.622	3.856
> [Vit\_int8(tflite) [armv8.2-a-generic-linux\_android29-llvm\_cpu][default-flags,dt-uk] local\_task(embedded\_elf)[2-thread,full-inference,system-scheduling] with default @ pixel-6-pro[big-cores]](https://perf.iree.dev/serie?IREE?6c111c114ceccecfdeb1b3608ec4701ac6c62fa29abfa7270a6737f92c94cb0b)	474.414 (vs. 507.173, 6.46%↓)	477.231	10.756
> [GPT2\_117M\_TF\_1X4XI32(stablehlo) [armv8.2-a-generic-linux\_android29-llvm\_cpu][default-flags,dt-uk] local\_sync(embedded\_elf)[full-inference,default-flags] with default @ pixel-6-pro[big-cores]](https://perf.iree.dev/serie?IREE?8ae7cfed6678287118515c19784beaae637b5bfa1a259ee0c40d0ae15de02f32)	29.689 (vs. 31.697, 6.33%↓)	29.658	1.084
> _[Top 3 out of 7 results showed]_
> 
> ### Regressed Total Dispatch Sizes 🚩
> Benchmark Name	Total Dispatch Size (bytes)
> [DeepLabV3\_fp32(tflite) [armv8.2-a-generic-linux\_android29-llvm\_cpu][experimental-flags,dt-only,compile-stats]](https://perf.iree.dev/serie?IREE?dfc2b952c58ab45e4ab30c731c677164e023dcc2350e7a1c2b1897955680d82b-9e15f7e6-383c-47ec-bd38-ecba55a5f10a)	85552 (vs. 79120, 8.13%↑)
> [DeepLabV3\_fp32(tflite) [armv8.2-a-generic-linux\_android29-llvm\_cpu][default-flags,dt-uk,compile-stats]](https://perf.iree.dev/serie?IREE?3160a297a2c9d3d21caeec097b6fe19150c3feae5fa872e21817af0be8a8176a-9e15f7e6-383c-47ec-bd38-ecba55a5f10a)	88840 (vs. 82504, 7.68%↑)
> [MobileBertSquad\_fp16(tflite) [x86\_64-cascadelake-linux\_gnu-llvm\_cpu][experimental-flags,no-dt,compile-stats]](https://perf.iree.dev/serie?IREE?5a4c96fc279262ad7d7f1d446d0bd3685b2ca42e06b0167df5be5737c9d42901-9e15f7e6-383c-47ec-bd38-ecba55a5f10a)	90472 (vs. 84648, 6.88%↑)
> _[Top 3 out of 4 results showed]_
> 
> ### Improved Total Dispatch Sizes 🎉
> Benchmark Name	Total Dispatch Size (bytes)
> [GPT2\_117M\_TF\_1X1XI32(stablehlo) [x86\_64-cascadelake-linux\_gnu-llvm\_cpu][experimental-flags,no-dt,compile-stats]](https://perf.iree.dev/serie?IREE?366507a9cec8b97b0885fe7f7c7827f75ef75b3db38a638f2277f21fefd4b159-9e15f7e6-383c-47ec-bd38-ecba55a5f10a)	19264 (vs. 20928, 7.95%↓)
> [GPT2\_117M\_TF\_1X4XI32(stablehlo) [x86\_64-cascadelake-linux\_gnu-llvm\_cpu][default-flags,dt-uk,compile-stats]](https://perf.iree.dev/serie?IREE?c0780698f17161a7646f3a7adc513f6dc06c04611adb2402d9f87f7c9b122a29-9e15f7e6-383c-47ec-bd38-ecba55a5f10a)	34632 (vs. 36936, 6.24%↓)
> [GPT2\_117M\_TF\_1X1XI32(stablehlo) [armv8.2-a-generic-linux\_android29-llvm\_cpu][experimental-flags,no-dt,compile-stats]](https://perf.iree.dev/serie?IREE?8f68e64101d3f8c2b383df66a744ea21b27ab09ae76d71422bb09fefb3e40169-9e15f7e6-383c-47ec-bd38-ecba55a5f10a)	11240 (vs. 11944, 5.89%↓)
> _[Top 3 out of 4 results showed]_
> 
> For more information:
> 
> * [Full benchmark result tables](https://gist.github.com/iree-github-actions-bot/9b9da6407a1ac8d4497a8cdaa57374b0)
> * [Build](https://github.com/openxla/iree/actions/runs/7174365946/attempts/3)
> 
> [Source Workflow Run](https://github.com/openxla/iree/actions/runs/7174365946)

The baseline is before the recent LLVM integration (#15855). I think we need to rebase to get a more recent one

**Review by MaheshRavishankar — APPROVED** [review]

**Review by pzread — APPROVED** [review]

**Review by bjacob — APPROVED** [review]

**Comment by bjacob** [comment]
Good stepping stone towards https://github.com/openxla/iree/issues/15784.

The core of https://github.com/openxla/iree/issues/15784 can't be tackled though without adding a new ukernel entry point allowing to query whether the ukernel has optimized code for a given case depending on CPU features and element types.

**Comment by dcaballe** [comment]
This is great, Hanhan! Thanks for the fix! Along the lines of the changes introduced here, I think we should aim for unifying the pipelines so that we have a single one where ukernels are handled early on and tiling/vectorization happen later for ops that were not lowered to ukernels or when ukernels are disabled. It has been a pain to keep these parallel pipelines aligned and there's always something missing in one of them.

**Pull request merged**
