### PR TITLE
Cherry-pick llvm/llvm-project@83b582d5 and llvm/llvm-project@19a0ac78

### PR DESCRIPTION
**Pull request by nicolasvasilache**

### CODE REVIEW

**Comment by nicolasvasilache** [comment]
@hanhanW for integrate

**Comment by ThomasRaoux** [comment]
FYI @vmurali

**Review by ThomasRaoux — APPROVED** [review]

**Comment by vmurali** [comment]
This has to be cherry-picked again because of integrate https://github.com/iree-org/iree/pull/11663

**Comment by vmurali** [comment]
This has to be cherry-picked again because of integrate
https://github.com/iree-org/iree/pull/11663

**Comment by nicolasvasilache** [comment]
This was done in #11665

**Pull request merged**
