### PR TITLE
[Flow] Make all input maps identity

### PR DESCRIPTION
**Pull request by IanWood1**
Change ElementwiseOpInterchangePattern from making output maps identity to making the input maps identity.
https://github.com/iree-org/iree/issues/18006

### CODE REVIEW

**Comment by MacDue** [comment]
~cc @banach-space, I think this is likely going to cause problems for scalable vectorization (not tested yet).~

Edit: Seems fine :slightly_smiling_face: (I was concerned this was going to lead to more unsupported scalable vector types).

**Comment by MaheshRavishankar** [comment]
@IanWood1  any leads on what the regression in dispatch count is due to?

**Comment by IanWood1** [comment]
Okay, I finally tracked it down. It looks like its the result of multiple consecutive transposes e.g.

```mlir

  %2 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d1, d0)>], iterator_types = ["parallel", "parallel"]} ins(%0 : tensor<10x10xf32>) outs(%1 : tensor<10x10xf32>) {
  ^bb0(%in: f32, %out: f32):
    linalg.yield %in : f32
  } -> tensor<10x10xf32>
  %3 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d1, d0)>], iterator_types = ["parallel", "parallel"]} ins(%2 : tensor<10x10xf32>) outs(%1 : tensor<10x10xf32>) {
  ^bb0(%in: f32, %out: f32):
    linalg.yield %in : f32
  } -> tensor<10x10xf32>

```

that get fused into this (from `ElementwiseOpFusion`):

```mlir
  %2 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d1, d0)>, affine_map<(d0, d1) -> (d1, d0)>], iterator_types = ["parallel", "parallel"]} ins(%0 : tensor<10x10xf32>) outs(%1 : tensor<10x10xf32>) {
  ^bb0(%in: f32, %out: f32):
    linalg.yield %in : f32
  } -> tensor<10x10xf32>

```
linalg::GenericOp's canonicalization patterns only handle when all maps are identity and not when all maps are equivalent permutations. I added a quick pattern to flip them to all identity to see if that clears up the issue. This is something that transpose prop would definitely clean up. But also is a bit strange that `ElementwiseOpFusion` only produces these results when the outputs are permuted.


Also, small side note, these ops are labeled as transposes which is a bit misleading. It seems to make sense to always make the indexing maps identity if possible


Edit: there still seems to be some slight regressions...

**Comment by hanhanW** [comment]
> Also, small side note, these ops are labeled as transposes which is a bit misleading.

I think it is because some people (like me) had an assumption that the output indexing map is always identity. Because it looks like a canonical form. It is definitely wrong when there are two results with different indexing maps.

> It seems to make sense to always make the indexing maps identity if possible

This makes sense to me. I'd expect to see identity indexing maps if possible.

**Comment by MaheshRavishankar** [comment]
> Okay, I finally tracked it down. It looks like its the result of multiple consecutive transposes e.g.
> 
> ```mlir
>   %2 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d1, d0)>], iterator_types = ["parallel", "parallel"]} ins(%0 : tensor<10x10xf32>) outs(%1 : tensor<10x10xf32>) {
>   ^bb0(%in: f32, %out: f32):
>     linalg.yield %in : f32
>   } -> tensor<10x10xf32>
>   %3 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d1, d0)>], iterator_types = ["parallel", "parallel"]} ins(%2 : tensor<10x10xf32>) outs(%1 : tensor<10x10xf32>) {
>   ^bb0(%in: f32, %out: f32):
>     linalg.yield %in : f32
>   } -> tensor<10x10xf32>
> ```
> 
> that get fused into this (from `ElementwiseOpFusion`):
> 
> ```mlir
>   %2 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d1, d0)>, affine_map<(d0, d1) -> (d1, d0)>], iterator_types = ["parallel", "parallel"]} ins(%0 : tensor<10x10xf32>) outs(%1 : tensor<10x10xf32>) {
>   ^bb0(%in: f32, %out: f32):
>     linalg.yield %in : f32
>   } -> tensor<10x10xf32>
> ```
> 
> linalg::GenericOp's canonicalization patterns only handle when all maps are identity and not when all maps are equivalent permutations.

You mean the canonicalization pattern upstream? Yeah I think I might have done that (oversight). Just fix it upstream.

> I added a quick pattern to flip them to all identity to see if that clears up the issue. This is something that transpose prop would definitely clean up. But also is a bit strange that `ElementwiseOpFusion` only produces these results when the outputs are permuted.

What is strange here, not following?

> 
> Also, small side note, these ops are labeled as transposes which is a bit misleading. It seems to make sense to always make the indexing maps identity if possible

In this case we should just fold it away... missing what is the "labeled as transposes" is refering to though

> 
> Edit: there still seems to be some slight regressions...

**Comment by IanWood1** [comment]
> > I added a quick pattern to flip them to all identity to see if that clears up the issue. This is something that transpose prop would definitely clean up. But also is a bit strange that `ElementwiseOpFusion` only produces these results when the outputs are permuted.
> 
> What is strange here, not following?

I just would of assumed that the indexing_maps would have been identity instead of equal permutations (which I think is the same as identity, at least for a linalg.generic with a single yield).



> > Also, small side note, these ops are labeled as transposes which is a bit misleading. It seems to make sense to always make the indexing maps identity if possible
> 
> In this case we should just fold it away... missing what is the "labeled as transposes" is refering to though

Oops, I gave no context, the dispatches were labeled as transposes because of their indexing maps although they were just memcpys.


Okay, I'll fix upstream + look at the remaining issues.

**Comment by IanWood1** [comment]
Removed the commit and now waiting on https://github.com/llvm/llvm-project/pull/101430

**Comment by IanWood1** [comment]
The other regressions are because transpose -> pack fusion requires identity indexing maps and they aren't being folded

**Comment by hanhanW** [comment]
> transpose -> pack fusion requires identity indexing maps and they aren't being folded

I thought that the upstream patterns are complete to handle the cases. Can you share the IR that `(transpose, pack)` is not folded into a single pack?

Meanwhile, it is not a blocker to me. We're transiting to "late materialization" path, so it's fine. We should be able to handle the case when we move early materialization path to preprocessing.

**Comment by IanWood1** [comment]
The logic for forming dispatch regions requires the transpose to have identity indexing maps to be able to fuse a transpose with a pack. In iree_MobileBertSquad_fp32_tflite_.mlir:


```mlir
%inserted_slice_1661 = tensor.insert_slice %1552 into %83[0, 0] [384, 32] [1, 1] : tensor<384x32xf32> into tensor<1536x32xf32>
%inserted_slice_1662 = tensor.insert_slice %1556 into %inserted_slice_1661[384, 0] [384, 32] [1, 1] : tensor<384x32xf32> into tensor<1536x32xf32>
%inserted_slice_1663 = tensor.insert_slice %1560 into %inserted_slice_1662[768, 0] [384, 32] [1, 1] : tensor<384x32xf32> into tensor<1536x32xf32>
%inserted_slice_1664 = tensor.insert_slice %1564 into %inserted_slice_1663[1152, 0] [384, 32] [1, 1] : tensor<384x32xf32> into tensor<1536x32xf32>
%expanded_1665 = tensor.expand_shape %inserted_slice_1664 [[0, 1], [2]] output_shape [4, 384, 32] : tensor<1536x32xf32> into tensor<4x384x32xf32>
%1565 = flow.dispatch.region -> (tensor<384x4x32xf32>) {
  %1822 = tensor.empty() : tensor<384x4x32xf32>
  %1823 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d1, d0, d2)>], iterator_types = ["parallel", "parallel", "parallel"]} ins(%expanded_1665 : tensor<4x384x32xf32>) outs(%1822 : tensor<384x4x32xf32>) {
  ^bb0(%in: f32, %out: f32):
    linalg.yield %in : f32
  } -> tensor<384x4x32xf32>
  flow.return %1823 : tensor<384x4x32xf32>
}
%1566 = flow.dispatch.region -> (tensor<24x4x32x16x1xf32>) {
  %1822 = tensor.empty() : tensor<24x4x32x16x1xf32>
  %pack = tensor.pack %1565 outer_dims_perm = [0, 1, 2] inner_dims_pos = [0, 2] inner_tiles = [16, 1] into %1822 : tensor<384x4x32xf32> -> tensor<24x4x32x16x1xf32>
  flow.return %pack : tensor<24x4x32x16x1xf32>
}

```

**Comment by MaheshRavishankar** [comment]
> The other regressions are because transpose -> pack fusion requires identity indexing maps and they aren't being folded

Where are the regressions. I dont see any on this PR

**Comment by IanWood1** [comment]
> > The other regressions are because transpose -> pack fusion requires identity indexing maps and they aren't being folded
> 
> Where are the regressions. I dont see any on this PR

They should appear on the previous version of the comment. MobileBert with dt had some transpose -> packs that weren't being fused causing ~1% increase in dispatches

**Comment by IanWood1** [comment]
The sdxl regressions are coming from the backend somewhere. There is a difference in performance when the inputs are transposed and when the outputs are transposed. After Flow, the IR is nearly identical except for swapped indexing maps. @hanhanW @qedawkins any idea where this difference might be materializing?


I printed logs for a single transpose with and without the changes to make the input indexing maps identity:
Before changes: https://gist.github.com/IanWood1/3eabf1f3dff2ce7f604cdd2fdea1c128/raw
After changes: https://gist.github.com/IanWood1/1b396254f92982a57ffd8bec983f5a51/raw


Edit: After TileAndDistributeToWorkgroups, `workgroup_id_x` and `workgroup_id_y` are flipped when comparing original vs after these changes.

**Comment by hanhanW** [comment]
I spent some time on reading the issue, and now I understand why we want to make input maps identity. It is mainly for fusion heuristic.

Then my question is: Can we normalize the indexing maps after dispatch formation? Say that we make output maps identity after outlining dispatches or make output maps identity in [codegen common preprocessing passes](https://github.com/iree-org/iree/blob/235e110f4809f3d5414619d36fac00c4e4c02551/compiler/src/iree/compiler/Codegen/Common/Passes.cpp#L14-L22)? It makes codegen get the same dispatch (i.e., the output indexing map becomes identity).

**Comment by MaheshRavishankar** [comment]
If you think that will help CPU codegen, then we can have a pass in the CPU backend that will do the inversion. But is it a bug in tile and distribution to workgroups

**Comment by qedawkins** [comment]
> The sdxl regressions are coming from the backend somewhere. There is a difference in performance when the inputs are transposed and when the outputs are transposed. After Flow, the IR is nearly identical except for swapped indexing maps. @hanhanW @qedawkins any idea where this difference might be materializing?
> 
> I printed logs for a single transpose with and without the changes to make the input indexing maps identity: Before changes: https://gist.github.com/IanWood1/3eabf1f3dff2ce7f604cdd2fdea1c128/raw After changes: https://gist.github.com/IanWood1/1b396254f92982a57ffd8bec983f5a51/raw
> 
> Edit: After TileAndDistributeToWorkgroups, `workgroup_id_x` and `workgroup_id_y` are flipped when comparing original vs after these changes.

FWIW in both of those examples it is going down the `LLVMGPUTransposeSharedMem` pipeline, and I don't think we have any active developers familiar with that pipeline. We might want to consider removing that pipeline or finding a way to move it to a different pipeline (like `LLVMGPUTileAndFuse`).

**Comment by hanhanW** [comment]
CPU side is perhaps fine. I was thinking about GPU because of the log. 

I agree that `LLVMGPUTransposeSharedMem` is not that important to IREE because most of transpose should be fused into other generic ops, and we should teach other existing lowering strategy to handle the case.

**Comment by IanWood1** [comment]
Commits were added to https://github.com/iree-org/iree/pull/18074

**Pull request closed without merging**
