### PR TITLE
Add FlashAttention v2

### PR DESCRIPTION
**Pull request by harsh-nod**
This patch adds the algorithmic modifications introduced in FA2 into the tile and decompose attention pass.

### CODE REVIEW

**Review by MaheshRavishankar — COMMENTED** [review]
I dont know the details, but is there a need to support both FlashAttentionV1 and FlashAttentionV2 ?

**Comment by harsh-nod** [comment]
> I dont know the details, but is there a need to support both FlashAttentionV1 and FlashAttentionV2 ?

FlashAttentionV2 provides performance improvements on top of FlashAttentionV1 without introducing any approximations and losing any accuracy. So I think it should be safe to drop FlashV1 and replace with FlashV2.

**Review by MaheshRavishankar — APPROVED** [review]

**Comment by MaheshRavishankar** [comment]
I approved. @harsh-nod you should really make yourself the OWNER of these code paths :)

**Comment by harsh-nod** [comment]
> I approved. @harsh-nod you should really make yourself the OWNER of these code paths :)

Thanks, will do :) Right now I forgot to update the llvm gpu test in this PR and that's why the builders are failing. Taking a closer look at it, but it might need some upstream fixes. So just going to put this on hold for now and will message on here when everything else is ready. Thanks for the review!

**Comment by Groverkss** [comment]
Moved to https://github.com/openxla/iree/pull/15527 (talked with Harsh offline) after upstream fixes and test fixes

**Pull request closed without merging**
