### PR TITLE
Adding `iree_compiler_cc_library`/`iree_runtime_cc_library` to cmake to match bazel.

### PR DESCRIPTION
**Pull request by benvanik**
Progress on #9421. This is only doing the renaming and not shuffling around any of the copts/linkopts yet.

### CODE REVIEW

**Comment by benvanik** [comment]
This effectively no-op change breaks everything and I have no idea why.... oh~ cmake~

**Comment by GMNGeoffrey** [comment]
> This effectively no-op change breaks everything and I have no idea why.... oh~ cmake~

As a potential hint. It looks like building the compiler stuff is all working and it's only the runtime that is failing (at least, there are no errors for building the compiler in the full logs)

**Comment by ScottTodd** [comment]
This may be a bit easier to land now that https://github.com/openxla/iree/pull/12645 is merged.

**Comment by benvanik** [comment]
Dropping for now as it'd be easier to do from scratch than rebase this.

**Pull request closed without merging**
