### PR TITLE
Remove transform.structured.lower_vectors

### PR DESCRIPTION
**Pull request by qcolombet**
This op has been upstreamed as transform.lower_vectors.

Note: I only saw uses of the open source variant in the code base at this point and everything works locally when I remove it, I'd like the CI to double check that.
Hence, the WIP in the title.

### CODE REVIEW

**Review by nicolasvasilache — APPROVED** [review]
yes this one should be good to drop

**Comment by qcolombet** [comment]
Thanks @nicolasvasilache for the confirmation. Removing the WIP keyword.

**Comment by qcolombet** [comment]
Hi @nicolasvasilache, could you take another look?
In particular the previous version was missing the update for the `iree-dialect-opt` tool and tests.

**Comment by qcolombet** [comment]
Also can someone check that the changes in `BUILD` make sense?
I don't know how to test with bazel.

**Review by stellaraccident — COMMENTED** [review]
Bazel change looks reasonable. If the CI address, it is fine.

**Comment by qcolombet** [comment]
Thanks @stellaraccident

**Comment by qcolombet** [comment]
And thanks @nicolasvasilache for showing me how to build with bazel (offline).

**Pull request merged**
