### PR TITLE
[Codegen][llvmgpu] Refactor op cloning in prefetch shared memory pass

### PR DESCRIPTION
**Pull request by jerryyin**
I refactored the prefetch shared memory pass by using `rewriter.clone()` with a IRMapping. With this, the pass can now handle ops with a region (like `scf.if`) which would otherwise create invalid IRs when there's scf.if in k loop.

### CODE REVIEW

**Comment by manupak** [comment]
Im a bit surprised to see that you needed to handle the regions seperately..
From:
https://github.com/llvm/llvm-project/blob/8e4423eb0888e5fe381a23ec1fa6969f2d096ed1/mlir/lib/IR/Operation.cpp#L738-L742

AFAIK, clone(..) is different from cloneWithoutRegions(...) API. 
Is there any special reason we need to handle regions here specifically ?

**Comment by jerryyin** [comment]
@manupak That's a good question. I asked myself this question in middle of the PR too. As it turns out the default `clone` behavior is not the `clone` we'd use in this prefetch class. The default `clone` or `cloneRegionbefore` will make a naive clone of the op. But the clone we've created here is doing more than naively cloning and making a copy of the op/regions. It will clone a new subgraph and make sure new ops operands are referencing values from the newly created subgraph 

For example, below is the reason we can't use any native clone functions as-is:
https://github.com/iree-org/iree/blob/acd051c042fbfcc99f3b6616d03b01231f3423d0/compiler/src/iree/compiler/Codegen/LLVMGPU/Utils/PrefetchSharedMemoryCopy.cpp#L263-L266

This is also the exact reason why the original clone in this class can't deal with if/else regions correctly: By cloning using the default, it barely make a naive clone that will copy over the exact same value/ops used by the original if/else. This turns into a problem if we want to put the newly cloned graph before the k-loop because then the cloned region would reference a value not created yet, therefore yielding a lowering failure.

**Comment by manupak** [comment]
> It will clone a new subgraph and make sure new ops operands are referencing values from the newly created subgraph

Im not still getting why `clone( op , IRMapping )` wont work here ?

**Comment by manupak** [comment]
e.g. : https://github.com/iree-org/iree/blob/5b0740c97a33edce29e753b14b9ff04789afcc53/compiler/plugins/input/StableHLO/Conversion/Preprocessing/FlattenTuplesInCFG.cpp#L305-L311

**Comment by manupak** [comment]
My understanding is if the mapping contained all the IR mapping for : operands, operands for regions -- it should work ?

**Comment by jerryyin** [comment]
Taking a second look, looks `builder.clone()` come with a `CloneOptions` option which I can turn on `cloneOperandsFlag`. I'll give it a shot and let you know!

**Comment by jerryyin** [comment]
@manupak It was brilliant suggestion and massively simplified the whole implementation. Please refer to latest commit for using clone with mapping directly.

**Review by manupak — APPROVED** [review]
Im glad it helped!
LGTM! I d wait for a codeowner to review :)

**Review by kuhar — COMMENTED** [review]
This code is on life support, but simplifications like this are welcome.

Have you checked that this continues to work across SDXL and iree-kernel-benchmark? I'm asking because the code is not tested very thoroughly via LIT.

**Comment by kuhar** [comment]
Also, the PR description seems out of sync with the code changes?

**Comment by jerryyin** [comment]
@kuhar Hey thanks for the review.

> This code is on life support

I'm surprised to hear about this because I bump into a failure from this pass when running tileAndFuse pipeline. I've attempted to disable this pass and can confirm comparatively there's a good speed up by running this pass. Do we have a different software pipelining implementation somewhere else that I'm not aware of? Please feel free to point out that I'd be interested to learn about it.

> Have you checked that this continues to work across SDXL and iree-kernel-benchmark?

I don't expect this to cause regressions but it is always good to double check. Assuming there are multiple steps to get benchmark run end-to-end, I can follow-up offline with you on this. Would be convenient if there's a automated way to check it. 

> Also, the PR description seems out of sync with the code changes?

Updated the PR description with latest state of code change.

**Comment by kuhar** [comment]
> Do we have a different software pipelining implementation somewhere else that I'm not aware of? Please feel free to point out that I'd be interested to learn about it.

Not right now, but we will be switch to something similar to the pipeliner from Triton. I started the work but haven't finished yet. ETA ~2nd half of December.

> I don't expect this to cause regressions but it is always good to double check. Assuming there are multiple steps to get benchmark run end-to-end, I can follow-up offline with you on this. Would be convenient if there's a automated way to check it.

SG. The reason I asked for this is that this implementation has known correctness issues and I wouldn't be surprised if something suddenly fails if we start changing the logic.

**Comment by jerryyin** [comment]
Communicated with @kuhar offline and confirmed that both gemm bench and SDXL perf impact is less than 5%. I decided it is not worthwhile uploading the corresponding run logs since nothing stand out from the benchmarking. Would be happy to upload if any reviewer decides a second pair of eye is necessary.

**Review by kuhar — APPROVED** [review]
Thanks for the due diligence

**Pull request merged**
