### PR TITLE
Integrate LLVM at llvm/llvm-project@7752fec6

### PR DESCRIPTION
**Pull request by hanhanW**
Revert commits:

- https://github.com/llvm/llvm-project/commit/ae059a1f9f1e501b08a99cb636ec0869ec204c6f

### CODE REVIEW

**Review by ScottTodd — APPROVED** [review]

**Comment by hanhanW** [comment]
```
  FAILED: tests/e2e/tensor_ops/check_rocm_hip_pack.mlir_module.vmfb /home/esaimana/actions-runner/_work/iree/iree/build-tests/tests/e2e/tensor_ops/check_rocm_hip_pack.mlir_module.vmfb 
  cd /home/esaimana/actions-runner/_work/iree/iree/build-tests/tests/e2e/tensor_ops && /home/esaimana/actions-runner/_work/iree/iree/.venv/bin/iree-compile --output-format=vm-bytecode --mlir-print-op-on-diagnostic=false --iree-hal-target-backends=rocm --iree-rocm-target-chip=gfx1100 /home/esaimana/actions-runner/_work/iree/iree/tests/e2e/tensor_ops/pack.mlir -o check_rocm_hip_pack.mlir_module.vmfb --iree-hal-executable-object-search-path=\"/home/esaimana/actions-runner/_work/iree/iree/build-tests\"
  error: Illegal instruction detected: Operand has incorrect register class.
```

It looks a LLVM failure.. looking

**Comment by hanhanW** [comment]
Confirmed that https://github.com/llvm/llvm-project/pull/102198 is the issue locally. I'll try to create a repro and signal it in upstream.

**Comment by hanhanW** [comment]
To repro it in IREE: `iree-compile --output-format=vm-bytecode --iree-hal-target-backends=rocm --iree-rocm-target-chip=gfx1100 --iree-rocm-bc-dir=/opt/rocm ~/repro.mlir -o /tmp/z.vmfb`

```mlir
func.func private @generate_2D_source(%height : index, %width : index) -> tensor<?x?xi32> {
  %init_source = tensor.empty(%height, %width) : tensor<?x?xi32>
  %source = linalg.generic {
      indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>],
      iterator_types = ["parallel", "parallel"]}
      outs(%init_source : tensor<?x?xi32>) {
    ^bb0(%b0 : i32):
      %outer = linalg.index 0 : index
      %inner = linalg.index 1 : index
      %strided = arith.muli %outer, %width : index
      %linearized = arith.addi %inner, %strided : index
      %linearized_i32 = arith.index_cast %linearized : index to i32
      linalg.yield %linearized_i32 : i32
  } -> tensor<?x?xi32>
  // This blocks the fusion for inputs and testing ops.
  %0 = util.optimization_barrier %source : tensor<?x?xi32>
  %1 = flow.tensor.tie_shape %0 : tensor<?x?xi32>{%height, %width}
  return %1 : tensor<?x?xi32>
}

func.func @static_pack_pad_transpose_outer_dims_large() {
  %height = arith.constant 100 : index
  %width = arith.constant 250 : index
  %0 = call @generate_2D_source(%height, %width) : (index, index) -> tensor<?x?xi32>
  %source = tensor.cast %0 : tensor<?x?xi32> to tensor<100x250xi32>
  %padding_value = arith.constant 42 : i32

  %init_pack = tensor.empty() : tensor<16x4x32x16xi32>
  %pack = tensor.pack %source padding_value(%padding_value : i32)
      outer_dims_perm = [1, 0] inner_dims_pos = [0, 1] inner_tiles = [32, 16] into %init_pack
      : tensor<100x250xi32> -> tensor<16x4x32x16xi32>

  %pad = tensor.pad %source low[0, 0] high[28, 6] {
    ^bb0(%b0 : index, %b1 : index):
      tensor.yield %padding_value : i32
  } : tensor<100x250xi32> to tensor<128x256xi32>
  %reshape = tensor.expand_shape %pad [[0, 1], [2, 3]] output_shape [4, 32, 16, 16] : tensor<128x256xi32> into tensor<4x32x16x16xi32>
  %init_transpose = tensor.empty() : tensor<16x4x32x16xi32>
  %transpose = linalg.transpose
    ins(%reshape : tensor<4x32x16x16xi32>)
    outs(%init_transpose : tensor<16x4x32x16xi32>)
    permutation = [2, 0, 1, 3]

  check.expect_eq(%pack, %transpose) : tensor<16x4x32x16xi32>
  return
}
```

**Comment by hanhanW** [comment]
Here is the LLVM module before translate it to ISA: https://gist.github.com/hanhanW/b806883680dd028ed82943b84483c2b8

And it failed in https://github.com/iree-org/iree/blob/5a48912c52f65ead960bec9bfde5a836d1b02ab2/compiler/plugins/target/ROCM/ROCMTarget.cpp#L555

which calls `translateModuleToISA` method: https://github.com/iree-org/iree/blob/5a48912c52f65ead960bec9bfde5a836d1b02ab2/compiler/plugins/target/ROCM/ROCMTarget.cpp#L191-L203

@MaheshRavishankar @kuhar how do we reproduce the failure using LLVM tools? I think we can ask for a revert if we can provide such repro to the author.

**Comment by broxigarchen** [comment]
> Here is the LLVM module before translate it to ISA: https://gist.github.com/hanhanW/b806883680dd028ed82943b84483c2b8
> 
> And it failed in
> 
> https://github.com/iree-org/iree/blob/5a48912c52f65ead960bec9bfde5a836d1b02ab2/compiler/plugins/target/ROCM/ROCMTarget.cpp#L555
> 
> which calls `translateModuleToISA` method:
> 
> https://github.com/iree-org/iree/blob/5a48912c52f65ead960bec9bfde5a836d1b02ab2/compiler/plugins/target/ROCM/ROCMTarget.cpp#L191-L203
> 
> @MaheshRavishankar @kuhar how do we reproduce the failure using LLVM tools? I think we can ask for a revert if we can provide such repro to the author.

Ran a quick repro. These are the error info:

error: Illegal instruction detected: Operand has incorrect register class.
V_CMP_EQ_U16_t16_e32 0, killed $vgpr254, implicit-def $vcc, implicit $exec
error: Illegal instruction detected: Operand has incorrect register class.
V_CMP_EQ_U16_t16_e32 0, killed $vgpr254, implicit-def $vcc, implicit $exec
error: Illegal instruction detected: Operand has incorrect register class.
V_CMP_EQ_U16_t16_e32 0, killed $vgpr254, implicit-def $vcc, implicit $exec
error: Illegal instruction detected: Operand has incorrect register class.
V_CMP_EQ_U16_t16_e32 0, killed $vgpr254, implicit-def $vcc, implicit $exec
error: Illegal instruction detected: Operand has incorrect register class.
V_CMP_EQ_U16_t16_e32 0, killed $vgpr254, implicit-def $vcc, implicit $exec
error: Illegal instruction detected: Operand has incorrect register class.
V_CMP_EQ_U16_t16_e32 0, killed $vgpr254, implicit-def $vcc, implicit $exec
error: Illegal instruction detected: Operand has incorrect register class.
V_CMP_EQ_U16_t16_e32 0, killed $vgpr254, implicit-def $vcc, implicit $exec
error: Illegal instruction detected: Operand has incorrect register class.
V_CMP_EQ_U16_t16_e32 0, killed $vgpr254, implicit-def $vcc, implicit $exec
error: Illegal instruction detected: Operand has incorrect register class.
V_CMP_EQ_U16_t16_e32 0, killed $vgpr254, implicit-def $vcc, implicit $exec
error: Illegal instruction detected: Operand has incorrect register class.
V_CMP_EQ_U16_t16_e32 0, killed $vgpr254, implicit-def $vcc, implicit $exec
error: Illegal instruction detected: Operand has incorrect register class.
V_CMP_EQ_U16_t16_e32 0, killed $vgpr254, implicit-def $vcc, implicit $exec
error: Illegal instruction detected: Operand has incorrect register class.

**Pull request merged**
