### PR TITLE
Enable CUDA (compiler and runtime) by default in CMake builds.

### PR DESCRIPTION
**Pull request by stellaraccident**
On platforms where we can download compatible CUDA SDK components, enable CUDA compiler and runtime support by default.

### CODE REVIEW

**Review by ScottTodd — APPROVED** [review]

**Comment by pzread** [comment]
Looks like in `build_tools/third_party/cuda/CMakeLists.txt` the `iree_get_executable_path(_EXE_PATH generate_embed_data)` is called and creates the target `generate_embed_data` because `-DIREE_HOST_BINARY_ROOT=` is used in those workflow. But later in `./CMakeLists.txt` the `add_subdirectory(build_tools/embed_data/)` is called and it tries to define the build target `generate_embed_data` unconditionally and pops the error.

It seems like `build_tools/embed_data/CMakeLists.txt` shouldn't try to build the `generate_embed_data` when `-DIREE_HOST_BINARY_ROOT=` is used.

**Comment by ScottTodd** [comment]
> Looks like in `build_tools/third_party/cuda/CMakeLists.txt` the `iree_get_executable_path(_EXE_PATH generate_embed_data)` is called and creates the target `generate_embed_data` because `-DIREE_HOST_BINARY_ROOT=` is used in those workflow. But later in `./CMakeLists.txt` the `add_subdirectory(build_tools/embed_data/)` is called and it tries to define the build target `generate_embed_data` unconditionally and pops the error.
> 
> It seems like `build_tools/embed_data/CMakeLists.txt` shouldn't try to build the `generate_embed_data` when `-DIREE_HOST_BINARY_ROOT=` is used.

My changes in https://github.com/iree-org/iree/pull/11764 (and follow-ups) will simplify (and likely fix) that.

**Comment by ScottTodd** [comment]
Specifically the change from checking `CMAKE_CROSSCOMPILING` to `IREE_HOST_BINARY_ROOT` here: 
image

**Comment by ScottTodd** [comment]
I sent https://github.com/iree-org/iree/pull/11832 that just rebased this PR's commit. Presubmits passed there.

**Pull request closed without merging**
