### PR TITLE
Adding `--iree-hal-substitute-executable-*=` flags.

### PR DESCRIPTION
**Pull request by benvanik**
This allows for specifying one or more `executable_name=file.xxx` pairs that each replace a `hal.executable` op with the `executable_name` with the contents of `file.xxx`. .mlir/.mlirbc files are loaded and a `hal.executable` with the matching name is used as a replacement while any other file type will cause the original executable to be externalized and linked with the specified file (.ptx/.spv/etc).

The additional `--iree-hal-substitute-executable-*-from=` flags allow for scanning a directory for executables by name to build the substitution mapping. Only files in the executable_name or module_executable_name form will be substituted but we can extend this in the future to support variant naming.

Because of phase ordering constraints around where codegen is able to mutate host-related code such as workgroup count calculations there are two flag sets:
  `--iree-hal-substitute-executable-source=name=file.xxx`
  `--iree-hal-substitute-executable-sources-from=path/`
 and
  `--iree-hal-substitute-executable-object=name=file.xxx`
  `--iree-hal-substitute-executable-objects-from=path/`
Sources are substituted immediately prior to benchmark generation and when substituting target objects (.ptx, .spv, etc) require that it's ok to skip codegen (workgroup count calculation is not dependent on root op detection, etc). Objects are substituted immediately after codegen for use in cases where codegen is to generate the host code. There are uses for both depending on what the input IR is and what the developer wants to modify (host code, device code, or both).

The primary developer workflows this covers are:
1. dump executable sources via `--iree-hal-dump-executable-sources-to=` and modify them, potentially running any number of iree-opt passes, before linking them back in to the original program they came from
2. author custom implementations ala the custom_dispatch sample in target toolchains (.cu -> .ptx, .glsl -> .spv, etc) and use those in full programs without needing to modify the compiler
3. do either of the above and use the substituted executable for microbenchmarking via `--iree-hal-dump-executable-benchmarks-to=` (so one can easily microbenchmark handwritten kernels)

Example usage:
```sh
# dump sources for a program
iree-compile ... \
  --iree-hal-dump-executable-sources-to=~/sources/
# <modify some of the sources>
# recompile with the new changes and substitute 2 executables
iree-compile ... \
    --iree-hal-substitute-executable-source=_main_dispatch_0=~/sources/modified_dispatch_0.mlir \
    --iree-hal-substitute-executable-source=_main_dispatch_1=~/sources/modified_dispatch_1.mlir
# same thing with search paths
iree-compile ... \
    --iree-hal-executable-object-search-path=~/sources/ \
    --iree-hal-substitute-executable-source=_main_dispatch_0=modified_dispatch_0.mlir
# same thing but matching all files by name as from dump-sources-to:
iree-compile ... \
    --iree-hal-substitute-executable-sources-from=~/sources/
```

This works with ptx/spv as well:
```sh
# dump ptx binaries
iree-compile ... \
    --iree-hal-dump-executable-binaries-to=~/binaries/
# <modify dispatch ptx>
# replace @_main_dispatch_0 with the external ptx file
iree-compile ... \
    --iree-hal-substitute-executable-object=_main_dispatch_0=~/binaries/modified_dispatch_0.ptx
```

It's also possible to iterate on microbenchmarks using the custom sources/objects:
```sh
# dump all benchmarks with the substitution active
iree-compile ... \
    --iree-hal-substitute-executable-source=_main_dispatch_0=~/sources/modified_dispatch_0.mlir \
    --iree-hal-dump-executable-benchmarks-to=~/benchmarks/
# inspect benchmark for the dispatch and see the hello.world attr
# can use iree-compile to build the benchmark and then iree-benchmark-module
```

Progress on #12222 (the rest for linking alternative formats is orthogonal).

### CODE REVIEW

**Comment by benvanik** [comment]
(moved up into PR description for posterity)

**Comment by kuhar** [comment]
I have an actual use case for this, giving it a try now.

**Comment by kuhar** [comment]
I wasn't able to get this to work with .spv files. I assumed that because the examples included .ptx, it should also work with .spv.

My workflow was something like this:
1. Compile the original program and dump binaries:
   ```mlir
   func.func @main() {
    %lhs = util.unfoldable_constant dense<1> : tensor<1024x1024xi8>
    %rhs = util.unfoldable_constant dense<1> : tensor<1024x1024xi8>
    %c0 = arith.constant 0 : i32
    %i0 = arith.constant 0 : index
    %init = tensor.empty() : tensor<1024x1024xi32>
    %CC = linalg.fill ins(%c0 : i32) outs(%init : tensor<1024x1024xi32>) -> tensor<1024x1024xi32>
    %D = linalg.matmul ins(%lhs, %rhs: tensor<1024x1024xi8>, tensor<1024x1024xi8>)
                      outs(%CC: tensor<1024x1024xi32>) -> tensor<1024x1024xi32>
    check.expect_eq_const(%D, dense<1024> : tensor<1024x1024xi32>) : tensor<1024x1024xi32>
    return
    }
    ```
    
    ```shell
    iree-compile matmul_1k_i32_i32.mlir --iree-hal-target-backends=vulkan-spirv --iree-vulkan-target-triple=valhall-unknown-android31 --iree-hal-benchmark-dispatch-repeat-count=100 --iree-hal-dump-executable-binaries-to=binaries -o benchmark.vmf
   ```

2. Produce a new spir-v file based on the binary in `binaries`:
    ```shell
    mkdir replace
    cp binaries/module__main_dispatch_0_vulkan_spirv_fb.spv replace
    # modify replace/module__main_dispatch_0_vulkan_spirv_fb.spv
    ```

3. Try using `./replace` as the substitution dir:
    ```shell
    iree-compile matmul_1k_i8_i32.mlir --iree-hal-target-backends=vulkan-spirv --iree-vulkan-target-triple=valhall-unknown-android31 --iree-hal-benchmark-dispatch-repeat-count=100 --iree-hal-dump-executable-binaries-to=./dumps --iree-hal-substitute-executables-from=./replace -o benchmark.vmfb     
   WARNING: iree-hal-substitute-executables could not perform the requested substitution as the executable `_main_dispatch_0_vulkan_spirv_fb` was not found in the module
   
   # Try to fix the name mismatch. 
   mv replace/module__main_dispatch_0{_vulkan_spirv_fb,}.spv
   ```
   
   ```
     # recompile
     NOTE: hal.executable `_main_dispatch_0` substituted with object file at `./replace/module__main_dispatch_0.spv`                         
     matmul_1k_i8_i32.mlir:8:8: error: failed to materialize conversion for result #0 of operation 'arith.constant' that remained live after conversion                                                                   
       %D = linalg.matmul ins(%lhs, %rhs: tensor<1024x1024xi8>, tensor<1024x1024xi8>)                                                        
            ^                                                                                                                                
     matmul_1k_i8_i32.mlir:8:8: note: see current operation: %1 = "arith.constant"() {value = 1 : index} : () -> index                                                                                                    
     matmul_1k_i8_i32.mlir:8:8: note: see existing live user here: %89:3 = "flow.dispatch.workgroup_count_from_dag_root"(%3, %3, %1) : (index, index, index) -> (index, index, index)
     matmul_1k_i8_i32.mlir:0:0: error: conversion to vm.module failed             
     matmul_1k_i8_i32.mlir:0:0: note: see current operation: 
   
   ```
   
4. Try using a substitution with explicit mapping: ` --iree-hal-substitute-executable=_main_dispatch_0=./replace/module__main_dispatch_0.spv`. This failed with the same error as 3.

@benvanik am I holding this wrong or is .spv substitution not supported yet?

**Comment by benvanik** [comment]
spv should work fine - not sure what the arith thing is - can you post the IR before that error?
(I'll try to repro here after breakfast)

**Comment by benvanik** [comment]
I'll also see if there's an easier route for substituting single variants based on filename, but I'm not sure the filenames are something we want to make stable and it may always require a rename if trying to do the automatic directory-based substitution

**Comment by kuhar** [comment]
> spv should work fine - not sure what the arith thing is - can you post the IR before that error?

Sure, but the repro above is much more concise. (I assume you meant `--mlir-print-ir-after-failure`)
[failure.log](https://github.com/iree-org/iree/files/10768952/failure.log)

**Comment by benvanik** [comment]
oh I think I see the issue - if you substitute an spv file the automatic workgroup count calculation stuff can't then do its thing and doesn't know how to replace the workgroup_count_from_dag_root with what it should be - I'm not sure of a solution to that :/
that's unfortunate - may require some hand editing to make it possible

**Comment by kuhar** [comment]
> I'll also see if there's an easier route for substituting single variants based on filename, but I'm not sure the filenames are something we want to make stable and it may always require a rename if trying to do the automatic directory-based substitution

This doesn't seem like a big deal for me at all, it's very easy to drop the name suffix with a one-liner in bash

**Comment by benvanik** [comment]
ok here's my thought: split the flag in two and support `--iree-hal-substitute-executable-source=` and `--iree-hal-substitute-executable-object=` - the former would do what this already does and the latter would run all of codegen just to produce the workgroup count and then do the swap afterward. If you want to change the workgroup size/count/etc you'd edit the mlir sources and pass one or both flags, and if you just wanted to edit the object without changing any host side stuff you'd just use the latter.

**Comment by benvanik** [comment]
unfortunately the benchmark generation wouldn't work with this route in a single invocation as benchmarks are emitted prior to codegen, but on the compilation of the benchmark you could still swap out the object

**Comment by benvanik** [comment]
PTAL @kuhar - I tested your command sequence (without the directory stuff, because that's harder) and it works now:
`--iree-hal-substitute-executable-object=_main_dispatch_0=D:\\Dev\\iree-tmp\\exe\\bin\\module__main_dispatch_0_vulkan_spirv_fb.spv`

**Comment by kuhar** [comment]
Thanks @benvanik. Now it does compile for me but fails to run on android:
```
+ adb shell 'cd /data/local/tmp/jakub && taskset 80 ./iree-benchmark-module --module=benchmark.vmfb --device=vulkan --function=main --device_allocator=caching '
iree/runtime/src/iree/hal/drivers/vulkan/native_executable.cc:157: UNAVAILABLE; VK_ERROR_INITIALIZATION_FAILED; while invoking native function hal.executable.create; while calling import; 
[ 1]   native hal.executable.create:0 -
[ 0] bytecode module.__init:250 /usr/local/google/home/kubak/iree/i8-benchmarks/ubenchmark/matmul_1k_i8_i32.mlir:8:8
```

**Comment by benvanik** [comment]
are you sure your spv is valid? can you turn on the validation layers?

(there's nothing different once the spv is linked in from the custom_dispatch sample, so if that works I'd expect this to if the spirv is valid)

**Comment by kuhar** [comment]
Hmm, I'll double check, all I did was taking the dumped spir-v and cycling through spirv-cross and glslc...

**Comment by kuhar** [comment]
> Hmm, I'll double check, all I did was taking the dumped spir-v and cycling through spirv-cross and glslc...

I tried something simpler than going to glsl: I manually inserted 4 `OpNop` to the binary and re-assembled it. With the original .spv, the replacement works fine. When I supply the .spv with nops, it crashes. I added a debug print just before `vkCreateShaderModule` and can see that the size of the shader increased by 16 bytes like I expect, so it seems like it does use the substitute shader.

**Comment by benvanik** [comment]
can you dump the data passed to vkCreateShaderModule? if it's the exact bytes you have in your .spv then I'm not sure it's related to this but maybe something else?

**Comment by kuhar** [comment]
> can you dump the data passed to vkCreateShaderModule? if it's the exact bytes you have in your .spv then I'm not sure it's related to this but maybe something else?

I confirmed the shader passed to vulkan is bit-identical to the substitute spv.

**Comment by kuhar** [comment]
I also tried enabling validation layers (added `--vulkan_validation_layers=true` to iree-benchmark-module) and it didn't report anything

**Comment by benvanik** [comment]
what's the diff between substituting and not after SubstituteExecutablesPass runs and does the swap? if there's nothing, then this sounds like spirv related stuff to dig down separately - if there are differences (maybe something changing in the pipeline layout, etc) then it's probably related to this.

**Comment by kuhar** [comment]
Yeah, the IR dumps are identical modulo the contents of `#hal.executable.object`

**Comment by benvanik** [comment]
Cool - something we can work through separately then?

**Review by kuhar — APPROVED** [review]

**Comment by qcolombet** [comment]
Awesome!

**Pull request merged**
