### PR TITLE
don't assert, just fail to match, when |buffer| is not a memref

### PR DESCRIPTION
**Pull request by bjacob**

### CODE REVIEW

**Comment by benvanik** [comment]
out of curiosity what's the buffer type you're seeing? (if it's not memref there may be other issues)

**Comment by bjacob** [comment]
```
(gdb) call buffer.dump()
%c0_i32 = arith.constant 0 : i32
```

**Comment by bjacob** [comment]
ok, let me close that then and debug.

**Comment by bjacob** [comment]
Some more info...

```
// -----// IR Dump Before LowerLinalgMicrokernels //----- //
func.func @matmul_DYNxDYNxi8_times_DYNxDYNxi8_into_DYNxDYNxi32_dispatch_0() {
  %c1 = arith.constant 1 : index
  %c0 = arith.constant 0 : index
  %c0_i32 = arith.constant 0 : i32
  %0 = hal.interface.constant.load[0] : i32
  %1 = hal.interface.constant.load[1] : i32
  %2 = arith.index_cast %0 : i32 to index
  %3 = arith.index_cast %1 : i32 to index
  %4 = hal.interface.binding.subspan set(0) binding(2) type(storage_buffer) offset(%c0) alignment(64) : memref<1x1x8x8xi32>
  memref.assume_alignment %4, 64 : memref<1x1x8x8xi32>
  %5 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) offset(%c0) alignment(64) : memref<1x?x8x4xi8>{%2}
  memref.assume_alignment %5, 64 : memref<1x?x8x4xi8>
  %6 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) offset(%c0) alignment(64) : memref<1x?x8x4xi8>{%3}
  memref.assume_alignment %6, 64 : memref<1x?x8x4xi8>
  %workgroup_id_x = hal.interface.workgroup.id[0] : index
  %workgroup_count_x = hal.interface.workgroup.count[0] : index
  %workgroup_id_y = hal.interface.workgroup.id[1] : index
  %workgroup_count_y = hal.interface.workgroup.count[1] : index
  scf.for %arg0 = %workgroup_id_y to %c1 step %workgroup_count_y {
    scf.for %arg1 = %workgroup_id_x to %c1 step %workgroup_count_x {
      linalg.fill ins(%c0_i32 : i32) outs(%4 : memref<1x1x8x8xi32>)
      linalg.mmt4d {lowering_config = #iree_codegen.lowering_config<tile_sizes = [[1, 1, 0, 0, 0, 0]]>} ins(%5, %6 : memref<1x?x8x4xi8>, memref<1x?x8x4xi8>) outs(%4 : memref<1x1x8x8xi32>)
    }
  }
  return
}

iree-compile: /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/include/mlir/IR/Types.h:263: U mlir::Type::cast() const [U = mlir::MemRefType]: Assertion `isa<U>()' failed.

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff79f4546 in __GI_abort () at abort.c:79
#2  0x00007ffff79f442f in __assert_fail_base (fmt=0x7ffff7b6adf8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0xc5b4dd1 "isa<U>()", 
    file=0xbcebf54 "/usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/include/mlir/IR/Types.h", line=263, function=<optimized out>)
    at assert.c:92
#3  0x00007ffff7a03222 in __GI___assert_fail (assertion=0xc5b4dd1 "isa<U>()", 
    file=0xbcebf54 "/usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/include/mlir/IR/Types.h", line=263, 
    function=0xbcce35b "U mlir::Type::cast() const [U = mlir::MemRefType]") at assert.c:101
#4  0x000000000037be0a in mlir::Type::cast<mlir::MemRefType> (this=0x7fffffff85b0)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/include/mlir/IR/Types.h:263
#5  0x00000000023f4fd7 in mlir::iree_compiler::IREE::VMVX::(anonymous namespace)::computeBufferDescriptor (loc=..., buffer=..., builder=...)
    at /usr/local/google/home/benoitjacob/iree/compiler/src/iree/compiler/Dialect/Modules/VMVX/Transforms/LowerLinalgMicrokernels.cpp:118
#6  0x00000000023fd723 in mlir::iree_compiler::IREE::VMVX::(anonymous namespace)::GenericPipelineDecomposer::beginTransformation (this=0x7fffffff89f8, 
    rewriter=...) at /usr/local/google/home/benoitjacob/iree/compiler/src/iree/compiler/Dialect/Modules/VMVX/Transforms/LowerLinalgMicrokernels.cpp:324
#7  0x00000000023fcec1 in mlir::iree_compiler::IREE::VMVX::(anonymous namespace)::LinalgGenericEmitter::matchAndRewrite (this=0xd7acbb0, op=..., rewriter=...)
    at /usr/local/google/home/benoitjacob/iree/compiler/src/iree/compiler/Dialect/Modules/VMVX/Transforms/LowerLinalgMicrokernels.cpp:410
#8  0x0000000002408343 in mlir::detail::OpOrInterfaceRewritePatternBase<mlir::linalg::LinalgOp>::matchAndRewrite (this=0xd7acbb0, op=0xd79ce60, rewriter=...)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/include/mlir/IR/PatternMatch.h:329
#9  0x0000000007e6507f in mlir::PatternApplicator::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&, llvm::function_ref<bool (mlir::Pattern const&)>, llvm::function_ref<void (mlir::Pattern const&)>, llvm::function_ref<mlir::LogicalResult (mlir::Pattern const&)>) (this=0x7fffffff93e0, op=0xd79ce60, 
    rewriter=..., canApply=..., onFailure=..., onSuccess=...)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Rewrite/PatternApplicator.cpp:201
#10 0x0000000007e04152 in (anonymous namespace)::GreedyPatternRewriteDriver::simplify (this=0x7fffffff93b8, regions=...)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Transforms/Utils/GreedyPatternRewriteDriver.cpp:270
#11 0x0000000007e03788 in mlir::applyPatternsAndFoldGreedily (regions=..., patterns=..., config=...)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Transforms/Utils/GreedyPatternRewriteDriver.cpp:404
#12 0x0000000000388052 in mlir::applyPatternsAndFoldGreedily (op=0xd4532a0, patterns=..., config=...)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/include/mlir/Transforms/GreedyPatternRewriteDriver.h:71
#13 0x0000000002401f66 in mlir::iree_compiler::IREE::VMVX::LowerLinalgMicrokernelsPass::runOnOperation (this=0xd4ac8a0)
    at /usr/local/google/home/benoitjacob/iree/compiler/src/iree/compiler/Dialect/Modules/VMVX/Transforms/LowerLinalgMicrokernels.cpp:794
#14 0x0000000007ecda6a in mlir::detail::OpToOpPassAdaptor::run (pass=0xd4ac8a0, op=0xd4532a0, am=..., verifyPasses=true, parentInitGeneration=1)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:470
#15 0x0000000007ece064 in mlir::detail::OpToOpPassAdaptor::runPipeline (pm=..., op=0xd4532a0, am=..., verifyPasses=true, parentInitGeneration=1, 
    instrumentor=0xd3cdce0, parentInfo=0x7fffffff9ae8) at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:534
#16 0x0000000007ecee8e in mlir::detail::OpToOpPassAdaptor::runOnOperationImpl (this=0xd365750, verifyPasses=true)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:675
#17 0x0000000007ecdd2d in mlir::detail::OpToOpPassAdaptor::runOnOperation (this=0xd365750, verifyPasses=true)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:657
#18 0x0000000007ecda5b in mlir::detail::OpToOpPassAdaptor::run (pass=0xd365750, op=0xd7817b0, am=..., verifyPasses=true, parentInitGeneration=1)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:468
#19 0x0000000007ece064 in mlir::detail::OpToOpPassAdaptor::runPipeline (pm=..., op=0xd7817b0, am=..., verifyPasses=true, parentInitGeneration=1, 
    instrumentor=0xd3cdce0, parentInfo=0x7fffffff9f88) at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:534
#20 0x0000000007ecee8e in mlir::detail::OpToOpPassAdaptor::runOnOperationImpl (this=0xd4297a0, verifyPasses=true)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:675
#21 0x0000000007ecdd2d in mlir::detail::OpToOpPassAdaptor::runOnOperation (this=0xd4297a0, verifyPasses=true)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:657
#22 0x0000000007ecda5b in mlir::detail::OpToOpPassAdaptor::run (pass=0xd4297a0, op=0xd765500, am=..., verifyPasses=true, parentInitGeneration=1)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:468
#23 0x0000000007ece064 in mlir::detail::OpToOpPassAdaptor::runPipeline (pm=..., op=0xd765500, am=..., verifyPasses=true, parentInitGeneration=1, 
    instrumentor=0xd3cdce0, parentInfo=0x7fffffffa8a0) at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:534
#24 0x0000000007ed2321 in mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int)::$_4::operator()(mlir::OpPassManager&, mlir::Operation*) const (this=0x7fffffffa870, pipeline=..., root=0xd765500)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:456
#25 0x0000000007ed20a2 in llvm::function_ref<mlir::LogicalResult (mlir::OpPassManager&, mlir::Operation*)>::callback_fn<mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int)::$_4>(long, mlir::OpPassManager&, mlir::Operation*) (callable=140737488332912, 
    params=0xd765500, params=0xd765500) at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:45
#26 0x00000000025235c1 in llvm::function_ref<mlir::LogicalResult (mlir::OpPassManager&, mlir::Operation*)>::operator()(mlir::OpPassManager&, mlir::Operation*) const (this=0xd3365a0, params=0xd765500, params=0xd765500)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:68
#27 0x0000000002523165 in mlir::Pass::runPipeline (this=0xd336530, pipeline=..., op=0xd765500)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/../mlir/include/mlir/Pass/Pass.h:195
#28 0x0000000003af2c77 in mlir::iree_compiler::IREE::HAL::TranslateTargetExecutableVariantsPass::runOnOperation (this=0xd336530)
    at /usr/local/google/home/benoitjacob/iree/compiler/src/iree/compiler/Dialect/HAL/Transforms/TranslateExecutables.cpp:67
#29 0x0000000007ecda6a in mlir::detail::OpToOpPassAdaptor::run (pass=0xd336530, op=0xd765500, am=..., verifyPasses=true, parentInitGeneration=1)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:470
#30 0x0000000007ece064 in mlir::detail::OpToOpPassAdaptor::runPipeline (pm=..., op=0xd765500, am=..., verifyPasses=true, parentInitGeneration=1, 
    instrumentor=0xd3cdce0, parentInfo=0x7fffffffac88) at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:534
#31 0x0000000007ecee8e in mlir::detail::OpToOpPassAdaptor::runOnOperationImpl (this=0xd4333e0, verifyPasses=true)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:675
#32 0x0000000007ecdd2d in mlir::detail::OpToOpPassAdaptor::runOnOperation (this=0xd4333e0, verifyPasses=true)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:657
#33 0x0000000007ecda5b in mlir::detail::OpToOpPassAdaptor::run (pass=0xd4333e0, op=0xd3f7790, am=..., verifyPasses=true, parentInitGeneration=1)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:468
#34 0x0000000007ece064 in mlir::detail::OpToOpPassAdaptor::runPipeline (pm=..., op=0xd3f7790, am=..., verifyPasses=true, parentInitGeneration=1, 
    instrumentor=0xd3cdce0, parentInfo=0x7fffffffb4c0) at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:534
#35 0x0000000007ed2321 in mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int)::$_4::operator()(mlir::OpPassManager&, mlir::Operation*) const (this=0x7fffffffb490, pipeline=..., root=0xd3f7790)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:456
#36 0x0000000007ed20a2 in llvm::function_ref<mlir::LogicalResult (mlir::OpPassManager&, mlir::Operation*)>::callback_fn<mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int)::$_4>(long, mlir::OpPassManager&, mlir::Operation*) (callable=140737488336016, 
    params=0xd3f7790, params=0xd3f7790) at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:45
#37 0x00000000025235c1 in llvm::function_ref<mlir::LogicalResult (mlir::OpPassManager&, mlir::Operation*)>::operator()(mlir::OpPassManager&, mlir::Operation*) const (this=0xd4447f0, params=0xd3f7790, params=0xd3f7790)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:68
#38 0x0000000002523165 in mlir::Pass::runPipeline (this=0xd444780, pipeline=..., op=0xd3f7790)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/../mlir/include/mlir/Pass/Pass.h:195
#39 0x0000000003af3fad in mlir::iree_compiler::IREE::HAL::TranslateExecutablesPass::runOnOperation (this=0xd444780)
    at /usr/local/google/home/benoitjacob/iree/compiler/src/iree/compiler/Dialect/HAL/Transforms/TranslateExecutables.cpp:121
#40 0x0000000007ecda6a in mlir::detail::OpToOpPassAdaptor::run (pass=0xd444780, op=0xd3f7790, am=..., verifyPasses=true, parentInitGeneration=1)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:470
#41 0x0000000007ece064 in mlir::detail::OpToOpPassAdaptor::runPipeline (pm=..., op=0xd3f7790, am=..., verifyPasses=true, parentInitGeneration=1, 
    instrumentor=0xd3cdce0, parentInfo=0x7fffffffb8a8) at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:534
#42 0x0000000007ecee8e in mlir::detail::OpToOpPassAdaptor::runOnOperationImpl (this=0xd444950, verifyPasses=true)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:675
#43 0x0000000007ecdd2d in mlir::detail::OpToOpPassAdaptor::runOnOperation (this=0xd444950, verifyPasses=true)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:657
#44 0x0000000007ecda5b in mlir::detail::OpToOpPassAdaptor::run (pass=0xd444950, op=0xd394160, am=..., verifyPasses=true, parentInitGeneration=1)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:468
#45 0x0000000007ece064 in mlir::detail::OpToOpPassAdaptor::runPipeline (pm=..., op=0xd394160, am=..., verifyPasses=true, parentInitGeneration=1, 
    instrumentor=0x0, parentInfo=0x0) at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:534
#46 0x0000000007ecf92c in mlir::PassManager::runPasses (this=0x7fffffffc610, op=0xd394160, am=...)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:837
#47 0x0000000007ecf84c in mlir::PassManager::run (this=0x7fffffffc610, op=0xd394160)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:817
#48 0x000000000020e023 in mlir::iree_compiler::runIreecMain(int, char**)::$_2::operator()(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::raw_ostream&) const (this=0x7fffffffc858, ownedBuffer=std::unique_ptr<llvm::MemoryBuffer> = {...}, os=...)
    at /usr/local/google/home/benoitjacob/iree/compiler/src/iree/compiler/Tools/iree_compile_lib.cc:273
#49 0x000000000020d71c in mlir::iree_compiler::runIreecMain (argc=12, argv=0x7fffffffd878)
    at /usr/local/google/home/benoitjacob/iree/compiler/src/iree/compiler/Tools/iree_compile_lib.cc:321
#50 0x000000000020cb92 in main (argc=12, argv=0x7fffffffd878) at /usr/local/google/home/benoitjacob/iree/tools/iree-compile-main.cc:10
```

Again the op triggering this is the `linalg.fill`.

My understanding is that `linalg.fill` is just as "generic" as any other linalg op.   Which means that its generally normal for linalg generic ops to have an operand that's an `arith.constant`, not a buffer.  Given that, I still wonder if the originally proposed patch here is all we can do?

@stellaraccident @benvanik

**Comment by benvanik** [comment]
I'm not familiar with the code, but I'd want `computeBufferDescriptor` to handle anything but buffers - whatever code is calling into that should check to see if it's a buffer instead

**Comment by bjacob** [comment]
ooh but i actually want that fill to be fused into that mmt4d so that the microkernel call that we emit is a "C = A*B", not a "C += A*B".

so at least for that particular instance it's worth seeing if Stella's WIP fusion stuff can take care of that...

**Comment by benvanik** [comment]
I think there may only be a single callsite that can ever pass in anything but a buffer (beginTransformation, what you're hitting above) and it should be checking if the operand it is working on is a buffer or not before calling. It's much more readable to have the single place doing the generic walk say `if (isa buffer) { do buffer stuff } else { don't do buffer stuff}` as a reader will be able to use the context to know that it's doing (today it's not clear the operands may not be buffers, which is what caused this issue!). Changing the function semantics as used by all callers doesn't help that and makes things muddier: computeBufferDescriptor returns None if the descriptor can't be computed but if the logic is inlined all callers need to be aware that None means an error _or_ that the type wasn't a buffer (which is also an error?) if the caller could possibly pass one in.

**Pull request closed without merging**
