### PR TITLE
Add additional macOS CI using GitHub x86_64 runners

### PR DESCRIPTION
**Pull request by GMNGeoffrey**
For now we are duplicating rather than replacing because running on
these appears to be significantly slower than the current setup on our own mac mini. We'd like to see how caching changes that picture. It's
also slightly different CI coverage because these are x86_64 rather
than arm_64.

Part of https://github.com/openxla/iree/issues/12727

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
Thank you Lei! Really appreciate you iterating on this :-)

**Comment by antiagainst** [comment]
> Thank you Lei! Really appreciate you iterating on this :-)

No problem!  It's coming online! :)

**Comment by antiagainst** [comment]
Finally one success run: https://github.com/openxla/iree/actions/runs/4508013248/jobs/7936341562?pr=12725

It takes around 1 hour 10min with a cold start. Much slower than the Mac mini we have (~30min). It's the slowest in all the CI jobs now. Trying to trigger a new run with cache hits to see how much time we'd need to wait.

**Comment by antiagainst** [comment]
Actually given this is a pull request it cannot write cache so cannot verify that.

**Comment by GMNGeoffrey** [comment]
Yeah running it on presubmit was only for testing. Let's put it back to postsubmit and try it out. If you're concerned about the detection on postsubmit being too slow, we could make this a duplicate job instead of a replacement and then see where we want to go based on how fast the cached runs are. Do you remember how fast the cold-start run on our mini took?

**Comment by antiagainst** [comment]
> Yeah running it on presubmit was only for testing. Let's put it back to postsubmit and try it out. If you're concerned about the detection on postsubmit being too slow, we could make this a duplicate job instead of a replacement and then see where we want to go based on how fast the cached runs are. 

SGTM to have duplicated job for now. Let's see how fast the GitHub hosted runners run with cache hits. Let me update the pull request to do that. 

> Do you remember how fast the cold-start run on our mini took?

It takes a bout 30min to start afresh.

**Review by antiagainst — APPROVED** [review]

**Comment by antiagainst** [comment]
@GMNGeoffrey I've marked this as ready for review and give approval to it. Please feel free to double check and land if you don't have more issues.

**Pull request merged**
