### PR TITLE
Experimental distributed Python API

### PR DESCRIPTION
**Pull request by sogartar**
* Add rudimentary non-production distributed Python API

It has functionality to run all ranks through 1 Python function that takes care of starting subprocesses and their runtimes.

* Distributed execution validation

Add functionality that validates distributed StableHLO is producing the same results as non-distributed.

* Add execution time measurement

* Add example to run a simple model across 2 GPUs

### CODE REVIEW

**Review by stellaraccident — CHANGES_REQUESTED** [review]
I'm generally ok with landing this if it helps move distributed execution forward.

However, I'm a bit confused by the CMake plumbing: this *looks* like a pure Python package that can just be `pip install -e experimental/distributed/python` from the source directory, not requiring any build support.

Feel free to push back and tell me the CMake side is needed. Or drop it and it is ok to land.

**Comment by stellaraccident** [comment]
Also, please format the code with black.

**Comment by sogartar** [comment]
> However, I'm a bit confused by the CMake plumbing: this _looks_ like a pure Python package that can just be `pip install -e experimental/distributed/python` from the source directory, not requiring any build support.
> 
> Feel free to push back and tell me the CMake side is needed. Or drop it and it is ok to land.

It is pure Python. I wanted to be consistent with the other packages, but I am happy to delete code. The `setup.py` would be much shorter then.
There is not a single test right now there, but I assumed I will not be able to run CTest against this package like the rest of the source if it was not in CMake.

**Comment by sogartar** [comment]
> Also, please format the code with black.

It was some unrelated file. I rebased the PR. It should not complain now.

**Comment by sogartar** [comment]
@stellaraccident, I made the Python package use only `pyproject.toml` instead of `setup.py` and CMake.

**Review by stellaraccident — APPROVED** [review]

**Pull request merged**
