### PR TITLE
NFC: Unify registration of Util interfaces on external ops

### PR DESCRIPTION
**Pull request by qedawkins**
This decouples linalg from the Util directory and unifies where various Util interfaces are registered under a new directory, `ExternalInterfaces`.

We still need to keep `HoistableTypeInterface` where it is because it generates flow.tensor.bitcast.

### CODE REVIEW

**Comment by benvanik** [comment]
Not sure I like coupling more linalg and such into util - is there a reason to have them moved here? (running during flow, etc?)

**Comment by benvanik** [comment]
Ugh I forgot UtilExternalModels already has linalg stuff - hate it, but this is just consolidating there so is good. Can you move the HoistableTypeInterface as well?

**Comment by qedawkins** [comment]
> Not sure I like coupling more linalg and such into util - is there a reason to have them moved here? (running during flow, etc?)

We have to register these interfaces on linalg somewhere; same with the other external interfaces in Util I assume. There is nothing Flow/GlobalOptimization specific in these interfaces, so it seems cleaner to me to register with the other Util interfaces. If you want we can decouple linalg entirely from Util and have a separate `Interfaces` directory next to `Dialects/Codegen/etc.` maybe.

**Comment by benvanik** [comment]
yeah, probably want to have that dir - right now any change to anything upstream requires a near full rebuild of the compiler as every other dialect/passes/etc depends on util transitively - the fewer deps we have in it the better. Ideally only the init_whatever files we have at the leaf pull in and register the interfaces. Something for future cleanup.

**Comment by qedawkins** [comment]
> Ugh I forgot UtilExternalModels already has linalg stuff - hate it, but this is just consolidating there so is good. Can you move the HoistableTypeInterface as well?

`HoistableTypeInterface` needs `tensor.reinterpret_cast`. Right now we have to generate a `flow.bitcast` to avoid trying to store dense constants of `i4` values. It would be nice to retire that bitcasting pattern entirely (maybe force the use of parameters for sub-byte types at this level and then allow inlining after flow, at which point we introduce the bitcasts?)

**Comment by qedawkins** [comment]
Also regarding `tensor.reinterpret_cast`, I took a look at what it would take, and I would expect we'd get push back if the op doesn't have a full lowering path in-tree. So looking at memref, there is `memref.reinterpret_cast`, but it doesn't allow changing the element type of the memref: https://mlir.llvm.org/docs/Dialects/MemRef/#memrefreinterpret_cast-memrefreinterpretcastop

**Comment by qedawkins** [comment]
> yeah, probably want to have that dir - right now any change to anything upstream requires a near full rebuild of the compiler as every other dialect/passes/etc depends on util transitively - the fewer deps we have in it the better. Ideally only the init_whatever files we have at the leaf pull in and register the interfaces. Something for future cleanup.

Makes sense, let me add a TODO for that as a follow up.

**Comment by benvanik** [comment]
yeah, they're weird about stuff
if the hoisting of tensors depends on flow stuff, then flow would probably be the right place for it to be registered (it's only possible to hoist if flow exists, so users linking in flow would be the ones to get the impl)

**Comment by qedawkins** [comment]
> yeah, probably want to have that dir - right now any change to anything upstream requires a near full rebuild of the compiler as every other dialect/passes/etc depends on util transitively - the fewer deps we have in it the better. Ideally only the init_whatever files we have at the leaf pull in and register the interfaces. Something for future cleanup.

ok I just went ahead and moved it.

**Review by benvanik — APPROVED** [review]

**Pull request merged**
