### PR TITLE
Add Intel ARC A770 and Nvidia Pascal Vulkan Target triples

### PR DESCRIPTION
**Pull request by powderluv**
This allows IREE vulkan to run on Pascal and ARC.

### CODE REVIEW

**Review by antiagainst — CHANGES_REQUESTED** [review]
Could you add tests to `compiler/src/iree/compiler/Dialect/Vulkan/Utils/test/target_env_conversion.mlir`?

**Comment by powderluv** [comment]
yes. How do I invoke the test ?

**Comment by antiagainst** [comment]
> yes. How do I invoke the test ?

It's compiler LIT test. So doing what the `// RUN` lines said there, with `iree-opt | FileCheck` like for existing cases.

**Comment by nithinsubbiah** [comment]
@antiagainst is there anything else needed to land this patch? I'm guessing the lit tests added in this patch cover the added targets but please let me know if I overlooked something, thanks!

edit: just noticed CI (test_gpu) failure, will fix it

**Comment by antiagainst** [comment]
Yeah. We need to fix the test to be able to land.

**Comment by antiagainst** [comment]
Done via https://github.com/openxla/iree/pull/12911.

**Pull request closed without merging**
