### PR TITLE
Add `iree-dump-parameters` to test `tools = []`.

### PR DESCRIPTION
**Pull request by ScottTodd**
ci-exactly: build_test_all_bazel

### CODE REVIEW

**Review by benvanik — APPROVED** [review]

**Comment by ScottTodd** [comment]
fyi @stellaraccident in case you were looking at this too. I don't have Bazel set up on my dev machine right now, so trying to fix the failure at head

**Comment by benvanik** [comment]
ah we'll need this in the cmakelists.txt too - I forgot that

**Comment by ScottTodd** [comment]
> ah we'll need this in the cmakelists.txt too - I forgot that

Indeed. Now why didn't the lint check fail?

https://github.com/openxla/iree/actions/runs/6751277450/job/18355084516?pr=15416#step:3:751
```
Processing tools/test
  tools/test/CMakeLists.txt required no update
0 CMakeLists.txt files were updated, 1 were skipped, and 1 required no change.
```

local:
```
D:\dev\projects\iree (bazel-fix-parameters)
λ python .\build_tools\bazel_to_cmake\bazel_to_cmake.py
Using repo root D:\dev\projects\iree
Converting directory tree rooted at: D:\dev\projects\iree\compiler
0 CMakeLists.txt files were updated, 10 were skipped, and 204 required no change.
Converting directory tree rooted at: D:\dev\projects\iree\runtime
0 CMakeLists.txt files were updated, 16 were skipped, and 57 required no change.
Converting directory tree rooted at: D:\dev\projects\iree\samples
0 CMakeLists.txt files were updated, 2 were skipped, and 4 required no change.
Converting directory tree rooted at: D:\dev\projects\iree\tests
0 CMakeLists.txt files were updated, 0 were skipped, and 16 required no change.
Converting directory tree rooted at: D:\dev\projects\iree\tools
1 CMakeLists.txt files were updated, 1 were skipped, and 0 required no change.
```

**Comment by ScottTodd** [comment]
Not sure why the lint check failed. Going to just let the Bazel CI run and then merge. Trusting the CMake build :P

**Comment by ScottTodd** [comment]
Oh wait, https://github.com/openxla/iree/commit/cbe57993986207547307497b6d4e1558557308a1 has this fix already. Reverting this PR.

**Pull request closed without merging**
