### PR TITLE
Add some line breaks in package index

### PR DESCRIPTION
**Pull request by silvasean**
This makes scanning it visually a bit nicer.

### CODE REVIEW

**Comment by silvasean** [comment]
Here is the Torch-MLIR's package index for reference: https://llvm.github.io/torch-mlir/package-index/

**Comment by GMNGeoffrey** [comment]
What's the use case for scanning visually? I hadn't expected that to be a thing

**Comment by silvasean** [comment]
> What's the use case for scanning visually? I hadn't expected that to be a thing

A simple example would be to see which packages are even available on the site, or which Python versions, etc.

**Comment by GMNGeoffrey** [comment]
Ok. We should really make a proper index for these things #9532

**Pull request merged**
