### PR TITLE
[ROCM] Add flag to enable GlobalISel

### PR DESCRIPTION
**Pull request by qedawkins**
There are observed correctness issues related to SelectionDAG. This adds a flag to switch to GlobalISel and defaults it to true.

### CODE REVIEW

**Comment by nirvedhmeshram** [comment]
Thanks! I started a e2e onnx suite test for this PR here https://github.com/nod-ai/SHARK-TestSuite/actions/runs/11561174652

**Review by MaheshRavishankar — APPROVED** [review]
Cool! This is useful!

**Comment by Groverkss** [comment]
Not blocking, but curious how sdxl perf looks like after this

**Comment by qedawkins** [comment]
Looks like they aren't even running based on CI...

There are some issues to triage before we can turn this on so I'm going to land this flag off by default first and then we can try flipping it once it's ready

**Pull request merged**
