### PR TITLE
Rename CompileSpec and RunSpec to clear names

### PR DESCRIPTION
**Pull request by pzread**
Drop the names CompileSpec/RunSpec and use more descriptive names.

### CODE REVIEW

**Review by GMNGeoffrey — COMMENTED** [review]
Hmmm I didn't think spec vis config was confusing. IMO they're basically synonymous in this case, with spec having a bit more of a declarative connotation, perhaps. My confusion was rather around the multiple things called "run config". I think calling it `ModuleRunConfig` doesn't help much because IREE runs modules and I think the inputs we're getting are not necessarily referred to as modules. We could go with `ModelRunConfig`, although the fact that it's a model is kind of an irrelevant detail (we could be executing any program here, even though we're currently focused on ML models). e2e is super overloaded, but `E2EModelRunConfig` seems clearer to me.

At the risk of anchoring on something that's kind of an implementation detail, we could use VMFBRun(Spec|Config) or IREERun(Spec|Config) for the part that's only specifying how IREE should execute a compiled artifact. Compile config is clear (for now). We could change one of the "run" to "execution", though I'm not actually sure whether I would call the end-to-end thing or just the bit that the IREE runtime does "execution". I guess I just used "execute a compiled artifact" in the sentence above, so perhaps that's the one that feels right :-D At least having them have different names might make reading easier.

So I guess my proposal is:
`E2EModelRunConfig` = `CompileConfig` + `VMFBExecutionConfig`

@ScottTodd any thoughts?

**Comment by ScottTodd** [comment]
> Hmmm I didn't think spec vis config was confusing. IMO they're basically synonymous in this case, with spec having a bit more of a declarative connotation, perhaps. 

Agreed.

> So I guess my proposal is: `E2EModelRunConfig` = `CompileConfig` + `VMFBExecutionConfig`
> 
> @ScottTodd any thoughts?

Those names make sense to me, as do the proposed names in this PR.

How about picking names that just match what tools they are associated with? `CompileAndRunConfig` = `IREECompileConfig` + `IREERunModuleConfig`?

**Comment by GMNGeoffrey** [comment]
> How about picking names that just match what tools they are associated with? `CompileAndRunConfig` = `IREECompileConfig` + `IREERunModuleConfig`?

But `And` in the name is so gross :-P

**Comment by pzread** [comment]
Makes sense to me. Use VMFBExecutionConfig for RunConfig and E2EModelRunConfig for RunSpec.

I still rename CompileSpec to ModelCompileConfig since I want to remove the term "Spec" here.

**Review by GMNGeoffrey — APPROVED** [review]
This looks clearer to me. I think Scott's suggestion of just using "and" isn't the worst though (despitem my protestations). Up to you, unless Scott has strong feelings :-)

**Comment by pzread** [comment]
I was trying to find a better name to differentiate `compile_config` and `model_compile_config`, but have no idea right now. Merge this change first.

**Pull request merged**
