### PR TITLE
Revert "[LLVMGPU][ROCm] Add MFMA_F32_16x16x4_F32 instruction"

### PR DESCRIPTION
**Pull request by ScottTodd**
Reverts iree-org/iree#17847

This broke SDXL rocm pipeline tests on mi300, see https://github.com/iree-org/iree/pull/17847#issuecomment-2226327936. The tests aren't showing error messages (`root:benchmark_sdxl_rocm.py:31 Command failed with error: b''`) so I can't easily tell what the issue is, https://github.com/nod-ai/SHARK-TestSuite/issues/286 is filed to improve the situation there.

### CODE REVIEW

**Review by kuhar — APPROVED** [review]

**Comment by ScottTodd** [comment]
Going to see if I can get logs locally while the CI sanity check runs on this.

**Comment by ScottTodd** [comment]
Hmm... seems like compilation succeeded but benchmarking failed. Possibly a runtime error from the driver if unsupported instructions were included or something. I don't have an easy way to check right now.

**Comment by pashu123** [comment]
@ScottTodd Do you have instruction to repro this?

**Comment by ScottTodd** [comment]
> @ScottTodd Do you have instruction to repro this?

The logs should (ideally) provide enough info: https://github.com/iree-org/iree/actions/runs/9911235296/job/27383808262#step:16:46

`INFO     root:benchmark_sdxl_rocm.py:25 ('Exec:', 'iree-compile /home/esaimana/actions-runner/_work/iree/iree/SHARK-TestSuite/iree_tests/benchmarks/sdxl/sdxl_pipeline_bench_f16.mlir --iree-hal-target-backends=rocm --iree-rocm-target-chip=gfx942 --iree-global-opt-propagate-transposes=true --iree-codegen-llvmgpu-use-vector-distribution --iree-codegen-gpu-native-math-precision=true --iree-rocm-waves-per-eu=2 --iree-opt-outer-dim-concat=true --iree-llvmgpu-enable-prefetch -o /home/esaimana/actions-runner/_work/iree/iree/SHARK-TestSuite/iree_tests/benchmarks/sdxl/sdxl_full_pipeline_fp16_rocm.vmfb')`
`INFO     root:benchmark_sdxl_rocm.py:25 ('Exec:', 'iree-benchmark-module --device=hip://0 --device_allocator=caching --module=/home/esaimana/actions-runner/_work/iree/iree/SHARK-TestSuite/iree_tests/pytorch/models/sdxl-prompt-encoder-tank/model_gpu_rocm_real_weights.vmfb --parameters=model=/home/esaimana/actions-runner/_work/iree/iree/SHARK-TestSuite/iree_tests/pytorch/models/sdxl-prompt-encoder-tank/real_weights.irpa --module=/home/esaimana/actions-runner/_work/iree/iree/SHARK-TestSuite/iree_tests/pytorch/models/sdxl-scheduled-unet-3-tank/model_gpu_rocm_real_weights.vmfb --parameters=model=/home/esaimana/actions-runner/_work/iree/iree/SHARK-TestSuite/iree_tests/pytorch/models/sdxl-scheduled-unet-3-tank/real_weights.irpa --module=/home/esaimana/actions-runner/_work/iree/iree/SHARK-TestSuite/iree_tests/pytorch/models/sdxl-vae-decode-tank/model_gpu_rocm_real_weights.vmfb --parameters=model=/home/esaimana/actions-runner/_work/iree/iree/SHARK-TestSuite/iree_tests/pytorch/models/sdxl-vae-decode-tank/real_weights.irpa --module=/home/esaimana/actions-runner/_work/iree/iree/SHARK-TestSuite/iree_tests/benchmarks/sdxl/sdxl_full_pipeline_fp16_rocm.vmfb --function=tokens_to_image --input=1x4x128x128xf16 --input=1xf16 --input=1x64xi64 --input=1x64xi64 --input=1x64xi64 --input=1x64xi64 --benchmark_repetitions=10 --benchmark_min_warmup_time=3.0')`

Source files might be split between https://github.com/nod-ai/SHARK-TestSuite/tree/4486c44a3d9e61dd20317fe1d23be71ff1610f32/iree_tests/benchmarks/sdxl and https://github.com/nod-ai/SHARK-TestSuite/tree/4486c44a3d9e61dd20317fe1d23be71ff1610f32/iree_tests/pytorch/models

**Comment by ScottTodd** [comment]
I was also planning on fixing the script to print the right error logs and then getting a CI run with that PR again to check that logs appear.

**Comment by ScottTodd** [comment]
Trying to get more info with https://github.com/iree-org/iree/pull/17907

**Comment by ScottTodd** [comment]
https://github.com/iree-org/iree/actions/runs/9944277339/job/27470515222?pr=17907#step:7:171
```
popenargs = (['iree-run-module', '--device=hip', '--module=/home/esaimana/iree_tests_cache/artifacts/sdxl_unet/model.rocm_gfx942.v...', '--module=/home/esaimana/iree_tests_cache/artifacts/sdxl_unet/sdxl_unet_pipeline_bench_f16.rocm_gfx942.vmfb', ...],)
kwargs = {'cwd': PosixPath('/home/esaimana/iree_tests_cache/artifacts/sdxl_unet'), 'stderr': -1, 'stdout': -1}
process = <Popen: returncode: 1 args: ['iree-run-module', '--device=hip', '--module=/h...>
stdout = b''
stderr = b"iree/runtime/src/iree/hal/drivers/hip/native_executable.c:186: INTERNAL; HIP driver error 'hipErrorNoBinaryForGpu' (...e/stable_diffusion_xl_base_1_0_PNDM_64_1024x1024_fp16_unet_3.mlir:1717:10; creating VM context; creating run context\n"
```

**Pull request merged**
