### PR TITLE
[StableHLO] Migrate samples to StableHLO

### LINKED ISSUE #13869: [StableHLO] Port mhlo tests to stablehlo
There are a lot of existing non-mhlo specific tests in the source tree that need to be ported to operate on stablehlo before we can drop mhlo input conversion support:

```
➜ ~/iree/iree git:(main) 
$ rg '=mhlo[^_]' --files-with-matches
```

-  [x] experimental/web/sample_dynamic/build_sample.sh
-  [x] experimental/web/sample_static/build_sample.sh
-  [x] samples/colab/edge_detection.ipynb
-  [x] samples/colab/mnist_training.ipynb
-  [x] samples/dynamic_shapes/test.sh
-  [x] samples/dynamic_shapes/README.md
-  [x] samples/models/mnist.mlir
-  [x] samples/variables_and_state/variables_and_state.ipynb
-  [x] samples/vision_inference/README.md
-  [x] tests/e2e/models/BUILD.bazel
-  [x] tests/e2e/models/CMakeLists.txt
-  [x] tests/e2e/models/collatz.mlir
-  [x] tests/e2e/models/edge_detection.mlir
-  [x] tests/e2e/models/fragment_000.mlir
-  [x] tests/e2e/models/fullyconnected.mlir
-  [x] tests/e2e/models/mnist_fake_weights.mlir
-  [x] tests/e2e/models/resnet50_fake_weights.mlir
-  [x] tests/e2e/models/unidirectional_lstm.mlir
-  [x] tests/e2e/regression/BUILD.bazel
-  [x] tests/e2e/regression/CMakeLists.txt
-  [x] tests/e2e/regression/globals_ml_program.mlir
-  [x] tests/e2e/regression/trace_dispatch_tensors.mlir
-  [x] tests/e2e/vulkan_specific/BUILD.bazel
-  [x] tests/e2e/vulkan_specific/CMakeLists.txt
~~-  [ ] tests/e2e/xla_ops/BUILD.bazel~~
~~-  [ ] tests/e2e/xla_ops/CMakeLists.txt~~
-  [x] tests/microbenchmarks/CMakeLists.txt

There should be some semi-mechanical way to convert mhlo to stablehlo but do not run any other passes.

Parent issue: https://github.com/openxla/iree/issues/12678

### PR DESCRIPTION
**Pull request by kuhar**
Tested by running all notebooks locally.

The mnist model was converted using
`iree-opt --iree-convert-mhlo-to-stablehlo`.

Fixes: https://github.com/openxla/iree/issues/13869

### CODE REVIEW

**Comment by kuhar** [comment]
Seems like editing a few strings in the notebooks also caused them to be re-serialized in equivalent but different format. Is this fine or should I redo these modifications with some plain text editor? Not sure what the best practices for working with notebooks are.

**Comment by benvanik** [comment]
@ScottTodd would know more, but I suspect it's where you ran it? did you use colab? (I see vscode things in there - maybe colab now adds those?)

**Comment by kuhar** [comment]
Yeah I edited those in vscode but I didn't execute them there, so they have the previous contents.

**Comment by kuhar** [comment]
Rebase and update experimental samples

**Comment by ScottTodd** [comment]
> Seems like editing a few strings in the notebooks also caused them to be re-serialized in equivalent but different format. Is this fine or should I redo these modifications with some plain text editor? Not sure what the best practices for working with notebooks are.

I would recommend dropping the metadata and output changes from this PR, yes.

---

The best supported (but also inconvenient) way to edit is in Colab, as documented here: https://github.com/openxla/iree/tree/main/samples/colab#working-with-github

For simple text replacements like these, you can edit in VSCode (open with text editor) and then either
A) Save without formatting
B) Save with formatting and then only git commit the relevant changes (ignore metadata changes, newlines, etc.). 

Open with text editor:
image

Here's how I pick which lines to commit in `git gui`:
image

**Comment by kuhar** [comment]
Thanks @ScottTodd, I used the text editor mode to edit them without reserializing whole notebooks.

**Review by ScottTodd — APPROVED** [review]

**Pull request merged**
