### PR TITLE
[flow] enable reduction+broadcast+elementwise by default

### PR DESCRIPTION
**Pull request by okkwon**

### CODE REVIEW

**Comment by okkwon** [comment]
I still get the same failure for CUDA: check_cuda_cuda_bert_encoder_unrolled_fake_weights. @ThomasRaoux Please take a look.

I also found new failure for vulkan, related to dynamic dims. (This is new. Looking into it.)

**Comment by benvanik** [comment]
Are these regressions real? (first I've really seen of this report so I'm not sure how much to trust it yet, but it looks awesome!)
image

**Comment by okkwon** [comment]
@pzread what is the total dispatch size? Do we have "number of dispatches", which is static information from the compiler?

**Comment by okkwon** [comment]
I was able to reproduce the vulkan failure and created an issue:
https://github.com/iree-org/iree/issues/9802

**Comment by benvanik** [comment]
It's final machine code binary size - so this PR likely triggers some nasty unrolling that massively bloats the binaries (and thus also takes much longer to compile). I don't think it's the PR's fault, but we can't land it until we figure out how to not regress. Maybe @dcaballe's recent changes to LLVM unrolling will help?

**Comment by benvanik** [comment]
(massive kudos to @pzread - we've had regressions like this in the past we haven't noticed until it was too late!)

**Comment by okkwon** [comment]
Cool. Yes, we should investigate and confirm that. The nasty unrolling might have improved the perf.

**Comment by benvanik** [comment]
It looks like the reported latencies are within the noise so I think it's mostly a wash but looking at some traces would be useful. Our (previous?) reliance on the LLVM autovectorizer/unrolling could trigger these pathologically bad cases - at some point you unroll so much your inner loop doesn't fit in I$ and you get slower! The fusion this PR does should reduce code size (as we have fewer dispatches with the per-dispatch overhead in the binary) so I think it'll be a good change regardless of performance impact if we can reel in whatever is causing the explosion and reap the binary size improvements.

**Comment by okkwon** [comment]
The improvement in the latency is real. @hanhanW also measured. I am wondering if the improvement is coming from the unrolling or not, since the CPU side may have less impact from the lower number of dispatches.

**Comment by benvanik** [comment]
Is it an improvement not tracked in the benchmarks? (I'm going off of the posts above, which show as many regressions as improvements of the same 1-10% magnitude)

**Comment by dcaballe** [comment]
> Maybe @dcaballe's recent changes to LLVM unrolling will help?

We disabled LLVM vectorizers by default (https://github.com/iree-org/iree/pull/9642). If a loop is not vectorized in MLIR and it's not in LLVM, it might be more aggressively unrolled. You could try enabling the vectorizers again and see what happens.

LLVM unrolling is still enabled by default since disabling it leads to significant regressions. You can try disabling it and see what happens (https://github.com/iree-org/iree/pull/9658).

> (massive kudos to @pzread - we've had regressions like this in the past we haven't noticed until it was too late!)

+1! I'm super excited about this new feature!

**Comment by hanhanW** [comment]
The regression about compilation time and binary sizes could be real. I image that the total number of dispatches are less, but the kind of dispatches are more. E.g.,, we could only have `matmul_1 + elem_1` case w/o the flag on. But have new `matmul_1 + elem_2` w/ the flag on. In the context, the compilation time and binary sizes could get increased because we have more heavy dispatches to compile.

**Comment by hanhanW** [comment]
> Is it an improvement not tracked in the benchmarks? (I'm going off of the posts above, which show as many regressions as improvements of the same 1-10% magnitude)

It's tracked in the benchmarks. See

image

**Comment by okkwon** [comment]
The dynamic shape case is disabled for now since Vulkan needs more work to support it. (#9802)

**Comment by ThomasRaoux** [comment]
Could we add some execution tests for the corner cases we identified in e2e/regression? That would make me feel more confident as I'm not convinced all the backends have a robust handling of such dispatch regions. What do you think?

**Comment by okkwon** [comment]
Sounds good.

**Comment by okkwon** [comment]
Created https://github.com/iree-org/iree/issues/9938 for adding e2e tests.

**Review by ThomasRaoux — APPROVED** [review]

**Comment by MaheshRavishankar** [comment]
Sorry, I didnt comment on this for a while. But wasnt sure if the increase in compilation time and dispatch sizes are justified. Would be good to triage the cause of those two.

**Comment by okkwon** [comment]
Oh. Good point. I will revert the flag again until we get some good understanding about them.

**Comment by MaheshRavishankar** [comment]
Eh, its in, so unless someone else objects, I dont think it needs to be reverted. But would be good to triage to know if it should be reverted.

**Comment by ThomasRaoux** [comment]
My guess is that the problem is that the broadcasted dimension is not being tiled and end up being vectorized and fully unrolled which generates a large amount of code.
We should fix it (assuming this is the problem) rather sooner than later but if it doesn't break anything it probably doesn't require a revert.

**Comment by pzread** [comment]
Not sure why, but the dispatch size on the merge run looks fine: 65088->65904 bytes
https://perf.iree.dev/serie?IREE?MiniLML12H384Uncased%20%5Bint32%5D%20(TF)%20CPU-x86_64-CascadeLake%20full-inference%2Cdefault-flags%20%5Bcompilation%3Amodule%3Acomponent-size%3Atotal-dispatch-size%5D

**Comment by okkwon** [comment]
Also, the compilation time seems also in the range of noise. https://perf.iree.dev/serie?IREE?MiniLML12H384Uncased%20%5Bint32%5D%20(TF)%20CPU-x86_64-CascadeLake%20full-inference%2Cdefault-flags%20%5Bcompilation%3Amodule%3Acompilation-time%5D

**Comment by okkwon** [comment]
Not much to triage here based on the latest perf run. I won't revert the change. I am going to add more small e2e tests which might help identify the issue later.

**Comment by pzread** [comment]
I noticed that the MiniLM latency on CUDA is doubled with this change. Is that expected?
https://perf.iree.dev/serie?IREE?MiniLML12H384Uncased%20%5Bint32%5D%20(TF)%20full-inference%2Cdefault-flags%20with%20IREE-CUDA%20%40%20GCP-a2-highgpu-1g%20(GPU-NVIDIA-A100-SXM4-40GB)

**Comment by MaheshRavishankar** [comment]
huh, I dont think it is expected. Maybe it needed some upstream fixes w.r.t CUDA handling reductions that might be needed

**Comment by okkwon** [comment]
@ThomasRaoux do you have an idea? I believe the CUDA path was tested with the option on.

**Comment by ThomasRaoux** [comment]
Yes I had tested the model from Nod. Is it the same one? Something must have changed. @pzread how can we get the mlir for this?

**Comment by pzread** [comment]
All artifacts can be found here: https://buildkite.com/iree/iree-benchmark-linux/builds/963

Imported MLIR is in this tgz: https://buildkite.com/organizations/iree/pipelines/iree-benchmark-linux/builds/963/jobs/018264b4-09e0-4154-82f4-d60090c9b882/artifacts/018264d2-3d46-456b-bb0d-6e8dc209939f (`build-targets/linux-x86_64/benchmark_suites/TF/minilm-l12-h384-uncased-tf-model.mlir`)

Compiled CUDA vmfb module is in this tgz: https://buildkite.com/organizations/iree/pipelines/iree-benchmark-linux/builds/963/jobs/018264b4-09e0-4154-82f4-d60090c9b882/artifacts/018264d2-3d45-430e-aa8a-a80df1e97aa2

**Comment by pzread** [comment]
Here is the command that the benchmark ran with:
```
taskset 0xFF /var/lib/buildkite-agent/builds/gcp-buildkite-bench-cuda-a100-1/iree/iree-benchmark-linux/build-targets/linux-cuda/tools/iree-benchmark-module --module_file=../../vmfb/minilm-l12-h384-uncased-tf-model.mlir-0876e46c6fb410aee345a41906f446a6.vmfb --entry_function=predict --function_input=1x512xi32 --function_input=1x512xi32 --function_input=1x512xi32  --device=cuda://0 --time_unit=ns
```

**Comment by ThomasRaoux** [comment]
Thanks @pzread! I'm looking at it.

**Comment by ThomasRaoux** [comment]
I see the problem, one transformation is somehow missing. I'll send a patch to fix it

**Comment by ThomasRaoux** [comment]
Should be fixed by:
https://github.com/iree-org/iree/pull/10010

**Comment by ThomasRaoux** [comment]
Looks like the big increase went down but the perf are still slower than before the change. It looks like the integrate may also have caused some perf problem. I'll try to debug it on monday

**Comment by MaheshRavishankar** [comment]
It does look like integrate caused a regression (which is interesting since this integrate was literally no changes to IREE itself, first time I have seen that :P ). Looking through the list of LLVM commits https://github.com/iree-org/iree-llvm-fork/compare/8ae4b985e710fb51a4e01df1cba4df6e64ac1bb3...58526b2d2be932e893218857cc47a16fb05cf1c0 nothing stands out.

**Comment by ThomasRaoux** [comment]
I compared the vmfb binary before and after the second regression and they are identical so this seems like an environment issue. I had seen that on gcp before. I restarted the VM used for benchmarking and in the latest run we are faster than before Okwan’s change so we do the expected speed up. 

So everything should be solved at this point.

**Pull request merged**
