### PR TITLE
[Codegen] Register AMDGPU transform ops to transform interpreter

### PR DESCRIPTION
**Pull request by Groverkss**

### CODE REVIEW

**Review by qedawkins — APPROVED** [review]

**Review by qedawkins — CHANGES_REQUESTED** [review]
wait, does `amdgpu::createOptimizeSharedMemory` depend on transform dialect ops?

**Comment by Groverkss** [comment]
> wait, does `amdgpu::createOptimizeSharedMemory` depends on transform dialect ops?

There is a transform dialect op for this as well as a pass. I could use either, but going with transform op for now

**Review by qedawkins — APPROVED** [review]
ok I checked and it's fine. Add to the PR description that this also changes the pass used for avoiding bank conflicts.

**Comment by Groverkss** [comment]
> ok I checked and it's fine. Add to the PR description that this also changes the pass used for avoiding bank conflicts.

Oh, that's a mistake. Let me remove that. It has some regressions and I'm going to check those before committing them.

**Pull request merged**
