### PR TITLE
Add `--iree-flow-data-tiling-assume-tile-sizes-divisors-of`

### PR DESCRIPTION
**Pull request by bjacob**
This flag is a short-term workaround for the difficulty of properly solving #11360, const-evaluating `pad + set_encoding`. The difficulty is that the shape is not known at Flow, it is still a `upper_bound_tile_size` op there. See discussion below https://github.com/openxla/iree/issues/11360#issuecomment-1642234084 .

However, a common case can be unblocked: when the shapes are static and are known to be multiples of some power of two that one is willing to assume is divided by any tile size that could result from materialization. Typically at the moment, 16.

So this flag is meant to unblock such users to experiment with constant-evaluating the set_encoding dispatches in their data-tiled matmul workloads. Motivation = https://github.com/nod-ai/SHARK/issues/1589 . However, trying to apply that there currenrly runs into issues, at least the minimized issues filed as https://github.com/openxla/iree/issues/14437 and https://github.com/openxla/iree/issues/14439.  The former is orthogonal to the present PR and gives a different error message than I get on the e2e workload, while the latter depends on this PR and gives the same message as on the e2e workload.

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
Trying to understand the issue here. Looking at the gist from the tagged issue, is the issue that for this sequence

```
  %padded_0 = tensor.pad %cst low[0, 0] high[%7, %8] {
  ^bb0(%arg2: index, %arg3: index):
    tensor.yield %c0_i8 : i8
  } : tensor<100x100xi8> to tensor<?x?xi8>
  %9 = iree_linalg_ext.set_encoding %padded_0 : tensor<?x?xi8> -> tensor<?x?xi8, #iree_linalg_ext.encoding<user = MATMUL_I8I8I32, role = RHS, original_type = tensor<100x100xi8>>>
```

It looks the computation of the "constant frontier" gets blocked somewhere. Can you tell me where?

**Comment by bjacob** [comment]
See https://github.com/openxla/iree/issues/11360#issuecomment-1642234084 - the constant expressions analysis thinks that all of this is a constant, but because the dims are dynamic, some `tensor.dim` end up where they shouldn't and we get a compile error.

**Comment by MaheshRavishankar** [comment]
> See [#11360 (comment)](https://github.com/openxla/iree/issues/11360#issuecomment-1642234084) - the constant expressions analysis thinks that all of this is a constant, but because the dims are dynamic, some `tensor.dim` end up where they shouldn't and we get a compile error.

Ok, ill carry the discussion over there.

**Comment by MaheshRavishankar** [comment]
Irrespective of that... can we just do this for the case where the operands of the `matmul` are constants.. This seems like a pretty heavy hammer.

**Comment by bjacob** [comment]
Converted back to draft. Ordering of next steps:

* https://github.com/openxla/iree/issues/14437 and https://github.com/openxla/iree/issues/14439 need to be resolved first as they block using this in practice.
* Use this, observe some real benefit on e2e workload.
* Then resume the conversation about this PR ; however, in the interim, maybe enough progress will have happened on https://github.com/openxla/iree/issues/11360 that this won't be needed anymore.

**Comment by hanhanW** [comment]
The pass itself is ready without changing the Flow pipeline. I added a lit test and revert the pipeline changes, and think that we can land this to unblock const_eval work.

**Comment by MaheshRavishankar** [comment]
If it isnt too much trouble, could you base your const eval work on top of this PR. I want to see if we can just fix the underlying issue for good before landing some code that we will have to undo quickly. The PR itself looks OK, but just a bit apprehensive w.r.t adding more `flow` level flags.

**Comment by hanhanW** [comment]
Sure. The pass is mainly for generating `set_encoding %cst` ops when they are aligned with `16`. Here is the rest of code: https://github.com/openxla/iree/commit/7560493411ecb1f286c6e1da8e8ffef0b78b887b

I put IR dump and some snippets about what's happening to https://github.com/openxla/iree/issues/11360#issuecomment-1670094543

**Comment by hanhanW** [comment]
We are able to fold set_encoding(constants) now, this is no longer needed. Closing the PR...

**Pull request closed without merging**
