### PR TITLE
[LLVMCPU] Make unpack fusion dispatches select config based on root ops.

### LINKED ISSUE #12135: Remove `iree-codegen-llvm-generic-ops-workgroup-size-for-unpack-op`
This is being introduced in #12134 and shouldn't be needed anymore once work described in comments there is completed.

### LINKED ISSUE #12531: The tiling sizes for unpack ops are wrong for fusion cases
The root cause is that the distribution tiling sizes are not selected for perfect tiling cases. The lowering config is set by only look into unpack ops. This is wrong because there could be transpose variants in consumers. The tiling algorithm is starting from consumer. The tiling sizes could be transposed when pulling the unpack ops. We should interchange the tiling sizes by looking into consumers' indexing maps.

To repro: `iree-opt --pass-pipeline='builtin.module(hal.executable(hal.executable.variant(iree-codegen-tile-and-distribute-to-workgroups)), canonicalize, cse)' ~/repro.mlir`

```
hal.executable private @main_dispatch_27_generic_128x384_dispatch_0_generic_128x384 {
hal.executable.variant public @embedded_elf_x86_64, target = <"llvm-cpu", "embedded-elf-x86_64", {cpu = "generic", cpu_features = ""}> {
  hal.executable.export public @main_dispatch_27_generic_128x384_dispatch_0_generic_128x384 ordinal(0) layout(#hal.pipeline.layout<push_constants = 0, sets = [<0, bindings = [<0, storage_buffer, ReadOnly>, <1, storage_buffer, ReadOnly>, <2, storage_buffer>]>]>) attributes {translation_info = #iree_codegen.translation_info<CPUDataTiling>} {
  ^bb0(%arg0: !hal.device, %arg1: index, %arg2: index):
    %c1 = arith.constant 1 : index
    %0 = affine.apply affine_map<()[s0] -> (s0 ceildiv 16)>()[%arg1]
    %1 = affine.apply affine_map<()[s0] -> (s0 ceildiv 32)>()[%arg2]
    hal.return %1, %0, %c1 : index, index, index
  }
  builtin.module {
    func.func @main_dispatch_27_generic_128x384_dispatch_0_generic_128x384() {
      %c0 = arith.constant 0 : index
      %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<48x4x8x32xf32>>
      %1 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<128xf32>>
      %2 = hal.interface.binding.subspan set(0) binding(2) type(storage_buffer) alignment(64) offset(%c0) : !flow.dispatch.tensor<writeonly:tensor<128x384xf32>>
      %3 = flow.dispatch.tensor.load %0, offsets = [0, 0, 0, 0], sizes = [48, 4, 8, 32], strides = [1, 1, 1, 1] : !flow.dispatch.tensor<readonly:tensor<48x4x8x32xf32>> -> tensor<48x4x8x32xf32>
      %4 = flow.dispatch.tensor.load %1, offsets = [0], sizes = [128], strides = [1] : !flow.dispatch.tensor<readonly:tensor<128xf32>> -> tensor<128xf32>
      %5 = tensor.empty() : tensor<128x384xf32>
      %6 = tensor.empty() : tensor<384x128xf32>
      %unpack = tensor.unpack %3 inner_dims_pos = [0, 1] inner_tiles = [8, 32] into %6 {lowering_config = #iree_codegen.lowering_config<tile_sizes = [[32, 16]]>} : tensor<48x4x8x32xf32> -> tensor<384x128xf32>
      %7 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0)>, affine_map<(d0, d1) -> (d1, d0)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%4, %unpack : tensor<128xf32>, tensor<384x128xf32>) outs(%5 : tensor<128x384xf32>) {
      ^bb0(%in: f32, %in_0: f32, %out: f32):
        %8 = arith.addf %in, %in_0 : f32
        linalg.yield %8 : f32
      } -> tensor<128x384xf32>
      flow.dispatch.tensor.store %7, %2, offsets = [0, 0], sizes = [128, 384], strides = [1, 1] : tensor<128x384xf32> -> !flow.dispatch.tensor<writeonly:tensor<128x384xf32>>
      return
    }
  }
}
}
```

The ideal IR should not have extract_slice op between unpack and generic ops.

### PR DESCRIPTION
**Pull request by hanhanW**
Fixes https://github.com/openxla/iree/issues/12135
Fixes https://github.com/openxla/iree/issues/12531

### CODE REVIEW

**Comment by hanhanW** [comment]
It depends on https://github.com/openxla/iree/pull/12590, please take a look at https://github.com/openxla/iree/pull/12637/commits/273eff347678b8b4021d3cd784ff3828121f6969

@bjacob FYI that the `iree-codegen-llvm-generic-ops-workgroup-size-for-unpack-op` will be removed by the PR. You'll have to switch to `iree-codegen-llvm-generic-ops-workgroup-size` after we land the PR.

**Comment by hanhanW** [comment]
The unpack fusion does not work well with peeling approach. Because there is a tensor.empty() op created. Seems to hit issue https://github.com/openxla/iree/issues/11196

https://gist.githubusercontent.com/hanhanW/6bb2ddff56e11aba7bdad805d1e1fa6c/raw

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
Ill review it after the dependent PR lands. But I thought we would really not need to do anything for unpack fused with consumer... The consumer already has the lowering config and we can use that to tile + fuse, etc. Ill revisit after the diff is a bit cleaner.

**Comment by hanhanW** [comment]
> Ill review it after the dependent PR lands. But I thought we would really not need to do anything for unpack fused with consumer... The consumer already has the lowering config and we can use that to tile + fuse, etc. Ill revisit after the diff is a bit cleaner.

The lowering config is driven by the consumer. We have to adjust tiling sizes to be aligned with inner tile sizes. Otherwise, we'll lead to non-perfect tiling on unpack ops. The tiled unpack ops will become unpack + extract_slice.

**Comment by hanhanW** [comment]
I won't be able to land the PR because it hits unbounded stack allocation. It is actually bounded if we study the IR carefully. Here is the IR after peeling: https://gist.githubusercontent.com/hanhanW/a2cde2c48465d25f73b1859fce7c815e/raw

It creates a tensor.empty op in a peeled loop:

```
%27 = scf.for %arg2 = %21 to %17 step %c8 iter_args(%arg3 = %26) -> (tensor<?x16xi8>) {
%28 = affine.apply affine_map<(d0)[s0] -> (-d0 + s0)>(%arg2)[%17]
%29 = affine.apply affine_map<(d0) -> (d0 floordiv 8)>(%arg2)
%30 = tensor.empty(%28) : tensor<?x8xi32>
  %31 = scf.for %arg4 = %c0 to %c16 step %c8 iter_args(%arg5 = %arg3) -> (tensor<?x16xi8>) {
    %32 = affine.apply affine_map<(d0) -> (d0 floordiv 8)>(%arg4)
    %extracted_slice_0 = tensor.extract_slice %24[%29, %32, 0, 0] [1, 1, 8, 8] [1, 1, 1, 1] : tensor<?x2x8x8xi32> to tensor<1x1x8x8xi32>
    %unpack = tensor.unpack %extracted_slice_0 inner_dims_pos = [0, 1] inner_tiles = [8, 8]
      into %30
```

**Comment by MaheshRavishankar** [comment]
@hanhanW maybe we can disable peeling if there are unpack ops in the dispatch.

**Comment by hanhanW** [comment]
> @hanhanW maybe we can disable peeling if there are unpack ops in the dispatch.

I looked into more details... I found that it does not work well with ConvertToDestinationPassingStyle pass because they are quantized cases. (like the issue we've hit for quantized_matmul + generic). The type mismatch, so we always see a tensor.empty op. There are couple workarounds.

1. We could disable the simplification of for op ranges. This would keep affine_min/max ops, so we still can infer constant bounded sizes.

https://github.com/llvm/llvm-project/blob/11da3de82d35afb8011c7aea42d76bb57d0e23cd/mlir/lib/Dialect/SCF/Transforms/LoopSpecialization.cpp#L183-L195

2. Fallback to non-peeling path. The trade-off is that some ops might not get vectorized because the dim sizes are not divisible by tiling sizes. I do observe that the case in quantized model won't get vectorized.

Testing w/ option two now..

**Comment by hanhanW** [comment]
Looks like we have 5% improvements `MobileBertSquad [int8] (TFLite)` on single-threaded. It looks true to me because we can observe it on both Pixel4 and Pixel6.

**Review by bjacob — APPROVED** [review]

**Comment by bjacob** [comment]
Thank you for solving this!

**Review by MaheshRavishankar — APPROVED** [review]

**Pull request merged**
