### PR TITLE
[LLVMGPU] Convert maximumf/minimumf to max/min for ROCM

### PR DESCRIPTION
**Pull request by nirvedhmeshram**
AMDGPU does not support the former

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
@dcaballe FYI for you regarding the changes upstream for Nan propagation.... Seems like AMDGPU have issues as well.

**Review by MaheshRavishankar — APPROVED** [review]

**Review by kuhar — APPROVED** [review]
This seems like a good workaround for now, until the amdgpu supports these

**Comment by nirvedhmeshram** [comment]
@kuhar @MaheshRavishankar I dont have write access so please merge this when you get the chance after the CI passes

**Comment by kuhar** [comment]
@nirvedhmeshram done

**Pull request merged**
