### PR TITLE
Hotfixes following #13460

### PR DESCRIPTION
**Pull request by bjacob**
* On Windows, compile errors in x86 intrinsics code apparently caused by using AVX512 types in translation units where AVX512 was not enabled, in the bitcode builds i.e. using Clang-on-Windows. Maybe it's stricter than other compilers that have been quietly compiling this code so far (Clang on other OSes, MSVC on Windows).
* On Mac/arm64, CMake build errors caused by not `add_subdirectory` the x86-64 directory, which is now necessary to build bitcode.

### CODE REVIEW

**Comment by bjacob** [comment]
@ScottTodd still getting `Event type 'pull_request' is not allowed on this runner. Aborting workflow.`

**Comment by ScottTodd** [comment]
> @ScottTodd still getting `Event type 'pull_request' is not allowed on this runner. Aborting workflow.`

Ah, I guess it's disabled in some other way then:
```
Run '/Users/antiagainst/actions-runner/runner-root/config/hooks/pre_job.sh'
```
https://github.com/openxla/iree/actions/runs/5027770230/jobs/9017669872?pr=13697#step:2:2
@antiagainst ?

**Comment by bjacob** [comment]
Progress, no more compile error, but running into a linking error (https://github.com/openxla/iree/actions/runs/5027770230/jobs/9017669780):

```
error: linking module flags 'wchar_size': IDs have conflicting values in 'ukernel_bitcode.bc' and 'e2e_matmul_mmt4d_i8_small_ukernel_x86_llvm_cpu_local_task_linked_llvm_cpu'
```

Looks like something about `wchar_t` type on Windows. Going to just disable bitcode on Windows for now.

**Comment by benvanik** [comment]
sgtm - if you file an issue I'll take a look tonight!

**Review by benvanik — APPROVED** [review]

**Comment by benvanik** [comment]
(unless @ScottTodd gets to it first)

**Comment by bjacob** [comment]
Filed #13699.

Crap I also need to disable the e2e tests that were added that would fail due to this bitcode being disabled on Windows. Hang on...

**Comment by bjacob** [comment]
@benvanik @ScottTodd very sorry that this is still not working. The problem is now that bitcode is disabled on Win32, the compiler fails to build as it unconditionally depends on bitcode.

Error:
https://github.com/openxla/iree/actions/runs/5028073724/jobs/9018350012?pr=13700

PR that triggered this Windows CI: https://github.com/openxla/iree/pull/13700

Sorry I'm at EOD here. Feel free to just roll back though this isn't "hard" to hotfix -- just dont have more time.

**Comment by ScottTodd** [comment]
Thanks! I'll start looking at Windows now.

**Review by ScottTodd — CHANGES_REQUESTED** [review]
I sent https://github.com/openxla/iree/pull/13703 with more Windows fixes

**Pull request closed without merging**
