### PR TITLE
WIP: enable transpose fusion to debug mmt4d perf regression

### PR DESCRIPTION
**Pull request by okkwon**
This is not for code review. This is for debugging the perf regression on mmt4d when the transpose fusion is enabled.

### CODE REVIEW

**Comment by bjacob** [comment]
I benchmarked all 2x2=4 combinations of these 2 boolean flags. The benchmark is `MobileBertSquad [int8] (TFLite) 1-thread,big-core,full-inference,experimental-flags with IREE-Dylib`, and the device is Moto Edge x30.  Results:

ensure-inplaceable-consumer | normalize-input-indexing-map | latency (ms)
--- | --- | ---
false | false | 227
true | false | 227    <--- current default
false | true | 598
true | true | 227

So the only combination that performs differently from the default is when BOTH booleans are inverted. And then it's a > 2x slowdown.

**Comment by MaheshRavishankar** [comment]
> I benchmarked all 2x2=4 combinations of these 2 boolean flags. The benchmark is `MobileBertSquad [int8] (TFLite) 1-thread,big-core,full-inference,experimental-flags with IREE-Dylib`, and the device is Moto Edge x30. Results:
> 
> ensure-inplaceable-consumer	normalize-input-indexing-map	latency (ms)
> false	false	227
> true	false	227 <--- current default
> false	true	598
> true	true	227
> So the only combination that performs differently from the default is when BOTH booleans are inverted. And then it's a > 2x slowdown.

Yeah, both are needed for this to take effect. If you drop one, then it goes back to default behavior.

**Comment by bjacob** [comment]
Here is what is going on. When these booleans are flipped, we return `false` [here](https://sourcegraph.com/github.com/google/iree@f3e6772d2249343c87f9d431e12a548db05f9f49/-/blob/compiler/src/iree/compiler/Codegen/LLVMCPU/VectorContractCustomKernels.cpp?L45). This is a helper function checking if a `vector.contract` meets the requirements to be implemented as a specific inline assembly kernel, so when it returns `false`, we don't use the inline assembly kernel and return to default codegen, explaining the performance difference.  The most obvious way that this manifests itself in the resulting binary is that it uses naive `int32x4` SIMD multiplications (`mla`) instead of `int8*int8->int32` dot-product instructions (`sdot`) as in the inline asm kernel that we have for this case.

Why does it return false here? The code is checking if the `vector.contract` has exactly 3 iterators. It expects 2 `parallel` iterators and 1 `reduction` iterator, in no particular order.

But logging shows that instead we get:

```
iteratorTypes.size() = 6, expected 3
dump of the vector.contract:

%47 = vector.contract {indexing_maps = [affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d2, d3, d5)>, affine_map<(d0, d1, d2, d3, d4, d5) -> (d1, d2, d4, d5)>, affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d1, d3, d4)>], iterator_types = ["parallel", "parallel", "reduction", "parallel", "parallel", "reduction"], kind = #vector.kind<add>} %46, %25, %cst : vector<1x32x1x4xi32>, vector<1x32x8x4xi32> into vector<1x1x1x8xi32>
```

So there are 6 iterators here, but 3 of them refer to unit dimensions.

I think what happens is that we were expecting the `vector.contract` to be produced by the [dedicated vectorization pattern](https://sourcegraph.com/github.com/google/iree@f3e6772d2249343c87f9d431e12a548db05f9f49/-/blob/compiler/src/iree/compiler/Codegen/Common/VectorizeMMT4d.cpp?L39) that we had for mmt4d, that was producing `vector.contract` without unit dims, and instead we now seem to be on a generic vectorization pattern.

I think i need a chat with @MaheshRavishankar to decide whether the proper fix is (1) ensure we return to the VectorizeMMT4d pattern or (2) delete VectorizeMMT4d and ensure that the later VectorContractCustomKernels pattern is happy with the unit dims.

I guess (2) would be great, but we did (1) for some specific reasons that revolved around composing with vector-transfer flattening patterns to ensure that we had good codegen for the (otherwise 2D and therefore slow) vector transfers and I dont remember offhand if anything in VectorizeMMt4d is (still) needed to make that happen.

**Comment by MaheshRavishankar** [comment]
> Here is what is going on. When these booleans are flipped, we return `false` [here](https://sourcegraph.com/github.com/google/iree@f3e6772d2249343c87f9d431e12a548db05f9f49/-/blob/compiler/src/iree/compiler/Codegen/LLVMCPU/VectorContractCustomKernels.cpp?L45). This is a helper function checking if a `vector.contract` meets the requirements to be implemented as a specific inline assembly kernel, so when it returns `false`, we don't use the inline assembly kernel and return to default codegen, explaining the performance difference. The most obvious way that this manifests itself in the resulting binary is that it uses naive `int32x4` SIMD multiplications (`mla`) instead of `int8*int8->int32` dot-product instructions (`sdot`) as in the inline asm kernel that we have for this case.
> 
> Why does it return false here? The code is checking if the `vector.contract` has exactly 3 iterators. It expects 2 `parallel` iterators and 1 `reduction` iterator, in no particular order.
> 
> But logging shows that instead we get:
> 
> ```
> iteratorTypes.size() = 6, expected 3
> dump of the vector.contract:
> 
> %47 = vector.contract {indexing_maps = [affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d2, d3, d5)>, affine_map<(d0, d1, d2, d3, d4, d5) -> (d1, d2, d4, d5)>, affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d1, d3, d4)>], iterator_types = ["parallel", "parallel", "reduction", "parallel", "parallel", "reduction"], kind = #vector.kind<add>} %46, %25, %cst : vector<1x32x1x4xi32>, vector<1x32x8x4xi32> into vector<1x1x1x8xi32>
> ```
> 
> So there are 6 iterators here, but 3 of them refer to unit dimensions.
> 
> I think what happens is that we were expecting the `vector.contract` to be produced by the [dedicated vectorization pattern](https://sourcegraph.com/github.com/google/iree@f3e6772d2249343c87f9d431e12a548db05f9f49/-/blob/compiler/src/iree/compiler/Codegen/Common/VectorizeMMT4d.cpp?L39) that we had for mmt4d, that was producing `vector.contract` without unit dims, and instead we now seem to be on a generic vectorization pattern.
> 
> I think i need a chat with @MaheshRavishankar to decide whether the proper fix is (1) ensure we return to the VectorizeMMT4d pattern or (2) delete VectorizeMMT4d and ensure that the later VectorContractCustomKernels pattern is happy with the unit dims.
> 
> I guess (2) would be great, but we did (1) for some specific reasons that revolved around composing with vector-transfer flattening patterns to ensure that we had good codegen for the (otherwise 2D and therefore slow) vector transfers and I dont remember offhand if anything in VectorizeMMt4d is (still) needed to make that happen.

THanks for digging into this. Do you mind sharing a dump of `-mlir-print-ir-after-all` for this example. THat will help connect all the pieces for me.

**Comment by MaheshRavishankar** [comment]
I havent tried this but this IR should reproduce the issue as well

```
func.func %repro(%arg0 : tensor<128x256xf32>, %arg1 : tensor<256x512xf32>) -> tensor<512x128xf32> {
  %cst = arith.constant 0.0 : f32
  %init = linalg.init_tensor [128, 512] : tensor<128x512xf32>
  %fill = linalg.fill ins(%cst : f32) outs(%init : tensor<128x512xf32>) -> tensor<128x512xf32>
  %gemm = linalg.matmul ins(%arg0, %arg1 : tensor<128x256xf32>, tensor<256x512xf32>) outs(%fill : tensor<128x512xf32>) -> tensor<128x512xf32>
  %transpose_init = linalg.init_tensor [512, 128] : tensor<512x128xf32>
  %transpose = linalg.generic { indexing_maps = [affine_map<(d0, d1) -> (d1, d0)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%gemm: tensor<128x512xf32>) outs(%transpose_init : tensor<512x128xf32>) {
    ^bb0(%b0 : f32, %b1 : f32):
      linalg.yield %b0 : f32
    } -> tensor<512x128xf32>
  return %transpose : tensor<512x128xf32>
}
```

**Comment by bjacob** [comment]
https://gist.github.com/bjacob/bc956f6820da35960bd9ef6ce73d7168

**Comment by benvanik** [comment]
Ping on this if it's still relevant.

**Comment by okkwon** [comment]
Closing. Transpose fusion should be covered by the global layout optimizations.

**Pull request closed without merging**
