### PR TITLE
Fix StreamOps lambda function

### PR DESCRIPTION
**Pull request by hcindyl**

### CODE REVIEW

**Review by benvanik — APPROVED** [review]
nice find!

**Comment by hcindyl** [comment]
> nice find!

It's GCC warning's find :)

However, I can't make this test pass correctly 
 https://github.com/openxla/iree/blob/1357afa92aee4d01bcee0b9fc00a1370d63ce68c/compiler/src/iree/compiler/Dialect/Stream/Transforms/test/schedule_allocation.mlir#L529

```
within split at /work/compiler/src/iree/compiler/Dialect/Stream/Transforms/test/schedule_allocation.mlir:511 offset :19:12: error: 'stream.async.call' op function argument type mismatch; expected '!stream.resource<transient>' but callee provides '!stream.resource<*>'
```

Could you please provide a possible fix?

**Comment by hcindyl** [comment]
> > nice find!
> 
> It's GCC warning's find :)
> 
> However, I can't make this test pass correctly
> 
> https://github.com/openxla/iree/blob/1357afa92aee4d01bcee0b9fc00a1370d63ce68c/compiler/src/iree/compiler/Dialect/Stream/Transforms/test/schedule_allocation.mlir#L529
> 
> ```
> within split at /work/compiler/src/iree/compiler/Dialect/Stream/Transforms/test/schedule_allocation.mlir:511 offset :19:12: error: 'stream.async.call' op function argument type mismatch; expected '!stream.resource<transient>' but callee provides '!stream.resource<*>'
> ```
> 
> Could you please provide a possible fix?

Test fixed. :)

**Comment by hcindyl** [comment]
part of https://github.com/openxla/iree/issues/14507

**Review by benvanik — APPROVED** [review]

**Pull request merged**
