### PR TITLE
Bump LLVM to fc7f7260a609b2092260b6a5e867a20cf364808c

### PR DESCRIPTION
**Pull request by nicolasvasilache**
LLVM commit: fc7f7260a609b2092260b6a5e867a20cf364808c
MHLO commit: d70cd274ea4cf31fdc7d29d4cc70e1569acb74d8
TF commit: 4ee381cc670f77c703f59d03da473ac6dfdae58e

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
We probably need to update TF as well (see here https://github.com/iree-org/iree/blob/main/docs/developers/developing_iree/llvm_version_bump.md#strategy-2-sync-everything-to-a-googletensorflow-commit)

**Comment by MaheshRavishankar** [comment]
#9614 cherry picked a commit. Needs to be reflected here.

**Comment by antiagainst** [comment]
> #9614 cherry picked a commit. Needs to be reflected here.

Looks the commit I cherry picked is part of this bump. So you can overwrite that without problem. :)

**Comment by MaheshRavishankar** [comment]
> > #9614 cherry picked a commit. Needs to be reflected here.
> 
> Looks the commit I cherry picked is part of this bump. So you can overwrite that without problem. :)

Awesome! Thanks for confirming!

**Review by MaheshRavishankar — APPROVED** [review]

**Pull request merged**
