### PR TITLE
Migrate to use linalg.transpose op and unify all the pack tests.

### PR DESCRIPTION
**Pull request by hanhanW**
- Use linalg.transpose op instead of linalg.generic op.
- Add `static_` prefix to static test cases.
- Unify the creation of golden values.

### CODE REVIEW

**Review by MaheshRavishankar — APPROVED** [review]
Nice that this works for now. We probably need a generalization pattern in Flow for `linalg.transpose` though....

**Comment by hanhanW** [comment]
> We probably need a generalization pattern in Flow for `linalg.transpose` though....

Yes, it's pretty new, and I found that it works e2e in IREE. I verified that the vectorization works well for the op. We probably have to generalize it into linalg.generic op or ask backends to set proper config and pipeline for it. It's fine for testing for now. :-)

**Comment by MaheshRavishankar** [comment]
> > We probably need a generalization pattern in Flow for `linalg.transpose` though....
> 
> Yes, it's pretty new, and I found that it works e2e in IREE. I verified that the vectorization works well for the op. We probably have to generalize it into linalg.generic op or ask backends to set proper config and pipeline for it. It's fine for testing for now. :-)

If we dont generalize before elementwise op fusion, it will restrict fusion. So that will have an impact...

**Comment by hanhanW** [comment]
> If we dont generalize before elementwise op fusion, it will restrict fusion. So that will have an impact...

I see the point now, thanks!

**Pull request merged**
