### PR TITLE
Re-apply converting TF models using TF Python API.

### LINKED ISSUE #13026: Tracking: Removing the iree-import-tf binary
Rolling forward from a previous attempt and tracking progress here.

* `git revert 922973bc7051d948d9a4f7c9f3faa6ef2269d491` and fixup conflicts
* Draft new PR https://github.com/openxla/iree/pull/13025
* Update model generation in https://github.com/iree-org/iree-samples/blob/main/iree-tf/library/generate_saved_models.py#L53 and/or discover incantation to load existing

### PR DESCRIPTION
**Pull request by stellaraccident**
Revert "Revert "Convert TF models using TF Python API." (#12972)"

This reverts commit 922973bc7051d948d9a4f7c9f3faa6ef2269d491.

Fixes #13026

### CODE REVIEW

**Comment by stellaraccident** [comment]
I may be able to re-enable a bunch of those tests with the newly re-hacked importer. Would like to get a clean baseline first, though.

**Review by mariecwhite — APPROVED** [review]

**Review by jpienaar — APPROVED** [review]
Thanks!

**Comment by ScottTodd** [comment]
The "Regressed Total Artifact Sizes" for EfficientNetV2STF (`164107793 (vs. 86810885, 89.04%↑)`) could be worth looking into. I wonder if that's coming from program structure / import path changes, or something more superficial like debug information.

Similarly, some of the compile time changes are large (+100%, -70% for different programs).

**Comment by jpienaar** [comment]
Sounds good to file tracking bug for that (maybe just the equivalent of debug info eliding pass as you mentioned)

**Comment by stellaraccident** [comment]
I honestly don't think we care about the EfficientNetV2STF case. It is not an inference optimized model on this engine and no one is running it that way. We could theoretically file a bug on the TF team but they are not engaged in this area.

The compile time changes, I expect are down to two things:

* The new path does an abominable amount of string re-encoding (I think ~6x more than the previous on the MLIR assembly). I glanced at these and saw that the overhead scales with the size of the weights in the model, which makes perfect sense given this. It is  fine for something unsupported. (I did stick my fingers in my ears and sing to myself because I have higher standards than this in general)
* We are invoking the TF importer in-process as part of the Python API. For small models/cases, this can have a ~half second advantage because initializing TF is so slow and only happens once. The advantage works against the previous disadvantage.

Again: the team supporting this functionality (StableHLO AOT export for TF) does not consider this a priority, so we are going to minimize time spent.

**Pull request merged**
