### PR TITLE
Switch x86 experimental-flags benchmarks to data tiling + ukernels.

### PR DESCRIPTION
**Pull request by hanhanW**

### CODE REVIEW

**Comment by hanhanW** [comment]
The improvements and regression are as expected, that we've been tracking some time ago. There are constant packing overheads in vision models, so they are slower.

We probably want to look into dispatch size regression for `PersonDetect`. I think it can be a follow-up because we don't actively track the model for x86.

**Comment by MaheshRavishankar** [comment]
Is Bert the only GEMM-based model we have?

**Comment by hanhanW** [comment]
> Is Bert the only GEMM-based model we have?

I'll check tomorrow.  I think Marie knows better about what's been tracking on x86 side.

**Comment by bjacob** [comment]
Depends what you mean by GEMM-based?  Matrix multiplications are easily the majority of the arithmetic in a majority of models. This gist has a breakdown of our TFLite benchmark suite:
https://gist.github.com/bjacob/8d756382f08be143aa174d30bb03c109
While reading it, keep in mind that the 'tosa.conv2d' op, in the case of 1x1 kernel, is a matrix multiplication. So for example, in this part of the gist, you can see that this model is a majority of matmuls too:

```
TOSA ops in model_0e466f69-91d6-4e50-b62b-a82b6213a231_MobileSSD_fp32.tflite.mlir:
     59 tosa.clamp
     55 tosa.conv2d
            breakdown by filter:
                54 (kernel 1x1)
                 1 (kernel 3x3)
            breakdown by dilation:
                55 (dilation 1x1)
     33 tosa.depthwise_conv2d
            breakdown by filter:
            [...]
```

MobileBERT is still special (of the models in this suite) in several ways:
* Some of its matmuls are runtime-times-runtime values, as opposed to most inference workloads doing constant-times-runtime ("constant weights").
* Most of its matmuls are large and round (multiples of 128 mostly) in all three M/N/K dimensions, as opposed to most other NN architectures exercising matmuls that are very narrow in some dimension.
* It really is even more dominated by matmuls than most other models in the suite.

**Review by bjacob — APPROVED** [review]

**Comment by hanhanW** [comment]
Here is the list: https://github.com/openxla/iree/blob/437a4e3ce2d947d56b60ce7bef95edbe1bc615b1/build_tools/python/e2e_test_framework/models/model_groups.py#L85C1-L133

For Bert models, we have MiniLMBert, BertLarge, and MobileBert. We expect improvements happening on MiniLMBert and BertLarge.

The base commit does not include multi-lowering config change, rebased to ToT and re-run benchmarks.

**Comment by hanhanW** [comment]
@MaheshRavishankar  The observed improvements and regression are as same as what we have. I think we can enable data tiling benchmarks and fix other stack allocation issues afterwards. What do you think?

**Review by MaheshRavishankar — APPROVED** [review]

**Comment by MaheshRavishankar** [comment]
> @MaheshRavishankar The observed improvements and regression are as same as what we have. I think we can enable data tiling benchmarks and fix other stack allocation issues afterwards. What do you think?

Sounds good. I just remember seeing bigger increases from your local runs.

**Review by pzread — APPROVED** [review]

**Comment by hanhanW** [comment]
> Sounds good. I just remember seeing bigger increases from your local runs.

My local runs include models that are not enabled on CI, which is BertForMaskedLMTF and T5LargeTFBatch1.

image

**Pull request merged**
