### PR TITLE
[Flow] Switch to new pass generation tablegen definitions

### PR DESCRIPTION
**Pull request by qedawkins**
This is mostly NFC, however it reworks the transform interpreter for dispatch formation to be in line with other uses of the transform dialect across the codebase. In the future these passes need to be unified somehow.

ci-extra: test_nvidia_a100, build_test_all_windows

### CODE REVIEW

**Review by benvanik — APPROVED** [review]
nice! thanks also for the cleanups!

**Comment by MaheshRavishankar** [comment]
Ah nice! I have been thinking should I do this first before I do anything else here.. Thanks for doing this!

**Comment by qedawkins** [comment]
> Ah nice! I have been thinking should I do this first before I do anything else here.. Thanks for doing this!

Yeah same, I just felt like doing something monotonous. Maybe GlobalOptimization next. Codegen seems like it'll be a pain though...

**Comment by MaheshRavishankar** [comment]
> > Ah nice! I have been thinking should I do this first before I do anything else here.. Thanks for doing this!
> 
> Yeah same, I just felt like doing something monotonous. Maybe GlobalOptimization next. Codegen seems like it'll be a pain though...

Codegen is also on my list. I split those op so that they could be done piecewise... if i get through my backlog, ill get to it.

**Pull request merged**
