### PR TITLE
Add Colab notebook showing ResNet50 compilation and execution.

### PR DESCRIPTION
**Pull request by ScottTodd**
Note that we just recently started being able to compile and execute ResNet correctly, so there are still many areas where performance will be improving soon.

### CODE REVIEW

**Review by asaadaldien — APPROVED** [review]

**Comment by bhack** [comment]
Can we add a little bit of timing prints?
I know that we are not performance oriented now but It could be useful to check time by time how this will evolve on colab.

**Comment by ScottTodd** [comment]
> Can we add a little bit of timing prints?
> I know that we are not performance oriented now but It could be useful to check time by time how this will evolve on colab.

@bhack 

I'd prefer to keep the Colab notebooks focused on ergonomics and experimentation. The Python bindings and Colab environment(1) introduce some overheads that make comparisons less meaningful. Performance history over time will be great to track, but I don't think Colab notebooks are the place for it.

The ["Resnet50 Improvements" project](https://github.com/google/iree/projects/14) is tracking some of the most visible optimization work, and the IR snapshot [linked there](https://gist.github.com/benvanik/9a94c3a4b23d4ebbd4e4c23ccdd20377) has much room for improvement.

Out of curiosity, I added some timing locally (but don't plan to commit it):
```
def run_tf():
  tf_model.predict(input_data)
tf_time = timeit.timeit(run_tf, number=1)

def run_iree():
  rt_context.modules.module.predict(input_data)
iree_time = timeit.timeit(run_iree, number=1)
```

With all the above caveats, default flags for the Bazel build, TF takes ~0.11 seconds and IREE VMLA (reference CPU backend) takes ~14.3 seconds(2). The vulkan-spirv backend was failing for me on Windows with a `VK_ERROR_DEVICE_LOST`, which could indicate a timeout (for which partitioning our work and having faster kernels will help).

(1) Building the compiler and runtime together appears to affect the optimization flags. I think we're using `opt` flags, but `NDEBUG` is unset, so some very costly `DCHECK` (debug only checks) are still compiled in?
(2) It actually takes ~145 seconds (yes, that's 10x) before https://github.com/google/iree/pull/1917. So, still plenty of places to optimize :D

---

By the way, correctness tests are defined here: https://github.com/google/iree/blob/4ed6414a826b276064d5fa131e608bfc56c382dc/integrations/tensorflow/e2e/BUILD#L101-L152

**Comment by bhack** [comment]
ok thanks

**Comment by bhack** [comment]
If have something internal minimal to plot a graph on a page it could by interesting to see how checkpoints will improve over time. :)

**Review by rybakov — APPROVED** [review]
with classification result it is better to show an image too

**Comment by ScottTodd** [comment]
> with classification result it is better to show an image too

Good idea, done.

**Pull request closed without merging**
