### PR TITLE
Cherry-pick landed PR from LLVM

### PR DESCRIPTION
**Pull request by dcaballe**
The last integrate breaks the compilation of internal models because a PR didn't make to the last integrate: https://github.com/llvm/llvm-project/pull/82843 The PR landed already on the LLVM side. Would it make sense to just cherry-pick it or should we wait until next integrate?

### CODE REVIEW

**Comment by hanhanW** [comment]
The recent llvm integrate pins it to a commit (which was landed 6 hours ago). Maybe you can coordinate with @qedawkins and see if you can bump it to include your commit?

**Comment by qedawkins** [comment]
My understanding was that breakages are good enough justification for a cherry-pick, although if it was that recent we could try just bumping straight to the commit in question?

**Comment by stellaraccident** [comment]
I have no problem at all with cherry picking for breakages.

**Review by qedawkins — APPROVED** [review]
Approving, but if you want to try bumping straight to the relevant commit that would be welcome as well.

**Comment by hanhanW** [comment]
I just found that the cherry-pick == bump LLVM submodules. The recent one is just one behind @dcaballe 's commit.

image

**Comment by qedawkins** [comment]
ah darn, that's unfortunate, then doubly approved :)

**Review by hanhanW — CHANGES_REQUESTED** [review]
It is very close to head, may I try to bump it again. Because we also need https://github.com/llvm/llvm-project/commit/46bd65a0509fefdf50d44f63640a7b8bd8ad0d14 to fix numerical issues?

I'm creating a PR now.

**Comment by qedawkins** [comment]
ok I will let you guys figure it out then, but I am ok with whatever works given that there are breakages.

**Comment by hanhanW** [comment]
It is landed in https://github.com/openxla/iree/pull/16609, closing the PR

**Pull request closed without merging**
