### PR TITLE
(Do not submit) Force data-tiling to get a (DT-Only vs DT+UK) benchmark comparison table

### PR DESCRIPTION
**Pull request by bjacob**
The useful DT/UK benchmark comparison tables only show No-DT and DT+UK, as DT-Only benchmarks are skipped, and I don't know how to un-skip them. I want to compare DT-Only with DT-UK ahead of proposing enabling UK by default. So this PR just forces DT on so that the "No-DT" column really shows "DT-Only".

### CODE REVIEW

**Comment by pzread** [comment]
It is not obvious currently, DT-only benchmarks can be triggered by adding `benchmark-extra: x86_64-dt-only,android-cpu-dt-only` to the bottom of PR description

**Comment by bjacob** [comment]
Ah, thanks!!

**Comment by hanhanW** [comment]
> The useful DT/UK benchmark comparison tables only show No-DT and DT+UK, as DT-Only benchmarks are skipped, and I don't know how to un-skip them.

Add `benchmark-extra: x86_64-dt-only` to the end of PR description, and re-trigger the CI. (I don't have a link on hands for now, but there are other options. I'll circle back on this once I get it)

**Comment by hanhanW** [comment]
https://iree.dev/developers/general/contributing/#continuous-integration-ci has more information, but the list of available flags are missed..

**Comment by ScottTodd** [comment]
> https://iree.dev/developers/general/contributing/#continuous-integration-ci has more information, but the list of available flags are missed..

https://iree.dev/developers/general/contributing/#ci-behavior-manipulation can expand one of the tip sections for this: 
image

That links to https://iree.dev/developers/performance/benchmark-suites/#choose-benchmark-presets

(Feel free to add any common configurations directly to the docs to make them easier to discover and copy/paste)

**Pull request closed without merging**
