### PR TITLE
Reduce the number of benchmark_repetitions to 5

### PR DESCRIPTION
**Pull request by hanhanW**
This is a workaround to fix iree-benchmark-android. For more details:
https://github.com/google/iree/issues/4852

### CODE REVIEW

**Comment by hanhanW** [comment]
Testing with https://buildkite.com/iree/iree-android-benchmark/builds/1878

**Comment by hanhanW** [comment]
cool, it is working on both phones.

**Comment by antiagainst** [comment]
This isn't the proper way to fix. Let's not do this. :)

**Comment by hanhanW** [comment]
> This isn't the proper way to fix. Let's not do this. :)

SG, I saw the trace in #4852, let's fix it in a proper way!

**Pull request closed without merging**
