### PR TITLE
Delete test_benchmark_suites job matrix.

### PR DESCRIPTION
**Pull request by ScottTodd**
Progress on https://github.com/openxla/iree/issues/16431

This job matrix runs at the end of the presubmit CI pipeline, making it a potential bottleneck for total time taken: 
image

Looking at the details for a test run like https://github.com/openxla/iree/actions/runs/7919322698/job/21620549177?pr=16420, the only test executed is `iree/tools/test/iree_run_module_correctness_test`. We should be running correctness tests for every program we benchmark (otherwise we could be benchmarking code that doesn't work, or we could game the numbers by skipping meaningful computations)... but the current setup is not doing that. New tests for benchmark programs should be added to the package-based CI (https://github.com/openxla/iree/issues/16203), perhaps as part of [`experimental/regression_suite`](https://github.com/openxla/iree/tree/main/experimental/regression_suite).

### CODE REVIEW

**Review by pzread — APPROVED** [review]

**Comment by hcindyl** [comment]
It is unfortunate that the `test_benchmark_suites` job reduced itself to run only the non-model tasks. We should find a way to see why other tests are bypassed, instead of retiring the flow altogether. 

The original request of the job in CI is trying to catch LLVM codegen regression with crosscompile targets, specifically on RISCV. It started out with just checking person_detection model, then extended to mobilenet and efficientnet. I have lost track on why we turned off them later, but the idea is to run realistic workload beyond the sanity checks.

**Comment by ScottTodd** [comment]
> It is unfortunate that the `test_benchmark_suites` job reduced itself to run only the non-model tasks. We should find a way to see why other tests are bypassed, instead of retiring the flow altogether.
> 
> The original request of the job in CI is trying to catch LLVM codegen regression with crosscompile targets, specifically on RISCV. It started out with just checking person_detection model, then extended to mobilenet and efficientnet. I have lost track on why we turned off them later, but the idea is to run realistic workload beyond the sanity checks.

I'm sympathetic to the test coverage needs across platforms, targets, and workloads, but this current CI setup is
* Not actually serving those needs right now
* Burning resources and developer time

I'd much rather spend time expanding test suites and that platform matrix in a sustainable way than try to retrofit the current, broken jobs.

I'd also like to see when/where the coverage changed... but I suspect that CI logs in GitHub have expired, so finding a point when the workflow ran more tests would be tricky.

**Comment by ScottTodd** [comment]
> I'd also like to see when/where the coverage changed... but I suspect that CI logs in GitHub have expired, so finding a point when the workflow ran more tests would be tricky.

These `iree_benchmark_suite_module_test`s are still defined: https://github.com/openxla/iree/blob/0c540db090d4aa55211e706b13f88014b8c3c7d6/tests/e2e/stablehlo_models/generated_e2e_model_tests.cmake#L7-L18

So might just be a matter of going through that CMake function and seeing why the current CI jobs aren't running them...
(We might be able to get them running [again], but I don't want such tests to be tightly coupled to these multi-stage jobs)

**Comment by ScottTodd** [comment]
Can't debug locally. Trying with some logging on https://github.com/openxla/iree/pull/16440.

**Comment by ScottTodd** [comment]
Found out why the tests weren't getting run... going to think some about how to get that coverage added back. Could start with https://github.com/openxla/iree/pull/16439 to move the benchmark jobs to postsubmit / opt-in only. Right now we're uploading 70-100GB of artifacts for _every presubmit run_ without getting much value.

**Comment by ScottTodd** [comment]
Abandoning this in favor of https://github.com/openxla/iree/pull/16439 for now.

**Pull request closed without merging**
