### PR TITLE
remove the `matmul` ukernel

### PR DESCRIPTION
**Pull request by bjacob**
If you care about performance then you should be enabling data tiling, and then, by the time ukernels are considered, matmuls have been turned into mmt4d.

### CODE REVIEW

**Review by benvanik — APPROVED** [review]

**Comment by MaheshRavishankar** [comment]
Haven't looked at this yet, but is there a downside to keeping this?

**Comment by benvanik** [comment]
code size and implementation complexity (this gets linked into every runtime build and people porting the ukernel library may think they need it) - we only want ukernels for things we actually generate

**Comment by bjacob** [comment]
I'm looking at this more at the source level - the git diff is -370 lines, that's as many lines that people reading this code won't have to read or scroll through.

**Comment by MaheshRavishankar** [comment]
Understood, but as of today this is the only one that exercises the `ukernel.generic` path. So I'd prefer to keep it till something else uses it. We have lit tests etc, but this would be vehicle for e2e tests.

**Comment by benvanik** [comment]
I'm coding up a custom_dispatch sample that uses it now :)
If we want to leave this PR open until that lands that's ok with me.

**Comment by bjacob** [comment]
SG, I didn't realize that.

**Comment by bjacob** [comment]
Superseded by #13175.

**Pull request closed without merging**
