### PR TITLE
Add folding arithmetic extensions

### PR DESCRIPTION
**Pull request by erman-gurses**
Add folding arithmetic extensions on floating point data types into vector contraction operations

### CODE REVIEW

**Review by harsh-nod — APPROVED** [review]
lgtm! thanks!

**Comment by harsh-nod** [comment]
Can you add a test that shows how this op works?

**Review by harsh-nod — CHANGES_REQUESTED** [review]
Could you add a test that shows how this op works?

**Comment by erman-gurses** [comment]
> Could you add a test that shows how this op works?

Sure, I just added a test case.

**Review by harsh-nod — APPROVED** [review]
lgtm! thanks!

**Pull request merged**
