### PR TITLE
[ROCMTarget] Add denormal flushing for fp32 math

### PR DESCRIPTION
**Pull request by Groverkss**
This flag improves exp2 perf on amdgpu llvm backend for Flash Attention 2 kernels

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
Are we planning to do it for all, or do we only do it if the dispatch has exp2?

**Review by kuhar — COMMENTED** [review]
This is a heavy hammer wrt gambling on numerics -- I don't think we should make it the default.

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
@Groverkss  agreeing with @kuhar's comment. Here is what you could do

1) For attention dispatches add it to the `translation_info`s dictionary attribute
2) Do something similar to this (https://github.com/MaheshRavishankar/iree/blob/e35ec5a13bc0df9a1c19f15346eb1350dacef3ac/compiler/src/iree/compiler/Codegen/Common/ReconcileTranslationInfo.cpp#L103) and propagate this to a function attribute.
3) This should then get propagated to the llvm function by itself.
4) Then you can query the llvm dialect function attributes to set this.

A few steps, but thats the best way we have right now.

**Comment by Groverkss** [comment]
Replaced by https://github.com/iree-org/iree/pull/17365

**Pull request closed without merging**
