### PR TITLE
Integrate llvm-project at llvm/llvm-project@82371e6

### PR DESCRIPTION
**Pull request by kuhar**
* Reset third_party/llvm-project: llvm/llvm-project@82371e68e45db2e2c30e7ed39820a027c680515d (2023-07-11 22:53:38 +0900): [Bazel] Fixup for D153758, D153850, and D153861 (global-isel-combiner-matchtable)
* Cherry-pick a bazel fix: llvm/llvm-project@be29fe2f987b5bf58d7f6aa77c06e58d9402064a
* Revert llvm/llvm-project@2c5739675cf8fc9191b8735be7c012e846fa49de ([mlir][nvgpu] Implement `nvgpu.device_async_copy` by NVVMToLLVM Pass)

### CODE REVIEW

**Comment by kuhar** [comment]
I'm not sure what is wrong with this one; we have 2 compilation failures, one on `lowering_config.mlir` (llvm-cpu), one on unaligned matmul (cuda). I tried dumping IR between passes and I suspect that the culprit is https://reviews.llvm.org/D154932 and the new patterns are sufficiently different to invalidate some assumptions in `RemoveSingleIterationLoop`.

Repro:
```shell
tools/iree-compile --output-format=vm-bytecode --mlir-print-op-on-diagnostic=false --iree-hal-target-backends=llvm-cpu --iree-input-type=stablehlo ../tests/e2e/regression/lowering_config.mlir -o check_regression_llvm-cpu_lowering_config.mlir_module.vmfb --mlir-disable-threading --mlir-print-ir-after-all
```

The diffs:
Before:
```mlir
      scf.for %arg2 = %7 to %c512 step %8 {
        %9 = flow.dispatch.tensor.load %2, offsets = [0, %arg0, %arg1, %arg2], sizes = [36, 7, 7, 64], strides = [1, 1, 1, 1] : !flow.dispatch.tensor<writeonly:tensor<36x7x7x512xf32>> -> tensor<36x7x7x64xf32>
        %10 = flow.dispatch.tensor.load %0, offsets = [0, %arg0, %arg1, 0], sizes = [36, 9, 9, 512], strides = [1, 1, 1, 1] : !flow.dispatch.tensor<readonly:tensor<36x9x9x512xf32>> -> tensor<36x9x9x512xf32>
        %11 = flow.dispatch.tensor.load %1, offsets = [0, 0, 0, %arg2], sizes = [3, 3, 512, 64], strides = [1, 1, 1, 1] : !flow.dispatch.tensor<readonly:tensor<3x3x512x512xf32>> -> tensor<3x3x512x64xf32>
        %12 = scf.for %arg3 = %c0 to %c36 step %c6 iter_args(%arg4 = %9) -> (tensor<36x7x7x64xf32>) {
          %13 = scf.for %arg5 = %c0 to %c7 step %c1 iter_args(%arg6 = %arg4) -> (tensor<36x7x7x64xf32>) {
            %14 = scf.for %arg7 = %c0 to %c64 step %c32 iter_args(%arg8 = %arg6) -> (tensor<36x7x7x64xf32>) {
              %extracted_slice = tensor.extract_slice %10[%arg3, %arg5, 0, 0] [6, 3, 9, 512] [1, 1, 1, 1] : tensor<36x9x9x512xf32> to tensor<6x3x9x512xf32>
              %extracted_slice_1 = tensor.extract_slice %arg8[%arg3, %arg5, 0, %arg7] [6, 1, 7, 32] [1, 1, 1, 1] : tensor<36x7x7x64xf32> to tensor<6x1x7x32xf32>
              %15 = vector.transfer_write %cst, %extracted_slice_1[%c0, %c0, %c0, %c0] {in_bounds = [true, true, true, true]} : vector<6x1x7x32xf32>, tensor<6x1x7x32xf32>
              %16 = scf.for %arg9 = %c0 to %c3 step %c1 iter_args(%arg10 = %15) -> (tensor<6x1x7x32xf32>) {
                %17 = scf.for %arg11 = %c0 to %c512 step %c4 iter_args(%arg12 = %arg10) -> (tensor<6x1x7x32xf32>) {
                  %extracted_slice_2 = tensor.extract_slice %extracted_slice[0, %arg9, 0, %arg11] [6, 1, 9, 4] [1, 1, 1, 1] : tensor<6x3x9x512xf32> to tensor<6x1x9x4xf32>
                  %extracted_slice_3 = tensor.extract_slice %extracted_slice_2[0, 0, 0, 0] [6, 1, 9, 4] [1, 1, 1, 1] : tensor<6x1x9x4xf32> to tensor<6x9x4xf32>
                  %extracted_slice_4 = tensor.extract_slice %arg12[0, 0, 0, 0] [6, 1, 7, 32] [1, 1, 1, 1] : tensor<6x1x7x32xf32> to tensor<6x7x32xf32>
                  %18 = vector.transfer_read %extracted_slice_3[%c0, %c0, %c0], %cst_0 {in_bounds = [true, true, true]} : tensor<6x9x4xf32>, vector<6x9x4xf32>
                  %19 = vector.transfer_read %11[%arg9, %c0, %arg11, %arg7], %cst_0 {in_bounds = [true, true, true]} : tensor<3x3x512x64xf32>, vector<3x4x32xf32>
                  %20 = vector.transfer_read %extracted_slice_4[%c0, %c0, %c0], %cst_0 {in_bounds = [true, true, true]} : tensor<6x7x32xf32>, vector<6x7x32xf32>
                  %21 = vector.extract_strided_slice %18 {offsets = [0, 0, 0], sizes = [6, 7, 4], strides = [1, 1, 1]} : vector<6x9x4xf32> to vector<6x7x4xf32>
                  %22 = vector.extract_strided_slice %18 {offsets = [0, 1, 0], sizes = [6, 7, 4], strides = [1, 1, 1]} : vector<6x9x4xf32> to vector<6x7x4xf32>
                  %23 = vector.extract_strided_slice %18 {offsets = [0, 2, 0], sizes = [6, 7, 4], strides = [1, 1, 1]} : vector<6x9x4xf32> to vector<6x7x4xf32>
                  %24 = vector.extract %19[0] : vector<3x4x32xf32>
                  %25 = vector.extract %19[1] : vector<3x4x32xf32>
                  %26 = vector.extract %19[2] : vector<3x4x32xf32>
                  %27 = vector.contract {indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d3)>, affine_map<(d0, d1, d2, d3) -> (d3, d2)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>], iterator_types = ["parallel", "parallel", "parallel", "reduction"], kind = #vector.kind<add>} %21, %24, %20 : vector<6x7x4xf32>, vector<4x32xf32> into vector<6x7x32xf32>
                  %28 = vector.contract {indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d3)>, affine_map<(d0, d1, d2, d3) -> (d3, d2)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>], iterator_types = ["parallel", "parallel", "parallel", "reduction"], kind = #vector.kind<add>} %22, %25, %27 : vector<6x7x4xf32>, vector<4x32xf32> into vector<6x7x32xf32>
                  %29 = vector.contract {indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d3)>, affine_map<(d0, d1, d2, d3) -> (d3, d2)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>], iterator_types = ["parallel", "parallel", "parallel", "reduction"], kind = #vector.kind<add>} %23, %26, %28 : vector<6x7x4xf32>, vector<4x32xf32> into vector<6x7x32xf32>
                  %30 = vector.transfer_write %29, %extracted_slice_4[%c0, %c0, %c0] {in_bounds = [true, true, true]} : vector<6x7x32xf32>, tensor<6x7x32xf32>
                  %inserted_slice_5 = tensor.insert_slice %30 into %arg12[0, 0, 0, 0] [6, 1, 7, 32] [1, 1, 1, 1] : tensor<6x7x32xf32> into tensor<6x1x7x32xf32>
                  scf.yield %inserted_slice_5 : tensor<6x1x7x32xf32>
                }
                scf.yield %17 : tensor<6x1x7x32xf32>
              }
              %inserted_slice = tensor.insert_slice %16 into %arg8[%arg3, %arg5, 0, %arg7] [6, 1, 7, 32] [1, 1, 1, 1] : tensor<6x1x7x32xf32> into tensor<36x7x7x64xf32>
              scf.yield %inserted_slice : tensor<36x7x7x64xf32>
            }
            scf.yield %14 : tensor<36x7x7x64xf32>
          }
          scf.yield %13 : tensor<36x7x7x64xf32>
        }
        flow.dispatch.tensor.store %12, %2, offsets = [0, %arg0, %arg1, %arg2], sizes = [36, 7, 7, 64], strides = [1, 1, 1, 1] : tensor<36x7x7x64xf32> -> !flow.dispatch.tensor<writeonly:tensor<36x7x7x512xf32>>
      }
```

After:
```mlir
      scf.for %arg2 = %7 to %c512 step %8 {
        %9 = flow.dispatch.tensor.load %2, offsets = [0, %arg0, %arg1, %arg2], sizes = [36, 7, 7, 64], strides = [1, 1, 1, 1] : !flow.dispatch.tensor<writeonly:tensor<36x7x7x512xf32>> -> tensor<36x7x7x64xf32>
        %10 = flow.dispatch.tensor.load %0, offsets = [0, %arg0, %arg1, 0], sizes = [36, 9, 9, 512], strides = [1, 1, 1, 1] : !flow.dispatch.tensor<readonly:tensor<36x9x9x512xf32>> -> tensor<36x9x9x512xf32>
        %11 = flow.dispatch.tensor.load %1, offsets = [0, 0, 0, %arg2], sizes = [3, 3, 512, 64], strides = [1, 1, 1, 1] : !flow.dispatch.tensor<readonly:tensor<3x3x512x512xf32>> -> tensor<3x3x512x64xf32>
        %12 = scf.for %arg3 = %c0 to %c36 step %c6 iter_args(%arg4 = %9) -> (tensor<36x7x7x64xf32>) {
          %13 = scf.for %arg5 = %c0 to %c7 step %c1 iter_args(%arg6 = %arg4) -> (tensor<36x7x7x64xf32>) {
            %14 = scf.for %arg7 = %c0 to %c64 step %c32 iter_args(%arg8 = %arg6) -> (tensor<36x7x7x64xf32>) {
              %extracted_slice = tensor.extract_slice %arg8[%arg3, %arg5, 0, %arg7] [6, 1, 7, 32] [1, 1, 1, 1] : tensor<36x7x7x64xf32> to tensor<6x1x7x32xf32>
              %15 = vector.transfer_write %cst, %extracted_slice[%c0, %c0, %c0, %c0] {in_bounds = [true, true, true, true]} : vector<6x1x7x32xf32>, tensor<6x1x7x32xf32>
              %16 = scf.for %arg9 = %c0 to %c3 step %c1 iter_args(%arg10 = %15) -> (tensor<6x1x7x32xf32>) {
                %17 = scf.for %arg11 = %c0 to %c512 step %c4 iter_args(%arg12 = %arg10) -> (tensor<6x1x7x32xf32>) {
                  %18 = affine.apply affine_map<()[s0, s1] -> (s0 + s1)>()[%arg5, %arg9]
                  %19 = vector.transfer_read %10[%arg3, %18, %c0, %arg11], %cst_0 {in_bounds = [true, true, true], permutation_map = affine_map<(d0, d1, d2, d3) -> (d0, d2, d3)>} : tensor<36x9x9x512xf32>, vector<6x9x4xf32>
                  %20 = vector.transfer_read %11[%arg9, %c0, %arg11, %arg7], %cst_0 {in_bounds = [true, true, true]} : tensor<3x3x512x64xf32>, vector<3x4x32xf32>
                  %21 = vector.transfer_read %arg12[%c0, %c0, %c0, %c0], %cst_0 {in_bounds = [true, true, true], permutation_map = affine_map<(d0, d1, d2, d3) -> (d0, d2, d3)>} : tensor<6x1x7x32xf32>, vector<6x7x32xf32>
                  %22 = vector.extract_strided_slice %19 {offsets = [0, 0, 0], sizes = [6, 7, 4], strides = [1, 1, 1]} : vector<6x9x4xf32> to vector<6x7x4xf32>
                  %23 = vector.extract_strided_slice %19 {offsets = [0, 1, 0], sizes = [6, 7, 4], strides = [1, 1, 1]} : vector<6x9x4xf32> to vector<6x7x4xf32>
                  %24 = vector.extract_strided_slice %19 {offsets = [0, 2, 0], sizes = [6, 7, 4], strides = [1, 1, 1]} : vector<6x9x4xf32> to vector<6x7x4xf32>
                  %25 = vector.extract %20[0] : vector<3x4x32xf32>
                  %26 = vector.extract %20[1] : vector<3x4x32xf32>
                  %27 = vector.extract %20[2] : vector<3x4x32xf32>
                  %28 = vector.contract {indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d3)>, affine_map<(d0, d1, d2, d3) -> (d3, d2)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>], iterator_types = ["parallel", "parallel", "parallel", "reduction"], kind = #vector.kind<add>} %22, %25, %21 : vector<6x7x4xf32>, vector<4x32xf32> into vector<6x7x32xf32>
                  %29 = vector.contract {indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d3)>, affine_map<(d0, d1, d2, d3) -> (d3, d2)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>], iterator_types = ["parallel", "parallel", "parallel", "reduction"], kind = #vector.kind<add>} %23, %26, %28 : vector<6x7x4xf32>, vector<4x32xf32> into vector<6x7x32xf32>
                  %30 = vector.contract {indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d3)>, affine_map<(d0, d1, d2, d3) -> (d3, d2)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>], iterator_types = ["parallel", "parallel", "parallel", "reduction"], kind = #vector.kind<add>} %24, %27, %29 : vector<6x7x4xf32>, vector<4x32xf32> into vector<6x7x32xf32>
                  %31 = vector.broadcast %30 : vector<6x7x32xf32> to vector<1x6x7x32xf32>
                  %32 = vector.transpose %31, [1, 0, 2, 3] : vector<1x6x7x32xf32> to vector<6x1x7x32xf32>
                  %33 = vector.transfer_write %32, %arg12[%c0, %c0, %c0, %c0] {in_bounds = [true, true, true, true]} : vector<6x1x7x32xf32>, tensor<6x1x7x32xf32>
                  scf.yield %33 : tensor<6x1x7x32xf32>
                }
                scf.yield %17 : tensor<6x1x7x32xf32>
              }
              %inserted_slice = tensor.insert_slice %16 into %arg8[%arg3, %arg5, 0, %arg7] [6, 1, 7, 32] [1, 1, 1, 1] : tensor<6x1x7x32xf32> into tensor<36x7x7x64xf32>
              scf.yield %inserted_slice : tensor<36x7x7x64xf32>
            }
            scf.yield %14 : tensor<36x7x7x64xf32>
          }
          scf.yield %13 : tensor<36x7x7x64xf32>
        }
        flow.dispatch.tensor.store %12, %2, offsets = [0, %arg0, %arg1, %arg2], sizes = [36, 7, 7, 64], strides = [1, 1, 1, 1] : tensor<36x7x7x64xf32> -> !flow.dispatch.tensor<writeonly:tensor<36x7x7x512xf32>>
      }
```

**Comment by kuhar** [comment]
The first test does not crash after locally reverting llvm/llvm-project@867afe5e53194607d671dbf1ae5d190793f02d1f.

@matthias-springer, could you take a look and advise how to proceed?

The second test still does:
```
tests/e2e/matmul/e2e_matmul_direct_f32_gpu_large_unaligned_cuda_cuda.mlir:13:13: error: 'nvgpu.device_async_copy' op bypassL1 does not satify alignment for 'memref<3x128x16xf32, #gpu.address_space<workgroup>>' with destination element 2. Unset bypassL1, or set destination element to 4
```

**Comment by kuhar** [comment]
The second one (unaligned matmul cuda) does not verify after the `TransformsDialectInterpreter`:
```mlir
// -----// IR Dump After EraseHALDescriptorTypeFromMemRef (iree-codegen-erase-hal-descriptor-type-from-memref) //----- //
func.func @matmul_457x330xf32_times_330x514xf32_into_457x514xf32_dispatch_0_matmul_457x514x330_f32() {
  %c0 = arith.constant 0 : index
  %cst = arith.constant 0.000000e+00 : f32
  %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<457x330xf32>>
  %1 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<330x514xf32>>
  %2 = hal.interface.binding.subspan set(0) binding(2) type(storage_buffer) alignment(64) offset(%c0) : !flow.dispatch.tensor<writeonly:tensor<457x514xf32>>
  %3 = flow.dispatch.tensor.load %0, offsets = [0, 0], sizes = [457, 330], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<457x330xf32>> -> tensor<457x330xf32>
  %4 = flow.dispatch.tensor.load %1, offsets = [0, 0], sizes = [330, 514], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<330x514xf32>> -> tensor<330x514xf32>
  %5 = tensor.empty() : tensor<457x514xf32>
  %6 = linalg.fill ins(%cst : f32) outs(%5 : tensor<457x514xf32>) -> tensor<457x514xf32>
  %7 = linalg.matmul ins(%3, %4 : tensor<457x330xf32>, tensor<330x514xf32>) outs(%6 : tensor<457x514xf32>) -> tensor<457x514xf32>
  flow.dispatch.tensor.store %7, %2, offsets = [0, 0], sizes = [457, 514], strides = [1, 1] : tensor<457x514xf32> -> !flow.dispatch.tensor<writeonly:tensor<457x514xf32>>
  return
}

/usr/local/google/home/kubak/iree/build-relass/tests/e2e/matmul/e2e_matmul_direct_f32_gpu_large_unaligned_cuda_cuda.mlir:13:13: error: 'nvgpu.device_async_copy' op bypassL1 does not satify alignment for 'memref<3x128x16xf32, #gpu.address_space<workgroup>>' with destination element 2. Unset bypassL1, or set destination element to 4
  %result = linalg.matmul ins(%lhs, %rhs: tensor<457x330xf32>, tensor<330x514xf32>) outs(%acc: tensor<457x514xf32>) -> tensor<457x514xf32>
            ^
/usr/local/google/home/kubak/iree/build-relass/tests/e2e/matmul/e2e_matmul_direct_f32_gpu_large_unaligned_cuda_cuda.mlir:9:1: note: called from
func.func @matmul_457x330xf32_times_330x514xf32_into_457x514xf32(%lhs: tensor<457x330xf32>, %rhs: tensor<330x514xf32>) -> tensor<457x514xf32> {
^
// -----// IR Dump After TransformDialectInterpreter Failed (iree-transform-dialect-interpreter) //----- //
"hal.executable.variant"() ({
  "hal.executable.export"() ({
  ^bb0(%arg0: !hal.device):
    %0 = "arith.constant"() <{value = 5 : index}> : () -> index
    %1 = "arith.constant"() <{value = 4 : index}> : () -> index
    %2 = "arith.constant"() <{value = 1 : index}> : () -> index
```

**Comment by kuhar** [comment]
I bisected the cuda failure down to https://reviews.llvm.org/D154345. It passes after reverting this commit.

Do we need to update something on the IREE side, @grypp?

**Comment by matthias-springer** [comment]
> The first test does not crash after locally reverting [llvm/llvm-project@867afe5](https://github.com/llvm/llvm-project/commit/867afe5e53194607d671dbf1ae5d190793f02d1f).
> 
> @matthias-springer, could you take a look and advise how to proceed?
> 
> The second test still does:
> 
> ```
> tests/e2e/matmul/e2e_matmul_direct_f32_gpu_large_unaligned_cuda_cuda.mlir:13:13: error: 'nvgpu.device_async_copy' op bypassL1 does not satify alignment for 'memref<3x128x16xf32, #gpu.address_space<workgroup>>' with destination element 2. Unset bypassL1, or set destination element to 4
> ```

The crash is caused by a bug in `Linalg/Transforms/Hoisting.cpp`. [D154932](https://reviews.llvm.org/D154932) enables more aggressive folding of vector transfer ops with permutation maps (these were previously left unchanged). The generated IR is correct, but triggers a bug in `Hoisting.cpp`, which then generated invalid IR.

I have a fix for `Hoisting.cpp`, which deactivates hoisting in such unsupported cases (https://reviews.llvm.org/D155052). However, that may not be desirable because it would likely regress performance. We may be able to get away with not doing any vector transfer/tensor slice folding during IREE vectorization.

**Comment by grypp** [comment]
> I bisected the cuda failure down to https://reviews.llvm.org/D154345. It passes after reverting this commit.
> 
> Do we need to update something on the IREE side, @grypp?

It is not a bug actually. I put a verifier, we should not generate `bypassL1` for this case. 

```
/usr/local/google/home/kubak/iree/build-relass/tests/e2e/matmul/e2e_matmul_direct_f32_gpu_large_unaligned_cuda_cuda.mlir:13:13: error: 'nvgpu.device_async_copy' op bypassL1 does not satify alignment for 'memref<3x128x16xf32, #gpu.address_space<workgroup>>' with destination element 2. Unset bypassL1, or set destination element to 4
```

Let me work on a fix.

**Comment by matthias-springer** [comment]
I added back the patterns that were deleted in [D154932](https://reviews.llvm.org/D154932) to IREE. [D154932](https://reviews.llvm.org/D154932) makes sense as a cleanup in MLIR and this will unblock the integrate and give us more time to fix the lowering issues in IREE.

**Comment by kuhar** [comment]
Everything passes now, should be ready to merge.

edit:
The passes brought over from MLIR need tests.

**Review by hanhanW — APPROVED** [review]

**Pull request merged**
