### PR TITLE
Add quantized models x86_64 and riscv benchmark suites.

### PR DESCRIPTION
**Pull request by hanhanW**
Fixes https://github.com/iree-org/iree/issues/9871

### CODE REVIEW

**Comment by pzread** [comment]
Should we also add the EfficientNet model?

**Comment by dcaballe** [comment]
Thanks for adding this, Hanhan! I didn't know it was just adding one line per model! :)
Yes, adding EfficientNet-Lite0-quant would be great. That's the only one missing.
Thanks!

**Comment by GMNGeoffrey** [comment]
LGTM, but deferring to @pzread. I don't quite know what the extra latency is on the benchmarks from adding these models. I don't actually see any results that mention RISC-V

**Comment by hanhanW** [comment]
I added the EfficientNet model, and verify that it's a mirror of  https://tfhub.dev/tensorflow/lite-model/efficientnet/lite0/int8/2

**Comment by hanhanW** [comment]
How do I check if it works for RISC-V benchmarks? Is it available now?

**Review by pzread — APPROVED** [review]

**Comment by pzread** [comment]
> How do I check if it works for RISC-V benchmarks? Is it available now?

We only track the size and compilation time on RISC-V targets. They looks good in the list.

Thanks a lot for doing this 🙂

**Comment by hanhanW** [comment]
> > How do I check if it works for RISC-V benchmarks? Is it available now?
> 
> We only track the size and compilation time on RISC-V targets. They looks good in the list.
> 
> Thanks a lot for doing this 🙂

Got you, thanks!

**Comment by dcaballe** [comment]
Thank you so much!

**Pull request merged**
