### PR TITLE
Add vector.gather lowering patterns to the  LLVMCPUVectorLoweringPass pass

### LINKED ISSUE #15364: iree-compile fails because of the lowering to builtin.unrealized_conversion_cast operations
### What happened?

During the compilation of the following reproducer, IREE fails with the error: `failed to legalize operation 'builtin.unrealized_conversion_cast' that was explicitly marked illegal`.

### Steps to reproduce your issue

model.mlir:
```
module @execute_model attributes {mhlo.num_partitions = 1 : i32, mhlo.num_replicas = 1 : i32} {
  func.func public @main(%arg0: tensor<2592000x3xf32>, %arg1: tensor<518400x1xi32>) -> tensor<518400xf32> {
      %0 = stablehlo.slice %arg0 [0:2592000, 0:1] : (tensor<2592000x3xf32>) -> tensor<2592000x1xf32>
      %1 = stablehlo.reshape %0 : (tensor<2592000x1xf32>) -> tensor<2592000xf32>
      %2 = "stablehlo.gather"(%1, %arg1) {dimension_numbers = #stablehlo.gather<collapsed_slice_dims = [0], start_index_map = [0], index_vector_dim = 1>, indices_are_sorted = false, slice_sizes = dense<1> : tensor<1xi64>} : (tensor<2592000xf32>, tensor<518400x1xi32>) -> tensor<518400xf32>
      return %2 : tensor<518400xf32>
  }
}
```

Command: `iree-compile --iree-input-type=stablehlo --iree-hal-target-backends=llvm-cpu model.mlir`

### What component(s) does this issue relate to?

_No response_

### Version information

commit 7b92a6d38599d3255b4513f1019c540a3401cfd3 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by banach-space**
Fixes: https://github.com/openxla/iree/issues/15364

### CODE REVIEW

**Comment by banach-space** [comment]
I'm not sure whether this is the right place to add this patterns, so sending this for early feedback. Also, in order to fix https://github.com/openxla/iree/issues/15364 we will need https://github.com/llvm/llvm-project/pull/72991 to make it's way to IREE first.

**Review by hanhanW — COMMENTED** [review]
The example in MLIR fix is in memref/vector world. We want to do such vector lowering in [LLVMCPUVectorLoweringPass](https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPUVectorLowering.cpp). Can you try to add it to the first stage of the pass? I.e., the order can be `gather lowering -> contraction lowering -> the rest...`.

**Comment by banach-space** [comment]
Ping

**Comment by hanhanW** [comment]
oops, sorry that I did not notice that it is ready fore review. It carried llvm commit when I reviewed it. Can we add a pipeline test for gather lowering, like `pipeline_vectorize_nd_extract_tests.mlir`?

@dcaballe does adding it to vector lowering pass look okay to you?

**Comment by hanhanW** [comment]
or maybe we can add a test to https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/Codegen/LLVMCPU/test/vector_lowering.mlir?

**Review by dcaballe — APPROVED** [review]

**Review by hanhanW — APPROVED** [review]

**Pull request merged**
