### PR TITLE
Decomposed linalg's quantized depthwise conv zero-point computations

### PR DESCRIPTION
**Pull request by rsuderman**
Moving the zero-point adjustment outside of the depthwise convolution and into generics should reduce the overall computation time required by reducing the inner mul-add reduction.

### CODE REVIEW

**Review by bjacob — APPROVED** [review]
Is this covered by some existing e2e test, perhaps any existing e2e test involving quantized convs with nonzero zero-points and where this pattern is enabled? I wouldn't feel quite comfortable about something like this being covered only by lit tests.

**Comment by rsuderman** [comment]
> Is this covered by some existing e2e test, perhaps any existing e2e test involving quantized convs with nonzero zero-points and where this pattern is enabled? I wouldn't feel quite comfortable about something like this being covered only by lit tests.

Not checked in but I ran local numerical validations with the operation. I could not think of a way to validate the numerical performance and trust the results.

**Comment by rsuderman** [comment]
Going to delay committing until linalg's pooling operations are vectorized as performance regresses in some cases.

**Comment by MaheshRavishankar** [comment]
FYI @vmurali

**Comment by rsuderman** [comment]
> FYI @vmurali

I am still not seeing good enough performance to land. Trying to verify it is not only my macbook.

**Comment by rsuderman** [comment]
The zip below contains two numerically identical programs, one is a decomposition of the other. I would expect the decomposed version to run significantly faster but it doesn't appear to be going faster.

[Archive.zip](https://github.com/iree-org/iree/files/10387853/Archive.zip)

**Pull request merged**
