### PR TITLE
Refactor matmul workgroup size computation and improve RISC-V default

### PR DESCRIPTION
**Pull request by dcaballe**
This PR moves hard-coded workgroup tile sizes to an independent function
and pave the way for introducing more sophisticated tile size computation.
As part of this refactoring, we change the default tile sizes for RISC-V
to avoid vectorizing the dimension k, which resulted in very inefficient
code (see comments).

### CODE REVIEW

**Comment by dcaballe** [comment]
This PR improves MobileBERT quant by 3X, Person Detect by 2X and the rest of the models by >1.5X. We should see some changes in code size.

**Comment by MaheshRavishankar** [comment]
Win Win! Thanks @dcaballe

**Review by MaheshRavishankar — COMMENTED** [review]
Looks fine to me. Not stamping cause I'd like Hanhan to take a look as well (and auto-merge is enabled).

**Comment by hanhanW** [comment]
> Looks fine to me. Not stamping cause I'd like Hanhan to take a look as well (and auto-merge is enabled).

Thanks! I just finished a round of integration. I'll take a look while waiting for CI bots. :D

**Review by hanhanW — APPROVED** [review]
Looks nice to me!

**Pull request merged**
