### PR TITLE
Import `iree_amdgpu_library.cmake` from `users/benvanik/amdgpu`

### PR DESCRIPTION
**Pull request by bjacob**

### CODE REVIEW

**Comment by benvanik** [comment]
you're not building elfs, correct?

**Comment by bjacob** [comment]
Oh I see, you're warning me about the custom_command running LLD. Hadn't seen that one. I'll need to carve out the part that I need.

**Comment by benvanik** [comment]
yeah, that's the expensive part usually - I originally wanted to have iree_amdgpu_library + iree_amdgpu_binary that did the linking but hadn't got around to it

**Comment by bjacob** [comment]
i could implement that suggestion, but now that would mean that the new `iree_amdgpu_library` would be different from the one in your branch. For now I'll just close this and instead import the correct clang bits out of this, into our existing AMDGPU-ukernels custom command currently doing `clang -x hip`. Later on we will properly deduplicate.

**Pull request closed without merging**
