### PR TITLE
[NFC] Replace LinalgExt::TilingPattern with walk-based transforms. 

### PR DESCRIPTION
**Pull request by hanhanW**
It introduces `tileLinalgOpsWithFilter` which tiles (and optionally distribute) LinalgOp ops if they match the filter. The revision removes the pattern wrapper and uses `linalg::tileLinalgOp` API. They are using the same API, so this is a NFC.

ci-extra: test_a100

### CODE REVIEW

**Review by qedawkins — APPROVED** [review]
I'm not as familiar with the details of the previous implementation, but the changes here look like a good cleanup, thanks!

**Comment by hanhanW** [comment]
> I'm not as familiar with the details of the previous implementation, but the changes here look like a good cleanup, thanks!

Just for future reference: the removed pattern is using `linalg::tileLinalgOp` which is as same as the new method. Peeling is not needed because GPU backends do not use it atm.

image

**Review by MaheshRavishankar — COMMENTED** [review]
Oh this is kind of going backwards. We are trying to
1) Move away from filter based patterns, 
2) Not use `linalg::tileLinalgOp` but instead use `scf::tileUsingScfForOp/scf::tileUsingScfForallOp`. 

This is going back on both of these.... This is a red flag for me... I understand this is for some sort of cleanup, but I fear this is increasing our tech debt. I would ask for a revert, but I dont know all the context on this change.

**Comment by qedawkins** [comment]
> Oh this is kind of going backwards. We are trying to
> 
>     1. Move away from filter based patterns,
> 
>     2. Not use `linalg::tileLinalgOp` but instead use `scf::tileUsingScfForOp/scf::tileUsingScfForallOp`.
> 
> 
> This is going back on both of these.... This is a red flag for me... I understand this is for some sort of cleanup, but I fear this is increasing our tech debt. I would ask for a revert, but I dont know all the context on this change.

The way I read this change was that it replaced greedy rewriters with walks, which should always be better when possible. The transition to `scf::tileUsingScfForOp/scf::tileUsingScfForallOp` sounds good, but it's not immediately clear to me that this change makes that transition more difficult.

Will let Hanhan comment on more context though, I'm not really advocating strongly one way or another, just that per the status quo, this looks like a nice cleanup to me.

**Comment by hanhanW** [comment]
I think that can be a follow-up. I'd like to use `scf::tileUsingScfForOp`, but I found it is hard on LLVMGPU side. Because some canonicalization patterns are missing. I think this is more like moving "tech debt" from LinalgExt to a single API call. Then we can delete 200 lines of code. We are in the same situation, but we delete more redundant codes.

If I have more cycles, my next step is to replace it with `scf::tileUsingScfForOp + tileDispatchUsingSCFFopOp`. After that, we replace `tileDispatchUsingSCFFopOp` with `scf::tileUsingScfForallOp` when we are able to plumb it through other backends. Does the plan make sense?

**Comment by MaheshRavishankar** [comment]
> I think that can be a follow-up. I'd like to use `scf::tileUsingScfForOp`, but I found it is hard on LLVMGPU side. Because some canonicalization patterns are missing. I think this is more like moving "tech debt" from LinalgExt to a single API call. Then we can delete 200 lines of code. We are in the same situation, but we delete more redundant codes.
> 
> If I have more cycles, my next step is to replace it with `scf::tileUsingScfForOp + tileDispatchUsingSCFFopOp`. After that, we replace `tileDispatchUsingSCFFopOp` with `scf::tileUsingScfForallOp` when we are able to plumb it through other backends. Does the plan make sense?

Cool! I was working towards that, but slowly. First refactoring upstream to get tile using scf.forall on par with scf.for and then rely on scr.forall for first level distribution too. Was planning to push more next year, but happy to get some help there

**Comment by hanhanW** [comment]
Okay, I figured a way to structure this better:

- https://github.com/openxla/iree/pull/15938
- https://github.com/openxla/iree/pull/15939

We should be able to replace `distributeLinalgOpsWithFilter` with scf methods once they are ready. For tiling only cases, we will be using `scf::tileUsingSCFForOp` methods.

**Pull request merged**
