### PR TITLE
[Flow] Allow producer fusion for non-DpsInit operands

### PR DESCRIPTION
**Pull request by Max191**

### CODE REVIEW

**Comment by Max191** [comment]
Some fusions seen in SDXL (discussed here https://github.com/openxla/iree/issues/16450) are blocked because of restrictions in FormDispatchRegions. There are some issues with doing element-wise fusion of tensor ops (https://github.com/openxla/iree/issues/13285), so we can try fusing into a dispatch region and see what happens.

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
Please add unit test for the case you expect to fuse.

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
Actually I mis-read this. We probably dont want to change this. This is going to fuse all leading elementwise operations into GEMMs and convolutions etc. We dont want to do that always. I probably confused you when we discussed. I think what I meant was we should just remove the check here https://github.com/MaheshRavishankar/iree/blob/a662a4c3b54d4c70cf23ecd48a25d2c5a4ac9ca5/compiler/src/iree/compiler/Dialect/Flow/Transforms/FusionOfTensorOps.cpp#L118-L119 . So this will fuse it like an elementwise operation + reduction fusion. There was an issue with this (the one you refered to above https://github.com/openxla/iree/issues/13285)

**Comment by Max191** [comment]
> Actually I mis-read this. We probably dont want to change this. This is going to fuse all leading elementwise operations into GEMMs and convolutions etc. We dont want to do that always. I probably confused you when we discussed. I think what I meant was we should just remove the check here https://github.com/MaheshRavishankar/iree/blob/a662a4c3b54d4c70cf23ecd48a25d2c5a4ac9ca5/compiler/src/iree/compiler/Dialect/Flow/Transforms/FusionOfTensorOps.cpp#L118-L119 . So this will fuse it like an elementwise operation + reduction fusion. There was an issue with this (the one you refered to above #13285)

Ah, ok. Let me open up another PR

**Pull request closed without merging**
