### PR TITLE
Revert `tensor.cast` to flow reshape conversion

### PR DESCRIPTION
**Pull request by IanWood1**
Revert `tensor.cast` to `flow.tensor.reshape` conversion because this is occurring too early. This happens as early as `GlobalOptimization` since Flow CanonicalizerPass is used there. Also, stop cloning `tensor::CastOp`s into dispatches.

Reverted pr: https://github.com/iree-org/iree/pull/18351 Original Issue: https://github.com/iree-org/iree/issues/18229

### CODE REVIEW

**Comment by IanWood1** [comment]
Okay, it appears like everything is working. I just need to fix up `dispatch_linalg_on_tensors.mlir`

**Comment by hanhanW** [comment]
Is the plan adding shape inference to tensor.expand/collapse_shape's canonicalization patterns?

cc @nirvedhmeshram who landed the patch

**Comment by IanWood1** [comment]
Yes, I have a WIP pr https://github.com/llvm/llvm-project/pull/112265. Also, It looks like `collapse_shape` already has this pattern

**Review by nirvedhmeshram — APPROVED** [review]
LGTM, yes converting to reshape early was working around an issue of tenor.casts in dispatches at the expense of shape inference, so this way we can do that shape inference on tensors and by not cloning the casts in the dispatches the original issue wont happen. Thanks!

**Comment by IanWood1** [comment]
Given CI runs against onnx ops (https://github.com/iree-org/iree/actions/runs/11336536464/job/31526991018?pr=18772) I think this should be good to merge?

**Comment by nirvedhmeshram** [comment]
> Given CI runs against onnx ops (https://github.com/iree-org/iree/actions/runs/11336536464/job/31526991018?pr=18772) I think this should be good to merge?

The CI doesn't really test the full coverage of onnx models but if the IR in the original issue is still compiling, I think this is okay to merge.

**Comment by IanWood1** [comment]
`iree-compile` hit an assertion due to the elided dense attrs (after compilation) which I assume means it works

**Comment by nirvedhmeshram** [comment]
> `iree-compile` hit an assertion due to the elided dense attrs (after compilation) which I assume means it works

Yes, that old IR had that issue so you are good to go.

**Review by MaheshRavishankar — APPROVED** [review]

**Pull request merged**
