### PR TITLE
Bump torch-mlir to 8eb34dae78940efe529fedef5bbe96c905f3ee3b

### PR DESCRIPTION
**Pull request by jinchen62**
llvm/torch-mlir@8eb34da

### CODE REVIEW

**Comment by zjgarvey** [comment]
I'll take a look at the failures.

**Comment by jinchen62** [comment]
@zjgarvey I'm waiting for onnx_ops run on rocm and vulkan to update the json files. But I don't get the onnx_models failure.

**Comment by zjgarvey** [comment]
Yeah, it looks like the model download failed or something? Not sure. After you update the xfails, we can see if it happens again

**Review by zjgarvey — APPROVED** [review]
Can you put a link to the torch-mlir commit we are bumping to in the PR comment before merging?

Also, it looks like the timeout happened again but on a different machine. Not sure what is going on, but I don't think it is related to this patch.

**Pull request merged**
