### PR TITLE
[NFC] Move encoding logic from LinalgExt to Codegen/Common

### PR DESCRIPTION
**Pull request by hanhanW**
The revision centralizes the materialization logics. All the tests are already covered by `common/CPU/test/llvmcpu_materialize_encoding.mlir` and `common/CPU/test/vmvx_materialize_encoding.mlir`. We only add a dynamic shape test case to lit test.

- Move the implementations from LinalgExt to Codegen/Common.
- Rename `EncodingInfo.h` to `EncodingUtils.h`.
- Replace `IREE::LinalgExt::getDims` with `tensor::getMixedSizes`.

### CODE REVIEW

**Comment by hanhanW** [comment]
cc @Max191 @NatashaKnk @pzread who might touch these files.

**Review by MaheshRavishankar — COMMENTED** [review]
I wonder if there is a better dialect to move these to? They are used in Global Optimization, and not really codegen. So codegen does not seem like a good fit. Maybe Util dialect, but not sure about that.

**Comment by bjacob** [comment]
> I wonder if there is a better dialect to move these to? They are used in Global Optimization, and not really codegen. So codegen does not seem like a good fit. Maybe Util dialect, but not sure about that.

I think this is a good follow-up Issue to file, but shouldn't block this PR, which is defragmenting existing code into one place, Codegen/Common, where the bulk of it /already/ resides. After this PR, moving it to another directory is easier.

**Review by bjacob — APPROVED** [review]
Thanks @hanhanW , I had been dreaming of doing that. +844 -1399, this is great!!

**Pull request merged**
