### PR TITLE
Fix version information for iree-compile

### LINKED ISSUE #13213: iree-compile not reporting version
Released iree-compile binaries should be reporting their version (i.e. via `iree-compile --version`) but seem to be printing "unknown".

### PR DESCRIPTION
**Pull request by dellis23**
Fixes #13213

### CODE REVIEW

**Review by jpienaar — COMMENTED** [review]
Does this only trigger on release builds (e.g., nightly) or in general?

**Comment by dellis23** [comment]
I assume it would be for nightly builds, but I'm not sure what you mean for by "in general".  Are you thinking there are additional cases you would want to be handled or would want to not be handled?  @benvanik mentioned there are cases where we want to exclude it for hermeticism sake.  Actually, I should include him on the review too.

**Comment by jpienaar** [comment]
> I assume it would be for nightly builds, but I'm not sure what you mean for by "in general". Are you thinking there are additional cases you would want to be handled or would want to not be handled? @benvanik mentioned there are cases where we want to exclude it for hermeticism sake. Actually, I should include him on the review too.

Yes, my question is actually just that: is this codepath only triggered on nightly builds. And indeed in local dev, this could invalidate your compilation cache constantly for no reason.

**Comment by stellaraccident** [comment]
I found the problem on nightly builds, but all that is doing is sourcing these CMake variables from the overall environment: https://github.com/openxla/iree/blob/main/compiler/setup.py#L151 (which the CI sets up with current build info)

If you set those variables yourself and see the version info propagate properly, that should tell us it is working (and will work for releases).

**Review by benvanik — APPROVED** [review]
yeah should only happen on deployable binaries or opt-in - this PR seems to enable it on the install action which feels like the right place (building for deployment) but I'm also not too familiar with the script :)

(just don't want this by default for normal development - hermetic builds are really useful both for normal development (no need to relink everything) and for many deployments https://bazel.build/basics/hermeticity)

**Review by stellaraccident — COMMENTED** [review]
I can't comment on unchanged lines, but this may be better to update the get_cmake_version_info_args() function. I would change that to return the two existing version options and add IREE_EMBEDDED_RELEASE_INFO=ON if `version_info` evals to true. That will be set properly on CI.

I think we should set all of the version flags together in that one place and only if explicit version info is provided in the overall environment.

**Comment by dellis23** [comment]
> I can't comment on unchanged lines, but this may be better to update the get_cmake_version_info_args() function. I would change that to return the two existing version options and add IREE_EMBEDDED_RELEASE_INFO=ON if `version_info` evals to true. That will be set properly on CI.
> 
> I think we should set all of the version flags together in that one place and only if explicit version info is provided in the overall environment.

Done, though obviously I don't _really_ know if it worked since `version_info` is empty for me.

**Review by jpienaar — APPROVED** [review]

**Comment by dellis23** [comment]
Good to merge @stellaraccident?

**Review by stellaraccident — APPROVED** [review]

**Pull request merged**
