### PR TITLE
[LLVMCPU] Add support for peeling tensor.pack ops.

### PR DESCRIPTION
**Pull request by hanhanW**

### CODE REVIEW

**Comment by dcaballe** [comment]
How is that we are looking into peeling again? I thought we wanted to get rid of it due to code size concerns.

**Comment by hanhanW** [comment]
> How is that we are looking into peeling again? I thought we wanted to get rid of it due to code size concerns.

What I want to achieve is to have basic vectorization for pack ops and pack fusion with 16x16 vector shuffle approach. The dynamic shapes for pack op decomposition is quite complicated. Because there are tensor.pad ops involved and they are padded to a "dynamic shape" -- which we know that it's bounded by tiling sizes and tensor.pack inner tile sizes. I think we will be able to apply masking on such pad ops and have better codegen, but that takes some time. The peeling approach for pack op can move us to a much better state while we're working on better vectorization. IMO, we can enable 16x16 shuffle optimization for all pack ops with low hanging fruit works; we can keep adding features/needs to masking vectorization. WDYT?

**Review by dcaballe — APPROVED** [review]
Not so worried about applying masking but more about the technical debt of having and ad-hoc vectorization path for this op. Mahesh has a similar case that would benefit from masking but it's difficult if vectorization doesn't happen within the main path. It would be great if we could look into what is needed to integrate pad vectorization into the main vectorization path. Do you plan to look into that?

**Comment by hanhanW** [comment]
> Not so worried about applying masking but more about the technical debt of having and ad-hoc vectorization path for this op. Mahesh has a similar case that would benefit from masking but it's difficult if vectorization doesn't happen within the main path. It would be great if we could look into what is needed to integrate pad vectorization into the main vectorization path. Do you plan to look into that?

I only plan to add it to single pack op codegen pipeline, so we won't add much tech debt about peeling.

Yes, I plan to look into that. (or maybe we can look into that together). I think it would work if

1. We teach [lowerPack](https://github.com/llvm/llvm-project/blob/644b63bd31f55aaaf1ebafc7df7cd7cea2aa26a8/mlir/lib/Dialect/Linalg/Transforms/Transforms.cpp#L483-L489) to handle dynamic shapes.
2. We can infer the [masking size for pad op.](https://github.com/llvm/llvm-project/blob/644b63bd31f55aaaf1ebafc7df7cd7cea2aa26a8/mlir/lib/Dialect/Linalg/Transforms/Vectorization.cpp#L1411)

**Review by MaheshRavishankar — APPROVED** [review]
Was going to say the same thing as Diego... maybe we should use masking here... but your call.

**Pull request merged**
