### PR TITLE
Use zero-initialization instead of memset

### PR DESCRIPTION
**Pull request by bjacob**
Generated by:

For C files, initializing with `= {0}`:
```
git grep --name-only '\bmemset\b' | grep '\.c$' | xargs perl -0777 -i -pe 's/\n[ ]+([a-zA-Z0-9_]+)[ ]([a-zA-Z0-9_]+);\n([ ]+)memset\(\&\g2, 0, sizeof[ (]*(\g1|\g2)[)]*\);/\n$3$1 $2 = {0};/g'
```

For C++ files, initializing with `= {}`:
```
git grep --name-only '\bmemset\b' | grep '\.cc$' | xargs perl -0777 -i -pe 's/\n[ ]+([a-zA-Z0-9_]+)[ ]([a-zA-Z0-9_]+);\n([ ]+)memset\(\&\g2, 0, sizeof[ (]*(\g1|\g2)[)]*\);/\n$3$1 $2 = {};/g'
```

### CODE REVIEW

**Comment by benvanik** [comment]
I'm not sure that's valid in C++ - setting to {} doesn't zero initialize things AFAIK

https://stackoverflow.com/questions/61240589/how-to-initialize-a-struct-to-0-in-c

**Comment by benvanik** [comment]
maybe sometimes it does - ugh C++ - fiddling in compiler explorer and most compilers seem to be fine with it for the simpler structs I make but not others (like the wait handle type that has a union with an array in it)

**Comment by bjacob** [comment]
Indeed, saw the CI failure with Asan (reproduced locally). https://en.cppreference.com/w/cpp/language/zero_initialization . Unions are the one thing where this blows up as only the first member gets initialized. 

(The other thing is members of reference type, but we probably don't have any in the kind of simple structs that we would zero-initialize and also, zero-initializing a reference would be UB anyway).

**Comment by kuhar** [comment]
> maybe sometimes it does - ugh C++ - fiddling in compiler explorer and most compilers seem to be fine with it for the simpler structs I make but not others (like the wait handle type that has a union with an array in it)

AFAIU `= {}` initializes the first union member and makes it be the active member, unless there's a user-declared constructor provided. To me the right thing to do (for c++ files) when union members have different sizes is to provide a constructor and memset the whole thing: https://godbolt.org/z/EsEdsYs9c

**Comment by benvanik** [comment]
> > maybe sometimes it does - ugh C++ - fiddling in compiler explorer and most compilers seem to be fine with it for the simpler structs I make but not others (like the wait handle type that has a union with an array in it)
> 
> AFAIU `= {}` initializes the first union member and makes it be the active member, unless there's a user-declared constructor provided. To me the right thing to do (for c++ files) when union members have different sizes is to provide a constructor and memset the whole thing: https://godbolt.org/z/EsEdsYs9c

yeah, thinking that memset is the least surprising thing here and consistent everywhere. It's been the way to zero memory in C for 30+ years :)

**Comment by bjacob** [comment]
SG :-)

**Pull request closed without merging**
