### PR TITLE
[GlobalOpt] Generalize Linalg named ops after graph level optimization.

### PR DESCRIPTION
**Pull request by hanhanW**
Some Linalg named ops are created at graph level optimization. E.g., we
could generate `linalg.transpose` ops in data-tiling path. IREE wants
some named ops being in generic form because they are better handled by
IREE as `linalg.generic` ops.

It also moves `createLiftGenericToTransposeBatchMatmulPass` to the single if-statement.

### CODE REVIEW

**Comment by hanhanW** [comment]
It does not impact our benchmark suite. I noticed the issue when I was debugging other things. It is still a good thing to have before going to const-eval and flow.

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
The generalization of named ops needs to trigger always. All the linalg named ops might not be supported as is, and some of them hamper fusion (like linalg.map as-is wont fuse with other elementwise operations).

**Comment by hanhanW** [comment]
> The generalization of named ops needs to trigger always. All the linalg named ops might not be supported as is, and some of them hamper fusion (like linalg.map as-is wont fuse with other elementwise operations).

I totally agree with you. This is why I invoke the pass again at the end of data-tiling part.

**Review by MaheshRavishankar — APPROVED** [review]
Ah you invoke it again. Makes sense.

**Pull request merged**
