### PR TITLE
Integrate LLVM at llvm/llvm-project@1a6ec906fb37

### PR DESCRIPTION
**Pull request by hanhanW**
- Cherry pick https://github.com/llvm/llvm-project/commit/bb82092de71466728630050691fa9c20796b3cbc

### CODE REVIEW

**Comment by hanhanW** [comment]
https://github.com/llvm/llvm-project/pull/85016 should fix the issue. I will cherry-pick it once it's landed.

**Comment by hanhanW** [comment]
The regression happens because we dont fuse `unpack -> generic` anymore, looking..

**Comment by hanhanW** [comment]
The issue happens when we fold unit dims, there are additional `tensor.expand_shape` bubbled up which becomes a fusion barrier between unpack and generic op. We don't see any reshape ops after outlining dispatches because we run CollapseDims after FormDispatchRegion. The pass creates below snippet and folds the reshapes away.

```mlir
  %75 = flow.dispatch.region -> (tensor<784x96xf32>) {
    %unpack = tensor.unpack %74 outer_dims_perm = [0, 1] inner_dims_pos = [0, 1] inner_tiles = [16, 16] into %72 : tensor<49x6x16x16xf32> -> tensor<784x96xf32>
    flow.return %unpack : tensor<784x96xf32>
  }
  %expanded_100 = tensor.expand_shape %75 [[0, 1], [2]] : tensor<784x96xf32> into tensor<28x28x96xf32>
  %76 = tensor.empty() : tensor<28x28x96xf32>
  %collapsed_101 = tensor.collapse_shape %expanded_100 [[0, 1], [2]] : tensor<28x28x96xf32> into tensor<784x96xf32>
  %77 = flow.dispatch.region -> (tensor<784x96xf32>) {
    %cst_253 = arith.constant 0.166666672 : f32
    %cst_254 = arith.constant 0.000000e+00 : f32
    %cst_255 = arith.constant 6.000000e+00 : f32
    %cst_256 = arith.constant 3.000000e+00 : f32
    %330 = tensor.empty() : tensor<784x96xf32>
    %331 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%collapsed_101, %cst_36 : tensor<784x96xf32>, tensor<96xf32>) o
    ^bb0(%in: f32, %in_258: f32, %out: f32):
      %332 = arith.addf %in, %in_258 : f32
      %333 = arith.addf %332, %cst_256 : f32
      %334 = arith.minimumf %333, %cst_255 : f32
      %335 = arith.maximumf %334, %cst_254 : f32
      %336 = arith.mulf %332, %335 : f32
      %337 = arith.mulf %336, %cst_253 : f32
      linalg.yield %337 : f32
    } -> tensor<784x96xf32>
    %expanded_257 = tensor.expand_shape %331 [[0, 1], [2]] : tensor<784x96xf32> into tensor<28x28x96xf32>
    flow.return %331 : tensor<784x96xf32>
  }
```

**Comment by hanhanW** [comment]
We are quite behind now, can we land it with regressions? I think reshape propagation would help, and I can help with that afterwards.

**Review by stellaraccident — APPROVED** [review]
Sounds ok to me.

**Pull request merged**
