### PR TITLE
Integrate llvm-project at 0258a53521cf  and bump dependencies

### PR DESCRIPTION
**Pull request by dcaballe**
* llvm-project: 0258a53521cf
* mlir-mhlo: 63a907f9839f06863a64d7f47d059624f7e035bf

### CODE REVIEW

**Comment by dcaballe** [comment]
Clean integrate, it seems. Enabling auto-merge.

**Review by hanhanW — APPROVED** [review]

**Comment by hanhanW** [comment]
I disabled auto-merge because we want to check regressions before landing it. (just in case)

**Comment by dcaballe** [comment]
I'm curious... How are the benchmark running? I don't see the benchmark labels on my side

**Comment by ScottTodd** [comment]
> I'm curious... How are the benchmark running? I don't see the benchmark labels on my side

Benchmarks run by default on "LLVM integrate PRs", which are detected with this logic: https://github.com/openxla/iree/blob/dd5aac13ed95399770543c3cbdc4a7846d4fa99a/build_tools/github_actions/configure_ci.py#L93-L101

**Pull request merged**
