### PR TITLE
Change lowering to make `AttentionOp`'s outermost iterators parallel

### PR DESCRIPTION
**Pull request by IanWood1**
Change lowering to make `AttentionOp`'s outermost iterators parallel and innermost iterators reduction. This is done by making k1 & k2 the right most affine dim expr.

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
This is probably exposing some correctness issues during codegen. @Groverkss  you need to guide how to land these PRs. We can hold off till cpp attention pipeline is ready to be flipped on.

**Comment by Groverkss** [comment]
> This is probably exposing some correctness issues during codegen. @Groverkss you need to guide how to land these PRs. We can hold off till cpp attention pipeline is ready to be flipped on.

This is crashing the attention transform script in sdxl-scripts afaiu, because you changed the order of dimensions. I can send a fix tomorrow. You can land this if you want.

**Comment by MaheshRavishankar** [comment]
> > This is probably exposing some correctness issues during codegen. @Groverkss you need to guide how to land these PRs. We can hold off till cpp attention pipeline is ready to be flipped on.
> 
> This is crashing the attention transform script in sdxl-scripts afaiu, because you changed the order of dimensions. I can send a fix tomorrow. You can land this if you want.

I'd rather wait for the c++ pipeline and not waste your time on the transform scripts.

**Comment by ScottTodd** [comment]
> > > This is probably exposing some correctness issues during codegen. @Groverkss you need to guide how to land these PRs. We can hold off till cpp attention pipeline is ready to be flipped on.
> > 
> > 
> > This is crashing the attention transform script in sdxl-scripts afaiu, because you changed the order of dimensions. I can send a fix tomorrow. You can land this if you want.
> 
> I'd rather wait for the c++ pipeline and not waste your time on the transform scripts.

Can we delete https://github.com/iree-org/iree/blob/main/build_tools/pkgci/external_test_suite/attention_and_matmul_spec.mlir  ? Then also stop using at it https://github.com/iree-org/iree/blob/d8d140764c40c328537e374e9143ca6bab8f5a14/experimental/regression_suite/shark-test-suite-models/sdxl/test_unet.py#L89-L93

I'm not sure if that's implicated in the error logs, maybe they are separable issues: https://github.com/iree-org/iree/actions/runs/10167277834/job/28119806233?pr=18047#step:7:181

```
popenargs = (['iree-run-module', '--device=hip', '--module=/mnt/share/amdsharks/iree_tests_cache/artifacts/sdxl_unet/model.rocm_gf...module=/mnt/share/amdsharks/iree_tests_cache/artifacts/sdxl_unet/sdxl_unet_pipeline_bench_f16.rocm_gfx90a.vmfb', ...],)
kwargs = {'cwd': PosixPath('/mnt/share/amdsharks/iree_tests_cache/artifacts/sdxl_unet'), 'stderr': -1, 'stdout': -1}
process = <Popen: returncode: 1 args: ['iree-run-module', '--device=hip', '--module=/m...>
stdout = b'EXEC @produce_image_latents\n[FAILED] result[0]: element at index 8063 (0.490479) does not match the expected (1.198......][...][...][...][...][...][...][...][...][...][...][...][...][...][...][...][...][...][...][...][...][...][...]]]\n'
stderr = b'', retcode = 1
```

**Comment by MaheshRavishankar** [comment]
Yeah thats exactly what we need first!

**Comment by IanWood1** [comment]
I think this should work now? https://github.com/iree-org/iree/pull/18074 should have removed the dependence on TD scripts for attention

**Comment by raikonenfnu** [comment]
> I think this should work now? #18074 should have removed the dependence on TD scripts for attention

Looks like it's passing even on TD script?

**Review by MaheshRavishankar — APPROVED** [review]

**Pull request merged**
