### PR TITLE
Disable LSAN in the ASAN tests on Vulkan

### LINKED ISSUE #11203: tensor_cast asan flake
https://github.com/iree-org/iree/actions/runs/3492591056/jobs/5846535193 (which was a presubmit run testing other stuff, but should still be representative) had a failure in `iree/tests/e2e/tensor_ops/tensor_cast.mlir.test` only when run a bunch of times. The logs are not super helpful though:

```
2022-11-17T22:58:53.5635431Z  588/1085 Test  #136: iree/tests/e2e/tensor_ops/tensor_cast.mlir.test ..........................................................***Failed    2.99 sec
2022-11-17T22:58:53.5636685Z -- Testing: 1 tests, 1 workers --
2022-11-17T22:58:53.5673679Z FAIL: IREE :: e2e/tensor_ops/tensor_cast.mlir (1 of 1)
2022-11-17T22:58:53.5675536Z ******************** TEST 'IREE :: e2e/tensor_ops/tensor_cast.mlir' FAILED ********************
2022-11-17T22:58:53.5676066Z Script:
2022-11-17T22:58:53.5676456Z --
2022-11-17T22:58:53.5677664Z : 'RUN: at line 1';   iree-run-mlir --iree-hal-target-backends=llvm-cpu /work/tests/e2e/tensor_ops/tensor_cast.mlir | FileCheck /work/tests/e2e/tensor_ops/tensor_cast.mlir
2022-11-17T22:58:53.5679528Z : 'RUN: at line 2';   [[ $IREE_VMVX_DISABLE == 1 ]] || (iree-run-mlir --iree-hal-target-backends=vmvx /work/tests/e2e/tensor_ops/tensor_cast.mlir | FileCheck /work/tests/e2e/tensor_ops/tensor_cast.mlir)
2022-11-17T22:58:53.5681710Z : 'RUN: at line 3';   [[ $IREE_VULKAN_DISABLE == 1 ]] || (iree-run-mlir --iree-hal-target-backends=vulkan-spirv /work/tests/e2e/tensor_ops/tensor_cast.mlir | FileCheck /work/tests/e2e/tensor_ops/tensor_cast.mlir)
2022-11-17T22:58:53.5682646Z --
2022-11-17T22:58:53.5683006Z Exit Code: 1
2022-11-17T22:58:53.5683266Z 
2022-11-17T22:58:53.5683441Z Command Output (stderr):
2022-11-17T22:58:53.5683889Z --
2022-11-17T22:58:53.5684402Z Tracer caught signal 11: addr=0x4978 pc=0x55726567fa9a sp=0x7f88659f9d40
2022-11-17T22:58:53.5685027Z ==47855==LeakSanitizer has encountered a fatal error.
2022-11-17T22:58:53.5685788Z ==47855==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
2022-11-17T22:58:53.5687135Z ==47855==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
2022-11-17T22:58:53.5687562Z 
2022-11-17T22:58:53.5687757Z --
2022-11-17T22:58:53.5687958Z 
2022-11-17T22:58:53.5693532Z ********************
2022-11-17T22:58:53.5762529Z ********************
2022-11-17T22:58:53.5762959Z Failed Tests (1):
2022-11-17T22:58:53.5763535Z   IREE :: e2e/tensor_ops/tensor_cast.mlir
2022-11-17T22:58:53.5763856Z 
2022-11-17T22:58:53.5763867Z 
2022-11-17T22:58:53.5764044Z Testing Time: 2.82s
```

### PR DESCRIPTION
**Pull request by bjacob**
Fixes #11203.

This PR started out as a tentative massaging of LSAN to avert some issue on CI bots, but that didn't work and it later appeared that there was a rich history of LSAN issues with Swiftshader and the correct course of action was to disable the LSAN part of ASAN when running ASAN tests on Vulkan.

Reusing this PR so we keep the motivating history in one place. See the below https://github.com/iree-org/iree/pull/11206#issuecomment-1320578288

### CODE REVIEW

**Comment by bjacob** [comment]
amazing, this reveals a proper LeakSanitizer leak report. reverting to draft, need to resolve that.

**Comment by bjacob** [comment]
I have debugged this as far down as I could. The issue is specific to Vulkan driver. The LSAN reports don't contain much information:

```
Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x55f965b14a9e in malloc (/work/build-asan/tools/iree-check-module+0x118a9e) (BuildId: da70135225776a21b58d75a24af3a71af4421586)
    #1 0x7f674a1f5e4d  (/lib64/ld-linux-x86-64.so.2+0x13e4d) (BuildId: 61ef896a699bb1c2e4e231642b2e1688b2f1a61e)
```

This LSAN issue does not reproduce locally, even with Swiftshader built by `build_tools/third_party/swiftshader/build_vk_swiftshader.sh`.

Essentially the only piece of information in the above CI log is the allocation size, which is consistently 48 bytes, and the number of blocks leaked, which is consistently 1.

So all I could do was to set a breakpoint on `malloc` and make it conditional on the first argument register (`rdi`) being 48.

```
(gdb) b malloc if $rdi==48
```

Resulting log: https://gist.github.com/bjacob/79d2ab308161ade9dd1eb3570bdee156

All the hits are in Vulkan calls below `iree_hal_vulkan_driver_create`. I couldn't find one that would be a plausible leak (and indeed, the leak report doesn't reproduce outside of CI). I can only guess that some system library on the CI host, either `libc` or `libvulkan`, is somehow LSAN-unfriendly.

My best shot at this point would be to disable LSAN (keeping ASAN) for Vulkan tests...

**Comment by GMNGeoffrey** [comment]
Did you try reproing within the docker container? That should give you exactly the same environment.

**Comment by bjacob** [comment]
I haven't. But now that @ScottTodd  has brought up the history of LSAN issues he's dealt with in the past when he initially enabled ASan/Vulkan and which motivated the current disabled tests (https://github.com/iree-org/iree/pull/8489 ), I realize all this is just one more iteration of that, and we are better off giving up with LSAN on Vulkan, by splitting the ASan tests between Vulkan and other backends, and for Vulkan, running with `ASAN_OPTIONS=detect_leaks=0`, which will disable LSAN and thus allow us to reenable ASAN testing on more Vulkan tests.

**Review by antiagainst — APPROVED** [review]

**Pull request merged**
