### PR TITLE
[Flow] Re-enable dynamic shaped dequant fusion

### PR DESCRIPTION
**Pull request by qedawkins**
Support was added for the SPIR-V backend in #14751

### CODE REVIEW

**Comment by stellaraccident** [comment]
Hey Quinn, this seems to be hanging the vulkan/and test runner. I haven't verified but generally, this signals a very large compile time regression. Going to cancel and restart that workflow.

**Comment by qedawkins** [comment]
> Hey Quinn, this seems to be hanging the vulkan/and test runner. I haven't verified but generally, this signals a very large compile time regression. Going to cancel and restart that workflow.

Interesting, compilation was fast for what I thought was the same test locally. Would be nice to know exactly what is running there.

**Comment by stellaraccident** [comment]
Probably just the victim and can ignore. The machine seems to have died.

**Comment by qedawkins** [comment]
How do I get the gh workflow ID to reproduce locally based on: https://github.com/openxla/iree/tree/main/experimental/regression_suite? 224 didn't seem to work

**Comment by stellaraccident** [comment]
https://github.com/openxla/iree/actions/runs/6029468984/job/16360467138?pr=14885

The first number in that url

Thanks for beta testing

**Comment by qedawkins** [comment]
hmmm I'm guessing because the job was cancelled it never built the necessary packeges?
```
Package iree-compiler not found. Fetching from linux_x86_64_release_packages...
Fetching artifacts for workflow run 6029468984
Found artifacts:
  linux_x86_64_release_packages: /repos/openxla/iree/actions/artifacts/894068276/zip
Downloading artifact /repos/openxla/iree/actions/artifacts/894068276/zip
Extracting /tmp/tmpw3w_9ja5/linux_x86_64_release_packages.zip
Installing wheels: [(PosixPath('/tmp/tmpw3w_9ja5'), 'iree-compiler'), (PosixPath('/tmp/tmpw3w_9ja5'), 'iree-runtime')]
Running command: /tmp/iree_gh_venv/bin/python -m pip install --no-deps --no-index -f /tmp/tmpw3w_9ja5 --force-reinstall iree-compiler
Looking in links: /tmp/tmpw3w_9ja5
ERROR: Could not find a version that satisfies the requirement iree-compiler (from versions: none)
ERROR: No matching distribution found for iree-compiler
Traceback (most recent call last):
  File "/home/quinn/SHARK-Runtime/./build_tools/pkgci/setup_venv.py", line 234, in <module>
    sys.exit(main(parse_arguments()))
  File "/home/quinn/SHARK-Runtime/./build_tools/pkgci/setup_venv.py", line 119, in main
    return main(args)
  File "/home/quinn/SHARK-Runtime/./build_tools/pkgci/setup_venv.py", line 170, in main
    subprocess.check_call(cmd)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/iree_gh_venv/bin/python', '-m', 'pip', 'install', '--no-deps', '--no-index', '-f', '/tmp/tmpw3w_9ja5', '--force-reinstall', 'iree-compiler']' returned non-zero exit status 1.

```

**Comment by stellaraccident** [comment]
> hmmm I'm guessing because the job was cancelled it never built the necessary packeges?
> 
> ```
> Package iree-compiler not found. Fetching from linux_x86_64_release_packages...
> Fetching artifacts for workflow run 6029468984
> Found artifacts:
>   linux_x86_64_release_packages: /repos/openxla/iree/actions/artifacts/894068276/zip
> Downloading artifact /repos/openxla/iree/actions/artifacts/894068276/zip
> Extracting /tmp/tmpw3w_9ja5/linux_x86_64_release_packages.zip
> Installing wheels: [(PosixPath('/tmp/tmpw3w_9ja5'), 'iree-compiler'), (PosixPath('/tmp/tmpw3w_9ja5'), 'iree-runtime')]
> Running command: /tmp/iree_gh_venv/bin/python -m pip install --no-deps --no-index -f /tmp/tmpw3w_9ja5 --force-reinstall iree-compiler
> Looking in links: /tmp/tmpw3w_9ja5
> ERROR: Could not find a version that satisfies the requirement iree-compiler (from versions: none)
> ERROR: No matching distribution found for iree-compiler
> Traceback (most recent call last):
>   File "/home/quinn/SHARK-Runtime/./build_tools/pkgci/setup_venv.py", line 234, in <module>
>     sys.exit(main(parse_arguments()))
>   File "/home/quinn/SHARK-Runtime/./build_tools/pkgci/setup_venv.py", line 119, in main
>     return main(args)
>   File "/home/quinn/SHARK-Runtime/./build_tools/pkgci/setup_venv.py", line 170, in main
>     subprocess.check_call(cmd)
>   File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['/tmp/iree_gh_venv/bin/python', '-m', 'pip', 'install', '--no-deps', '--no-index', '-f', '/tmp/tmpw3w_9ja5', '--force-reinstall', 'iree-compiler']' returned non-zero exit status 1.
> ```

Ah, it only builds for 3.11. Don't worry about it. I'm pretty sure this was machine death, not you. Will see it in post submit

**Comment by stellaraccident** [comment]
Runner came back and ran fine. Sorry for the false alarm.

**Review by stellaraccident — APPROVED** [review]

**Pull request merged**
