### PR TITLE
Initial CI workflow

### PR DESCRIPTION
**Pull request by GMNGeoffrey**
There doesn't seem to be a great way to test this without pushing :-/

### CODE REVIEW

**Comment by benvanik** [comment]
btw this has mostly working configurations for windows, linux, and mac:
https://github.com/google/iree/blob/benvanik-ci/.github/workflows/build_and_test.yml

it also shows how to do a matrix setup with compiler/build systems/etc

**Comment by GMNGeoffrey** [comment]
Yeah I'm referencing that, but wanted to get something working and then iterate

**Comment by benvanik** [comment]
cool - lemme know when you get it working

**Comment by GMNGeoffrey** [comment]
I thought I needed to have a PR to test this. Let's stop spamming people

**Pull request closed without merging**
