### PR TITLE
[TOSA] Align with custom assembly format change

### PR DESCRIPTION
**Pull request by tatwaichong**
Synchronize to the recent change in mlir.

This is the corresponding change to https://reviews.llvm.org/D155231. (haven't been landed yet)

### CODE REVIEW

**Comment by hanhanW** [comment]
cool, thanks!

**Review by jpienaar — APPROVED** [review]
Thanks!

**Review by hanhanW — CHANGES_REQUESTED** [review]
This will be landed with an integrate commit.

**Comment by tatwaichong** [comment]
Kindly remind that https://reviews.llvm.org/D155231 has been merged, free feel to adopt this PR to match.

**Comment by hanhanW** [comment]
> Kindly remind that https://reviews.llvm.org/D155231 has been merged, free feel to adopt this PR to match.

Thanks, I'll include the change in the next integrate!

**Comment by tatwaichong** [comment]
Close this PR as it has been merged along with integration.

**Pull request closed without merging**
