### PR TITLE
Split out accumulation into existing accumulator into separate generic op in e2e matmul test.

### PR DESCRIPTION
**Pull request by ThomasRaoux**
DetachElementWise pass used to transform matmul into the generic form but after https://github.com/openxla/iree/pull/10443 this is not happening anymore. Change the tool to directly use the canonical form so that we test the right form.

### CODE REVIEW

**Review by bjacob — CHANGES_REQUESTED** [review]
(not sure why my comment was posted twice, sorry).

**Review by bjacob — CHANGES_REQUESTED** [review]
This is problematic wrt the CPU path we're building --- if accumulating into an existing accumulator, representing that as such in the `linalg.matmul`, not detaching it into a separate `linalg.generic`, allows us to carry that into the `linalg.mmt4d` after data-tiling and then into the `mmt4d` ukernel. We lose that when we split that out into a separate generic op. This would thus result in this e2e matmul test no longer testing the accummulating-into-existing-accumulator part of the ukernels.

If this is desirable for some backend like CUDA, OK to do that conditionally on backend.

That was basically the criticism against DetachElementWise: it was doing prematurely, for all backends, something that is only desirable on some backends.

**Comment by ThomasRaoux** [comment]
> This is problematic wrt the CPU path we're building --- if accumulating into an existing accumulator, representing that as such in the `linalg.matmul`, not detaching it into a separate `linalg.generic`, allows us to carry that into the `linalg.mmt4d` after data-tiling and then into the `mmt4d` ukernel. We lose that when we split that out into a separate generic op. This would thus result in this e2e matmul test no longer testing the accummulating-into-existing-accumulator part of the ukernels.
> 
> If this is desirable for some backend like CUDA, OK to do that conditionally on backend.
> 
> That was basically the criticism against DetachElementWise: it was doing prematurely, for all backends, something that is only desirable on some backends.

Thanks for explaining, Benoit. I thoight this form is what we had picked as the canonical form and that’s what front ends would generate? In that case I thought we would want to test that for all the backends. In general that’s the form I see in models. Aren’t you scared we are testing a corner case here. 
I can surely had a condition to use that form on for GPU if you think this is the better solution.
Let me know what you prefer.

**Comment by bjacob** [comment]
It's true that the input dialects that we import into Linalg from, have accumulator-less matmuls:

* In TOSA there is `tosa.matmul` and it does not accumulate into an existing accumulator.
  - https://www.mlplatform.org/tosa/tosa_spec.html#_matmul
  - https://mlir.llvm.org/docs/Dialects/TOSA/#tosamatmul-mlirtosamatmulop
* In MHLO there is `mhlo.dot_general` and it also does not accumulate into an existing accumulator.
  - https://www.tensorflow.org/mlir/hlo_ops#mhlodot_general_mlirmhlodotgeneralop

Moreover, regardless of these particular dialects (but probably the cause of their design choices here), it is true that in NN applications, the most common case of matmuls is not accumulating into an existing accumulator.

However, the present test is a test for `linalg.matmul`, and that is accumulating into an existing accumulator. We want this test to ensure that all cases of `linalg.matmul` are e2e-correct.

It is often the case that the accumulator is produced by a fill-zero and that the codegen backend will have a pattern matching that into an accumulator-less matmul; we have a flavor of that in CPU ukernels where the accumulation into existing accumulator is controlled by a flag bit on the ukernel, so we have a pattern checking for such a fill-zero and setting the flag bit accordingly.  That's to say that I agree that we should be testing the fill-zero-accumulator case, already for my CPU purposes -- and I didn't realize/remember, but indeed it's true that at the moment we are not testing it. So yes, we need something along the lines of this PR.

But codegen patterns can go both ways: just like a pattern can match `fill-zero -> linalg.matmul`, there could just as well be a pattern going in the reverse direction, transforming the sequence as in this PR, `fill-zero -> linalg.matmul -> generic add to existing accumulator` into just `linalg.matmul`.

In summary, I have 2 concerns with the current state of this PR:
- It is changing the test from covering one of two `linalg.matmul` cases (existing accumulator) into another one of two cases (zero accumulator).  Instead, we should be testing both.
- The IR it generates could in fact be rewritten back into the accumulating `linalg.matmul` form, we can't know what we are effectively testing here.

This could be addressed as follows instead:

In the high level code driving how each test case is generated by calling `generate_function` and `generate_trace`, another dimension needs to be introduced, a boolean `accumulate`. One way to introduce that dimension without increasing the number of testcases and test latency would be to just pick it pseudorandom. Or you could spend more time reasoning about how to change the set of testcases being iterated over to add that dimension without multiplying the number of testcases by 2x overall (only add that in some cases, not all).
https://github.com/openxla/iree/blob/9fc77dd38f4bc42df469dd94627039b86df832a6/tests/e2e/matmul/generate_e2e_matmul_tests.py#L507-L517

You would pass that boolean `accumulate` to both `generate_function` and `generate_trace`.

In `generate_function`:

* When `accumulate` is `true`, keep generating the current `linalg.matmul`.
* When `accumulate` is `false`, do the zero-fill accumulator but (that's the key nuance from the current state of this PR) *do not* do the `linalg.generic` adding the accumulator. Just drop the accumulator input altogether -- the MLIR `func` you're generating now only takes `lhs` and `rhs` args.

In `generate_trace`, correspondingly, if `accumulate` is false, drop the accumulator altogether. As the `func` to be called no longer takes an accumulator arg.

**Comment by ThomasRaoux** [comment]
Thanks for the suggestions. One thing that confuse me is that as you point out in the quote below, the transformation could go both way and the IR are equivalent. 

> But codegen patterns can go both ways: just like a pattern can match fill-zero -> linalg.matmul, there could just as well be a pattern going in the reverse direction, transforming the sequence as in this PR, fill-zero -> linalg.matmul -> generic add to existing accumulator into just linalg.matmul.

To me that mean we should pick a single canonical form and transform the other form into the canonical one. This way we only need to handle one case in the backend rather than having to support two. This also reflects in the testing, if we could always convert one of the representation to the other one then we don't have to test both.
That's kind of what was the state of IREE until the change of `DetachElementWise` so I'm trying to understand why it is better to support two equivalent form of the IR rather than just one.

I understand that we want to test linalg.matmul however it should be valid for IREE to transform linalg.matmul to fill + matmul + add as a first step. Does that mean we should revert back to have `DetachElementWise` consistently do this transformation?

I know this doesn't directly answer your points but I'm trying to make sure I understand the problem before adding extra code in the test framework (and the potentially the backend)

**Comment by ThomasRaoux** [comment]
Is the problem that the fill + matmul + add is not a good representation for the CPU and mmt4d case? I guess one other solution would be to do the transformation from matmul to  fill + matmul + add into the backends that prefer it.

**Comment by bjacob** [comment]
The following two things are equivalent:

1. `linalg.matmul` with existing accumulator.
2. `zero-fill -> linalg.matmul -> linalg.generic adding the existing accumulator`.

The following two things are **not** equivalent:

1. `linalg.matmul` with existing accumulator.
2. [...]
3. `zero-fill -> linalg.matmul`.

The initial shape of this PR was changing 1. into 2. and my concerns were:
  * We want to continue covering 1.
  * That doesn't have to make any practical difference as codegen patterns might silently revert 2. back to 1.
  * If such a pattern kicks in, that still does not cover 3.

I'm proposing to change this PR to instead test 1. and 3.

We can't designate one form as "canonical" and test only that because then we are not guaranteed to hit all code paths of a backend that has separate code paths for the accumulating vs non-accumulating cases. We have such [separate code paths](https://github.com/openxla/iree/blob/bb21d92f144fc6e6d5ae465f2e5fb5905f7dcbf9/runtime/src/iree/builtins/ukernel/arch/arm_64/mmt4d_arm_64_i8mm.c#L43) within CPU ukernels.

We also shouldn't over-specialize our implemenation and testing of `linalg.matmul` to the current usage patterns. Even if the accumulating case is currently relatively little used, usage could pick up any time:
* Even though NNs are typically non-accumulating matmuls,  it's easy to think of transformations that would turn them into accumulating matmul:
   * Tile-and-distribute tiling along the K dimension would effectively transform one large non-accumulating `linalg.matmul` into smaller accumulating `linalg.matmul`. That's probably the best illustration why the perfect-loop-nest (ie accumulating) nature of linalg ops is a valuable trait for purposes of IREE codegen.
   * NNs do things like bias-addition that are typically looking like your linalg.generic adding to matmul result and a codegen pattern could rewrite that as an accumulating matmul.
* Even though the initial usage pattern is to ingest TOSA or *HLO, we could easily imagine other usage patterns coming from places where accumulating-matmul is the default. For example, BLAS GEMM is accumulating, if people ever start porting more general compute workloads.

That is to say that we really can't make assumptions either way about which of the accumulating or non-accumulating case is "canonical". It was a mistake for DetachElementWise to run unconditionally in Flow. Such a pass can only make sense in Codegen for one specific backend where we know that's the form we want to get in that backend.

**Comment by bjacob** [comment]
> Is the problem that the fill + matmul + add is not a good representation for the CPU and mmt4d case? I guess one other solution would be to do the transformation from matmul to fill + matmul + add into the backends that prefer it.

Yes, exactly.

**Comment by nicolasvasilache** [comment]
Do we have a path forward here?
#13492 is blocked on this.

**Comment by bjacob** [comment]
Thanks, that's useful info, I didn't know anything was blocked on this.
The path forward is clear in my mind so I'll just do it. (See my above comment, "I'm proposing to change this PR to instead test 1. and 3.").

**Comment by bjacob** [comment]
#13657 implements my proposal here.

**Comment by bjacob** [comment]
#13657 is merged. Close this?

**Comment by nicolasvasilache** [comment]
thanks @bjacob !

**Pull request closed without merging**
