### PR TITLE
Add swizziling using transform dialect

### PR DESCRIPTION
**Pull request by erman-gurses**
It connects the swizzling algorithm in the upstream LLVM with IREE using transform dialect.
See the LLVM upstream implementation: https://github.com/llvm/llvm-project/pull/79164

### CODE REVIEW

**Review by MaheshRavishankar — APPROVED** [review]
Nice!

**Comment by hanhanW** [comment]
I don't see any IREE specific logics. Shouldn't we add the transform op upstream and use it in IREE? Do we plan to upstream them later?

**Comment by MaheshRavishankar** [comment]
Yeah good point. @harsh-nod and @erman-gurses  can we add this upstream?

**Comment by Groverkss** [comment]
Can you not just run the pass directly? https://mlir.llvm.org/docs/Dialects/Transform/#transformapply_registered_pass-transformapplyregisteredpassop

**Comment by erman-gurses** [comment]
> Yeah good point. @harsh-nod and @erman-gurses can we add this upstream?

@MaheshRavishankar, @hanhanW, @Groverkss, I will look for a way to do that.

**Comment by erman-gurses** [comment]
Two PRs are landed to LLVM upstream regarding this PR.
https://github.com/llvm/llvm-project/pull/81550
https://github.com/llvm/llvm-project/pull/81791

**Pull request closed without merging**
