### PR TITLE
Integrate llvm-project at 913f21ae5c46

### PR DESCRIPTION
**Pull request by hanhanW**
* Reset third_party/llvm-project: 913f21ae5c460d6fdd73ac7663534e73f8e19044 (2023-08-11 10:17:01 -0700): [TextAPI] Express MH_SIM_SUPPORT in tbd files.

Cherry-pick:

* llvm/llvm-project@81c326ccdd9b8475b6b7180da36b24bb29ce4f42
* llvm/llvm-project@2b066501b1bcb21c408310e6cfca31ba02068736
* llvm/llvm-project@69a3c9cddf1919b7caaa625efa1829cd5628bf10
* llvm/llvm-project@1a38843f86df67e28b5aa2080195ab955cafb94e

### CODE REVIEW

**Comment by hanhanW** [comment]
@matthias-springer I think I have a [bad fix](https://github.com/openxla/iree/pull/14659/commits/b8654b911a9a766f31884c9ee566dd088580aeff) for https://github.com/llvm/llvm-project/commit/977cb4fdf8033548ec3e8a1bec7fc8e0e2fc0a62

I thought that the default behavior is just replace `false` with `none` string, but it hits an assertion. Could you help take a look?

**Comment by hanhanW** [comment]
never mind, other usages of `padAndHoistLinalgOp` is not updated. I have a fix now.

**Comment by hanhanW** [comment]
We got several failures about cuda backend. @MaheshRavishankar do you know who can help on this?

```
/work/runtime/src/iree/hal/drivers/cuda/native_executable.c:102: INTERNAL; CUDA driver error 'CUDA_ERROR_INVALID_PTX' (218): a PTX JIT compilation failed; while invoking native function hal.executable.create; while calling import; 
```

```
The following tests FAILED:
	174 - iree/tests/e2e/regression/check_regression_cuda_reduction_broadcast_elementwise.mlir (Subprocess aborted)
	176 - iree/tests/e2e/regression/check_regression_cuda_softmax.mlir (Subprocess aborted)
	179 - iree/tests/e2e/regression/aggressive_fusion_test_cuda_softmax.mlir (Subprocess aborted)
	180 - iree/tests/e2e/regression/aggressive_fusion_test_cuda_softmax_large.mlir (Subprocess aborted)
	735 - iree/tests/transform_dialect/cuda/softmax.mlir.test (Failed)
	736 - iree/tests/transform_dialect/cuda/softmax_partial.mlir.test (Failed)
```

**Comment by MaheshRavishankar** [comment]
Previous integration had a revert. You need to do the revert here too

**Comment by hanhanW** [comment]
> Previous integration had a revert. You need to do the revert here too

I see, thanks! Let me give it a shot

**Review by ScottTodd — APPROVED** [review]

**Pull request merged**
