### PR TITLE
Integrate llvm-project at llvm/llvm-project@b16372c

### PR DESCRIPTION
**Pull request by kuhar**
* Reset third_party/llvm-project: llvm/llvm-project@b16372c5fc65a6a7c14c19f01b17ac15a964d21f (2023-07-13 10:15:34 +0800): [PowerPC][MC] Set 'future' as default CPU type of XCOFF
* Cherry-pick: https://reviews.llvm.org/D155189: [mlir][nvvm] Add populate function (nfc)
* Cherry-pick: https://reviews.llvm.org/D155060: [mlir][nvvm] Add `cp.async.bulk.tensor.shared.cluster.global`

### CODE REVIEW

**Comment by kuhar** [comment]
Only 2 test failures, will take a closer look tomorrow:
```
The following tests FAILED:
        879 - iree/compiler/Codegen/LLVMGPU/test/nvvm_mma_sync_pipeline_test.mlir.test (Failed)
        880 - iree/compiler/Codegen/LLVMGPU/test/nvvm_pipeline_test.mlir.test (Failed)
```

**Comment by kuhar** [comment]
These are the same test that failed in https://github.com/openxla/iree/pull/14386#issuecomment-1632707395. FYI, @grypp, since you are most familiar with this.

**Comment by grypp** [comment]
@kuhar I have to add a new pass into nvidia pipeline. I put PR #14395.

**Comment by kuhar** [comment]
Looks good except for some potential performance regression on valhall. Do we know of anything recent that could have caused this, @antiagainst?

**Review by MaheshRavishankar — APPROVED** [review]

**Comment by kuhar** [comment]
> Looks good except for some potential performance regression on valhall. Do we know of anything recent that could have caused this, @antiagainst?

Looks like this could be noise. I'll merge and keep an eye on the plots to see if this needs more digging.

**Comment by pzread** [comment]
Looks like this integration results in regression in RISC-V benchmark. Filed the issue #14528

**Pull request merged**
