### PR TITLE
Update QueryAvailableDevices to also return path value of device

### PR DESCRIPTION
**Pull request by PhaneeshB**
the command `iree-run-module --list_devices` uses `driver_name` and device`path` information to list devices. [link](https://github.com/iree-org/iree/blob/main/runtime/src/iree/tooling/device_util.c#L100)
but the value returned by `HalDriver::QueryAvailableDevices` is `device_id` and `driver_name` [link](https://github.com/iree-org/iree/blob/main/runtime/bindings/python/hal.cc#L294)
this creates a problem to identify multiple devices of the same driver based on enumeration from `--list_devices` option.

Hal device has 3 identification values [link](https://github.com/iree-org/iree/blob/main/runtime/src/iree/hal/device.h#L70)

This PR updates `HalDriver::QueryAvailableDevices` to return a list of dict of all the 3 values for every device.
And changes the existing calls to adapt these changes.

### CODE REVIEW

**Review by benvanik — APPROVED** [review]
seems fine to me - not sure if there's anything relying on the current tuple behavior, though - will let the CI run but someone who knows the implications may need to chime in (@stellaraccident probably)

I'm guessing this is used on the nod side - did your python code require any changes to make use of this? If anyone is using these APIs I suspect it's you :)

**Comment by PhaneeshB** [comment]
> seems fine to me - not sure if there's anything relying on the current tuple behavior, though - will let the CI run but someone who knows the implications may need to chime in (@stellaraccident probably)
> 
> I'm guessing this is used on the nod side - did your python code require any changes to make use of this? If anyone is using these APIs I suspect it's you :)

Yes we need this to allow using a specific device for execution given that users have access to multiple cards on a system and want to test on each of them.

**Comment by PhaneeshB** [comment]
> @PhaneeshB: github seems to have forgotten how to run CIs. Can you rebase to main and push a new commit to see if github is happy with that?

@benvanik - github says :
```
2 workflows awaiting approval
First-time contributors need a maintainer to approve running workflows.
```
This happens to be my first iree contribution
I've rebased the commit, but it would still need a maintainer to approval to get the workflows running

**Comment by ScottTodd** [comment]
I approved the workflow runs. There are a few lint errors, which you can fix by running https://github.com/iree-org/iree/blob/main/build_tools/scripts/lint.sh

**Review by stellaraccident — APPROVED** [review]
Seems fine to me.

**Pull request merged**
