### PR TITLE
Update to wolfpld/tracy@baaed68b (2023-01-19)

### PR DESCRIPTION
**Pull request by antiagainst**

### CODE REVIEW

**Review by benvanik — APPROVED** [review]

**Comment by ScottTodd** [comment]
Does that commit correspond to a named release? It's useful to install from Tracy's releases on Windows, but we won't be able to do that if this includes a version bump that hasn't yet landed in a published release.

**Comment by benvanik** [comment]
here's the commits since the last major release: https://github.com/wolfpld/tracy/compare/5a1f5371b792c12aea324213e1dc738b2923ae21...baaed68bcf7e2dd9ea6b39cb6e26142514089bb3

when we have a windows release we could build our own tracy 🙏 
not immediately seeing any binary version bumps but we could test that

**Comment by antiagainst** [comment]
Yeah this is just pulling the latest commit from Tracy upstream.

**Comment by GMNGeoffrey** [comment]
+1 for using a named release unless we have a particular reason we want something more recent

**Comment by antiagainst** [comment]
It seems there are a few changes not in the previous release (0.9) that are good improvements:

```
- Allow customization of source location data through the following macros:
  - TracyFunction - defaults to __FUNCTION__
  - TracyFile - defaults to __FILE__
  - TracyLine - defaults to __LINE__
- Compare traces menu can now display source code differences between two
  traces.
- Files containing assembly listings are now annotated with source line
  information.
```
I'm waiting for the Android traces from CI; if we can open it fine with 0.9 prebuilt profiler I think we can land as-is.

**Comment by benvanik** [comment]
I'm ok with the tip of tree version mostly because I'm hoping that if we need to upstream any fixes soon it'll be easier to integrate them.

**Comment by antiagainst** [comment]
I've verified that prebuilt 0.9 works with the captured traces. So landing this.

**Comment by pzread** [comment]
Ah, when building binary for buildkite's 20.04 machine for #11954, I found this version actually didn't build on 20.04 with its libcapstone package 4.0.1 (needs 4.0.2). It seems to work fine now, but we should definitely upgrade the libcapstone package on those machines

**Comment by antiagainst** [comment]
@pzread: libcapstone on ubuntu 20.04 is really at version 3 I believe. I initially tried to build the binary on a local Pi I have here with 22.04, but that errored out when I tried to use it on ubuntu 20.04--22.04 actually ships with version 4. So I reverted to build it using 20.04. I think we may want to update the PIs to use 22.04? Though I'm not sure how much the version of capstone matters to worth such an effort.

**Comment by pzread** [comment]
> @pzread: libcapstone on ubuntu 20.04 is really at version 3 I believe. I initially tried to build the binary on a local Pi I have here with 22.04, but that errored out when I tried to use it on ubuntu 20.04--22.04 actually ships with version 4. So I reverted to build it using 20.04. I think we may want to update the PIs to use 22.04? Though I'm not sure how much the version of capstone matters to worth such an effort.

I messed up my environments and confirmed it can be built on 20.04 RPi (with libcapstone 4.0.1, which is actually version 3).

**Pull request merged**
