### PR TITLE
Bump LLVM to llvm/llvm-project@f01ed3bc8884223bf3edbaad8d3685622444cbf5

### PR DESCRIPTION
**Pull request by Max191**

### CODE REVIEW

**Review by MaheshRavishankar — APPROVED** [review]

**Review by dcaballe — APPROVED** [review]
DeepLabV3 regressions on Pixel 6 are expected and captured here so it should be ok to move on: https://github.com/openxla/iree/issues/16406

**Comment by Max191** [comment]
> DeepLabV3 regressions on Pixel 6 are expected and captured here so it should be ok to move on: #16406

Is there any reason not to just carry a revert in IREE of the offending PR (https://github.com/llvm/llvm-project/pull/79752) for now?

**Comment by MaheshRavishankar** [comment]
> > DeepLabV3 regressions on Pixel 6 are expected and captured here so it should be ok to move on: #16406
> 
> Is there any reason not to just carry a revert in IREE of the offending PR ([llvm/llvm-project#79752](https://github.com/llvm/llvm-project/pull/79752)) for now?

We could... but it seems to impact a few set of models that arent really on anyones priority list I guess.

**Comment by dcaballe** [comment]
This is only impacting Pixel 6 and the fixes would take some time. The impact of the revert (removing trailing unit dims on vectors transfer reads) has a much broader impact as we would be generating scalar code for those cases for all the targets.

**Comment by Max191** [comment]
> This is only impacting Pixel 6 and the fixes would take some time. The impact of the revert (removing trailing unit dims on vectors transfer reads) has a much broader impact as we would be generating scalar code for those cases for all the targets.

I see, that makes sense

**Pull request merged**
