### PR TITLE
Drop unused functions, but do not drop `-Wno-unused-function`

### PR DESCRIPTION
**Pull request by bjacob**
This is take two on #15471, now skips straight to the dessert, no veggies for @benvanik .

### CODE REVIEW

**Review by MaheshRavishankar — APPROVED** [review]
Oh no, my sugar levels are going to go sky high!!

**Review by antiagainst — APPROVED** [review]
Must review pull requests that delete code onyl!

**Review by hanhanW — APPROVED** [review]
`+0 -624`!

**Review by dcaballe — APPROVED** [review]
Awesome!

**Pull request merged**
