### PR TITLE
bump torch-mlir to e48fe4588631e7a37a2899f9d4cd5c4cbc967481

### PR DESCRIPTION
**Pull request by dan-garvey**
(allows for unifying fx_importer.py)

### CODE REVIEW

**Review by ScottTodd — APPROVED** [review]

**Comment by ScottTodd** [comment]
CI found some test failures: https://github.com/openxla/iree/actions/runs/8086732817/job/22097146456?pr=16607#step:5:151

```
  20/1395 Test   #62: torch-iree/InputConversion/test/scatter.mlir.test ..........................................................***Failed    0.35 sec
-- Testing: 1 tests, 1 workers --
FAIL: IREE :: plugins/input/Torch/torch-iree/InputConversion/test/scatter.mlir (1 of 1)
******************** TEST 'IREE :: plugins/input/Torch/torch-iree/InputConversion/test/scatter.mlir' FAILED ********************
Exit Code: 1

Command Output (stderr):
--
RUN: at line 1: iree-opt --split-input-file --pass-pipeline="builtin.module(func.func(torch-iree-tm-tensor-to-linalg-ext))" /work/compiler/plugins/input/Torch/torch-iree/InputConversion/test/scatter.mlir | FileCheck /work/compiler/plugins/input/Torch/torch-iree/InputConversion/test/scatter.mlir
+ FileCheck /work/compiler/plugins/input/Torch/torch-iree/InputConversion/test/scatter.mlir
+ iree-opt --split-input-file '--pass-pipeline=builtin.module(func.func(torch-iree-tm-tensor-to-linalg-ext))' /work/compiler/plugins/input/Torch/torch-iree/InputConversion/test/scatter.mlir
within split at /work/compiler/plugins/input/Torch/torch-iree/InputConversion/test/scatter.mlir:1 offset :6:8: error: 'tm_tensor.scatter' op requires attribute 'dimension_map'
  %0 = tm_tensor.scatter unique_indices(true)
       ^
within split at /work/compiler/plugins/input/Torch/torch-iree/InputConversion/test/scatter.mlir:1 offset :6:8: note: see current operation: 
%0 = "tm_tensor.scatter"(%arg2, %arg1, %arg0) <{operandSegmentSizes = array<i32: 2, 1>, unique_indices = true}> ({
^bb0(%arg3: i32, %arg4: i32):
  "tm_tensor.yield"(%arg3) : (i32) -> ()
}) : (tensor<3xi32>, tensor<3x1xi32>, tensor<8xi32>) -> tensor<8xi32>
within split at /work/compiler/plugins/input/Torch/torch-iree/InputConversion/test/scatter.mlir:28 offset :5:8: error: 'tm_tensor.scatter' op requires attribute 'dimension_map'
  %0 = tm_tensor.scatter unique_indices(true)
       ^
within split at /work/compiler/plugins/input/Torch/torch-iree/InputConversion/test/scatter.mlir:28 offset :5:8: note: see current operation: 
%0 = "tm_tensor.scatter"(%arg2, %arg1, %arg0) <{operandSegmentSizes = array<i32: 2, 1>, unique_indices = true}> ({
^bb0(%arg3: i32, %arg4: i32):
  %1 = "arith.addi"(%arg4, %arg3) <{overflowFlags = #arith.overflow<none>}> : (i32, i32) -> i32
  "tm_tensor.yield"(%1) : (i32) -> ()
}) : (tensor<3xi32>, tensor<3x1xi32>, tensor<8xi32>) -> tensor<8xi32>
/work/compiler/plugins/input/Torch/torch-iree/InputConversion/test/scatter.mlir:14:17: error: CHECK-LABEL: expected string not found in input
// CHECK-LABEL: func.func @scatter_update(
                ^
```

**Comment by dan-garvey** [comment]
Its from this:
https://github.com/llvm/torch-mlir/commit/e30a083affb65c301066eda3df7112c06f4291da#diff-d08876b67eafdb088647547d512c1b52173f7a6133f203c71a65c60c1918778b

I'll try and rework the tests tomorrow

**Comment by ScottTodd** [comment]
FYI, I regenerated the external ONNX test suite using this torch-mlir commit: https://github.com/nod-ai/SHARK-TestSuite/pull/84. (prefetching this assuming nothing else is broken - please let me know if you find anything)

**Comment by ScottTodd** [comment]
Are these failures legit? https://github.com/openxla/iree/actions/runs/8144463146/job/22259150196?pr=16607#step:6:49

I'll retry failed just in case...

**Comment by ScottTodd** [comment]
> Are these failures legit? https://github.com/openxla/iree/actions/runs/8144463146/job/22259150196?pr=16607#step:6:49
> 
> I'll retry failed just in case...

Oh, maybe preexisting + fixed by https://github.com/openxla/iree/pull/16661 .... phew. Thanks @antiagainst !

**Comment by ScottTodd** [comment]
Yeah that failure was preexisting and should be fixed now. Could sync this PR.

**Comment by dan-garvey** [comment]
so I should just rebase yeah?

**Comment by ScottTodd** [comment]
> so I should just rebase yeah?

Yes.

**Pull request merged**
