### PR TITLE
[experiment] Canonicalize first, then create dispatch regions

### PR DESCRIPTION
**Pull request by matthias-springer**

### CODE REVIEW

**Review by benvanik — APPROVED** [review]

**Comment by pzread** [comment]
> @MaheshRavishankar how did you trigger the benchmarks? I added the labels two hours ago but nothing has happened yet.

Currently your Github email address needs to be @google.com or you need to be part of the IREE buildkite team member. If you are not using @google.com, you can send me your Github email address. I'll add you to the team member.

**Comment by pzread** [comment]
> > @MaheshRavishankar how did you trigger the benchmarks? I added the labels two hours ago but nothing has happened yet.
> 
> Currently your Github email address needs to be @google.com or you need to be part of the IREE buildkite team member. If you are not using @google.com, you can send me your Github email address. I'll add you to the team member.

Oh wait, I saw your PRs triggered the pipeline before, maybe there was a transient issue so this PR didn't trigger.

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
Why this change? This was done to handle resolving `tensor.dim` operations that are generated during dispatch region formation.

**Comment by matthias-springer** [comment]
> Why this change? This was done to handle resolving tensor.dim operations
> that are generated during dispatch region formation.
>
I just needed a way to trigger the benchmarks. with this change we could
keep track of dispatch regions more easily and wouldn't have to do another
walk over the entire function. So I just wanted to see if the tensor.dim
creation is still exercised. --

Best regards,
Matthias Springer

Software Engineer * ***@***.*** * +1 (385) 200-0959

**Comment by MaheshRavishankar** [comment]
> Why this change? This was done to handle resolving tensor.dim operations that are generated during dispatch region formation.
> I just needed a way to trigger the benchmarks. with this change we could keep track of dispatch regions more easily and wouldn't have to do another walk over the entire function. So I just wanted to see if the tensor.dim creation is still exercised.

May not be exercised in our current benchmarks, but for dynamic shape cases, this will definitely be an issue. We might not have a lit test for it (but its hard to write a lit test for this kind of thing).

**Pull request closed without merging**
