### PR TITLE
Support cloning of ops with regions

### PR DESCRIPTION
**Pull request by matthias-springer**
This change adds two test cases with a `tensor.pad` who's yielded value
is a value defined by an op outside of the `tensor.pad`. Such paddings
appear in TFLite benchmarks (e.g., MobileNetV3SmallStaticBatch).

`legalizeDispatchWorkgroupOperands` could previously not handle such ops
and left the newly-created dispatch region op in an invalid state. The
TFLite benchmark still passed, but this was just by coincidance. This is
likely due to special handling/folding of constants in the
GreedyPatternRewriter. The second test case replaces the ConstantOp with
a block argument, in which case the GreedyPatternRewriter cannot
accidentally fix the invalid IR; this test case fails without this fix.

### CODE REVIEW

**Review by benvanik — APPROVED** [review]

**Comment by MaheshRavishankar** [comment]
Could you hold off on this one for a bit. It's not related to this PR specifically but there is an alternative here that might make this unnecessary

**Comment by matthias-springer** [comment]
> Could you hold off on this one for a bit. It's not related to this PR specifically but there is an alternative here that might make this unnecessary
> 
> Will provide more details when I am at my desk

Yes, I'm also not super happy with this because the cloning part is getting more and more complex. Maybe there's a better design where we select + clone ops one-by-one. Instead of building a list of ops and then sorting it in some way.

Something along the lines of: Take any value that:
* is used inside the dispatch region but the defining op is located outside
* the defining op is cloneable
* the value is not used by any other op outside of the dispatch region (except for ops that belong to different dispatch regions)

Or:
Add cloneable to fusion groups. An op can already belong to multiple fusion groups (FusionGroupsAttr is an array). Maybe we can just expand the heuristic for fusion groups a little bit and there's no need for the "cloning" step anymore. Fusion group ops are also cloned, so basically we do the same for fusion and cloning already, just split into two separate steps.

**Comment by MaheshRavishankar** [comment]
> > Could you hold off on this one for a bit. It's not related to this PR specifically but there is an alternative here that might make this unnecessary
> > Will provide more details when I am at my desk
> 
> Yes, I'm also not super happy with this because the cloning part is getting more and more complex. Maybe there's a better design where we select + clone ops one-by-one. Instead of building a list of ops and then sorting it in some way.
> 
> Something along the lines of: Take any value that:
> 
> * is used inside the dispatch region but the defining op is located outside
> * the defining op is cloneable
> * the value is not used by any other op outside of the dispatch region (except for ops that belong to different dispatch regions)
> 
> Or: Add cloneable ops to fusion groups. An op can already belong to multiple fusion groups (FusionGroupsAttr is an array). Maybe we can just expand the heuristic for fusion groups a little bit and there's no need for the "cloning" step anymore. Fusion group ops are also cloned, so basically we do the same for fusion and cloning already, just split into two separate steps.

Yeah pad op is not a clonable op. Basically clonable ops are really metadata ops that are OK to be replicated. It was a mistake to do this, and I didnt catch it on review. I think you should be able to do something like this https://github.com/iree-org/iree/pull/9194/files#diff-c9f4338d6d7230f44399f248a85d6a631c264bf976c0c80a6d48eadcf442d7acR1155 . The only case the pad is fused with its consumer is for the case where the pad op has only one use. For now we can check for that and add it to a fusion group with its consumer. Currently we dont do any fusion of across ins operands of an operation, but there are cases where this is needed. So this might fix your issue. I have a packed day of meetings, but I can try to get a patch out to you that does this.

Long term we want the pad to fuse with its producers. Using the TilingInterface this should all become easy. Then its a matter of making sure fusing pad with its producer works as expected. I was hoping to get your help on that one actually. Not too far away from experimenting on it (the PR above was trying to do that, but I shelved it cause I decided to just wait for TilingInterface to plumb through)

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
Just putting a hold on this for now cause there might be a better solution for it.

**Comment by MaheshRavishankar** [comment]
> > Could you hold off on this one for a bit. It's not related to this PR specifically but there is an alternative here that might make this unnecessary
> > Will provide more details when I am at my desk
> 
> Yes, I'm also not super happy with this because the cloning part is getting more and more complex. Maybe there's a better design where we select + clone ops one-by-one. Instead of building a list of ops and then sorting it in some way.
> 
> Something along the lines of: Take any value that:
> 
> * is used inside the dispatch region but the defining op is located outside
> * the defining op is cloneable
> * the value is not used by any other op outside of the dispatch region (except for ops that belong to different dispatch regions)
> 
> Or: Add cloneable ops to fusion groups. An op can already belong to multiple fusion groups (FusionGroupsAttr is an array). Maybe we can just expand the heuristic for fusion groups a little bit and there's no need for the "cloning" step anymore. Fusion group ops are also cloned, so basically we do the same for fusion and cloning already, just split into two separate steps.

Oh and I totally agree we should probably clone ops one at a time. The issue is that the ops to be moved into a dispatch are currently  determined and pulled into a `flow.dispatch.workgroups` operation. This operation is expected to be `IsolatedFromAbove`. We probably need a new operation (say `flow.dispatch.group`) which is not `IsolatedFromAbove` that allows you to move things in one at a time (without tiling it. `scf.for_each` does some of this but it also uses tile + fuse which is a complication that needs to be resolved). Having this new op will also allow layering the path through `flow.dispatch.workgroups` used by IREE directly and `scf.for_each` path better. We can create the "fusion group" using the same heuristics we have in dispatch formation today, and then the default IREE path will just make it isolated from above, add tied operands etc. (very easy transformation), and the `scf.for_each` can tile + fuse, etc.

**Comment by matthias-springer** [comment]
How about scf.execute_region? We just need any op with a region that can
yield stuff. (We can keep track of dispatch region execute regions and
other dispatch regions with the transform dialect or attributes or C++
coffee.) We could then convert that one into a dispatch region op.

One thing to keep in mind is that we cannot run the canonicalizer or
greedypatternrewriter in-between because it will host ops without side
effects. In particular ConstantOps, these have hard coded special handling
in the greedypatternrewriter.
-- 

Best regards,
Matthias Springer

Software Engineer * ***@***.*** * +1 (385) 200-0959

**Comment by MaheshRavishankar** [comment]
> How about scf.execute_region? We just need any op with a region that can yield stuff. (We can keep track of dispatch region execute regions and regular execute regions with the transform dialect or attributes or C++ coffee.) We could then convert that one into a dispatch region op. One thing to keep in mind is that we cannot run the canonicalizer or greedypatternrewriter in-between because it will host ops without side effects. In particular ConstantOps, these have hard coded special handling in the greedypatternrewriter.

Good point about canonicalizers. That is kind of a bummer, because one of the things we will need to do is to resolve `tensor.dim` operations which works best with greedy pattern rewriter. Maybe we can pull constants in during the transformation that makes the op `IsolatedFromAbove`  to get the current `flow.dispatch.workgroups`. Sucks though.
`scf.execute_region`maybe fine, but the description of the op is scary! I'd rather have an op that is explicitly for this reason that isnt broken by upstream changes.

**Comment by benvanik** [comment]
Nerdsniped! :P I'd been thinking about co-opting execute_region too but noticed the same scary issues - we really want an op that effectively defines a static function that we can embed in other functions as is common in most languages. If we had such an op we could define entire hierarchies - we can shard across programs, devices, queues, and commands and today the only thing we're able to express is commands (via flow.dispatch.workgroups). Thinking of ways to model this hierarchy such that we can later map it into the stream dialect would be really interesting. For today I was thinking of using scf.foreach_threads that survive after dispatch region formation to shard across queues/devices, but it's not quite the right representation for that stuff either (doesn't allow disparate workloads to be sharded, just the same workload duplicated). Would love to sync up if there are designs moving in that direction as we already have the lower-level representations and are just looking for something upstream-friendly at this point (and someone to actually build passes producing the ops :).

**Pull request closed without merging**
