### PR TITLE
[PkgCI] Remove attention TD pipeline to test attn C++ pipeline.

### PR DESCRIPTION
**Pull request by raikonenfnu**

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
you will need to adjust the times, but other wise looks good.

**Review by MaheshRavishankar — APPROVED** [review]

**Comment by raikonenfnu** [comment]
sgsg, going to wait for MI300 test to give me the expected time with C++ pipeline and then update the commit with updated time for both MI250 and MI300

**Comment by ScottTodd** [comment]
From CI results: 
* mi250 time regressed: https://github.com/iree-org/iree/actions/runs/10462111927/job/28980773452?pr=18292#step:9:152 (fine to update the expected time so the test passes)
* mi300 rocm had numerical differences: https://github.com/iree-org/iree/actions/runs/10462111927/job/28980773712?pr=18292#step:7:180 (those logs are too truncated to tell much)

Do you have a plan for the numerical changes?

**Review by saienduri — APPROVED** [review]
Nice, just need a rebase for CI

**Comment by ScottTodd** [comment]
Can this PR be picked back up again now that https://github.com/iree-org/iree/pull/18740 is in? They look related.

**Comment by saienduri** [comment]
This file no longer exists as part of https://github.com/iree-org/iree/pull/18639/files. No more specs 😄. We can probably close this PR

**Comment by ScottTodd** [comment]
Ah, thanks!

**Pull request closed without merging**
