### PR TITLE
Letting FusionOfTensorOps apply patterns forever.

### LINKED ISSUE #11333: FusionOfTensorOps pass silently failing when compiling random key generation
### What happened?

`iree-compile` exits without sending any text to stdout/stderr with a code of `1` when attempting to compile a Flax module that uses random key generation. Support for this is require for training.

This appears to be a regression and supersedes the error in https://github.com/iree-org/iree/issues/11201.

### Steps to reproduce your issue

Python to generate the module:

```python
import flax.linen as nn

class MakeRNG(nn.Module):
  pass

module = MakeRNG().bind({}, rngs={"random": jax.random.PRNGKey(0)})

def make_rng():
  return module.make_rng("random")

ir_module = jax.jit(make_rng, backend="iree").lower().compiler_ir()
with open("/tmp/make_rng.mlir", "wb") as f:
  ir_module.operation.print(file=f, binary=True, print_generic_op_form=True)
```

A MLIR reproducer can be found here: [`make_rng.mlir`](https://gist.github.com/phoenix-meadowlark/907d6c4edf65facc1461e5590a77ab8e)

The crash can be reproduced by running the following command:

```shell
iree-compile \
  --iree-hal-target-backends=llvm-cpu \
  --iree-input-type=mhlo \
  /tmp/make_rng.mlir \
  -o /tmp/make_rng.vmfb
```

### What component(s) does this issue relate to?

Compiler

### Version information

379d4a58f04bd4cd86e7d7b19aae85b2351b24d0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benvanik**
The way the patterns interact causes what is effectively folding to
count against the max iteration limit. The default of 10 is
insufficient when the input program has a lot of constants to fold.
In the future we could explore top-down traversal as an alternative.

Also added logging so when this pass fails we see something on stderr.
Fixes #11333.

### CODE REVIEW

**Comment by benvanik** [comment]
Actually, setting the driver into useTopDownTraversal seems to work better and produces the same IR (in this one small example). Since flipping the traversal is a bigger change than just increasing the limit I'll let you decide @MaheshRavishankar if you want this or useTopDownTraversal (may be some patterns that work better with one or the other I don't know about).

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
Thanks for the error messages. Just blocking cause I want to run benchmarks with this....

**Comment by MaheshRavishankar** [comment]
@benvanik w.r.t to patterns, I can try to remove the limit for the patterns at play here (they are just three patterns). Ill wait for what the benchmark results show.

**Comment by benvanik** [comment]
You think any of those numbers are meaningful? Those feel a bit high for the usual noise. I'll push the change that leaves it bottoms-up but increases max iterations and see what they say.

**Comment by MaheshRavishankar** [comment]
IIRC when Chris Lattner added the bottom up traversal, it was to help compilation time, so maybe the regressions make sense. Did you remove the top-down traversal?

**Comment by benvanik** [comment]
Yeah. Top down seemed to help this case because pattern application could complete quicker as each constant operation gets rewritten and by the time the end is reached there's nothing left. In bottom up it tries to fold every op each iteration and each time is only able to fold one of them at the end. So for things like this the top/bottom flip changes it from O(N)ish top-down to O(N^2)ish bottom-up. But benchmarks (probably) don't lie and that there are runtime implications means we're likely missing fusions when going top-down (probably multi-use cases or something). Probably best just to punt on that for now and just raise the max iteration count as unsatisfying as that is :P

**Comment by MaheshRavishankar** [comment]
> Yeah. Top down seemed to help this case because pattern application could complete quicker as each constant operation gets rewritten and by the time the end is reached there's nothing left. In bottom up it tries to fold every op each iteration and each time is only able to fold one of them at the end. So for things like this the top/bottom flip changes it from O(N)ish top-down to O(N^2)ish bottom-up. But benchmarks (probably) don't lie and that there are runtime implications means we're likely missing fusions when going top-down (probably multi-use cases or something). Probably best just to punt on that for now and just raise the max iteration count as unsatisfying as that is :P

Havent studied that (was one of the things I had filed away as something to look into later), but I think the order shouldnt matter, especially if we handle multi-use things correctly. The latter is now unblocked on CPU side at least... so definitely worth looking into now

**Review by MaheshRavishankar — APPROVED** [review]

**Pull request merged**
