### PR TITLE
Convert integrations/tensorflow/iree-dialects back into a symlink.

### PR DESCRIPTION
**Pull request by ScottTodd**
This directory contains 30k LOC and is frequently updated now, so maintaining two copies of it is getting expensive.

We originally had a symlink but changed to a hard fork in https://github.com/google/iree/pull/8137/commits/818946bf14b90342671eb907cffb1b2cd84eb872 with this message:
> We should have done this from the beginning and then updated it explicitly on frontend upgrades (which is what out of tree is doing).
Effectively, this directory is an island within the repo and must be isolated. This broke as changes to make it compatible with LLVM head don't work for the frontend version.

I'd like to understand that a bit better, and possibly explore alternative implementations if the directories really do need to diverge (such as patch files: https://docs.bazel.build/versions/main/repo/utils.html#patch)

### CODE REVIEW

**Comment by stellaraccident** [comment]
The only thing actually needed by tf integrations is the input dialect, which is like three files. It would be nice if we had a place to stash these "stub" dialects that didn't come with a lot of cost (similar to tmtensor). It is also possible that eventually, with the ml_program work, we have *no* dependency here... However, we may always have benefit of some kind of local input dialect for new or niche things.

Converting back to a symlink will have the cost of not being able to integrate to an llvm commit much different from tf. Might be ok for the short term... I think I was the main one with enough state to make those judgment calls anyway.

**Comment by ScottTodd** [comment]
> The only thing actually needed by tf integrations is the input dialect, which is like three files. It would be nice if we had a place to stash these "stub" dialects that didn't come with a lot of cost (similar to tmtensor). It is also possible that eventually, with the ml_program work, we have _no_ dependency here... However, we may always have benefit of some kind of local input dialect for new or niche things.
> 
> Converting back to a symlink will have the cost of not being able to integrate to an llvm commit much different from tf. Might be ok for the short term... I think I was the main one with enough state to make those judgment calls anyway.

Thanks for weighing in, but please enjoy your vacation 😅. I was planning on letting this sit until you got back (or there was a pressing need to land it sooner, I'm still at the "understand where our growing pains are and propose some adjustments" stage right now).

The end state with ml_program is ideal, and carving out a separate space with lower cost is a good idea too!

**Comment by stellaraccident** [comment]
> > The only thing actually needed by tf integrations is the input dialect, which is like three files. It would be nice if we had a place to stash these "stub" dialects that didn't come with a lot of cost (similar to tmtensor). It is also possible that eventually, with the ml_program work, we have _no_ dependency here... However, we may always have benefit of some kind of local input dialect for new or niche things.
> > Converting back to a symlink will have the cost of not being able to integrate to an llvm commit much different from tf. Might be ok for the short term... I think I was the main one with enough state to make those judgment calls anyway.
> 
> Thanks for weighing in, but please enjoy your vacation 😅. I was planning on letting this sit until you got back (or there was a pressing need to land it sooner, I'm still at the "understand where our growing pains are and propose some adjustments" stage right now).
> 
> The end state with ml_program is ideal, and carving out a separate space with lower cost is a good idea too!

You just happened to catch me waking up from a nap and thinking about relocating to a different beach, so no worries on the enjoying vacation front :)

I do think a lot of this will look a lot better in a few months given upstream work in progress. No objection from me for doing what you think will be an improvement in the interim -- I just wouldn't spend a lot of time analyzing or doing anything hard. Most of this stuff is transient at this point. But now you have all the state I do, and I trust you to make a decision. No need to wait for me.

**Comment by benvanik** [comment]
Closing as obsolete. I like the idea of removing this duplication (it really messes up my code search), but may be worth tracking it in an issue if there's dependencies we need to take care of first.

**Pull request closed without merging**
