### PR TITLE
Disable fusion for some multi-result cases.

### PR DESCRIPTION
**Pull request by hanhanW**
Fixes https://github.com/iree-org/iree/issues/10567

### CODE REVIEW

**Comment by hanhanW** [comment]
Hey @pzread, this PR fixes the issues I've seen in decoder. Mahesh mentioned that you have a script to count the number of dispatches for all the models. I'd like to do the same thing here, and figure out what's happening in the whole pipeline. I attached the repro to an internal bug. We can chat more about it in our 1:1, this is just a heads-up.

**Comment by pzread** [comment]
No changes on dispatch numbers with this patch
https://gist.github.com/pzread/eee32a1f4a583e2abe6aeee6e2acce92

**Comment by hanhanW** [comment]
SG, I think that's because we don't have ArgMin/Max-like ops in those tracking models. The regression of compilation time was a noise. They're gone after rebasing on ToT. I think we can land the PR; relax the condition when there's a need. What do you think?

**Comment by MaheshRavishankar** [comment]
> SG, I think that's because we don't have ArgMin/Max-like ops in those tracking models. The regression of compilation time was a noise. They're gone after rebasing on ToT. I think we can land the PR; relax the condition when there's a need. What do you think?

Actually there might be a fix upstream that can probably avoid this. Can we put this on the backburner for now unless it is really needed...

**Comment by benvanik** [comment]
(may relate to https://github.com/iree-org/iree/issues/6948 where we're suffering from way too little fusion - though it appears the ASR model we're tracking doesn't seem to trigger multi-result fusion today and this PR would be a no-op it'd be nice not to have one more place that is preventing us from getting good fusions unless it's required!)

**Comment by MaheshRavishankar** [comment]
@hanhanW I am assuming the patch you landed upstream makes this PR unnecessary?

**Comment by hanhanW** [comment]
> @hanhanW I am assuming the patch you landed upstream makes this PR unnecessary?

I'll verify it and close the PR. For now, I'll mark it draft

**Pull request closed without merging**
