### PR TITLE
[WIP] Add tests for structural ops

### PR DESCRIPTION
**Pull request by simon-camp**

### CODE REVIEW

**Comment by simon-camp** [comment]
@benvanik I realized we need to do a bit of mangling on function names in the CModuleTarget. In the process I also managed to produce name clashes in the bytecode module test. Should this be fixed or is the test to contrived?

CC @marbre

**Comment by benvanik** [comment]
IIUC it's just testing the test infra but that's fine :)

**Comment by simon-camp** [comment]
Yep, it really should test that valid C function names are generated, which needs to be implemented. And the test shows that a simple `reaplceInvalidCharBy_` is sub optimal. As a byproduct it breaks the test infra.

**Comment by benvanik** [comment]
Closing as obsolete.

**Pull request closed without merging**
