### PR TITLE
Add a foreach_thread_to_workgroup transform

### PR DESCRIPTION
**Pull request by nicolasvasilache**
This revision adds a transform dialect op that is very similar to `foreach_thread_to_gpu` to allow distributing to the first level of parallelism during codegen.

This is subject to conventions of what values are captured in the workgroup_count region and how these values are passed around in the `stream.cmd.dispatch` op.

For now the convention choosen is that `0` values are passed and the `tile_to_foreach_thread` may only use static sizes.

A followup PR will introduce a new transform dialect op to allow creating the sizes dynamically based on other conventions.

### CODE REVIEW

**Comment by nicolasvasilache** [comment]
I still plan to do some cleanups, rewordings and renamings tomorrow but the mechanics are ready for review.

Where to put the test is also up for debate, I don't want to extend tests/transform_dialect forever but until we can transport transform IR down to the HAL level, we still need separate files.

**Review by matthias-springer — APPROVED** [review]

**Comment by MaheshRavishankar** [comment]
If I can provide a suggestion:
1) You can read `flow.dispatch.default_workgroup_count` op as essentially compute `flow.dispatch.workgroup_count_from_consumer_root` op. The workload captured at the Flow level is the Range of the op that is tiled first (into which things are fused). I'll rename this anyway.
2) Totally agree we can have many different ops for different conventions for different use cases .

**Comment by nicolasvasilache** [comment]
Thanks @MaheshRavishankar !

At this time, I think the combination `wrap_in_dispatch_region` + `region_to_workgroups` lives the `workgroup_count` region empty. I am not completely clear how one should populate this at the flow level and how that would connect to passing the right information to the stream dispatch call.
Pointers that would help solve that part would be very useful!

Once we have that, I can easily tweak this PR to avoid reconstructing the region and inline the  `flow.dispatch.default_workgroup_count` as the tile size during backend-specific codegen.

At that point I think I would still need guidance to find the IR that should replace `flow.dispatch.default_workgroup_count` after tiling to `scf.foreach_thread` and perform the proper constant propagations etc.

Please let us know if this line of thought makes sense of needs to be updated.

**Comment by MaheshRavishankar** [comment]
> Thanks @MaheshRavishankar !
> 
> At this time, I think the combination `wrap_in_dispatch_region` + `region_to_workgroups` lives the `workgroup_count` region empty. I am not completely clear how one should populate this at the flow level and how that would connect to passing the right information to the stream dispatch call. Pointers that would help solve that part would be very useful!
> 

It'd be good to decouple the flow level and codegen level to start with. Based on this RFC from Stella (https://groups.google.com/g/iree-discuss/c/Mz0ECZmWeTA) we should start with Transform dialect usage scoped within Codegen itself. So  we should decouple the way the workgroup_count region is handled and the way the dispatch region lowering proceeds. AFAICS, with a transformation driver these are two independent "transformations" that are all controlled by the driver which provides both of these with consistent information.
With that you can process the region you get from Flow today. You can assume that the number of operands to `flow.dispatch.default_workgroup_count` is same as the dimensionality of the tiled consumer (i.e the operation that is tiled first and into which all the other operations are tiled and fused). The value of the operands is `(ub - lb)/step` of the untiled operation. I am happy to make this more ergonomic, but these assumptions hold for today.

> Once we have that, I can easily tweak this PR to avoid reconstructing the region and inline the `flow.dispatch.default_workgroup_count` as the tile size during backend-specific codegen.
> 
> At that point I think I would still need guidance to find the IR that should replace `flow.dispatch.default_workgroup_count` after tiling to `scf.foreach_thread` and perform the proper constant propagations etc.
> 
> Please let us know if this line of thought makes sense of needs to be updated.

**Pull request merged**
