### PR TITLE
[CPU] Add patterns to drop unit dimensions at vector level

### PR DESCRIPTION
**Pull request by dcaballe**
This PR adds patterns to the vector lowering pass to drop unit dimensions for vector elementwise ops.

Co-authored-by: Jerry Wu <cheyuw@google.com>

### CODE REVIEW

**Comment by dcaballe** [comment]
@banach-space, did you forget to enable this in IREE? I couldn't find the patterns anywhere

**Comment by hanhanW** [comment]
Shouldn't we move it to https://github.com/openxla/iree/pull/16160 ?

**Comment by dcaballe** [comment]
Is that ready? I thought it was still under investigation. I think whatever lands first should work. It's just about moving one line.

**Comment by hanhanW** [comment]
I see, makes sense to me. Thank you!
That one is waiting for a commit from integrate, but is ready for review. All the benchmark reports are positive. But yeah, we can land them in whatever order.

**Comment by pzread** [comment]
I was trying to enable this in https://github.com/openxla/iree/pull/15839, but it makes sense to enable it separately

**Review by pzread — APPROVED** [review]

**Comment by dcaballe** [comment]
Thanks! Let me add you ad a co-author

**Comment by banach-space** [comment]
> @banach-space, did you forget to enable this in IREE? I couldn't find the patterns anywhere

LGTM, thanks! Yeah, that landed in Dec and there was just too many things in parallel, sorry for missing that.

**Pull request merged**
