### PR TITLE
Generalize custom_dispatch/cpu/plugin CMake build

### PR DESCRIPTION
**Pull request by bjacob**
Ahead of adding plugins wrapping the builtin ukernels, generalize the existing ad-hoc CMake code into reusable functions to create both system and standalone plugins.

Also rename existing files to make room for more plugins.

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
Thanks Benoit! I think some else need to look at the CMake stuff since I dont have a full understanding of those.

**Review by benvanik — CHANGES_REQUESTED** [review]
There are some good cleanups here but this is the wrong place for it. The sample is intended to be representative of user code and something easily understandable - it cannot use any IREE build macros (like iree_cc_library) and should not be this complex. If you're intending to use this for something more then that will need to be a separate thing (I think I saw a PR that adds ukernel building and such) - that should live under experimental/. If it's extremely transient a `samples/custom_dispatch/cpu/ukernel/` to keep the worlds separate but still use sample-deps would be ok, but experimental is really the right place.

**Comment by bjacob** [comment]
OK thanks for the explanation. Will go to experimental/.

**Comment by bjacob** [comment]
Gone to experimental in https://github.com/openxla/iree/pull/13433

**Pull request closed without merging**
