### PR TITLE
[CI] Fix buildkite pipeline

### PR DESCRIPTION
**Pull request by kuhar**
Issue: https://github.com/openxla/iree/issues/13123

### CODE REVIEW

**Comment by pzread** [comment]
Manually triggered the test run https://buildkite.com/iree/iree-test-android/builds/8894#0187c3d0-5b4f-46ea-8007-0533db468063

Maybe you need to use `$$` https://buildkite.com/docs/pipelines/environment-variables#runtime-variable-interpolation

**Comment by kuhar** [comment]
Thanks @pzread, I tried `$$` instead. Can you rettriger? Seems like I don't have the permissions.

**Comment by pzread** [comment]
Running now https://buildkite.com/iree/iree-test-android/builds/8895

**Comment by kuhar** [comment]
> Running now https://buildkite.com/iree/iree-test-android/builds/8895

The ctest command in logs looks good now. Thank you!

**Review by pzread — APPROVED** [review]

**Pull request merged**
