### PR TITLE
[CPU] Optimize vector transfers for pack/unpack  before vector lowering

### LINKED ISSUE #15349: [CPU] Inefficient vector code for `tensor.pack` op
This is the hottest dispatch in one of our models. It looks like we are not generating good vector code for the following `tensor.pack` op. We use `#iree_codegen.lowering_config<tile_sizes = [[64, 4], [1, 1]]>} : tensor<?x?xf32> -> tensor<?x4x16x1xf32>` for it, which shouldn't map to any of the transpose patterns that we have?

```
hal.executable public @main_dispatch_1297 {
  hal.executable.variant public @system_elf_x86_64 target(<"llvm-cpu", "system-elf-x86_64", {cpu = "cascadelake", cpu_features = "+cmov,+mmx,+popcnt,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+avx,+avx2,+fma,+avx512f,+bmi,+bmi2,+aes,+pclmul,+avx512vl,+avx512bw,+avx512dq,+avx512cd,+avx512vnni,+adx,+clflushopt,+clwb,+cx16,+cx8,+crc32,+f16c,+fsgsbase,+fxsr,+invpcid,+lzcnt,+movbe,+pku,+prfchw,+rdrnd,+rdseed,+sahf,+x87,+xsave,+xsavec,+xsaveopt,+xsaves,+evex512", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128", link_embedded = false, native_vector_size = 64 : index, target_triple = "x86_64-unknown-linux-gnu", ukernels = false}>) {
    hal.executable.export public @main_dispatch_1297 ordinal(0) layout(#hal.pipeline.layout<push_constants = 0, sets = [<0, bindings = [<0, storage_buffer, ReadOnly>, <1, storage_buffer>]>]>) {
    ^bb0(%arg0: !hal.device):
      %x, %y, %z = flow.dispatch.workgroup_count_from_slice
      hal.return %x, %y, %z : index, index, index
    }
    builtin.module {
      func.func @main_dispatch_1297() {
        %c0 = arith.constant 0 : index
        %c12480 = arith.constant 12480 : index
        %cst = arith.constant 0.000000e+00 : f32
        %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<1200x500000xf32>>
        %1 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%c12480) : !flow.dispatch.tensor<writeonly:tensor<31250x1200x16x1xf32>>
        %2 = flow.dispatch.tensor.load %0, offsets = [0, 0], sizes = [1200, 500000], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<1200x500000xf32>> -> tensor<1200x500000xf32>
        %3 = tensor.empty() : tensor<31250x1200x16x1xf32>
        %pack = tensor.pack %2 padding_value(%cst : f32) outer_dims_perm = [1, 0] inner_dims_pos = [1, 0] inner_tiles = [16, 1] into %3 : tensor<1200x500000xf32> -> tensor<31250x1200x16x1xf32>
        flow.dispatch.tensor.store %pack, %1, offsets = [0, 0, 0, 0], sizes = [31250, 1200, 16, 1], strides = [1, 1, 1, 1] : tensor<31250x1200x16x1xf32> -> !flow.dispatch.tensor<writeonly:tensor<31250x1200x16x1xf32>>
        return
      }
    }
  }
}
```

After vectorization we generate a 1D transpose:
 
```
      %11 = scf.for %arg2 = %c0 to %4 step %c1 iter_args(%arg3 = %7) -> (tensor<?x4x16x1xf32>) {
        %12 = scf.for %arg4 = %c0 to %c4 step %c1 iter_args(%arg5 = %arg3) -> (tensor<?x4x16x1xf32>) {
          %13 = affine.apply affine_map<(d0) -> (d0 * 16)>(%arg2)
          %14 = affine.min affine_map<(d0, d1) -> (16, d0 - d1 * 16)>(%8, %arg2)
          %extracted_slice = tensor.extract_slice %10[%arg4, %13] [1, %14] [1, 1] : tensor<4x?xf32> to tensor<1x?xf32>
          %extracted_slice_0 = tensor.extract_slice %arg5[%arg2, %arg4, 0, 0] [1, 1, 16, 1] [1, 1, 1, 1] : tensor<?x4x16x1xf32> to tensor<1x1x16x1xf32>
          %15 = vector.create_mask %c1, %14 : vector<1x16xi1>
          %16 = vector.transfer_read %extracted_slice[%c0, %c0], %cst, %15 {in_bounds = [true, true]} : tensor<1x?xf32>, vector<1x16xf32>
          %17 = vector.transpose %16, [1, 0] : vector<1x16xf32> to vector<16x1xf32>
          %18 = vector.transfer_write %17, %extracted_slice_0[%c0, %c0, %c0, %c0] {in_bounds = [true, true]} : vector<16x1xf32>, tensor<1x1x16x1xf32>
          %inserted_slice = tensor.insert_slice %18 into %arg5[%arg2, %arg4, 0, 0] [1, 1, 16, 1] [1, 1, 1, 1] : tensor<1x1x16x1xf32> into tensor<?x4x16x1xf32>
          scf.yield %inserted_slice : tensor<?x4x16x1xf32>
        }
        scf.yield %12 : tensor<?x4x16x1xf32>
      }
```

```
iree-compile --iree-hal-target-backends=llvm-cpu --iree-llvmcpu-target-cpu=cascadelake \
     --iree-input-type=stablehlo --iree-llvmcpu-target-triple=x86_64-unknown-linux-gnu \
     --iree-llvmcpu-link-embedded=false --iree-opt-data-tiling=true --compile-from=executable-sources test.mlir -o test.vmfb
```

### PR DESCRIPTION
**Pull request by hanhanW**
Fixes https://github.com/openxla/iree/issues/15349

### CODE REVIEW

**Review by dcaballe — APPROVED** [review]
Thanks!

**Comment by hanhanW** [comment]
The regression looks real, need some investigation. I'd appreciate if someone can help look into it.

**Comment by hanhanW** [comment]
This is blocked by https://github.com/openxla/iree/issues/15493

The upstream pattern is generating invalid IRs.

**Comment by hanhanW** [comment]
The regression is noise because it does not contain any pack/unpack ops. The change only impacts pack/unpack ops.

**Pull request merged**
