### PR TITLE
Enable sub-type store integration tests for RISC-V.

### LINKED ISSUE #15613: [EPIC][CPU] int4 sub-type emulation
Creating an EPIC issue for tracking emulation support on CPU side. We should have full coverage on CPU side if we clear below tasks. @Max191 has been making good progress on this.

```[tasklist]
### Tasks
- [ ] https://github.com/openxla/iree/issues/15370
- [ ] https://github.com/openxla/iree/issues/15515
- [ ] https://github.com/openxla/iree/issues/15540
- [x] Missing emulation support for memref.reinterpret_cast -- https://github.com/llvm/llvm-project/pull/73144
- [ ] https://github.com/openxla/iree/issues/15575
- [ ] https://github.com/openxla/iree/issues/15369
```

### PR DESCRIPTION
**Pull request by hanhanW**
Fixes https://github.com/openxla/iree/issues/15613

### CODE REVIEW

**Review by MaheshRavishankar — APPROVED** [review]
Nice!

**Comment by hanhanW** [comment]
It seems that there are other issues on vulkan-spirv side.. I am going to exclude the enablement from this PR

**Comment by MaheshRavishankar** [comment]
> It seems that there are other issues on vulkan-spirv side.. I am going to exclude the enablement from this PR

Oh oh. @antiagainst fyi. Might be a latent bug which we might hit for real.

**Comment by antiagainst** [comment]
> > It seems that there are other issues on vulkan-spirv side.. I am going to exclude the enablement from this PR
> 
> Oh oh. @antiagainst fyi. Might be a latent bug which we might hit for real.

Yeah type emulation is always complicated with those many different bitwidth capabilities on SPIR-V. :) @hanhanW if you have a repro / issue that'd be nice for me to look into!

**Comment by hanhanW** [comment]
issue filed: https://github.com/openxla/iree/issues/15772

**Pull request merged**
