### PR TITLE
Switch e2e tests and benchmarks to `--iree-flow-enable-data-tiling` on `llvm-cpu`

### PR DESCRIPTION
**Pull request by bjacob**
Not switching `vmvx` e2e tests for now because that has to wait until we implement tile size selection for the VMVX backend.

### CODE REVIEW

**Review by antiagainst — APPROVED** [review]

**Review by pzread — APPROVED** [review]

**Comment by MaheshRavishankar** [comment]
Awesome! Now only VMVX is left!

**Review by MaheshRavishankar — APPROVED** [review]

**Comment by MaheshRavishankar** [comment]
FYI @julianwa and @mattwalsh (Sorry Matt, I know you wanted to write this PR :P . You can approve it)

**Review by hanhanW — APPROVED** [review]

**Comment by bjacob** [comment]
The [CI failure on buildkite/iree-benchmark-android/pr](https://buildkite.com/iree/iree-benchmark-android/builds/5060#0184d4c9-43f0-419d-8c6b-c59f10052588) is `No space left on device` on the Moto Edge X30 on `BUILDKITE_AGENT_NAME="IREE-LAB-RPI4-moto-1@ubuntu-1008524137-1`.

**Comment by bjacob** [comment]
The benchmark results show a flurry of both much-regressed results (particularly on little cores) and much-improved (particularly with multiple threads). We can either take this opportunity to do a deep dive with Tracy, or just do the switch now and focus on the performance of the resulting system. I'm inclined to do the latter because the most-regressed numbers here are on things that we have not been closely tracking (particularly, little-core performance). Most likely we are going to learn that the codegen for the new linalg_ext pack/unpack ops is suboptimal, which makes sense as we haven't invested much in it already. Also @hanhanW has already been working on minimizing the number of dispatches, which is one metric that we've know the new system to do worse than the old.  Overall I'm inclined to just merge this and focus on the new-world. WDYT? @MaheshRavishankar @hanhanW @benvanik @julianwa

**Comment by MaheshRavishankar** [comment]
I just see a couple of big core related regressions. Most other are little core related. So I am fine with merging it. I'd say @benvanik has the final say. I'd rather fix-forward performance issues

**Comment by benvanik** [comment]
sgtm!

**Pull request merged**
