### PR TITLE
Add sub-byte emulation support to llvm-cpu and vulkan backend.

### LINKED ISSUE #14481: Unexpected results for int4
### What happened?

Tested two simple IR with the only difference on int4 and int8. They are supposed to have same output, but the int4 gave weird results.

int4:
> #map = affine_map<(d0, d1, d2) -> (d0, d1, d2)>
module {
  func.func @forward() -> tensor<8x4x2xf32> {
    %cst = arith.constant dense<[[0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15], [0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15], [0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15], [0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15]]> : tensor<8x8xi4>
    %expanded_4 = tensor.expand_shape %cst [[0], [1, 2]] : tensor<8x8xi4> into tensor<8x4x2xi4>
    %0 = tensor.empty() : tensor<8x4x2xf32>
    %5 = linalg.generic {indexing_maps = [#map, #map], iterator_types = ["parallel", "parallel", "parallel"]} ins(%expanded_4 : tensor<8x4x2xi4>) outs(%0 : tensor<8x4x2xf32>) {
    ^bb0(%in: i4, %out: f32):
      %6 = arith.extui %in : i4 to i32
      %7 = arith.uitofp %6 : i32 to f32
      linalg.yield %7 : f32
    } -> tensor<8x4x2xf32>
    return %5 : tensor<8x4x2xf32>
  }
}

output:
> 8x4x2xf32=[[0 1][2 3][8 9][10 11]][[0 1][2 3][8 9][10 11]][[0 1][2 3][8 9][10 11]][[0 1][2 3][8 9][10 11]][[0 0][0 0][0 0][0 0]][[0 0][0 0][0 0][0 0]][[0 0][0 0][0 0][0 0]][[0 0][0 0][0 0][0 0]]

int8:
> #map = affine_map<(d0, d1, d2) -> (d0, d1, d2)>
module {
  func.func @forward() -> tensor<8x4x2xf32> {
    %cst = arith.constant dense<[[0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15], [0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15], [0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15], [0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15]]> : tensor<8x8xi8>
    %expanded_4 = tensor.expand_shape %cst [[0], [1, 2]] : tensor<8x8xi8> into tensor<8x4x2xi8>
    %0 = tensor.empty() : tensor<8x4x2xf32>
    %5 = linalg.generic {indexing_maps = [#map, #map], iterator_types = ["parallel", "parallel", "parallel"]} ins(%expanded_4 : tensor<8x4x2xi8>) outs(%0 : tensor<8x4x2xf32>) {
    ^bb0(%in: i8, %out: f32):
      %6 = arith.extui %in : i8 to i32
      %7 = arith.uitofp %6 : i32 to f32
      linalg.yield %7 : f32
    } -> tensor<8x4x2xf32>
    return %5 : tensor<8x4x2xf32>
  }
}

output:
> 8x4x2xf32=[[0 1][2 3][4 5][6 7]][[8 9][10 11][12 13][14 15]][[0 1][2 3][4 5][6 7]][[8 9][10 11][12 13][14 15]][[0 1][2 3][4 5][6 7]][[8 9][10 11][12 13][14 15]][[0 1][2 3][4 5][6 7]][[8 9][10 11][12 13][14 15]]

### Steps to reproduce your issue

1. iree-compile --iree-hal-target-backends=llvm-cpu int4.mlir -o int4.vmfb --iree-flow-inline-constants-max-byte-length=0
2. iree-run-module --device=local-task --module=int4.vmfb --function=forward
3. same steps for int8.mlir

### What component(s) does this issue relate to?

_No response_

### Version information

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
Based off of https://github.com/openxla/iree/commit/ea49d2b1531f1c7855ec2c65d7d9f97e5458d2ae

Fixes #14481

### CODE REVIEW

**Review by MaheshRavishankar — COMMENTED** [review]
Nice!

**Review by hanhanW — APPROVED** [review]
I think Mahesh already reviewed it, let me approve for him. (This PR is in a weird state. :p)

**Comment by MaheshRavishankar** [comment]
I haven't reviewed in detail yet. @hanhanW I'll review later tonight

**Comment by MaheshRavishankar** [comment]
Ah, I see it is merged. I'll leave comments anyway for post submit fixup

**Comment by hanhanW** [comment]
oops, sorry about that, I can address comments as follow-ups. Please take a look when you're available.

**Pull request merged**
