### PR TITLE
[Flow] Make dispatch name descriptive when there are pack/unpack ops.

### LINKED ISSUE #15027: [CPU] Add descriptive name to data tiling dispatches
I'm currently profiling a large model and I finding a few dozens of dispatches like:
* `main_dispatch_1171` 
* `main_dispatch_619`
* `main_dispatch_199`
* ...

When looking into them I see data copies and transposes so I'm assuming they are generated by data tiling? (maybe I'm wrong).
It would be really helpful if we could add something like `data_tiling_pack`, `data_tiling_unpack` or something else to the data tiling dispatches so that they can be easily identified.

cc: @MaheshRavishankar, @hanhanW

### PR DESCRIPTION
**Pull request by hanhanW**
- It adds element type if the dispatch only has pack/unpack ops.
- It adds "unpack_" prefix if the first tileable op is a unpack op.
- It adds "_pack" suffix if the last tileable op is a pack op.

Fixes https://github.com/openxla/iree/issues/15027

### CODE REVIEW

**Review by benvanik — APPROVED** [review]
nice!

**Comment by hanhanW** [comment]
Thanks for the quick review! I will wait for @dcaballe to confirm this is what he wants.

**Review by MaheshRavishankar — APPROVED** [review]
Cool! Thanks for crossing the t's and dotting the i's

**Review by dcaballe — APPROVED** [review]
Awesome! Thanks a lot for adding this!

**Pull request merged**
