### PR TITLE
[NFC] Move getRootOperation utility from CPUUtils -> Utils

### PR DESCRIPTION
**Pull request by Abhishek-Varma**
-- `getRootOperation` utility had no CPU specific construct and is
   being used by other backends : CPU, VMVX and a downstream project concerning AIE backend.
-- Therefore to disambiguate the header file's inclusion, this utility
   has been moved to a common space instead.

Signed-off-by: Abhishek Varma <abhvarma@amd.com>

### CODE REVIEW

**Comment by hanhanW** [comment]
This is intended because different backends have different definition about "rootOp". The method is expected to be used by CPU and VMVX backends for now.

**Review by hanhanW — CHANGES_REQUESTED** [review]
This is intended because different backends have different definition about "rootOp". The method is expected to be used by CPU and VMVX backends for now.

**Comment by Abhishek-Varma** [comment]
> This is intended because different backends have different definition about "rootOp". The method is expected to be used by CPU and VMVX backends for now.

You're correct - but we also have AIE backend trying to use this now. Perhaps then we should have a better name than "CPUUtils" now that three different backends use this. Let me know your thoughts.

**Review by hanhanW — APPROVED** [review]
> You're correct - but we also have AIE backend trying to use this now. Perhaps then we should have a better name than "CPUUtils" now that three different backends use this. Let me know your thoughts.

Okay, thanks for the information! So this is for downstream projects. Could you add it to PR description as well?

**Comment by Abhishek-Varma** [comment]
> > You're correct - but we also have AIE backend trying to use this now. Perhaps then we should have a better name than "CPUUtils" now that three different backends use this. Let me know your thoughts.
> 
> Okay, thanks for the information! So this is for downstream projects. Could you add it to PR description as well?

Hi Hanhan.

Thanks for approving. I've updated the PR's description now.
The PR seems to be blocked on the CLA (it's going on since 4 hours with no Pass/Fail response) although I've contributed to IREE a few times.

I tried checking the CLA doc, just in case to check if I still have the CLA signed and see one section where it mentions the following :-
```
Your contribution (commit) must be associated with at least one of:

1. The primary email on your Google Account associated with the signed CLA.
2. An Alternate email on your Google Account associated with the signed CLA. See and modify your aternate emails at https://myaccount.google.com/alternateemail.
3. The GitHub username associated with the signed CLA.
```
And I confirm that point number 3 satisfies the "at least" criteria above.

Maybe a server error because the "Manage account" gives 502 error.
Can you please help me out here with any actionable step that I may take to get this merged?

**Comment by hanhanW** [comment]
I'm no longer a Googler, so I don't have any access to related things. This is also new to me, so I don't know how to handle this. Maybe @jpienaar or others can help this.

**Review by MaheshRavishankar — APPROVED** [review]
Thanks! This works for me!

**Comment by Abhishek-Varma** [comment]
> > > You're correct - but we also have AIE backend trying to use this now. Perhaps then we should have a better name than "CPUUtils" now that three different backends use this. Let me know your thoughts.
> > 
> > 
> > Okay, thanks for the information! So this is for downstream projects. Could you add it to PR description as well?
> 
> Hi Hanhan.
> 
> Thanks for approving. I've updated the PR's description now. The PR seems to be blocked on the CLA (it's going on since 4 hours with no Pass/Fail response) although I've contributed to IREE a few times.
> 
> I tried checking the CLA doc, just in case to check if I still have the CLA signed and see one section where it mentions the following :-
> 
> ```
> Your contribution (commit) must be associated with at least one of:
> 
> 1. The primary email on your Google Account associated with the signed CLA.
> 2. An Alternate email on your Google Account associated with the signed CLA. See and modify your aternate emails at https://myaccount.google.com/alternateemail.
> 3. The GitHub username associated with the signed CLA.
> ```
> 
> And I confirm that point number 3 satisfies the "at least" criteria above.
> 
> Maybe a server error because the "Manage account" gives 502 error. Can you please help me out here with any actionable step that I may take to get this merged?

Hi @jpienaar 

Can you or someone you can me point to please help me getting this PR merged?

**Comment by benvanik** [comment]
(note that I'd strongly advise against trying to common this utility - what a "root op" is - or even that one exists at all - will change over time and as a downstream repo you're likely to run into issue as it does if you tie yourself to it - it's almost always better to start with a soft fork of implementation details that haven't been approved as part of the public API of the compiler than it is to reuse them. it's likely at some point you'll take an integrate, find it has broken your stuff, and you have to fork anyway)

**Comment by hanhanW** [comment]
I want to signal that I'm considering to update the method with CPU specific logics. I found that we would want pack op to be root op for some cases. I will likely discuss it in tile size infra improvement, but we're stilling working on a draft doc..

EDIT: the idea just came to my mind today, so I did not mention it in my review comments.

**Comment by qedawkins** [comment]
Also fly by comment since we're talking about what a root op is, I would be +1 on finding a different term for "root op" here, as the way that "Kernel Dispatch"/"Config" uses it is unrelated to how most of the rest of codegen uses it (as the root of an operation DAG). The notion of "root" in KernelConfig is closer to an anchor for a code generation strategy rather than anything specific about the surrounding IR structure. I know that reuse of terminology has caused confusion in the past, so could be worth changing if we're poking around here already.

**Comment by MaheshRavishankar** [comment]
Ok, lets hold off on this PR... I think fundamentally all backends should be doing something similar (and I agree the different uses of the term "root op" has been confusing). I will be soon changing the first level tile and distribute to use some of the upstream work I am doing. I'll take that as an opportunity to rethink the terminology here.

**Review by hanhanW — CHANGES_REQUESTED** [review]
Putting a blocker for now, since it needs more discussion.

**Comment by benvanik** [comment]
Closing stale PR.

**Pull request closed without merging**
