### PR TITLE
Bump Torch-MLIR to c26ca8b

### PR DESCRIPTION
**Pull request by vivekkhandelwal1**
This commit bumps Torch-MLIR to https://github.com/llvm/torch-mlir/commit/c26ca8b94d4b1020b9be58d9c525964dd0bd79fb.

### CODE REVIEW

**Comment by vivekkhandelwal1** [comment]
Hi @ScottTodd, I'm not able to understand this CI failure. I don't see any particular error message apart from some dispatch regression related error.

**Comment by zjgarvey** [comment]
If I understand correctly, this is not a regression, but an improvement? Benchmark time is improved and there is one less dispatch.

**Comment by benvanik** [comment]
Do we really have an == check? Or is the printing just bad? Improvements shouldn't cause breakages and checks like this should be <=.
```
ERROR experimental/benchmarks/sdxl/benchmark_sdxl_rocm.py::test_sdxl_rocm_benchmark - check 1563 == 1564: SDXL punet f8 dispatch count should not regress
```

**Comment by zjgarvey** [comment]
> Do we really have an == check? Or is the printing just bad? Improvements shouldn't cause breakages and checks like this should be <=.

Yeah. It's an equal check:

https://github.com/iree-org/iree/blob/c80fa3bcabbaffab33281c997979ff84974cd843/experimental/benchmarks/sdxl/benchmark_sdxl_rocm.py#L564-L568

**Comment by benvanik** [comment]
We should fix that - a good way to make things less useful is to add noise and alias success and failure - at absolute minimum that should print a giant "CONGRATS YOU MADE THINGS BETTER! THIS IS NOT AN ERROR! WE JUST HAVE A CHANGE DETECTOR" banner :P I don't want change detectors in the repo, though. @saienduri please change the logic to be <= and only error if there's regressions.

**Comment by saienduri** [comment]
Yeah, I agree. I originally proposed to have <= checks, but was specifically requested to make that an equal check. The error message is misleading though. Sorry about that. Have a PR here https://github.com/iree-org/iree/pull/19166 :)

**Comment by zjgarvey** [comment]
Closing. See https://github.com/iree-org/iree/pull/19168

**Pull request closed without merging**
