### PR TITLE
Add COPTS flag in iree_c_module rule

### PR DESCRIPTION
**Pull request by hcindyl**
To add extra c flags for emitc modules and optionally silence the warning flags.

### CODE REVIEW

**Comment by hcindyl** [comment]
Discussed with @marbre and it may take some time for the emitc investigation. Add a flag to silence GCC warnings from emitc for https://github.com/openxla/iree/issues/14507 and to allow the team have more time to investigate the emitc behavior.

**Review by benvanik — APPROVED** [review]

**Review by ScottTodd — APPROVED** [review]

**Review by marbre — APPROVED** [review]
**Edit:** I missed the *no*, in `-Wno-uninitialized`, I am fine with merging as is.

~~Adding the possibility to specify additional cflags is great. However, do we already want to enable warnings on uninitialized variables before #14540 is fixed? Both works for me, but I wanted to ask.~~

**Comment by hcindyl** [comment]
oh no... I broke the windows build... https://github.com/openxla/iree/actions/runs/5741229949/job/15560864691

Let me revert this and redo it again, sorry.

**Comment by benvanik** [comment]
thanks - we also hit issues in #14554 - let's try focusing on fixing the root causes instead of adding workarounds for the warnings.

**Comment by ScottTodd** [comment]
`ci_extra: build_test_all_windows` in the PR description should run Windows on presubmit

**Pull request merged**
