### PR TITLE
Revert "[hip] Implement async allocation/deallocation. (#19074)"

### PR DESCRIPTION
**Pull request by ScottTodd**
This reverts commit 42f78229c4964741550e8b952cc94eeeef2c79f7.

Failing tests: https://github.com/iree-org/iree/actions/runs/11748241815/job/32733175285#step:8:482

### CODE REVIEW

**Comment by benvanik** [comment]
#19082 just landed on top so you'll have to rebase/revert that too

**Review by benvanik — APPROVED** [review]

**Comment by ScottTodd** [comment]
> #19082 just landed on top so you'll have to rebase/revert that too

Should I just revert both, or try to slice out the single commit?

**Comment by ScottTodd** [comment]
I'll send a new PR that reverts both commits cleanly.

**Comment by ScottTodd** [comment]
Closing in favor of https://github.com/iree-org/iree/pull/19086

**Pull request closed without merging**
