### PR TITLE
[WIP] Prune collapse dimensions to ensure reshapes can be propagated.

### PR DESCRIPTION
**Pull request by MaheshRavishankar**

### CODE REVIEW

**Comment by benvanik** [comment]
@MaheshRavishankar still valid?

**Comment by MaheshRavishankar** [comment]
I'd like to keep this one if possible. I hit a road block but this is till good to do. You can close the OR if you think it is too much noise

**Comment by benvanik** [comment]
if you think you can land it in a week or two then fine, but otherwise we're going to be a bit more aggressive about closing stale/non-useful PRs going forward - a lot of our PRs are just standing in for a TODO list for people :)

**Comment by MaheshRavishankar** [comment]
I am not planning to land this. Ok, ill close the PR.

**Pull request closed without merging**
