### PR TITLE
Rename `IREE_HOST_BINARY_ROOT` to `IREE_TOOLS_INSTALL`.

### PR DESCRIPTION
**Pull request by ScottTodd**
Progress on https://github.com/iree-org/iree/issues/4662, depends on https://github.com/iree-org/iree/pull/11439

The expected path is the root of the install directory:
```
iree-build/
    install/ <-- this directory
        bin/    <-- not this directory ("binaries")
        lib/    <-- not this directory ("libraries")
        ...
        tests/
```

This also adds some documentation on the new variable in the root CMakeLists file. I'm also considering importing all binaries and libraries from the provided install directory, as a way to replace the current `iree_get_executable_path()` and associated code for cross compilation in our test functions (see https://github.com/iree-org/iree/pull/11402#pullrequestreview-1207342451).

### CODE REVIEW

**Comment by ScottTodd** [comment]
> Maybe we still want to have HOST in this name? (`IREE_HOST_TOOLS_INSTALL` or something) Making it explicit that this is intended to be the host tools install instead of target tools install would help avoid confusion and match common naming of this kind of thing.

Note that you can use this even when not cross compiling, so there doesn't need to be a "host" vs "target" distinction in the build. This setting should be a mechanism to use some tools from an existing build rather than building them from source. The real distinction we're making is compiler + other host tools (`iree-compile`, `iree-tblgen`, `c_embed_data`) vs runtime tools (`iree-run-module`, `iree-benchmark-module`). The directory points to the full "host" install, including `iree-run-module` and other runtime tools, but CMake should _not_ use those runtime tools from the install.

Naming ideas:
* `IREE_TOOLS_INSTALL`
* `IREE_HOST_TOOLS_INSTALL`
* `IREE_COMPILER_TOOLS_INSTALL`

**Comment by benvanik** [comment]
The use of this is for the build host binaries, so that iree-run-module exists in an install is orthogonal as iree-run-module should not be used by the build host.

I think INSTALL may be the wrong word as it's kind of tying this to a cmake install of something. If it's really just a directory of the tools required by the host to build then "IREE_HOST_TOOLS_PATH" or something seems appropriate. A user shouldn't need to build iree-run-module/etc for this and instead just the tools a build host needs to complete an IREE target build. That a cmake install produces a superset of the requirements feels incidental - a user may want to build/ship just what's required for their bot to cross-compile.

Maybe the root problem being addressed could be satisfied with a cmake helper for verifying that a path has all the required host tools (iree-opt, iree-compile, etc) - that may let us give the right error messages and such without enforcing the workflow ("you pointed us at foo/ but that doesn't have tool X" etc).

(just riffing, not sure exactly what's trying to be solved with the changes - I just worried it may be changing one misnamed thing to another :)

**Comment by ScottTodd** [comment]
The impetus for this bit of work was https://github.com/iree-org/iree/issues/11331 and how cross compilation is complicating that. We don't _just_ have a folder of binaries now - we have `bin/` and `lib/`.

Linux:
```
lib/
    libIREEcompiler.so
bin/
    iree-compile
    iree-opt
```

Windows:
```
lib/
    IREEcompiler.lib
bin/
    IREEcompiler.dll
    iree-compile.exe
    iree-opt.exe
```

I'm trying to unwind some of the complexity that has grown in our CMake files while also cleanly supporting the new dynamic linking modes for our tools.

**Comment by benvanik** [comment]
(restating what you're trying to do may be useful - I'm still unclear - having a helper cmake var that given an install path sets up other more fundamental vars seems ok; it's letting the install concept proliferate around the codebase that's sketching me out)

**Comment by ScottTodd** [comment]
> restating what you're trying to do may be useful

A bunch of things, each orthogonal but useful together:

* Add a dep on `bin/IREECompiler.dll` where it's needed: https://github.com/iree-org/iree/pull/11402 (I can either no-op that on Linux or also add a dep on `lib/libIREECompiler.so`)
* Uncouple using prebuilt tools from cross compiling: https://github.com/iree-org/iree/pull/11439
* Update the `IREE_HOST_BINARY_ROOT` name to more accurately match what it points to and how it is used (this PR)
* Find a more general way to add the `IREECompiler.dll` dep and simplify how our CMake functions depend on prebuilt tools (replacing `iree_get_executable_path()`)

**Comment by benvanik** [comment]
yeah as you say those things should be orthogonal to this var and if they are intersecting then there's probably some undesirable conflation happening that we should fix instead of just renaming :)

The place where we point to find the executables used for the build host tools shouldn't require a cmake install to have ever been performed (or cmake to have been used at all for the tools build), shouldn't be platform dependent, shouldn't have anything to do with cmake deps, and shouldn't relate to how the tool executables are linked (statically or dynamically). If anything differs based on any of those aspects we've got the var wrong and not just the naming.

Whatever we do with the var should be something compatible with what we will do with vcpkg, pip, custom user directory mixins (bring your own compiler build), bazel builds/etc, and what we'll want to do with find_program/find_package. cmake installs and such may feed into those but we don't want to couple our cross-compiling builds with any one particular host tool acquisition mechanism.

If we can decouple every other thing you're doing from this var renaming maybe we can think of a better name as I'm not sure what's being done here is it - maybe defer this until after all the other changes/fixes land and we can re-evaluate? I think we're doing tomato/tomatoe tradeoffs when really this is a burrito :)

**Comment by ScottTodd** [comment]
Maybe we should rename to
* `IREE_HOST_TOOLS` 
* `IREE_HOST_BINARIES`
* `IREE_HOST_BINARY_INSTALL`
 
or keep the `IREE_HOST_BINARY_ROOT` name, then change it to mean the `bin/` directory.

I can stop searching the `lib/` path on Linux for `libIREECompiler.so`, as long as changes to IREE compiler code affect `iree-compile` (they _don't_ on Windows, where changes are _only_ reflected in `IREECompiler.dll`). The important thing there is to set up a dependency relationship between the installed tools (including their shared libraries) and generated targets. I thought about ways to inspect the executables/binaries and list their runtime deps (e.g. `dumpbin` on Windows), but I don't see a way to make that portable across platforms / shell environments / etc.

**Comment by benvanik** [comment]
I think you're still circling around workarounds to an issue that shouldn't exist - we really should not be requiring anything of the executables like this - if you're needing to in cmake specify lib dirs and stuff things have already gone off the rails.

**Comment by ScottTodd** [comment]
I'm not working around something broken in just launching/running executables. What I've been debugging on https://github.com/iree-org/iree/issues/11331 and proposing fixes for in https://github.com/iree-org/iree/pull/11402 is how on Windows with shared libraries, changes to compiler code do not trigger rebuilding generated targets. That's because `iree-comple.exe` does not change whenever compiler code changes - only `IREECompiler.dll` changes. We don't have that problem on Linux - code changes _do_ update `iree-compile` (and `libIREECompiler.so`).

I have a fix for that (add a `DEPENDS` on an imported library that references `install/bin/IREECompiler.dll`), but I want to simplify it, which requires also simplifying how we import prebuilt binaries. That simplification will be easier if we first clarify how we want this CMake variable to behave.

**Comment by benvanik** [comment]
I think we're going in circles (which is probably my fault - sorry!) - let's chat in the morning :)

**Comment by ScottTodd** [comment]
> Whatever we do with the var should be something compatible with what we will do with vcpkg, pip, custom user directory mixins (bring your own compiler build), bazel builds/etc, and what we'll want to do with find_program/find_package. cmake installs and such may feed into those but we don't want to couple our cross-compiling builds with any one particular host tool acquisition mechanism.

BTW yes, completely agree with this :)

**Pull request closed without merging**
