### PR TITLE
[iree][sparse] allow sparse tensors in input IR

### PR DESCRIPTION
**Pull request by aartbik**
Just a "hello sparse world" example that allows sparse tensors
in the input IR. Nothing else is being done with the type yet
other than proper roundtripping

```
          Start  740: iree/tools/test/hello_sparse_world.mlir.test
 740/1542 Test  #740: iree/tools/test/hello_sparse_world.mlir.test ...............................................................   Passed    0.17 sec
```

### CODE REVIEW

**Review by qcolombet — APPROVED** [review]
🎉

**Review by yinying-lisa-li — APPROVED** [review]

**Review by benvanik — CHANGES_REQUESTED** [review]
Today this won't work as the ABI has no way to pass the tensors in. We should start with tensors on the inside of programs instead where we don't have to worry about how to marshal them across to runtime instance.

**Comment by aartbik** [comment]
> Today this won't work as the ABI has no way to pass the tensors in. We should start with tensors on the inside of programs instead where we don't have to worry about how to marshal them across to runtime instance.

It is completely unclear what your requested change with "this won't work" refers to, since this change merely adds the sparse tensor type to the registered dialects  and adds a round trip example :-)  Passing a sparse tensor type could still be "internal" to the program between private functions and not impact public ABI.

I think your comment is more reflective of your usual push back on this work but I suggest you wait with detailed feedback until you see how we actually handle passing in and out sparse tensors (with a 1:N relation of dense buffers and an internal pack operation; we have done this before ;-). We plan to implement this initial support in a separate plug-in, so that it does not immediately affect mainstream code.

**Comment by jpienaar** [comment]
I think we are talking a bit past each other. I'll check more once in.

**Comment by aartbik** [comment]
I have rewritten the fun "hello sparse world" example to keep the sparse tensor type fully internal to address your future concerns.

**Comment by dcaballe** [comment]
Would it make sense to send a brief summary of the sparse work/design to the iree discussion list to get the overall picture? That should help contextualize these PRs and help get general consensus of how we should go with it.

**Comment by aartbik** [comment]
> Would it make sense to send a brief summary of the sparse work/design to the iree discussion list to get the overall picture?

Happy to do that!

**Comment by benvanik** [comment]
Yeah, you can't just make changes like this without any context and obviously having never run it :)

**Comment by aartbik** [comment]
> Yeah, you can't just make changes like this without any context and obviously having never run it :)

I don't think this is an open source community I want to be a part of.
Bye!

**Pull request closed without merging**
