### PR TITLE
[cmake] Add cmake option to enable UBSan

### PR DESCRIPTION
**Pull request by kuhar**
UBSan features checks not performed by ASan. Both UBSan and ASan can be
enabled simultaneously.

Issue: https://github.com/iree-org/iree/issues/9922

### CODE REVIEW

**Review by GMNGeoffrey — APPROVED** [review]
Nice! It would be good to enable this as part of the same build as asan in our CI also. You could do that in this PR, actually.

Relevant script is currently https://github.com/iree-org/iree/blob/main/build_tools/kokoro/gcp_ubuntu/cmake/linux/x86-swiftshader-asan/build.sh though it will hopefully be soon moved to GitHub actions. Do you have a suggested name for a combined asan/ubsan build? Can't just be "sanitizers" because we've also got tsan...

**Comment by kuhar** [comment]
> Nice! It would be good to enable this as part of the same build as asan in our CI also. You could do that in this PR, actually.

I'd prefer to keep things separate so that the CI change is easier to roll back without breaking local builds. After all, ubsan complains a lot in my local build at the moment 😉 
 
> Relevant script is currently https://github.com/iree-org/iree/blob/main/build_tools/kokoro/gcp_ubuntu/cmake/linux/x86-swiftshader-asan/build.sh though it will hopefully be soon moved to GitHub actions. Do you have a suggested name for a combined asan/ubsan build? Can't just be "sanitizers" because we've also got tsan...

How about we just stick with `-asan` and add appropriate comments in the script? It's not the name has to fully describe what the build does. WDYT?

**Comment by kuhar** [comment]
V1: Rebased.

**Comment by GMNGeoffrey** [comment]
Sure, those are both fine with me. Wasn't sure if there was some better way to say "asan and ubsan" but :shrug:

**Comment by kuhar** [comment]
> Sure, those are both fine with me. Wasn't sure if there was some better way to say "asan and ubsan" but 🤷

FYI, in my previous project we had one uber script that decided the CMake configuration based on a list of 'features' to enable: https://github.com/GPUOpen-Drivers/llpc/blob/dc2dddef9f77a4d665a59b2569836589803d2537/docker/amdvlk.Dockerfile#L90. So we passed something like `"+asan+ubsan"` to enable both.

**Pull request merged**
