### PR TITLE
Update matmul tensorcore strategy to properly trigger pipelining with…

### PR DESCRIPTION
**Pull request by nicolasvasilache**
… mma.sync

### CODE REVIEW

**Review by qcolombet — APPROVED** [review]
I'm surprised there's no test update given we change the default for MmaSync.
Did you forget to `git add` a test?

**Comment by nicolasvasilache** [comment]
> I'm surprised there's no test update given we change the default for MmaSync. Did you forget to `git add` a test?

There is currently no programmatic way of controlling the strategy, we can add a test for this specific case once we have that.

**Comment by qcolombet** [comment]
> > I'm surprised there's no test update given we change the default for MmaSync. Did you forget to `git add` a test?
> 
> There is currently no programmatic way of controlling the strategy, we can add a test for this specific case once we have that.

Fixed that with CLI options like you suggested.
@nicolasvasilache Let me know if that looks good to you.

**Review by nicolasvasilache — COMMENTED** [review]
Great, thanks!

**Pull request merged**
