### PR TITLE
[Do Not Submit] CPU Custom Calls with `void*` argument/result list

### PR DESCRIPTION
**Pull request by vmurali**
Custom Call executed on the host side (i.e. the CPU). The calls can have arbitrary number/type for arguments and results. The callee's ABI is `void call(void* results, void ** arguments, std::optional<std::string>* error)`. The callee explicitly marshalls/unmarshalls the arguments and results from the `void*` pointers. So, the ABI that IREE runtime uses has to be explicitly decoded and packed into the ABI that the callee uses.

The type (and number) of arguments/results is stored now in `iree_vm_function_call_t` so that this information can be used to dynamically decode the buffer passed by the IREE runtime. The source of truth about the function signature is now the caller (rather than the callee).

### CODE REVIEW

**Comment by vmurali** [comment]
The next step is to create the compiler pass to change `mhlo/stablehlo.custom_call` to a simple `func.call` (and take care of output buffer aliasing, to deal with destination passing style).

**Review by benvanik — CHANGES_REQUESTED** [review]
We won't be able to do this in this way, unfortunately, as it violates several rules of the VM.

The change in context.c needs to be reverted as not trusting the requesting module is a security/correctness feature and allowing any importing module to define the calling convention of _other_ module it imports from is not valid. Modules need to declare what they export. Not having the information declared will lead to sadness as a change in the definition used by the compiler will result in memory corruption/security issues/etc at runtime unless they exactly match and there's no way to tell the user they don't. That may be fine for what you want to use this kind of thing for but it's not something that can be assumed in iree/vm/ as it has large implications.

The iree_vm_function_call_t structure is used on all calls and needs to be kept small - it can only contain the information used to make the call and nothing else. Modules are expected to cache any information they need either in the module (shared across many contexts) or module state (local to a context). You can get the cconv information via `iree_vm_function_signature(function)` as needed instead and cache it, but note as above you can't trust the importing module as a source of truth in general. If you want good error messages, security, etc you can construct the calling convention when you register your custom call in a way like native_module_packing.h does (`packing::cconv_storage_void<sizeof...(Params), Params...>::value()`) or however else you want. If you really can't declare the functions then YMMV and it'll be something you need to do in your layer above IREE with the risks associated with that.

To do what you're doing if you can't declare things in your own code you can load your module with the imports, use reflection to get the imported functions (linkage of `IREE_VM_FUNCTION_LINKAGE_IMPORT`), use `iree_vm_function_signature` to get the cconv, and then cache those on your custom module. This should let you make calls like you are today but then need to ensure you deal with the potential issues (two modules both importing a function but having conflicting signatures, etc). That should be possible without any changes today.

I don't think we'll have this sample in the repo - it's not something immediately reusable and does things in a way inconsistent with what we want people to do - if PJRT needs this it's better there where they've got the legacy baggage around void* calls with no definition.

**Comment by vmurali** [comment]
> We won't be able to do this in this way, unfortunately, as it violates several rules of the VM.

I agree with all of what you say. I just sent this PR to have this conversation.

> If you really can't declare the functions then YMMV and it'll be something you need to do in your layer above IREE with the risks associated with that.
> 
> To do what you're doing if you can't declare things in your own code you can load your module with the imports, use reflection to get the imported functions (linkage of `IREE_VM_FUNCTION_LINKAGE_IMPORT`), use `iree_vm_function_signature` to get the cconv, and then cache those on your custom module. This should let you make calls like you are today but then need to ensure you deal with the potential issues (two modules both importing a function but having conflicting signatures, etc). That should be possible without any changes today.

I don't follow this - if the custom functions are not declared by the user, how would I use `iree_vm_function_signature` to get it? I need the actual signature that the user is using, rather than void*, right? I cannot get this signature unless I parse the C++ code that the user writes. Can you please elaborate on how to get this signature?

**Comment by benvanik** [comment]
You can use `iree_vm_function_signature` to get the signature of the import, doing exactly what you are in here today (trusting the import declaration instead of the export definition). You'd just be doing this in your code instead of it being something the core IREE code does.

So if you have `my_module` that imports `custom_module.call` with signature `rr_r` you'd get the `iree_vm_function_t` of `custom_module.call` from `my_module`, get the signature with `iree_vm_function_signature`, and then use that to annotate `custom_module`'s `call` export. When you go to create a VM context with both modules they'll do the normal checks and ensure the signatures match - which they should because you just set one to the other.

**Comment by vmurali** [comment]
> You can use `iree_vm_function_signature` to get the signature of the import, doing exactly what you are in here today (trusting the import declaration instead of the export definition). You'd just be doing this in your code instead of it being something the core IREE code does.
> 
> So if you have `my_module` that imports `custom_module.call` with signature `rr_r` you'd get the `iree_vm_function_t` of `custom_module.call` from `my_module`, get the signature with `iree_vm_function_signature`, and then use that to annotate `custom_module`'s `call` export. When you go to create a VM context with both modules they'll do the normal checks and ensure the signatures match - which they should because you just set one to the other.

I don't have access to `my_module` when I write `custom_module`. How do I plumb `my_module` (or more specifically, `my_module`'s import table) to `custom_call`?

(My guess is that you expect a separate `custom-module-run` (or its equivalent in PJRT), rather dynamically link it using `iree-module-run`, which does the plumbing?)

**Comment by benvanik** [comment]
yeah, you are effectively JIT'ing a module based on the declarations only available in another module so you'll need to have the declaring module available when you do that. You can load your main module and then create your custom module using that as a template. Once they're both created you can instantiate them in a VM context. It's a bit backwards because not having the export declare its signature is backwards :)

An alternative would be to opt out of VM signature checks. A `IREE_VM_CONTEXT_FLAG_IGNORE_SIGNATURE_MISMATCHES` flag could be used to bypass the checks with a YMMV caveat. The change you have in context.c could be guarded on that flag such that the unsafe behavior is only done when the hosting application says it's ok.

**Comment by vmurali** [comment]
> An alternative would be to opt out of VM signature checks. A `IREE_VM_CONTEXT_FLAG_IGNORE_SIGNATURE_MISMATCHES` flag could be used to bypass the checks with a YMMV caveat. The change you have in context.c could be guarded on that flag such that the unsafe behavior is only done when the hosting application says it's ok.

This could be a quick workaround, but it still doesn't provide the signature from the importer to the exporter. Maybe I can cache the signature somehow in the exporter module in `context.c` instead of plumbing it through `iree_vm_function_call_t`

**Comment by benvanik** [comment]
Hmmm..... I'm not sure how I feel about it but could extend the module lookup_function to take the expected signature - then your custom module would be notified of all the import resolution events. If you (thread-safely) took the expected signature and cached it you'd have it available for calls in the future. It's not fantastic but would at least put the responsibility on the module implementing the dynamic export behavior instead of the module importing the functions. Let me see if I can make that work real quick.

**Comment by benvanik** [comment]
https://github.com/openxla/iree/pull/13562
This adds an `const iree_vm_function_signature_t* expected_signature` argument to the module `lookup_function` call. Your module can see if it's non-NULL and cache that on itself (be sure to use a mutex to guard as multiple threads may be performing lookups concurrently), and if NULL could just error out.

**Comment by vmurali** [comment]
I just verified that the `module->lookup_function` hack works, i.e. I can populate the signature based on the expected signature and everything goes through.

**Comment by benvanik** [comment]
Woohoo! I'm still not super happy with how I plumbed it and in the future I can probably refactor things to allow for batched import resolution so that you don't have to handle things per-lookup. Hopefully this at least unblocks you and we can defer that until some indeterminate future :)

**Comment by vmurali** [comment]
Nit: `NativeModule::dispatch_table_`'s type can be template parameterized and `NativeModule::ModuleBeginCall` function can be made virtual (or parts of it can be template parameterized/virtual) to support other means of populating the dispatch table and executing the function stored there. We can do that later. This avoids (more or less) copying `NativeModule` class into a slightly different `CustomModule` class.

**Comment by benvanik** [comment]
The C++ wrappers are meant for convenience/demos but I'd recommend using the C interface for something as low-level as this instead - the C++ stuff has additional overhead to pack/unpack things that you don't need. You'll end up with less code using the C interface.

**Comment by ScottTodd** [comment]
Closing some old PRs. This looks stale (and is marked "do not submit") and we have some similar samples in-tree.

**Pull request closed without merging**
