### PR TITLE
[WIP] Add sharding support for E2E test artifact generation

### PR DESCRIPTION
**Pull request by beckerhe**
This adds sharding support by doing the following:

1. Create strided CMake targets that can be built individually
2. Add a matrix strategy to the artifact generation workflow
3. Change the glue code in build_e2e_test_artifacts.sh accordingly.

### CODE REVIEW

**Comment by pzread** [comment]
It seems like we are trying to shard the building step here? I think what we want is to shard the benchmark executions.

Currently we generate the strategy matrix here to dispatch benchmark jobs to target devices: https://github.com/openxla/iree/blob/main/.github/workflows/benchmark_execution.yml#L54

That step parses an execution benchmark config exported in:
https://github.com/openxla/iree/blob/23666a604206fee145b5575f76d3a803f3448671/build_tools/cmake/build_e2e_test_artifacts.sh#L101C1-L104

The execution benchmark config describes a map of `target_device -> list of benchmarks + artifacts to download`. I'm thinking we can generate the benchmark config to have something like `target_device -> [[benchmark shard1], [benchmark shard2], ...]`. Details can be found in https://github.com/openxla/iree/blob/23666a604206fee145b5575f76d3a803f3448671/build_tools/benchmarks/export_benchmark_config.py#L7-L18

**Comment by beckerhe** [comment]
> It seems like we are trying to shard the building step here? I think what we want is to shard the benchmark executions.
> 
Yes. I'm aware. I started with that because Benchmark Large (example: https://github.com/openxla/iree/actions/runs/5226050090) is currently failing with a timeout in the artifact generation step and I wanted to find out if sharding would fix that. But I'm not sure if these compilations finish at all. They didn't on my machine while I was hacking this together. I assume @mariecwhite might know more. 

Independently of that I will look into the sharding of the execution next. Thank you for the links.

**Comment by pzread** [comment]
> > It seems like we are trying to shard the building step here? I think what we want is to shard the benchmark executions.
> 
> Yes. I'm aware. I started with that because Benchmark Large (example: https://github.com/openxla/iree/actions/runs/5226050090) is currently failing with a timeout in the artifact generation step and I wanted to find out if sharding would fix that. But I'm not sure if these compilations finish at all. They didn't on my machine while I was hacking this together. I assume @mariecwhite might know more.
> 
> Independently of that I will look into the sharding of the execution next. Thank you for the links.

I also noticed the build timeouts on large benchmark set. I created this one https://github.com/openxla/iree/pull/14051 to fail any build target taking longer than 1hr and there are several:

```
FAILED: e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH24_module_129b48d3bbdad4b4333986b8a35fcafa8d4434fead6233154cecfbdab0ca23e6/module.vmfb /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH24_module_129b48d3bbdad4b4333986b8a35fcafa8d4434fead6233154cecfbdab0ca23e6/module.vmfb 
cd /work/build-e2e-test-artifacts/tests/e2e/test_artifacts && timeout 1h /work/full-build-dir/install/bin/iree-compile --output-format=vm-bytecode --mlir-print-op-on-diagnostic=false --iree-hal-target-backends=cuda --iree-input-type=stablehlo --iree-hal-cuda-llvm-target-arch=sm_80 /work/build-e2e-test-artifacts/e2e_test_artifacts/model_173c7180-bad4-4b91-8423-4beeb13d2b0a-MODEL_T5_LARGE-fp32-JAX-512xi32-batch24_T5_LARGE_FP32_JAX_512XI32_BATCH24.mlirbc -o /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH24_module_129b48d3bbdad4b4333986b8a35fcafa8d4434fead6233154cecfbdab0ca23e6/module.vmfb --iree-hal-executable-object-search-path=\"/work/build-e2e-test-artifacts\"
[445/448] Generating /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH32_module_3dcbc01e07ee34df7e5535dd0be85071685655d51331314b7a17517feb74ed3b/module.vmfb from T5_LARGE_FP32_JAX_512XI32_BATCH32(stablehlo) [cuda-sm_80-linux_gnu-cuda][default-flags]
FAILED: e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH32_module_3dcbc01e07ee34df7e5535dd0be85071685655d51331314b7a17517feb74ed3b/module.vmfb /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH32_module_3dcbc01e07ee34df7e5535dd0be85071685655d51331314b7a17517feb74ed3b/module.vmfb 
cd /work/build-e2e-test-artifacts/tests/e2e/test_artifacts && timeout 1h /work/full-build-dir/install/bin/iree-compile --output-format=vm-bytecode --mlir-print-op-on-diagnostic=false --iree-hal-target-backends=cuda --iree-input-type=stablehlo --iree-hal-cuda-llvm-target-arch=sm_80 /work/build-e2e-test-artifacts/e2e_test_artifacts/model_173c7180-bad4-4b91-8423-4beeb13d2b0a-MODEL_T5_LARGE-fp32-JAX-512xi32-batch32_T5_LARGE_FP32_JAX_512XI32_BATCH32.mlirbc -o /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH32_module_3dcbc01e07ee34df7e5535dd0be85071685655d51331314b7a17517feb74ed3b/module.vmfb --iree-hal-executable-object-search-path=\"/work/build-e2e-test-artifacts\"
[446/448] Generating /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH16_module_d7ff0ce530c700c18dc4704dfcb75ec14540bd0794faee823a3cc1cd62ea53df/module.vmfb from T5_LARGE_FP32_JAX_512XI32_BATCH16(stablehlo) [cuda-sm_80-linux_gnu-cuda][default-flags]
FAILED: e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH16_module_d7ff0ce530c700c18dc4704dfcb75ec14540bd0794faee823a3cc1cd62ea53df/module.vmfb /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH16_module_d7ff0ce530c700c18dc4704dfcb75ec14540bd0794faee823a3cc1cd62ea53df/module.vmfb 
cd /work/build-e2e-test-artifacts/tests/e2e/test_artifacts && timeout 1h /work/full-build-dir/install/bin/iree-compile --output-format=vm-bytecode --mlir-print-op-on-diagnostic=false --iree-hal-target-backends=cuda --iree-input-type=stablehlo --iree-hal-cuda-llvm-target-arch=sm_80 /work/build-e2e-test-artifacts/e2e_test_artifacts/model_173c7180-bad4-4b91-8423-4beeb13d2b0a-MODEL_T5_LARGE-fp32-JAX-512xi32-batch16_T5_LARGE_FP32_JAX_512XI32_BATCH16.mlirbc -o /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH16_module_d7ff0ce530c700c18dc4704dfcb75ec14540bd0794faee823a3cc1cd62ea53df/module.vmfb --iree-hal-executable-object-search-path=\"/work/build-e2e-test-artifacts\"
[447/448] Generating /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH48_module_e70546885f5488d986fffccc21a118d82aa7933b7dccfe47b0093591e081231f/module.vmfb from T5_LARGE_FP32_JAX_512XI32_BATCH48(stablehlo) [cuda-sm_80-linux_gnu-cuda][default-flags]
FAILED: e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH48_module_e70546885f5488d986fffccc21a118d82aa7933b7dccfe47b0093591e081231f/module.vmfb /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH48_module_e70546885f5488d986fffccc21a118d82aa7933b7dccfe47b0093591e081231f/module.vmfb 
cd /work/build-e2e-test-artifacts/tests/e2e/test_artifacts && timeout 1h /work/full-build-dir/install/bin/iree-compile --output-format=vm-bytecode --mlir-print-op-on-diagnostic=false --iree-hal-target-backends=cuda --iree-input-type=stablehlo --iree-hal-cuda-llvm-target-arch=sm_80 /work/build-e2e-test-artifacts/e2e_test_artifacts/model_173c7180-bad4-4b91-8423-4beeb13d2b0a-MODEL_T5_LARGE-fp32-JAX-512xi32-batch48_T5_LARGE_FP32_JAX_512XI32_BATCH48.mlirbc -o /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH48_module_e70546885f5488d986fffccc21a118d82aa7933b7dccfe47b0093591e081231f/module.vmfb --iree-hal-executable-object-search-path=\"/work/build-e2e-test-artifacts\"
[448/448] Generating /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_BERT_LARGE_JAX_384XI32_BATCH512_module_9f4cafa63a150cabdf61a945dc6a04c9ddac88b75260bb4ce668199cdddbd581/module.vmfb from BERT_LARGE_JAX_384XI32_BATCH512(stablehlo) [cuda-sm_80-linux_gnu-cuda][default-flags]
FAILED: e2e_test_artifacts/iree_BERT_LARGE_JAX_384XI32_BATCH512_module_9f4cafa63a150cabdf61a945dc6a04c9ddac88b75260bb4ce668199cdddbd581/module.vmfb /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_BERT_LARGE_JAX_384XI32_BATCH512_module_9f4cafa63a150cabdf61a945dc6a04c9ddac88b75260bb4ce668199cdddbd581/module.vmfb 
cd /work/build-e2e-test-artifacts/tests/e2e/test_artifacts && timeout 1h /work/full-build-dir/install/bin/iree-compile --output-format=vm-bytecode --mlir-print-op-on-diagnostic=false --iree-hal-target-backends=cuda --iree-input-type=stablehlo --iree-hal-cuda-llvm-target-arch=sm_80 /work/build-e2e-test-artifacts/e2e_test_artifacts/model_47cb0d3a-5eb7-41c7-9d7c-97aae7023ecf-MODEL_BERT_LARGE-fp32-JAX-384xi32-batch512_BERT_LARGE_JAX_384XI32_BATCH512.mlirbc -o /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_BERT_LARGE_JAX_384XI32_BATCH512_module_9f4cafa63a150cabdf61a945dc6a04c9ddac88b75260bb4ce668199cdddbd581/module.vmfb --iree-hal-executable-object-search-path=\"/work/build-e2e-test-artifacts\"
ninja: build stopped: cannot make progress due to previous errors.
```

**Comment by beckerhe** [comment]
> > > It seems like we are trying to shard the building step here? I think what we want is to shard the benchmark executions.
> > 
> > 
> > Yes. I'm aware. I started with that because Benchmark Large (example: https://github.com/openxla/iree/actions/runs/5226050090) is currently failing with a timeout in the artifact generation step and I wanted to find out if sharding would fix that. But I'm not sure if these compilations finish at all. They didn't on my machine while I was hacking this together. I assume @mariecwhite might know more.
> > Independently of that I will look into the sharding of the execution next. Thank you for the links.
> 
> I also noticed the build timeouts on large benchmark set. I created this one #14051 to fail any build target taking longer than 1hr and there are several:
> 
> ```
> FAILED: e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH24_module_129b48d3bbdad4b4333986b8a35fcafa8d4434fead6233154cecfbdab0ca23e6/module.vmfb /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH24_module_129b48d3bbdad4b4333986b8a35fcafa8d4434fead6233154cecfbdab0ca23e6/module.vmfb 
> cd /work/build-e2e-test-artifacts/tests/e2e/test_artifacts && timeout 1h /work/full-build-dir/install/bin/iree-compile --output-format=vm-bytecode --mlir-print-op-on-diagnostic=false --iree-hal-target-backends=cuda --iree-input-type=stablehlo --iree-hal-cuda-llvm-target-arch=sm_80 /work/build-e2e-test-artifacts/e2e_test_artifacts/model_173c7180-bad4-4b91-8423-4beeb13d2b0a-MODEL_T5_LARGE-fp32-JAX-512xi32-batch24_T5_LARGE_FP32_JAX_512XI32_BATCH24.mlirbc -o /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH24_module_129b48d3bbdad4b4333986b8a35fcafa8d4434fead6233154cecfbdab0ca23e6/module.vmfb --iree-hal-executable-object-search-path=\"/work/build-e2e-test-artifacts\"
> [445/448] Generating /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH32_module_3dcbc01e07ee34df7e5535dd0be85071685655d51331314b7a17517feb74ed3b/module.vmfb from T5_LARGE_FP32_JAX_512XI32_BATCH32(stablehlo) [cuda-sm_80-linux_gnu-cuda][default-flags]
> FAILED: e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH32_module_3dcbc01e07ee34df7e5535dd0be85071685655d51331314b7a17517feb74ed3b/module.vmfb /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH32_module_3dcbc01e07ee34df7e5535dd0be85071685655d51331314b7a17517feb74ed3b/module.vmfb 
> cd /work/build-e2e-test-artifacts/tests/e2e/test_artifacts && timeout 1h /work/full-build-dir/install/bin/iree-compile --output-format=vm-bytecode --mlir-print-op-on-diagnostic=false --iree-hal-target-backends=cuda --iree-input-type=stablehlo --iree-hal-cuda-llvm-target-arch=sm_80 /work/build-e2e-test-artifacts/e2e_test_artifacts/model_173c7180-bad4-4b91-8423-4beeb13d2b0a-MODEL_T5_LARGE-fp32-JAX-512xi32-batch32_T5_LARGE_FP32_JAX_512XI32_BATCH32.mlirbc -o /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH32_module_3dcbc01e07ee34df7e5535dd0be85071685655d51331314b7a17517feb74ed3b/module.vmfb --iree-hal-executable-object-search-path=\"/work/build-e2e-test-artifacts\"
> [446/448] Generating /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH16_module_d7ff0ce530c700c18dc4704dfcb75ec14540bd0794faee823a3cc1cd62ea53df/module.vmfb from T5_LARGE_FP32_JAX_512XI32_BATCH16(stablehlo) [cuda-sm_80-linux_gnu-cuda][default-flags]
> FAILED: e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH16_module_d7ff0ce530c700c18dc4704dfcb75ec14540bd0794faee823a3cc1cd62ea53df/module.vmfb /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH16_module_d7ff0ce530c700c18dc4704dfcb75ec14540bd0794faee823a3cc1cd62ea53df/module.vmfb 
> cd /work/build-e2e-test-artifacts/tests/e2e/test_artifacts && timeout 1h /work/full-build-dir/install/bin/iree-compile --output-format=vm-bytecode --mlir-print-op-on-diagnostic=false --iree-hal-target-backends=cuda --iree-input-type=stablehlo --iree-hal-cuda-llvm-target-arch=sm_80 /work/build-e2e-test-artifacts/e2e_test_artifacts/model_173c7180-bad4-4b91-8423-4beeb13d2b0a-MODEL_T5_LARGE-fp32-JAX-512xi32-batch16_T5_LARGE_FP32_JAX_512XI32_BATCH16.mlirbc -o /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH16_module_d7ff0ce530c700c18dc4704dfcb75ec14540bd0794faee823a3cc1cd62ea53df/module.vmfb --iree-hal-executable-object-search-path=\"/work/build-e2e-test-artifacts\"
> [447/448] Generating /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH48_module_e70546885f5488d986fffccc21a118d82aa7933b7dccfe47b0093591e081231f/module.vmfb from T5_LARGE_FP32_JAX_512XI32_BATCH48(stablehlo) [cuda-sm_80-linux_gnu-cuda][default-flags]
> FAILED: e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH48_module_e70546885f5488d986fffccc21a118d82aa7933b7dccfe47b0093591e081231f/module.vmfb /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH48_module_e70546885f5488d986fffccc21a118d82aa7933b7dccfe47b0093591e081231f/module.vmfb 
> cd /work/build-e2e-test-artifacts/tests/e2e/test_artifacts && timeout 1h /work/full-build-dir/install/bin/iree-compile --output-format=vm-bytecode --mlir-print-op-on-diagnostic=false --iree-hal-target-backends=cuda --iree-input-type=stablehlo --iree-hal-cuda-llvm-target-arch=sm_80 /work/build-e2e-test-artifacts/e2e_test_artifacts/model_173c7180-bad4-4b91-8423-4beeb13d2b0a-MODEL_T5_LARGE-fp32-JAX-512xi32-batch48_T5_LARGE_FP32_JAX_512XI32_BATCH48.mlirbc -o /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_T5_LARGE_FP32_JAX_512XI32_BATCH48_module_e70546885f5488d986fffccc21a118d82aa7933b7dccfe47b0093591e081231f/module.vmfb --iree-hal-executable-object-search-path=\"/work/build-e2e-test-artifacts\"
> [448/448] Generating /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_BERT_LARGE_JAX_384XI32_BATCH512_module_9f4cafa63a150cabdf61a945dc6a04c9ddac88b75260bb4ce668199cdddbd581/module.vmfb from BERT_LARGE_JAX_384XI32_BATCH512(stablehlo) [cuda-sm_80-linux_gnu-cuda][default-flags]
> FAILED: e2e_test_artifacts/iree_BERT_LARGE_JAX_384XI32_BATCH512_module_9f4cafa63a150cabdf61a945dc6a04c9ddac88b75260bb4ce668199cdddbd581/module.vmfb /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_BERT_LARGE_JAX_384XI32_BATCH512_module_9f4cafa63a150cabdf61a945dc6a04c9ddac88b75260bb4ce668199cdddbd581/module.vmfb 
> cd /work/build-e2e-test-artifacts/tests/e2e/test_artifacts && timeout 1h /work/full-build-dir/install/bin/iree-compile --output-format=vm-bytecode --mlir-print-op-on-diagnostic=false --iree-hal-target-backends=cuda --iree-input-type=stablehlo --iree-hal-cuda-llvm-target-arch=sm_80 /work/build-e2e-test-artifacts/e2e_test_artifacts/model_47cb0d3a-5eb7-41c7-9d7c-97aae7023ecf-MODEL_BERT_LARGE-fp32-JAX-384xi32-batch512_BERT_LARGE_JAX_384XI32_BATCH512.mlirbc -o /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_BERT_LARGE_JAX_384XI32_BATCH512_module_9f4cafa63a150cabdf61a945dc6a04c9ddac88b75260bb4ce668199cdddbd581/module.vmfb --iree-hal-executable-object-search-path=\"/work/build-e2e-test-artifacts\"
> ninja: build stopped: cannot make progress due to previous errors.
> ```

Interesting. There are only a few commits between the last successful run and the first that timed out:

`git log --oneline f3d0369..967ab3b` gives me:

```
967ab3b5d Adding cuda.device :: compute_capability_major/minor queries. (#14033)
7514d3e8c Add pattern to map iota->sort->slice to topK (#13972)
e4c27f584 Support non-default sets of enabled LLVM CPU targets. (#13983)
b3a1ac9e8 Bump LLVM to llvm/llvm-project@faae4d5d (#14023)
1b8e95c3a Allowing for sync allocations to be deallocated via queue-ordered deallocas. (#14029)
860026f53 Declare exported headers to Bazel to fix `bazel build --incompatible_no_implicit_file_export` (#13982)
5c0fc0310 Adding a fallback for when CUDA memory pools are unsupported. (#14018)
c9419462f Exposing device configuration higher in the stack. (#14009)
3bd115aac Refresh deployment-configuration website pages. (#14013)
c12bf50e9 Harden the PadOp matcher (#14024)
c620ab2fa Clean up CapturingOpMatcher and derived classes, NFC (#14022)
```

**Comment by mariecwhite** [comment]
Just noticed the build timeouts. I'll create an issue with these details.

**Comment by mariecwhite** [comment]
Created https://github.com/openxla/iree/issues/14067

**Comment by beckerhe** [comment]
Thank you, @mariecwhite!

Assuming the issue can be fixed and we get back to normal non-timeout compilation times: Do we still want (need) sharding for the artifact generation at some point? I could finish this PR or drop it. Like I said it was just an experiment and I'm fine with either way. (@pzread @mariecwhite)

**Pull request closed without merging**
