### PR TITLE
[plugins][ROCM] Fix minor loc source resize bug

### LINKED ISSUE #17132: Compiling with ROCM backend and unknown debug locations crashes with assertion
```
iree-compile: iree/third_party/flatcc/src/runtime/builder.c:1494: flatcc_builder_ref_t _create_offset_vector_direct(flatcc_builder_t *, flatcc_builder_ref_t *, size_t, const flatbuffers_utype_t *): Assertion `0' failed.

#12 0x000070ba4904c6f3 iree_hal_rocm_ExecutableDef_source_locations_add(flatcc_builder*, int) /home/stella/src/iree-build/runtime/src/iree/schemas/rocm_executable_def_builder.h:192:1                                                      
#13 0x000070ba4904c6f3 mlir::iree_compiler::IREE::HAL::ROCMTargetBackend::serializeExecutable(mlir::iree_compiler::IREE::HAL::TargetBackend::SerializationOptions const&, mlir::iree_compiler::IREE::HAL::ExecutableVariantOp, mlir::OpBuild
er&) /home/stella/src/iree/compiler/plugins/target/ROCM/ROCMTarget.cpp:631:7  
```

Repro:

```
#loc = loc(unknown)
module {
  func.func @main(%arg0: tensor<5xf32> loc(unknown), %arg1: tensor<5xf32> loc(unknown)) -> tensor<5xf32> {
    %0 = tosa.add %arg0, %arg1 : (tensor<5xf32>, tensor<5xf32>) -> tensor<5xf32> loc(#loc)
    return %0 : tensor<5xf32> loc(#loc)
  } loc(#loc)
} loc(#loc)
```

```
iree-compile --iree-rocm-target-chip=gfx1100 --iree-hal-target-backends=rocm -o /dev/null repro.mlir  --iree-input-type=tosa
```

### PR DESCRIPTION
**Pull request by raikonenfnu**
PR fixes minor resize source loc bug where we resize even if loc is empty or unknown. This should fix https://github.com/iree-org/iree/issues/17132

### CODE REVIEW

**Review by antiagainst — CHANGES_REQUESTED** [review]
Nice, thanks! Add the input in the issue as a test case?

**Comment by raikonenfnu** [comment]
> Nice, thanks! Add the input in the issue as a test case?

Hi Lei, added a test in e2e rosa since this is the only place we are checking e2e that includes serialization. LMK if you know a better place to put the test in.

**Comment by benvanik** [comment]
compiler\plugins\target\ROCM\test\ is the right place for this
smoketest.mlir shows serialization being tested - this would be fine to add in there (but not tosa) - could probably be an empty executable just with no locs (KISS)

**Comment by benvanik** [comment]
(if you do add unrelated tests to places you must document them - and even in related places like the dir above you should add a note about _why_ you added the test (`// Tests serialization with unknown source locations.` etc) - I'd see what you added and delete it as it doesn't look like it's testing anything)

**Comment by raikonenfnu** [comment]
Understood, thanks!

**Comment by raikonenfnu** [comment]
> compiler\plugins\target\ROCM\test\ is the right place for this smoketest.mlir shows serialization being tested - this would be fine to add in there (but not tosa) - could probably be an empty executable just with no locs (KISS)

Nice, updated the test to look like that and was able to repro Stella's issue here.

**Review by benvanik — APPROVED** [review]

**Review by antiagainst — APPROVED** [review]

**Pull request merged**
