### PR TITLE
[NFC] Split VectorExt attributes into a separate file

### PR DESCRIPTION
**Pull request by qedawkins**
In preparation for potentially adding more attribute definitions.

### CODE REVIEW

**Comment by qedawkins** [comment]
I think this is better? The dialect is kind of small but attribute heavy so I figure this makes sense. Closer to how the codegen dialect is set up.

**Review by kuhar — APPROVED** [review]
LGTM but wait for Harsh & Kunwar

**Review by Groverkss — APPROVED** [review]
Splitting is good. We also need to move this dialect into Codegen/Dialect/Distribution, this is not exactly a vector dialect extension.

**Comment by qedawkins** [comment]
> Splitting is good. We also need to move this dialect into Codegen/Dialect/Distribution, this is not exactly a vector dialect extension.

Cool, we can do that later then.

**Pull request merged**
