### PR TITLE
Preserve lowering config attribute during rematerialization.

### PR DESCRIPTION
**Pull request by MaheshRavishankar**

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
Towards https://github.com/openxla/iree/issues/15091

**Review by qedawkins — COMMENTED** [review]
Can you share how this differs from what is trying to be achieved above? https://github.com/openxla/iree/blob/5962a515341e0a9cdc54a54b643fa7a30e2b1740/compiler/src/iree/compiler/Codegen/Common/RematerializeParallelOps.cpp#L53-L61

Perhaps an IR example or a test would make it clearer, but I'm trying to understand what kind of lowering config is still valid with a different number of loops.

**Comment by MaheshRavishankar** [comment]
> Can you share how this differs from what is trying to be achieved above?
> 
> https://github.com/openxla/iree/blob/5962a515341e0a9cdc54a54b643fa7a30e2b1740/compiler/src/iree/compiler/Codegen/Common/RematerializeParallelOps.cpp#L53-L61
> 
> Perhaps an IR example or a test would make it clearer, but I'm trying to understand what kind of lowering config is still valid with a different number of loops.

Ah, sorry forgot to remove that. It was looking for `lowering_config` specifically, but this moves any attribute that it doesnt know about.

**Comment by MaheshRavishankar** [comment]
> Can you share how this differs from what is trying to be achieved above?
> 
> https://github.com/openxla/iree/blob/5962a515341e0a9cdc54a54b643fa7a30e2b1740/compiler/src/iree/compiler/Codegen/Common/RematerializeParallelOps.cpp#L53-L61
> 
> Perhaps an IR example or a test would make it clearer, but I'm trying to understand what kind of lowering config is still valid with a different number of loops.

Ok, I missed the second part of your question. The number of loops doesnt change, since you only rematerialize elementwise parallel ops. By definition, the output is supposed to be a permutation, so after rematerialization, the fused op will have the same number of loops as the consumer.

**Review by qedawkins — APPROVED** [review]
That... makes sense. I was a bit confused on whose loops we were comparing and which config was being kept.

**Pull request merged**
