### PR TITLE
Revert "Add T5-Large Tensorflow Model (#12895)"

### PR DESCRIPTION
**Pull request by ThomasRaoux**
This reverts commit a593b6227049d8cb43618d7f6621eebe3bf3c3e6.

This solves out of disk problem on our CI VMs:
https://github.com/openxla/iree/actions/runs/4602186347/jobs/8131186559

### CODE REVIEW

**Review by ScottTodd — APPROVED** [review]

**Comment by GMNGeoffrey** [comment]
Can you link the failures you're seeing please?

**Comment by ThomasRaoux** [comment]
> Can you link the failures you're seeing please?

good point, added to the description

**Comment by GMNGeoffrey** [comment]
Unfortunately that link is time-bound :-( `{"count":11,"value":"Uri expired"}`

**Comment by ThomasRaoux** [comment]
> Unfortunately that link is time-bound :-( `{"count":11,"value":"Uri expired"}`

oops, tried again

**Pull request merged**
