### PR TITLE
Add math expand patterns pass

### LINKED ISSUE #17184: Math ops lowering and runtime issue
### What happened?

MLIR is [here](https://github.com/nod-ai/SHARK-TestSuite/blob/main/iree_tests/onnx/node/generated/test_acos/model.mlir).

Compilation failed after `iree-convert-to-llvm` pass.
> error: failed to legalize operation 'math.acos' that was explicitly marked illegal

I added theses [changes](https://github.com/iree-org/iree/commit/87edd2c230b549ffa1d2d6bdbe834bce86775911) and it compiled, but having runtime issue.
> iree/runtime/src/iree/hal/local/executable_plugin_manager.c:570: NOT_FOUND; missing 1 required executable imports: [acosf]; while invoking native function hal.executable.create; while calling import;
        [ 1]   native hal.executable.create:0 -
        [ 0] bytecode module.__init:268 model.mlir:4:10; creating VM context; creating run context

I'm not sure if the changes I made is right though.

### Steps to reproduce your issue

1. git clone https://github.com/nod-ai/SHARK-TestSuite.git
2. cd SHARK-TestSuite/iree_tests/onnx/node/generated/test_acos
3. iree-compile model.mlir --iree-hal-target-backends=llvm-cpu -o model.vmfb
4. iree-run-module --module=model.vmfb --device=local-sync --flagfile=test_data_flags.txt

### What component(s) does this issue relate to?

_No response_

### Version information

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jinchen62**
need to update llvm with https://github.com/llvm/llvm-project/pull/90718

### CODE REVIEW

**Review by pashu123 — APPROVED** [review]
LGTM!

**Comment by ScottTodd** [comment]
This was merged with test "failures" (affected tests are now passing when they are marked XFAIL): https://github.com/iree-org/iree/actions/runs/9059961537/job/24889009508#step:9:682

Please ensure that tests, particularly those for the feature you are adding or bug you are fixing, are passing before merging.

There was also discussion about changing test tolerances on https://github.com/iree-org/iree/issues/17184. That should have been included in this PR too, if needed.

**Comment by jinchen62** [comment]
@ScottTodd I thought it would update the xfail list automatically. Can I just remove those xfails from the cpu/cuda/vulkan configs like `build_tools/pkgci/external_test_suite/onnx_gpu_cuda.json`?

**Comment by ScottTodd** [comment]
> @ScottTodd I thought it would update the xfail list automatically. Can I just removed those xfails from the cpu/cuda/vulkan configs like `build_tools/pkgci/external_test_suite/onnx_gpu_cuda.json`?

Ah, sorry for the confusion. The .json files are _generated_ automatically but they are not _committed_ or _reviewed_ automatically - those steps still require human action. That was both intentional and simpler to implement, though we could further automate it. If a PR has test failures (like these: https://github.com/iree-org/iree/actions/runs/9059961537/job/24889009508#step:9:682) you can either copy/paste the .json that is logged in the following "Updating config file with latest XFAIL lists" step or go to the summary page for that job (https://github.com/iree-org/iree/actions/runs/9059961537) to download the new .json files: 
image

You can then commit the new files (after verifying that the changes they contain are as expected -- validating test coverage is an essential part of development)

**Pull request merged**
