### PR TITLE
Support multi channels by supporting channel splitting

### PR DESCRIPTION
**Pull request by okkwon**
Support multi channels by supporting channel splitting.

Channel splitting enables creating a set of sub-channels in SPMD way. It is powerful and flexible way to create a channel, which should cover major needs of creating a sub-channel. Each rank in a group will get a channel for the group. We may extend the group semantic more to make it more flexible, but for now channel splitting is sufficient to support all use cases for StableHLO collective ops.

Each value in the groups represents a rank in the input channel and
all ranks must be specified in the groups. Each group is specified
with parentheses and comma separated. Each rank specified in a group
is also comma separated. Groups can have a different sizes but cannot
be empty. Here are some examples with 4 ranks:

    "(0,1),(2,3)" - Two groups with size 2 each
    "(0),(1,2,3)" - Two groups with size 1 and 3, respectively
    "(0),(1),(2),(3)" - Four groups with size 1 each

Now, the channel provider does not create the unique ID. Instead, the root rank sets the ID and each participant including the root rank calls the provider function to broadcast the ID. In the MPI implementation, only color and key are necessary to split a communicator, but for other communication methods, it may need more information, so the original groups string is passed in the provider function too. It would be useful for debugging too.

The missing implementation here is the use of the input channel to split. Currently, we always split the default channel. It is marked as TODO. This needs a work to attach the MPI communicator to `iree_hal_channel_t`. The stablehlo always creates a group from the default channel, so that's okay for now, but this needs to be fixed to make the channel split op complete.

The code is tested with all_reduce, all_gather, and reduce_scatter with 2 and 4 processes setups.

### CODE REVIEW

**Review by benvanik — CHANGES_REQUESTED** [review]
There's some stuff tangled up in here that makes it difficult to review and I realized I was putting it off - sorry about that ;( As a meta-point I think a little bit of time verifying approach would help avoid some delays in the future. In particular the thrust of the change seems in the right direction (splitting channels) but the implementation has several things we'll need to work through.

Of major note:
* iree/base/ is a standard library and not something where we can dump specialized helpers (group parsing/etc)
* free-form strings across the binary compatibility boundary are avoided at nearly all costs - we should not be having the compiler emit strings that need to be handled in non-trivial ways (we have the ability to pass variadic lists of integers, for example)
* we need to err on the side of generality and low-level programmatic access - removing the generic channel creation API in favor of specialized ones that don't cover all use cases is a negative
* splitting may be done in a few ways - we need to ensure that non-NCCL implementations will be able to implement it even if that means more expensive emulation on NCCL or non-NCCL to meet the same interface - we just can't have two different ways

When adding APIs that survive into the runtime we need to think about how to bottom them out on the minimal possible surface area with the maximum possible applicability. If it's not possible to do that then it may indicate that the API doesn't quite fit with where it's being placed and we'll need to iterate on it a bit more.

For next steps I think we can work with @cc10512 since he's got some non-NCCL experience and get together a list of methods we want, the kind of parameters they take, an example implementation (pseudo code, etc) on both NCCL and non-NCCL, and ensure that we can lower non-PJRT/HLO programs to it (with the most extreme being that we should be able to implement basic MPI programs without HLO at all). Now that channel providers have landed we can also evaluate what things go there vs what goes on device or even channels themselves. I suspect we may want channels to be able to split themselves instead of asking the device/provider to split a channel - basically, iree_hal_channel_split ala MPI_Comm_split (whether we use color or some other mechanism).

**Comment by okkwon** [comment]
Thanks @benvanik for the early comments! I am rebasing the changes onto your channel provider changes.

The channel split (MPI_Comm_split) to get the unique ID will go into another channel provider function, e.g., `exchange_id_for_group(id, group, rank_in_group, count_in_group)`. Then, the runtime side can just create a channel with the unique ID.

Can you point me to the variadic list example? Or we can simply follow how mhlo does using -1 for empty data. Another way is to pack group ID and rank in the group in a 64-bit (32-bit for group and 32-bit for rank). It will pack the data in binary form and do not waste space.

I can keep the generic channel creation. My preference is that removing unused features if it is not used and adding it when a necessity show up. I'd like to hear more from Calin's use case.

**Comment by okkwon** [comment]
Rebasing is done and it passes my local tests, but I still need to discuss and resolve a few things. Switching to a draft PR.

**Comment by okkwon** [comment]
Thinking of packing the group string into binary form, i.e., constant buffer op with a series of group, rank tuples. Here is an example:

"(0,1),(2,3)" -> [0,0,0,1,1,2,1,3]. Each element type is int32_t.

This makes the size of the buffer = 2 * total number of ranks * 4 bytes.

@benvanik do you have a better idea? I can also use the original group <2xNxi64> to represent the group from StableHLO to HAL all the way through. (HAL will pass the attribute as ConstantBufferOp though.)

**Comment by benvanik** [comment]
We do not want to do that (byte buffers/etc) and shouldn't need to. Variadic arguments should be used instead.

**Comment by okkwon** [comment]
> We do not want to do that (byte buffers/etc) and shouldn't need to. Variadic arguments should be used instead.

Can you point me to an example?

**Comment by benvanik** [comment]
command buffer push_constants

https://github.com/google/iree/blob/main/compiler/src/iree/compiler/Dialect/HAL/IR/HALOps.td/#L996
https://github.com/google/iree/blob/main/compiler/src/iree/compiler/Dialect/HAL/hal.imports.mlir/#L263-L268
https://github.com/google/iree/blob/main/runtime/src/iree/modules/hal/module.c/#L750
(`CiD` indicating a single i32 repeating list)

I'm happy to help handle this if you want to split the PR up or can take it on - it's something I'm familiar with and can spend cycles on it if you'd like to work on the other parts of the stack.

**Comment by okkwon** [comment]
@benvanik I am a bit lost here because the push constants seem to be related to a dispatch and command buffer, but the collective ops have nothing to do with dispatch. 

Anyway, it would be nice to have your help here. You can work on the PR and change the the HAL interface directly. If you want me to split the PR in a preferred form, let me know. I can clean up some stuffs for you. Thanks!

**Comment by benvanik** [comment]
Those methods demonstrate how to make variadic calls - it's a `Variadic<I32>` in tablegen on the op -> the variadic `...` import declaration -> the variadic module call in the runtime.

Sure - I'll work on this tomorrow!

**Comment by okkwon** [comment]
Thanks Ben!

**Comment by okkwon** [comment]
This is fused into Ben's recent PRs. Thanks!

**Pull request closed without merging**
