### PR TITLE
Remove MHLO support

### PR DESCRIPTION
**Pull request by kuhar**
Drop the MHLO input conversion pipeline, which has been deprecated for over a week. The StableHLO pipeline is the direct replacement. See the announcement thread for more context:
https://groups.google.com/g/iree-discuss/c/s6dBpDtWhtk.

This still uses the copy of stablehlo from the mlir-hlo repo -- we will switch to the stablehlo repo in a follow-up PR.

Issue: https://github.com/openxla/iree/issues/12678

### CODE REVIEW

**Review by antiagainst — APPROVED** [review]
Woohoo!

**Comment by kuhar** [comment]
(I plan to submit this PR on Monday, unless something comes up, just like we announced on iree-discuss and openxa-discuss.)

**Review by ScottTodd — APPROVED** [review]
Will the mlir-hlo submodule be removed after this too?

**Comment by GMNGeoffrey** [comment]
> This still uses the copy of stablehlo from the mlir-hlo repo -- we will switch to the stablehlo repo in a follow-up PR.

:stuck_out_tongue:

**Comment by ScottTodd** [comment]
Oh, I can't read. Thanks :P

**Comment by kuhar** [comment]
Rebased.

**Comment by jpienaar** [comment]
Was the regressions in JAX tests addressed?

**Comment by kuhar** [comment]
@jpienaar Which one? I don't see any unresolved issues in my queue.

**Comment by jpienaar** [comment]
@rsuderman was there an issue tracking those?

**Comment by kuhar** [comment]
Rebased.

**Comment by kuhar** [comment]
> @rsuderman was there an issue tracking those?

I asked Rob offline and he gave this PR a green light:
> Make the switch over, while I have bandwidth I am going to keep hammering through the test suite and finding issues.
> No its fine at this point. I am going to hopefully get stuff fixed this week from the migration

**Pull request merged**
