### PR TITLE
Delete old e2e tests with massive checked-in IR files

### PR DESCRIPTION
**Pull request by GMNGeoffrey**
These were mostly added years ago before we had mechanisms for testing
models end-to-end. The tests here don't use our standard test
infrastructure and instead JIT-compile with `iree-run-mlir`. This is
nice to provide some small sample programs that can be iterated on
without having to think about build systems, but is not appropriate for
massive IR files. Now we have a better way. There are already
(CMake-only) end-to-end tests
[in this directory](https://github.com/openxla/iree/blob/main/tests/e2e/models/generated_e2e_model_tests.cmake)
that compile using the build system with the accompanying caching,
dependency analysis and parallelism and then the test is only actually
executing the module. The immediate motivation here is to delete the
resnet50 test that is our slowest on every platform and keeps timing
out or needing to be disabled.

### CODE REVIEW

**Review by ScottTodd — APPROVED** [review]

**Comment by GMNGeoffrey** [comment]
Putting those who originally added these models as reviewers (plus Ben, who usually has opinions on this sort of thing)

**Review by hanhanW — APPROVED** [review]

**Comment by GMNGeoffrey** [comment]
Also FYI @bjacob since you were complaining about this slow test :-)

**Review by ScottTodd — APPROVED** [review]

**Review by antiagainst — APPROVED** [review]

**Comment by MaheshRavishankar** [comment]
Oh... these are kind of useful tests (Sorry didnt see this before it landed).

**Comment by GMNGeoffrey** [comment]
Can you elaborate?

**Comment by MaheshRavishankar** [comment]
I have learnt how to get these benchmarks files and run them locally, but they are too many things involved to run them locally within a development cycle. These tests provide a reasonable basic testing on "realistic" things rather than lit-testing. If these dont pass then there is no point even putting up a draft PR/PR to run the benchmarks on CI. Some things need this kind of size for testing. We dont want too many of them (and I actually dont know why resnet is so slow), but I prefer having them as tests/e2e/ tests.

**Comment by GMNGeoffrey** [comment]
> Sorry didnt see this before it landed

No worries. Sorry I didn't let it sit for a bit longer. I thought I'd looped in the people who would be concerned. The resnet test was repeatedly failing on CI and sending failure notifications and Benoit was also in the process of reworking test timeouts partially to address this particular tests, so I rushed things a bit.

I still think we shouldn't be checking in these giant IR files. They're not really "source code" that is human maintainable. That said, your use case seems important, so let's address it. It sounds like what you want is some largish integration tests that are easy to run. I think we have a few persistent themes here:

1. Giant IR files aren't really human-maintainable.
2. When debugging at scale, having the tests trying to do everything all together causes issues (see, for instance the recent time debugging the memory error where we couldn't even tell if it was in the compiler or runtime).
3. Having sources for tests hosted elsewhere adds friction to local development.
4. Having the build system automagically fetch things over the network causes reliability and hermeticness problems.
5. Having tests themselves fetch things over the network has the same issues (like we have with `mnist_train_test` today).

Just to confirm, the three files here were fulfilling a role that is *not* satisfied by the remaining smaller IR samples, correct?

**Pull request merged**
