### PR TITLE
Cherry-pick commits to fix Android failures.

### LINKED ISSUE #12546: e2e_matmul_mmt4d_i8 test failure on Android devices after LLVM integration
After https://github.com/openxla/iree/commit/d015bbc5f1e0c6b117e5e1fbbbf8f42c381e09fb, we started to see [test failures](https://buildkite.com/iree/iree-test-android/builds/8439#0186b5dd-2de9-450b-ab41-acdddd40d778/488-1677) on all Android phones:

```
The following tests FAILED:
27 - iree/tests/e2e/matmul/e2e_matmul_mmt4d_i8_small_llvm-cpu_local-task_dotprod_on_android_device (Failed)
35 - iree/tests/e2e/matmul/e2e_matmul_mmt4d_i8_intrinsics_small_llvm-cpu_local-task_dotprod_on_android_device (Failed)
```

### PR DESCRIPTION
**Pull request by hanhanW**
The below sequence of 4 commits are cherry-picked:

https://github.com/llvm/llvm-project/commit/ae12e57a777f2287a656e17a6ce86ca6b86edb6e
https://github.com/llvm/llvm-project/commit/0847cc06a6c4feae5414f062141fbbd9b9aea4e0
https://github.com/llvm/llvm-project/commit/a10ac6554db4dee93232139d5c29f8d91ee01f3b
https://github.com/llvm/llvm-project/commit/1c6ea961938488997712763762079e535b8b704e

Fixes https://github.com/openxla/iree/issues/12546

### CODE REVIEW

**Comment by hanhanW** [comment]
I feel that the ongoing integrate is not a straight-forward one. In this context, we should cherry-pick the fixes to make CI green. @vmurali @antiagainst what do you think?

**Comment by vmurali** [comment]
The integrate's errors have nothing to do with this CL. I am happy either way.

**Review by vmurali — APPROVED** [review]

**Comment by antiagainst** [comment]
Nice. Thanks Hanhan for this!

**Comment by bjacob** [comment]
Thank you!!

**Pull request merged**
