### PR TITLE
Cherry-pick e62681e70a4e0cef34d7310d42de7d425784264b

### PR DESCRIPTION
**Pull request by matthias-springer**
Cherry-pick and integration fixes for
llvm-project@e62681e70a4e0cef34d7310d42de7d425784264b.

### CODE REVIEW

**Review by MaheshRavishankar — COMMENTED** [review]
Do you think we can drop the "ConvertToDestinationPassing` pass in IREE now?

Ill let Hanhan approve since this is a cherry-pick.

**Comment by hanhanW** [comment]
Passing it to @dcaballe because he's on integrate this week.

**Comment by dcaballe** [comment]
LGTM. Could you please land this asap? I'll start a new integrate later today.

**Review by dcaballe — APPROVED** [review]

**Comment by hanhanW** [comment]
I think Matthias is offline. I verify that there is only one cherry-pick commit. Let me rebase it to the main and cherry pick it, then we can land the PR.

**Pull request merged**
