### PR TITLE
Bump actions/add-to-project version to use new API.

### PR DESCRIPTION
**Pull request by ScottTodd**
(Untested)

Hoping this fixes errors like those on https://github.com/iree-org/iree/actions/runs/3380006187:

> [Adding issue to the IREE GitHub project](https://github.com/iree-org/iree/actions/runs/3380006187/jobs/5612284349#step:2:6)
Request failed due to following response errors: - The `ProjectNext` API is deprecated in favour of the more capable `ProjectV2` API. Follow the ProjectV2 guide at https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/, to find a suitable replacement.

skip-ci: this workflow isn't covered by CI

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
skip-ci is now a git trailer, so you need a colon (and optionally a reason)

`skip-ci: this workflow isn't covered by CI`

**Review by GMNGeoffrey — APPROVED** [review]

**Comment by ScottTodd** [comment]
Hmm.. that didn't work as easily as I hoped :P

https://github.com/iree-org/iree/actions/runs/3380205625/jobs/5612727185
> Error: Request failed due to following response errors:
>  - Your token has not been granted the required scopes to execute this query. The 'projectV2' field requires one of the following scopes: ['read:project'], but your token has only been granted the: ['admin:org', 'repo'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.
>  - Your token has not been granted the required scopes to execute this query. The 'id' field requires one of the following scopes: ['read:project'], but your token has only been granted the: ['admin:org', 'repo'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.

**Comment by GMNGeoffrey** [comment]
Probably need to edit/update the `ADD_TO_PROJECT_TOKEN`, which is probably in the iree-github-actions-bot account

**Comment by ScottTodd** [comment]
> Probably need to edit/update the `ADD_TO_PROJECT_TOKEN`, which is probably in the iree-github-actions-bot account

Okay, adding the `project` (and `read:project` by extension) scope did the trick. Thanks :)

**Pull request merged**
